### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by keenan137**
Correct registration of CustomAuthenticationStateProvider.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ac6f86c24d7195581a2d4f6066555b9c6fa662fa/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-30354) |

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @keenan137 ... The registration is correct. It's on two lines because we have a maximum width requirement for documentation to prevent horizontal scrolling.

**Comment by guardrex** [comment]
***BUT*** ... I've opened https://github.com/dotnet/AspNetCore.Docs/issues/30355 to shorten the name, then we can show this registration on one line.

**Comment by keenan137** [comment]
Hi @guardrex . I'm relatively new to these things so it might be something I'm doing wrong. When I followed the tutorial, for some reason, the AuthenticationState was not persisted properly. Only once I registered the CustomAuthoenticationProvider and then linked it on a new line with the AuthenticationStateProvider, did it persist and I was able to use something like AuthorizeView.

**Comment by guardrex** [comment]
Note that another reader found an error in part of this topic that we just fixed yesterday on https://github.com/dotnet/AspNetCore.Docs/pull/30386/files. The live version of the topic now shows the correct guidance:

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-7.0&tabs=visual-studio#notification-about-authentication-state-changes

WRT your report, open a new issue to discuss it. We don't work from closed issues/PRs. Use the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

Capture

I'll probably need to see a minimal repro project placed on GH (or at least every piece of your custom auth state provider and test component shown in comment code blocks).

**Pull request closed without merging**
