### PR TITLE
7.0 What's new: Adding gRPC JSON transcoding section

### LINKED ISSUE #26677: .NET 7.0 Update What's New: gRPC JSON transcoding
Update the What's New in ASP.NET Core 7.0 topic with a new section for gRPC that includes JSON transcoding feature.

Contributes to #26477 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by wadepickett**
[Internal review: gPRC section of What's new](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26679#grpc)

Fixes #26677 
Contributes to #26477 

Adding gRPC > gRPC JSON transcoding section to .NET 7.0 What's new

### CODE REVIEW

**Comment by wadepickett** [comment]
Build not happening.  Closing and reopening to force build.

**Comment by wadepickett** [comment]
Forcing build.  Closing and opening.

**Comment by wadepickett** [comment]
The build occurred, but the checks are not updating back to the issue for some reason.  Verified the build of the doc.

**Comment by wadepickett** [comment]
Closing and opening again since the build occurred successfully some time ago and is viewable, but the issue is not updating with the checks complete.  Maybe an action isn't triggering for some reason.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
