### PR TITLE
New snippet /8

### PR DESCRIPTION
**Pull request by Rick-Anderson**
---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md](https://github.com/dotnet/AspNetCore.Docs/blob/271cc40e45bf4c68bd8b6780653e92e7c043e0d5/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md) | [RDG008: Multiple public constructors](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg008?branch=pr-en-us-30627) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky please review.

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson is there any way for me to view the preview link? I don't have access to it

**Comment by sammychinedu2ky** [comment]
But apart from that the readme looks okay 👍

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson is there any way for me to view the preview link? I don't have access to it

Get a job at MS. I'm working on that but it will probably be years. I'll S&M and push live and you can review it.

**Comment by sammychinedu2ky** [comment]
Also what's S & M 😄

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
> Also what's S & M 😄

image

**Comment by sammychinedu2ky** [comment]
> > Also what's S & M 😄
> 
> image

Ah okay okay 👌

**Pull request merged**
