### PR TITLE
Edit pass on Blazor with Yarp

### LINKED ISSUE #28565: Edit pass of Blazor Support in Incremental Migration
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Version Independent ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Content: [Blazor Support in Incremental Migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-8.0&branch=pr-en-us-28535)
* Content Source: [aspnetcore/migration/inc/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @twsouthwick
* Microsoft Alias: **tasou**

### LINKED ISSUE #28566: Move embedded snippet to project file
Project file should go under the https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/migration/inc/samples folder

Given this is fixed in .NET 8, it's low priority.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Version Independent ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Content: [Blazor Support in Incremental Migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-8.0&branch=pr-en-us-28535)
* Content Source: [aspnetcore/migration/inc/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @twsouthwick
* Microsoft Alias: **tasou**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #28565
Fixes #28566

[Internal Review Topic](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-8.0&branch=pr-en-us-28574)

Taylor, sorry about the delay getting to this. It was a crazy week 😵 for me moving across the state of Florida. I'm stabilized now thank goodness. 😄

This is just an *NIT* edit pass to conform to some global and local repo guidelines that we follow. I'll list the significant ones here, and please let me know if you need further explanation ...

* Metadata updates
* Tracking updates for 8.0 on https://github.com/dotnet/AspNetCore.Docs/issues/28161
* `BlazorEndpointRouteBuilderExtensions` class
  * 85 char limit on line length to accommodate narrow screens
  * Dropped underscore on `_builders`.
  * Move code comments to text for MT.
* For diff block, only showing diff lines.

Let me know if I botched the lingo changes. I sometimes try to ***make up my own 🦖 framework!*** :see_no_evil: 😆

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> For diff block, I highly recommend that we remove everything outside of the diff lines because things evolve so fast in the framework that the other lines are bound to break at some point in the future, which leads to reader confusion and can generate GH doc issues. I refer to the file (Program.cs); so hopefully 🍀🤞, devs will find it easily enough ... I hope! 

Per the article:
 This will be fixed in the .NET 8 release later this year. For migration to ASP.NET Core 6.0 and 7.0, map Blazor's endpoints to achieve correct request routing by following the guidance in this article.

So I'd say leave it for now.

Really nice work @guardrex but TLDR

I just list highlights of the style guide:

- Avoid future tense
- Use sentence casing, Not Clown Casing in H2's
-

**Comment by guardrex** [comment]
I have to explain some of the changes so that they don't seem random.

**Comment by guardrex** [comment]
@Rick-Anderson ... Should we go ahead and merge?

**Comment by twsouthwick** [comment]
@guardrex @Rick-Anderson Sorry for the delay, but this looks good to me - didn't realize about the style stuff, so thanks for updating that!

> What's the plan for this article at .NET 8 RTM? Do you want to scope it to 6.0 and 7.0

Good question. Once there are APIs available for that and we can check the scenario, we can add a .NET 8 version of it. As of now, anyone using .NET 8 would still need to do this.

**Pull request merged**
