### PR TITLE
Rearrange text for clarity

### PR DESCRIPTION
**Pull request by samuelwine**
This article is excellently written. 
It is important to bear in mind that auth is one of the most challenging concepts for developers, particularly with the multitude of technologies and terms. As this is the first time Microsoft Identity Platform is mentioned in this article, I was confused as to whether Microsoft Identity Platform is the same thing as ASP.NET Core Identity. I would suggest that the proposed change makes this much clearer.

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Thanks @samuelwine! ... Rick primarily keeps an 👁️ on these, so let's have him look, too, just to make sure the change is welcome.

BTW ... They lower-case "identity platform" of "Microsoft identity platform" in spite of it's proper noun status ... *technically speaking* 😄. However, that's what they did, so we need to do that here, too.

**Comment by samuelwine** [comment]
thanks @guardrex

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
overloaded brand name = ambiguity.

**Comment by Rick-Anderson** [comment]
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

**Pull request merged**
