### PR TITLE
fix typo in directory name

### PR DESCRIPTION
**Pull request by timdeschryver**
Coming from https://github.com/dotnet/AspNetCore.Docs/issues/27865#issuecomment-1736466676 

This PR fixes a typo in the directory name (diagonstics => diagnostics).
After this PR, the "base" is good to pick up the other issues without interrupting each other.

Should be merged together with https://github.com/dotnet/AspNetCore.Docs.Samples/pull/192

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rg002.md](https://github.com/dotnet/AspNetCore.Docs/blob/9e8dbc688619b898c6adc3bf9c80eb86e88f87ac/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rg002.md) | [RDG002: Unable to resolve endpoint handler](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rg002?branch=pr-en-us-30498) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  had the same comment, I'm not seeing that. https://learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg002?view=aspnetcore-8.0 is rendering correctly and you version isn't finding the snippets.

**Comment by timdeschryver** [comment]
The reason why it's rendered correctly on the live learn website is because the samples are added to the directory containing the typo (diagonstics).
In other words, the typo exists within this repo and the samples repo.

This current state of this PR fails because it cannot find the snippets due to the rename within the docs, but not in the samples repo.

To fix the build (at least how I see it, and feel free to correct me), I think the PR of the samples repo needs be merged first (https://github.com/dotnet/AspNetCore.Docs.Samples/pull/192) because it fixes the typo within that repo.

After the samples PR is merged this PR will successfully build because it can now find the files.

I tested this on my local machine (it works on my machine 😅)
image

**Comment by Rick-Anderson** [comment]
@timdeschryver  can you change all the `rdg00x` to `rg00x` like I did in https://github.com/dotnet/AspNetCore.Docs/pull/30499/files, that will get rid of the merge conflict. I had to change that to generate the correct URL

**Comment by Rick-Anderson** [comment]
Actually, it's a file rename that needs to happen, drop the d in the file name

**Comment by timdeschryver** [comment]
Sorry, I was just leaving. Thanks for the fixup!

**Comment by Rick-Anderson** [comment]
Thanks for fixing this. @tdykstra notified me of the same problem and I couldn't see it, ha.

**Pull request merged**
