### PR TITLE
proxy_set_header Connection "Upgrade"

### PR DESCRIPTION
**Pull request by timbze**
Updating to match nginx documentation (also linked in this page) which works. https://www.nginx.com/blog/websocket-nginx/

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @timbze ... Hold a sec while I confer with our ⚔️ *Sergent at Code* 🏰 ...

@anurse When we added this on https://github.com/dotnet/AspNetCore.Docs/pull/15897#issuecomment-575697593, we didn't do the map bit. Was that a proper bit for us to have added at the time?

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
```

**Comment by timbze** [comment]
I needed that line for SignalR to work, but now I'm running into this issue: https://github.com/dotnet/aspnetcore/issues/17081

**Comment by timbze** [comment]
I ended up getting it working properly after using these lines:
`proxy_set_header Upgrade $http_upgrade;`
`proxy_set_header Connection $http_connection;`

And not this at all `proxy_set_header Connection "Upgrade";`

**Comment by guardrex** [comment]
The whole scenario is spelled out here :point_right: http://nginx.org/en/docs/http/websocket.html.

That's probably a good resource to add via a cross-link. It looks like if we're going to go with `$http_connection` that we should have the `map` entry.

I'll make an update to this PR with what I think would be good and then we'll see on review if it's sane.

**Comment by guardrex** [comment]
@timbze, can you confirm that the guidance there works in your scenario?

Also, I'm taking the example content from our Nginx topic, so I'm now showing the full set of headers. We'll have to see if that's the right thing to show.

**Also**, can you sign the CLA if you agree with its terms. We can't merge this PR without that.

**Comment by guardrex** [comment]
FYI @scottaddie ... This PR looks like it could've been merged without the CLA being signed. It only asked for it when I shot in a commit :point_up:. If I hadn't done that, I think we'd have had a .NET Foundation process violation for accepting content. cc: @jongalloway

**Comment by timbze** [comment]
@guardrex Yes it works for me with the example you have added now. And the other headers is exactly what I was using already too.

**Comment by guardrex** [comment]
**_Cool Corebeans!_**:tm: :+1: ... so we just need this reviewed by one of the engineers that works more with Linux than I do, which is very rarely. :smile:

**Comment by guardrex** [comment]
## Note to self

Work #11403 immediately after this merges.

**Comment by anurse** [comment]
> @anurse When we added this on [#15897 (comment)](https://github.com/dotnet/AspNetCore.Docs/pull/15897#issuecomment-575697593), we didn't do the map bit. Was that a proper bit for us to have added at the time?

I don't remember that being there when I used that post as a reference for earlier WebSocket configuration docs, but it seems reasonable to add it now.

**Comment by guardrex** [comment]
I'll merge now. I think we're good here. I'll tend to the additional work on this subject asap.

**Pull request merged**
