### PR TITLE
Fix typo in security.md

### PR DESCRIPTION
**Pull request by ericmutta**
The sentence:

> Minimal **app's** support loading...

Should read:

> Minimal **apps** support loading...

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/c830a8f5dced74c69c30534fbe3b3b60f49da360/aspnetcore/fundamentals/minimal-apis/security.md) | [Authentication and authorization in minimal APIs](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?branch=pr-en-us-31581) |

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@ericmutta keep them coming, you're up to `#23`
image

**Comment by ericmutta** [comment]
Thanks @Rick-Anderson! I am going through all the docs on Minimal APIs (hence the flurry of typo fixes), I especially love the [quick reference page](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0) both as a way of initially getting up to speed but also as a place to come back to later on when I need to remind myself of something - super handy 🚀

**Comment by Rick-Anderson** [comment]
> I especially love the [quick reference page](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0) both as a way of initially getting up to speed but also as a place to come back to later on when I need to remind myself of something - super handy 🚀

I think @tdykstra  split that page up, it used to be bigger. I see advantages to a big page as it's easier to search within a page vs search across multiple articles.

**Comment by tdykstra** [comment]
>I think @tdykstra split that page up, it used to be bigger. I see advantages to a big page as it's easier to search within a page vs search across multiple articles.

I didn't split it up, it's all there. But much of it is in H3 sections, which don't show up in the internal TOC. And much of it was moved to includes, which don't show up when you're looking at the .md file.

**Pull request merged**
