### PR TITLE
add note about xamarin apps

### PR DESCRIPTION
**Pull request by mairaw**
@coolcsh mentioned we should call out in the docs

### CODE REVIEW

**Comment by JamesNK** [comment]
Does that particular part fail (calling a non-TLS HTTP/2 endpoint) or does gRPC fail on Xamarin in general?

What I'd really like to know whether the .NET gRPC client works at all in Xamarin apps. I tried to setup Xamarin on my computer and failed, so I haven't been able to check myself. @jamesmontemagno said it sort of works and I don't know what that means 🤷‍♂

**Comment by mairaw** [comment]
I don't know either. Let's see if they can give us that feedback. @coolcsh indicated that part didn't work on Xamarin.

**Comment by Rick-Anderson** [comment]
@jamesmontemagno  can you comment or `@mention` someone to comment and review?

**Comment by JamesNK** [comment]
@shirhatti experimented with gRPC over HTTP/2 and Xamarin, and the finding was Xamarin's HTTP/2 doesn't support it yet.

What I think:
Close this and create a PR to the gRPC client page to say that calling gRPC over HTTP/2 with Grpc.Net.Client is currently not supported on Xamarin. We are working to improve HTTP/2 support in a future Xamarin release. Grpc.Core and gRPC-Web are viable alternatives that work today.

**Comment by mairaw** [comment]
@Rick-Anderson can you handle that?

**Comment by Rick-Anderson** [comment]
Yes, I'll take care of it unless @wadepickett beat's me to it.

**Comment by jamesmontemagno** [comment]
I think it would be nice to document what does work today with iOS/Android as there is a flow today.

**Pull request closed without merging**
