### PR TITLE
Update SIMD disable guidance 8.0

### LINKED ISSUE #30923: [blazor] SIMD can be disabled
The disabling of SIMD has been fixed and so the note from docs can be removed https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows#single-instruction-multiple-data-simd

### PR DESCRIPTION
**Pull request by guardrex**
Fixes  #30923

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/48af0d117977494d25a44b357b700ad6344da16f/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-30924) |

### CODE REVIEW

**Review by maraf — APPROVED** [review]
Looks great! 👍

**Comment by maraf** [comment]
One nit, unrelated. Can we change the URL for wasm features documentation? Instead of directly pointing to .md file on github, use aka link https://aka.ms/dotnet-wasm-features#simd---single-instruction-multiple-data

**Comment by guardrex** [comment]
There are two links here, and I may have updated the wrong one.

**Comment by guardrex** [comment]
Sorry about that, @maraf ... I just walked in the door after being OOF for a couple of hours, so my head wasn't in the game here. It should be in good shape now.

**Comment by maraf** [comment]
Awesome, thank you!

**Pull request merged**
