### PR TITLE
Correction to the root element in Blazor

### PR DESCRIPTION
**Pull request by poornimanayar**
Corrected the reference to the root component app in Blazor

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @poornimanayar ... Thanks, but this is in the <5.0 content, so it should remain as is.

**Comment by guardrex** [comment]
Oh ... sorry ... I didn't see the version tag that ended the <5.0 content early.

**_However_**, we'll need to version this change. I'll take care of it. Thanks for sending this in.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=20942) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=20942) before we can accept your contribution.<br/><br/>:x: poornimanayar [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=20942)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=20942) it.</sub>

**Comment by guardrex** [comment]
That should take care of it. I'm in the process of editing all of the topics right now, so I'll be fixing all of the little nits like this that I find.

btw -- @poornimanayar ... If you agree with the license terms, can you sign the CLA? :point_up: I can't merge this unless you sign off. No worries tho if you decide not to sign. I can set up a new PR with the updates.

cc: @jongalloway ... This is still a problem where we don't see the CLA on some PRs until after an update/review of the proposed changes. It virtually forces us to break the rule of not looking at the PR because we just don't know if the person has signed the CLA.

**Comment by poornimanayar** [comment]
Hi @guardrex ,

I have signed it. Is there anything tags etc I should watch out for when I submit changes like this in future?

Poornima

**Comment by guardrex** [comment]
We version content using "moniker range" properties, as you can see on the PR. They're easy to use. Sometimes, we need to discuss versioning prior to a PR, so recommend an issue first if the versioning seems complicated. If the versioning is simple, as it is here, then just submit the PR directly as you did (i.e., an issue isn't required for quick fixes like this).

**Review by guardrex — APPROVED** [review]

**Pull request merged**
