### PR TITLE
Fix typo in Setspn command

### LINKED ISSUE #19790: myuser should be myservername
In Section [Windows environment configuration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#windows-environment-configuration) the execute example should be **`setspn -S HTTP/myservername.mydomain.com myservername`** and not `setspn -S HTTP/myservername.mydomain.com myuser` (myservername instead of myuser).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Marusyk**
Fix typo in command according to [docs](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731241(v=ws.11)#adding-spns)

Fixes #19790

### CODE REVIEW

**Comment by blowdart** [comment]
@JunTaoLuo probably has a better idea of whats correct

**Comment by Rick-Anderson** [comment]
@JunTaoLuo quick review please.

**Comment by JunTaoLuo** [comment]
I'm inclined to not make this change. I don't think the user name has to be the same as the server name, even if that is usually the case.

**Comment by Marusyk** [comment]
@JunTaoLuo
Then, please, close issue #19790 with explonation

**Pull request closed without merging**
