### PR TITLE
Update View Compilation to 6.0

### LINKED ISSUE #22028: Add alternative way to conditionally enable runtime compilation of Razor pages
The documentation currently shows one way to conditionally enable runtime compilation of Razor pages, involving setting and environment variable.  I'd be nice to also show an alternative option in `Startup.cs`.

```csharp
// Store IWebHostEnvironment in the Startup's property
public Startup(IConfiguration configuration, IWebHostEnvironment env)
{
  Configuration = configuration;
  Env = env;
}

public IWebHostEnvironment Env { get;}

public void ConfigureServices(IServiceCollection services)
{
   var mvcBuilder = services.AddControllersWithViews();
   if (Env.IsDevelopment())
   {
        mvcBuilder.AddRazorRuntimeCompilation();
   }

    // code omitted for brevity
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### LINKED ISSUE #23910: Runtime compilation not relevant/working in asp.net core 6?
Recently converted from an asp.net core 5 project to a .net 6 one, and it seems that, at least the ["Conditionally enable .."](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio#conditionally-enable-runtime-compilation-in-an-existing-project) is not working anymore in asp.net core 6?

When creating a new asp.net core 6 project from Visual Studio template (which configures the project to use the "Conditionally enable ..." version) even the option seems to have been removed:
.net 5
image

.net 6
image

So the question is, has this feature been replaced by hot-reloading (even when hot-reloading has been disabled)? If yes, then the documentation should probably reflect that.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### LINKED ISSUE #24111: --razor-runtime-compilation is not a valid option in net6.0
Since I've upgraded from .NET 5 to .NET 6 conditional razor runtime compilation no longer works. 

So, in an effort to debug why it's stopped working I noticed that even the `dotnet new ` switch example from the doc does not work either. 

For example: 

```bash
dotnet new webapp --razor-runtime-compilation

Error: Invalid option(s):
--razor-runtime-compilation
   '--razor-runtime-compilation' is not a valid option

For more information, run:
   dotnet new webapp -h
``` 

Could the document be updated with the latest instructions on how to get razor runtime compilation working again as it used to in .NET 5. Making a change to a .cshtml during development should cause a recompile etc.

.NET info

```bash
 dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Computer info

```bash
OS: macOS 11.6 20G165 x86_64
Host: Macmini7,1
Kernel: 20.6.0
Uptime: 7 days, 4 hours, 20 mins
Packages: 313 (brew)
Shell: zsh 5.8
Resolution: 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: AnonymicePowerline 14
CPU: Intel i5-4278U (4) @ 2.60GHz
GPU: Intel Iris
Memory: 10445MiB / 16384MiB
```

And for completeness, in .NET 5 this is all I had to do in order to get my project compiling razor pages in development 

launchSettings.json
 
```json
{
"web": {
            "commandName": "Project",
            "dotnetRunMessages": true,
            "launchBrowser": true,
            "applicationUrl": "https://localhost:5001;http://localhost:5000",
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation",
                "ASPNETCORE_HTTPS_PORT": "5001"
            }
        },
}
```

launch.json
```json
{
    "name": ".NET Core Launch (web)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceRoot}/src/web/bin/Debug/net6.0/web.dll",
    "args": [],
    "cwd": "${workspaceFolder}/src/web",
    "stopAtEntry": false,
    "internalConsoleOptions": "openOnSessionStart",
    "launchBrowser": {
        "enabled": true,
        "args": "${auto-detect-url}",
        "windows": {
            "command": "cmd.exe",
            "args": "/C start ${auto-detect-url}"
        },
        "osx": {
            "command": "open"
        },
        "linux": {
            "command": "xdg-open"
        }
    },
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
    },
    "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
    }
}
```

and in my csproj file

```xml
 <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />
```

Can I also add that adding `AddRazorRuntimeCompilation()` to my `services.AddRazorPages()`  does work but hot reload does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #23910.
Fixes #24111.
Fixes #22028.

[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&branch=pr-en-us-24733&tabs=visual-studio).

### CODE REVIEW

**Comment by serpent5** [comment]
@Rick-Anderson Should I add a note/warning in the article to say that the Hosting Startup Assembly approach is currently broken?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Should I add a note/warning in the article to say that the Hosting Startup Assembly approach is currently broken?

Did https://github.com/dotnet/aspnetcore/pull/39381 fix it?

**Comment by serpent5** [comment]
Yes, that looks like the fix for this. I don't know when it'll be released in a patch.

**Comment by Rick-Anderson** [comment]
@pranavkm  when will https://github.com/dotnet/aspnetcore/pull/39381 be  released in a patch. Should we mention the problem until the patch is released?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Should I add a note/warning in the article to say that the Hosting Startup Assembly approach is currently broken?

Yes, say it will be fixed in the next patch release, then link to dotnet/aspnetcore#39381

**Comment by serpent5** [comment]
@Rick-Anderson Please review with the added warning.

**Pull request merged**
