### PR TITLE
Update DbContextFactory.cs

### PR DESCRIPTION
**Pull request by adamradocz**
I think checking null in the constructor is more elegant, and the code is a little bit simpler.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @adamradocz ... If Jeremy likes it, we'll just need to narrow your code down. OR ... you can do it. Make that so no line is longer than 85 characters to fit the width of our code block display.

**Comment by guardrex** [comment]
Also, I think there's a 5.x sample for this, too, right? If so, can you add the change to that sample app, too?

Finally, we'll need to confirm that the topic isn't highlighting any lines for this bit of code. Our in-topic highlights go by line number; so if a code block changes here in a code file, it can break the highlighting in the topic and highlight the wrong line(s) or highlight no line(s).

I'll help with that last aspect tomorrow. I'm going OOF right now on a major 🧠 **_brain fry_** 🧠😵 for the day. I'll be back on in the morning.

**Comment by guardrex** [comment]
Ok ... made the updates. This isn't part of the 5.x sample, and the topic's text doesn't display anything from this file.

@JeremyLikness ... If you're good with the update, we can proceed to merge.

**Review by guardrex — APPROVED** [review]

**Review by JeremyLikness — APPROVED** [review]
LGTM

**Comment by guardrex** [comment]
Thanks @adamradocz! :rocket:

**Comment by adamradocz** [comment]
@guardrex I just saw your comment, thanks for updating the PR.

**Pull request merged**
