### PR TITLE
VS command-line and env variables /5/ra

### LINKED ISSUE #22326: worth to mention that sending env variable via argument with double `__` doesnt work
this doesnt work in win : 

image

while this does work : 

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#command-line)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #22326
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0&branch=pr-en-us-22343#set-environment-and-command-line-arguments-with-visual-studio)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ghogen I couldn't find this documented in VS after an extensive google search. Shouldn't this be in the VS docs?
cc @IEvangelist

**Comment by Rick-Anderson** [comment]
@TerryGLee @Mikejo5000 who's the right person to review this and better yet move it to the VS docs so I can just link to that.

**Comment by Mikejo5000** [comment]
Looks like setting a command line argument has been typically documented in the platform/language docs rather than VS. That doesn't mean it's the right thing, however. Do you want to merge it for now and I'll create a User Story to investigate and possibly move it? In this case, it's the Debug tab, but the functionality might be better classified as something to do with running your app vs. debugging.

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
> Looks like setting a command line argument has been typically documented in the platform/language docs rather than VS. That doesn't mean it's the right thing, however. Do you want to merge it for now and I'll create a User Story to investigate and possibly move it? In this case, it's the Debug tab, but the functionality might be better classified as something to do with running your app vs. debugging.

Yes, that would be great.

**Pull request merged**
