### PR TITLE
Merge to live - 5/4

### PR DESCRIPTION
**Pull request by guardrex**

### CODE REVIEW

**Comment by guardrex** [comment]
@scottaddie Do you want to do the honors here?

..... or risk my taking down this whole repo :boom: ... and a few others along with it! 😜 lol

**Comment by guardrex** [comment]
Looks like "Electron" was added to the topic outside of the no-loc PR that went in ...

```
no-loc: [Electron]
```

https://github.com/dotnet/AspNetCore.Docs/blob/live/aspnetcore/security/samesite.md

 A quick fix might be to commit ...

```
no-loc: [Blazor, "Identity", "Let's Encrypt", Razor, SignalR]
```

... to the `live` branch *samesite.md* topic.

**Comment by Rick-Anderson** [comment]
@guardrex  I'll fix this

**Comment by Rick-Anderson** [comment]
Wow - amazing work, only one tiny merge conflict.

**Comment by guardrex** [comment]
Cool thanks 

... I don't mind screwing around with one of my branches. I don't like messing about with this one. 😨

**Comment by guardrex** [comment]
One thing tho @Rick-Anderson ... that fix breaks the 'we can find and replace on the whole repo' for future no-loc words. Did you want to do a new PR that adds "Electron" to all of the topics?

**Comment by Rick-Anderson** [comment]
@guardrex  I'd like to avoid that approach for now. See #18138

**Pull request merged**
