### PR TITLE
Min API param binding with record /1

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Contributes to #26540
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26897#parameter-binding-for-argument-lists)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
## Public review  of the doc build:
- download the [HTML files](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
- unzip
- view HTML file in a browser.
- For links outside the doc, remove the `review.` from URL.
@martincostello  please review

**Comment by martincostello** [comment]
The content here looks fine to me. I wonder if it's worth mentioning in the prose that the same attributes that apply to parameters (`[FromRoute]`, `[FromBody]`, `[FromServices]`, etc.) also work with the type used for `[AsParameters]` and cross-reference to wherever else in the docs that was originally explained for .NET 6 and parameter binding?

**Comment by Rick-Anderson** [comment]
@martincostello I think we need to add `[AsParameters]` to [Binding Precedence](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#binding-precedence)

Do you know where it goes  on that list?

**Comment by martincostello** [comment]
[Looking at the code](https://github.com/dotnet/aspnetcore/blob/7d1e7b192298f4c269de1c1afcc80ad5c5abb3dd/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L711-L720), it looks like it goes after `[FromServices]`.

**Comment by brunolins16** [comment]
@Rick-Anderson since `struct` are the most optimized scenario, what do you think about show that usage in the examples instead? Maybe mentioning that a `class` also works.

**Comment by brunolins16** [comment]
> The content here looks fine to me. I wonder if it's worth mentioning in the prose that the same attributes that apply to parameters (`[FromRoute]`, `[FromBody]`, `[FromServices]`, etc.) also work with the type used for `[AsParameters]` and cross-reference to wherever else in the docs that was originally explained for .NET 6 and parameter binding?

Maybe also include something related to the fact that it is not a complex model binding (recursive as MVC) and instead it iwll just expand the `properties` are handler `parameters`.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson since `struct` are the most optimized scenario, what do you think about show that usage in the examples instead? Maybe mentioning that a `class` also works.

@martincostello  would you be able to PR your [arg-lists sample](https://github.com/dotnet/AspNetCore.Docs.Samples/commits/main/fundamentals/minimal-apis/samples/arg-lists) and change it to structs?  Feel free to keep that sample and add a struct version.

**Comment by martincostello** [comment]
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/41

**Pull request merged**
