### PR TITLE
Add what's new page for June 2020

### PR DESCRIPTION
**Pull request by scottaddie**
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19117

[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/whats-new/2020-06?view=aspnetcore-1.0&branch=pr-en-us-19111)

### CODE REVIEW

**Comment by scottaddie** [comment]
@Rick-Anderson @wadepickett Is there anything you'd like to add to the list?

**Comment by Rick-Anderson** [comment]
Missing label SC PR's 
[is:pr label:SC ](https://github.com/dotnet/AspNetCore.Docs/pulls?q=is%3Apr+label%3ASC)

**Comment by Rick-Anderson** [comment]
I thought we were going to open a issue for the next month on "What's new" to list SC PR's or should we keep using the SC label?

**Comment by scottaddie** [comment]
@Rick-Anderson Thanks for the reminder. I picked up the SC PRs.

**Pull request merged**
