### PR TITLE
Update MongoDB Web Api to 6.0

### LINKED ISSUE #16196: Container list: Create a web API and MongoDB
18,666 PV
---
This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.

- [x] Replace NewtonSoftJson reference for Version 3.1 and newer #20791
- [x] Using asynchronous MongoClient APIs #21991
- [x] Suggestion: Add clarification for <port> in 'Test the web API' section #21920
- [x] Book Class #20773
- [x] MonoDB Rest API Tutorial : explain port #20488
- [x] The Startup.cs snipet is missing the following code. The current version produces an error where 'Configuration' doesn't get resolved #16514
- [x] MongoDB C# driver support #15942
- [x] ReplaceOne() method not working properly on .Net Core 3.0 #14829
- [x] MongoDB tutorial: Update to 3.0 and use proper snippets #14651
- [ ] what is the point to use Pascal casing in json to match CLR object's property names? #14623
- [x] Something about this article need adjusts #17256
- [x] Something about this article need adjusts #17271
- [x] Error in example code #17692
- [x] HTTP 500 thrown on a POST with the code from this document #17518
- [x] Does MongoDb .Net Drive use System.Text.Json? #18409
- [x]  ArgumentNullException: Value cannot be null. (Parameter 'name') #21105
- [x] Add additional JSON property so Swagger looks like non Swagger URL #21836
- [x] Missing information #23435

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

### LINKED ISSUE #24017: .NET 6 update: Create a web API with ASP.NET Core and MongoDB
[Enter feedback here]
I am a newer to asp.net and webapi, when I follow the instruction in this page, no Startup.cs file was found in my project, so that I can not follow the instruction. are there some disaccordings in the latest template in vs studio community edtion and the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #24017.
Fixes #16196.

[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&branch=pr-en-us-24126&tabs=visual-studio).

### CODE REVIEW

**Comment by serpent5** [comment]
@Rick-Anderson I think this fixes all the actionable items on the rather hefty [container issue](https://github.com/dotnet/AspNetCore.Docs/issues/16196), too.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I think this fixes all the actionable items on the rather hefty [container issue](https://github.com/dotnet/AspNetCore.Docs/issues/16196), too.

**FANTASTIC*** would you mind opening each container issue, pasting `Fixed in #24126`  and closing. That way everyone is notified.

**Review by Rick-Anderson — APPROVED** [review]
Amazing work! This has been a problem for 3 years.

**Comment by serpent5** [comment]
> That way everyone is notified.

Done. 😅

**Pull request merged**
