### PR TITLE
Add cross-link to SignalR auth guidance

### LINKED ISSUE #26648: Solution for Blazor WebAssembly does not work
I tried the solution for blazor wasm (ASPNET core hosted) and I still get the unauthorized response on connecting to a hub with Authorize attribute. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #26648

### CODE REVIEW

**Comment by guardrex** [comment]
@Cage-e ... Do you want to test with the SignalR authn/z guidance at ...

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0#authenticate-users-connecting-to-a-signalr-hub

... to see how cleanly it will apply (and even that it works OOB directly from that topic)? You could let me know about any problems associated with merely cross-linking this Blazor-SignalR article section to the SignalR authn/z topic's section. I'm a bit worried about this. I'm not really a "SignalR dude" in that I've never used it professionally. Therefore, I usually need to perform local testing to confirm that any given guidance is correct or requires additional notes or gotcha 😈 remarks. If you're planning on working your app forward based on Javier's remark (and the SignalR doc), it would be helpful if you let me know how it turns out and if this cross-link is sufficient here. If not, no worries ... I think that I'll mark this a draft PR for the moment and run some local tests to see what's what.

**Comment by guardrex** [comment]
I don't think this is going to cut it. I think it will need an example. Going by what Javier said, it will go something like this (I guess 🤔) based on our SignalR-Blazor WASM tutorial/sample app ...

```razor
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inject IAccessTokenProvider TokenProvider

...

var tokenResult = await TokenProvider.RequestAccessToken();

if (tokenResult.TryGetToken(out var token))
{
    hubConnection = new HubConnectionBuilder()
        .WithUrl(NavigationManager.ToAbsoluteUri("/chathub"), options => { options.AccessTokenProvider = () => Task.FromResult(token); })
        .Build();

    hubConnection.On<string, string>("ReceiveMessage", (user, message) =>
    {
        var encodedMsg = $"{user}: {message}";
        messages.Add(encodedMsg);
        StateHasChanged();
    });

    await hubConnection.StartAsync();
}
```

I'm thinking that I will run a full test of this to see how it goes here. I'll use our basic AAD hosted WASM guidance at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0

... then add in the SignalR bits from our SignalR-Blazor tutorial at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly

... then add `[Authorize]` to `ChatHub`. It should ...

* Fail before a user is signed into the app with AAD.
* Work after the user is signed in.

... **_in theory!_** 😆 ... I've never worked with SignalR + authn/z before, so we'll see how it goes. If that's all good, then I'll flesh out a full bit on this for the *Security and Identity* > *Blazor WebAssembly* node. For good measure, I'll cross-link it from both the *Fundamentals* > *SignalR* topic and the *SignalR-Blazor tutorial* topic.

**Comment by Cage-e** [comment]
I was just pushing the solution to the issue repo I had made. 
Yes this fixes the problem. although I think there is a slight build error in it. did a quick test but yes basically providing  the AccessTokenProvider  func to the connection solves it. 
Here is my commit for the solution if it helps:
https://github.com/Cage-e/HubAuth/commit/5af089f0c5d63c6ea7dc880b34b6492a479b4d45

My hub so far is not very sophisticated. Basic Authorization was what I needed, which found the solution. I will get in touch if I found any other issue.  Let me know if I could be of any help anyways.

Thanks for the help and tips. :)

**Comment by guardrex** [comment]
# 🎉

That's great news. I'm glad it worked out.

I'm still going to test myself and see if I can integrate the ADD and Blazor-SignalR topics with the example code that I devise. That way, I can rely on those existing topics and their demonstrations.

I think I won't bother with the auth state in the approach that you took. If I do that at all, I'll just apply the attribute to the component. The critical bit is the `options.AccessTokenProvider` piece for the hub connection with the decorated hub.

**Comment by guardrex** [comment]
@Cage-e ... I see what you mean now that I'm working with real code in VS. Did you try it this way ......

```csharp
var tokenResult = await TokenProvider.RequestAccessToken();

if (tokenResult.TryGetToken(out var token))
{
    hubConnection = new HubConnectionBuilder()
        .WithUrl(NavigationManager.ToAbsoluteUri("/chathub"), 
            options => { options.AccessTokenProvider = () => Task.FromResult(token?.Value); })
        .Build();

    ...
}
```

I see that it's looking for a string there (nullable), and I suspect now that `token?.Value` will work.

**Comment by guardrex** [comment]
@Cage-e ... I think I can roll with this without my explicitly testing it. I'm 🏃 on a lot of issues right now, especially .NET 7 work. It's best if I can go with coverage that 👀 looks right, then take further reader feedback. See the latest diff. How do you think this looks now?

**Comment by Cage-e** [comment]
@guardrex  I tested your diff and I confirm that it works. 
Pushed my [commit ](https://github.com/Cage-e/HubAuth/commit/04b0ce35fa1917698b12bce676196853379a7ae0)too as your code was smoother :)

**Comment by guardrex** [comment]
Great ... thanks for checking. Let's go with this for now and take further reader feedback. 🏃🏃🏃🏃

**Pull request merged**
