### PR TITLE
Document dev tunnels features added in 17.5 Preview 3 and later.

### LINKED ISSUE #28295: Document dev tunnels features added in 17.5 Preview 3 and later.
* The context menu in the dev tunnels Tool Window. 
  * Clear Active Tunnel: when a tunnel is configured as active (indicated by the checkmark on the left hand side), this will reset it to not using a tunnel.
  * Copy Tunnel Access Token: for scenarios where a tunnel is created with private or org access and the underlying app is not a web app serving HTML, so a Web API, users need to copy and paste the Tunnel Access Token as a header in the request. This will authenticate the tunnel and then forward the request. If this token is not specified, the request will be blocked because the auth check failed. Every time this is called a new token will be generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc01239c-b0fa-599f-506f-810572b43b1f
* Version Independent ID: cc01239c-b0fa-599f-506f-810572b43b1f
* Content: [Dev tunnels in Visual Studio 2022](https://learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?view=aspnetcore-7.0)
* Content Source: [aspnetcore/test/dev-tunnels.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/dev-tunnels.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 62266](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62266)

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #28295 

[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?branch=pr-en-us-28304)

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by sayedihashimi** [comment]
It looks good, I left a minor comment.

**Comment by tdykstra** [comment]
> It looks good, I left a minor comment.

I don't see the comment.

**Comment by sayedihashimi** [comment]
It’s above 
59CA8659-94DF-43AC-8F51-EB83557C5368

**Comment by tdykstra** [comment]
Thanks, I changed project to solution. Accidentally committed directly to main instead of creating a follow-up PR (commits to main aren't protected to require PR in this repo).

**Comment by sayedihashimi** [comment]
Thanks Tom.

**Pull request merged**
