### PR TITLE
Add preview2 Blazor linker changes

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17196

### CODE REVIEW

**Comment by pranavkm** [comment]
This includes preview2 specific changes. Please hold off on merging it until that's shipped

**Comment by guardrex** [comment]
Reviewing and merging now.

This one will go live when the Blazor WebAssembly sample app is also merged and I make any CSP topic updates, if needed. It should go live within an hour.

**Comment by pranavkm** [comment]
Good to go now

**Comment by guardrex** [comment]
I'm just touching up the grammar+style bits. Will only take a few minutes.

**Pull request merged**
