### PR TITLE
Blazor lifecycle diagram and coverage

### LINKED ISSUE #16287: Lifecycle diagram and coverage
[EDIT by guardrex to expand issue based on the engineering docs issue] 

Might be good to include a 'Component Lifecycle' diagram like the Vue Team have done. I've always found the Microsoft docs in general lacking in visual cues. This would be a perfect place to start!

Also address: [Add or improve docs for lifecycle methods (dotnet/aspnetcore #13473)](https://github.com/dotnet/aspnetcore/issues/13473)

**From the original [Improve Blazor component lifecycle page (aspnet/AspNetCore.Docs #14353)](https://github.com/aspnet/AspNetCore.Docs/issues/14353) issue (_closed now_)** ...

Expand content to include:

* A detailed description of what happens in what order, including:
    * How async tasks affect this
    * When (re)rendering is interleaved into this
    * How things are ordered among parent/child components
    * What kinds of work you're expected to do in each of the methods
 * Relationship with `Dispose`
    * Example: Pattern for cancelling background work
 * Relationship with JS interop
    * Example: Initializing a JS library by passing an `ElementReference`

### From DR on the PR to create the initial *Lifecycle* topic

Instead of focusing purely on the lifecycle events I think we want this article to explain more broadly how components work, like how and when the render. We should walk the user through a day in the life a component in a Blazor app. The lifecycle events are then just specific points that you can plugin your specific behaviors. 

Things that I think should be covered:
- What happens during the initial render of the app
  - We probably need to address prerendering as part of this
- When components get instantiated
- When services get injected from DI
- What happens when a parent/root component gets rendered
- When do components render after the initial render
  - In response to UI events and explicit calls to StateHasChanged
- How long do components life for? When do they get disposed?

WRT the short *State changes* (`StateHasChanged`) section ...

I think this section would fit in better with a broader description of how and when components get rendered. Right now this section on StateHasChanged feels a bit out of context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bae853d-80e3-ef81-69eb-e8276eb853fe
* Version Independent ID: 01216f14-b45c-73b0-9f1f-300e7ddd788f
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/lifecycle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #16287

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1&branch=pr-en-us-19543)

### CODE REVIEW

**Comment by danroth27** [comment]
@guardrex I think all of the changes you proposed sound good, except the addition of the SetParametersAsync in the first image during the property injection step. I don't think those are really related.

@SteveSandersonMS Component disposal isn't currently included in these diagrams. Other community diagrams that I've seen include it. Should we as well?

I think it's also import that include some mention of how Blazor evaluates whether a child component should be rendered on subsequent renders. High level, if the parameter values can be guaranteed to be the same then the child component won't be rendered. @SteveSandersonMS Do you agree that these details should be included? If yes, could you please provide the specifics?

**Comment by guardrex** [comment]
If I'm to perform the updates that I listed (perhaps after you, @SteveSandersonMS, make further updates :point_up:), can the PPT be emailed as an attachment to me? I can't access the provided link to that file.

**Comment by guardrex** [comment]
@danroth27 ...

* Does it make sense to place the events (*Parent renders*, *DOM event*, and *Render*) outside of the flow diagrams?
* Spot other changes?

lifecycle1

lifecycle2

lifecycle3

**Comment by guardrex** [comment]
@danroth27 Are the latest versions of the images in good shape? :point_up: https://github.com/dotnet/AspNetCore.Docs/pull/19543#issuecomment-679255776

**Comment by guardrex** [comment]
@danroth27 Do you need more 🕐 time before looking at these other ones? There's this one ... the images for the lifecycle topic ... and ...

* Integrate components (Javier never looked AFAIK) on https://github.com/dotnet/AspNetCore.Docs/pull/19887
* Overview updates on https://github.com/dotnet/AspNetCore.Docs/pull/20005
* Tooling updates on https://github.com/dotnet/AspNetCore.Docs/pull/20026

**Pull request merged**
