### PR TITLE
Generic type guidance enhancements

### LINKED ISSUE #23843: Remove Blazor templated components NOTE
For the *Infer generic types based on ancestor components* section at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-6.0#infer-generic-types-based-on-ancestor-components

Remove the following NOTE from the topic when VSC Razor support is available ...

> The Razor support in Visual Studio Code hasn't been updated to support this feature, so you may receive incorrect errors even though the project correctly builds. This will be addressed in an upcoming tooling release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698a8824-7a38-70d6-c041-0dca4c040217
* Version Independent ID: ae663e33-6a08-0b24-aa19-3fc3c9edccfc
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #23843

[Internal Review Link (links directly to the 'Generic type parameter support' section](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-6.0&branch=pr-en-us-24724#generic-type-parameter-support)

For max clarity, I think we should demonstrate the cascading generic type concepts with explicit and inferred types separated in a pair of sub-sections. The approach of explicit types is *very relevant* given Steve's remarks on the PU design issue (his *In scope* section). For example, explicit types overrule inferred types, are definitely supported, and might make more sense (or be required) in some scenarios (e.g., cascading values with `[CascadingParameter]`).

Especially important to me is to improve the current guidance that doesn't use fully-working, cut-'n-paste examples.

Another pair of approaches is to either supply different data to child components of the `RenderFragment` or pass the same data to the children via a `CascadingParameterAttribute`.

After a bit of trial-and-error experimentation 😅, this PR seems to show that these various approaches can be laid out cleanly.

## *NOTES*

* Although the latest doc coverage effort prior to this PR was specifically addressing **_inferred_** types, all of the guidance for generic types needed work. This PR is aimed at addressing the whole subject of generic types, not just inferred types.

* There are some code comments in the doc to help with reviewing this. Those code comments will be removed before merging the PR. You only need to review the doc itself ... ` aspnetcore/blazor/components/index.md`.

* The 6.0 PU design issue is here :point_right: [Infer component generic types from ancestor components (dotnet/aspnetcore #29349)](https://github.com/dotnet/aspnetcore/issues/29349)

## ❓ *QUESTIONS* ❓ 

1. The guidance is NOT to supply a type parameter with a generic name, for example `T` or `TItem`. However, I am using `TExample` ... because these are doc examples. Should we change `TExample` here to something more specific and drop the `T` part of the name? ... or because this is just a doc example, is it ok? 👂 

1. It looks like generic array params were addressed for 6.0 on https://github.com/dotnet/aspnetcore/pull/34734. This is [Steve's repro](https://github.com/dotnet/aspnetcore/issues/29105#issuecomment-884041958) of what was breaking ...

   ```csharp
   [Parameter]
   public T[] Items { get; set; }
   ```

   ```razor
   <SomeComponent T="string" Items="@(Array.Empty<string>())"></SomeComponent>
   ```

   Given that it was addressed for 6.0, such approaches should ✨ **_Just Work!_**&trade; ✨ now. I don't think we need to say anything specific about it, but let me know ... and what to say/show if you have something specific in mind. 👂

1. I'm only mildly concerned at this time about not further providing a full example of a `where` type constraint. If you have a concept (or fully-working, cut-'n-paste code example) that you'd like to see in the doc, I'm 👂 for it. If we don't go further than just saying this construct exists, that's fine with me. We aren't getting negative feedback on it. I think devs are ok at this time with what we have, but do you want to make any improvements? 👂 

   ```razor
   @typeparam TEntity where TEntity : IEntity
   ```

## My usual disclaimer

mccoy

### *I'm a doc author, not a framework engineer!* 🤣

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&mdash; Dr. Leonard H. "Bones" McCoy ([DeForest Kelley](https://en.wikipedia.org/wiki/DeForest_Kelley)) [Star Trek](http://www.startrek.com/), ©1966-69 [Paramount Pictures](http://www.paramount.com)

# 🇺🇦

### CODE REVIEW

**Comment by guardrex** [comment]
@TanayParikh ... **_Still NO RUSH on this one._** It's got some meat on it 🍖, and it takes a while to sort through the bits. Even if you need a few weeks/a month, it's cool. When you get to this, I ask a couple of important ❓ in the opening remarks ☝️. I'll react to your feedback and ping u back one last time on the updates given that I don't want these updates to go sideways on me.

### NOTE TO SELF

Don't forget **_GooberRex_**&trade; to kill 🔪 the inline comments that you left for review **_BEFORE_** merging the PR. 😆

**Comment by TanayParikh** [comment]
> **_Still NO RUSH on this one._** It's got some meat on it 🍖, and it takes a while to sort through the bits. Even if you need a few weeks/a month, it's cool

Thanks @guardrex. I'm tied up with a few issues & build ops at the moment. I'll return to this when I have some more time available. I want to ensure I give this a proper read and understand any nuances at play.

**Comment by guardrex** [comment]
Sure thing, @TanayParikh. I'll mark it *DRAFT* for the time being.

**Comment by guardrex** [comment]
@TanayParikh ... When you reach this ... again, **_no rush on it_** ... Javier asked me to add a piece per a product unit issue ...

**Blazor CascadingTypeParameter does not pass type parameter to children that have multiple type parameters**
https://github.com/dotnet/aspnetcore/issues/39994

I vaguely understand ... but not enough from the limited context to know exactly where to place a remark and exactly what it should say.

For one thing, the guidance doesn't address the **_multiple cascaded types_** scenario. More broadly than a calling out the limitation described on the PU issue, I wonder if we need a description (and possibly with an example) of cascading multiple types support. It doesn't necessarily need to be a full example, just a couple of lines of code after one of the existing examples ... or maybe it does need to be a complete example ... perhaps text + a fully working example in it's own H3 section.

If I find some time within in the next couple of weeks (I'm 🏃😅 on other issues for a while), I'll play with the scenario and see if I can come up with text/example(s). If you reach this PR for review before I get back to it, I can go off what you say to do ... add your example, if you have one in mind ... or at least at the minimum just add text to cover the limitation that Javier called out. You can provide the content in an issue comment, and I think you could simply provide me the line number from the diff where it should be placed.

**Comment by guardrex** [comment]
@TanayParikh ... I'm going to go ahead and get this merged. It should be fine. The community doesn't let me get away with too much around here 😄. The original ❓ in the opening comment are **_not blocking_**, and I added the bit for Javier's request to tell devs that values for all generic types in the set must be passed.

**Pull request merged**
