### PR TITLE
[Blazor] SSR Threats - N^2

### PR DESCRIPTION
**Pull request by hakenr**
Excessive characters removed.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/security/server/static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/f39be59f04a8cb3a568063da9e2af799848b32b8/aspnetcore/blazor/security/server/static-server-side-rendering.md) | [Threat mitigation guidance for ASP.NET Core Blazor static server-side rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/static-server-side-rendering?branch=pr-en-us-34065) |

### CODE REVIEW

**Comment by guardrex** [comment]
This is OK 👍. It's markdown for superscript.

**Comment by hakenr** [comment]
@guardrex Maybe, but it’s not supported by the docs platform:  

image

Should we replace it with `<sup>2</sup>`?

**Comment by guardrex** [comment]
I see. I'll report that to them.

Yes, please make that change.

**Review by guardrex — APPROVED** [review]
I found out that CommonMark's management refused to support superscript/subscript markdown syntax. HTML is the right approach.

I searched the repo, and this is the only spot to fix.

Thanks again!

**Comment by hakenr** [comment]
I hope this won't break the PDF export.

**Comment by guardrex** [comment]
It *should* fully support HTML. 🤞🍀

**Pull request merged**
