### PR TITLE
merge to live

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by guardrex** [comment]
@hishamco ... It looks like https://github.com/dotnet/AspNetCore.Docs/pull/19905 this morning introduced some build errors ... can you fix them? ... or should I try? I don't want to merge to live until we've resolved these.

Warning	User
codesnippet-not-found
aspnetcore/fundamentals/localization.md
Invalid code snippet link: 'localization/sample/3.x/Localization/Resources/SharedResource.cs'.
53, 1

Warning	User
codesnippet-not-found
aspnetcore/fundamentals/localization.md
Invalid code snippet link: 'localization/sample/3.x/Localization/Resources/SharedResource.cs'.
407, 1

Warning	User
codesnippet-not-found
aspnetcore/fundamentals/localization.md
Invalid code snippet link: 'localization/sample/3.x/Localization/Resources/SharedResource.cs'.
762, 1

**Comment by hishamco** [comment]
Seems there's a warning in the docs, I will fix them now ...

**Comment by guardrex** [comment]
Thanks @hishamco ... I'll stand-by on this merge to live.

**Comment by hishamco** [comment]
Just few minutes ...

**Comment by hishamco** [comment]
@guardrex fixed in #19910, sorry I didn't notice the warnings when I test the app

Thanks

**Pull request merged**
