### PR TITLE
Add Include not-latest-version or not-ga-yet

### PR DESCRIPTION
**Pull request by wadepickett**
Contributes to #32886

1st of several PR's.

Addresses all applicable files from folder in alpha order through fundamentals/.
Skipping the following folders:
* blazor/ (guardrex has already done this one.
* diagnostics/  These topics didn't seem like they would fit the need.

Docs with monikerRange: '< aspnetcore-8.0' or without any monikerRange at the top of the page get:

```
[!INCLUDE[](~/includes/not-latest-version.md)]

```

Docs with monikerRange: '>= aspnetcore-8.0' get:

```
<!-- UPDATE 9.0 Activate after release and INCLUDE is updated

[!INCLUDE[](~/includes/not-latest-version.md)]

-->
```

Docs with monikerRange: '>= aspnetcore-9.0' get:

```
[!INCLUDE[](~/includes/not-ga-yet.md)]

<!-- Uncomment this when 9.0 is the default value in the version selector and delete not-ga-yet.md

[!INCLUDE[](~/includes/not-latest-version.md)] 

-->
```

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-33155) |
| [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/data/ef-rp/crud.md) | [Part 2, Razor Pages with EF Core in ASP.NET Core - CRUD](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?branch=pr-en-us-33155) |
| [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/data/ef-rp/intro.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md) | ["RDG001: Unable to resolve route pattern"](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg001?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md) | [RDG002: Unable to resolve endpoint handler](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg002?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg003?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md) | [RDG004: Unable to resolve anonymous type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg004?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md) | ["RDG005: Invalid abstract type"](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg005?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md) | [RDG006: Invalid constructor parameters](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg006?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg007?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md) | [RDG008: Multiple public constructors](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg008?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md) | ["RDG009: Invalid nested AsParameters"](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg009?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md) | [RDG010: InvalidAsParameters Nullable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg010?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg011?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md) | [RDG012: Unable to resolve inaccessible type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg012?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md) | ["RDG013: Invalid source attributes"](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg013?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md) | [ASP.NET Core Request Delegate Generator (RDG) diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg-ids?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/rdg](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/best-practices.md) | [ASP.NET Core Best Practices](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/change-tokens.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/change-tokens.md) | [Detect changes with change tokens in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/environments.md) | [Use multiple environments in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/file-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/file-providers.md) | [aspnetcore/fundamentals/file-providers](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/host/platform-specific-configuration.md) | [Use hosting startup assemblies in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/http-context.md) | [Access `HttpContext` in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/http-requests.md) | [aspnetcore/fundamentals/http-requests](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-33155) |
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/2636a6041a463cdb1d6692aad3f5bc456a641144/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for Native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-33155) |

</details>

> [!NOTE]
> This table shows preview links for the 30 files with the most changes. For preview links for other files in this PR, select <strong>OpenPublishing.Build Details</strong> within [checks](https://github.com/dotnet/AspNetCore.Docs/pull/33155/checks).

### CODE REVIEW

**Comment by wadepickett** [comment]
@tdykstra, what should we do with topics that have no moniker versioning at all except perhaps for say, 2.0 inline for some specific paragraph.  Do we leave those out of this for now?
Here is an example from this build:
https://review.learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-9.0&branch=pr-en-us-33155

**Comment by tdykstra** [comment]
> @tdykstra, what should we do with topics that have no moniker versioning at all except perhaps for say, 2.0 inline for some specific paragraph. Do we leave those out of this for now? (I left them out of this 1st PR) Here is an example from this build: https://review.learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-9.0&branch=pr-en-us-33155

In the PR description box:
Docs with monikerRange: '< aspnetcore-8.0' 
-->
Docs with monikerRange: '< aspnetcore-8.0' or without monikerRange

**Comment by wadepickett** [comment]
Thanks!  I'll update the issue and PR descriptions.

**Comment by wadepickett** [comment]
If these look good to you and I can merge, then I will finish with the other PR's today, around 50 or so file changes per PR.

**Comment by wadepickett** [comment]
Just tested two topics that without MonikerRanges at the top, the include errors, so I backed them out so we can at least get this PR approved and merged.

In the next PR I will have to figure out where and why the include is breaking down on there.  

I have the feeling it would have been better to _not_ to try to handle any logic in the include itself for versioning, and just left that to tooling and regx for adding or removing an include with just the text needed.

**Review by tdykstra — APPROVED** [review]

**Comment by tdykstra** [comment]
> I have the feeling it would have been better to _not_ to try to handle any logic in the include itself for versioning, and just left that to tooling and regx for adding or removing an include with just the text needed.

Feel free to try that approach and if it works out better we can change it everywhere with a regex

**Pull request merged**
