### PR TITLE
Update markdown for UI element

### PR DESCRIPTION
**Pull request by l87y7m**
The two wrapping asterisks being rendered was confusing. Per text formatting guidelines, UI elements should be bold not code.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24876) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24876) before we can accept your contribution.<br/><br/>:x: l87y7m [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24876)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=24876) it.</sub>

**Comment by guardrex** [comment]
Thanks for sending this in, @l87y7m. Rick will be along in a bit to review.

Note in passing WRT "UI elements should be bold not code" ... it often doesn't work out for us because project templates, sample apps, example code, and parts of the IDEs (VS, VSC, VS4Mac) **_are not localized_**. When we don't code-fence this text, the localization engine machine translates the text automatically into other languages that then often doesn't match what the dev sees when they work with samples/examples.

**Comment by l87y7m** [comment]
> Note in passing WRT "UI elements should be bold not code" ... it often doesn't work out for us because project templates, sample apps, example code, and parts of the IDEs (VS, VSC, VS4Mac) **_are not localized_**. When we don't code-fence this text, the localization engine machine translates the text automatically into other languages that then often doesn't match what the dev sees when they work with samples/examples.

In this case, I may need to make the inverse change to leave the code fence, but remove the bold markdown. This would prevent the translation and remove the confusion from the two asterisks rendering.

**Comment by guardrex** [comment]
Oh, yes ... I see what you mean. Rick will be along in a bit. Wait for him to remark on this. He'll know what to do and advise further.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
Thanks for the fix. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

**Pull request merged**
