### PR TITLE
Set up localization.md for version >=6

### LINKED ISSUE #28522: Set up localization.md for version >=6
Put .NET 3 and .NET 5 versions in includes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 66585](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66585)

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #28522 

File Type | File Name | Published Url
-- | -- | --
content | aspnetcore/fundamentals/localization.md | https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-8.0&branch=pr-en-us-28523
content | aspnetcore/fundamentals/localization/make-content-localizable.md | https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?view=aspnetcore-8.0&branch=pr-en-us-28523
content | aspnetcore/fundamentals/localization/provide-resources.md | https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/provide-resources?view=aspnetcore-8.0&branch=pr-en-us-28523
content | aspnetcore/fundamentals/localization/select-language-culture.md | https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?view=aspnetcore-8.0&branch=pr-en-us-28523

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
Assuming all the content now uses absolute paths `[!code-csharp[](~/fundamentals/localization/`

**Comment by tdykstra** [comment]
Yes, when I moved text to includes the build found all the remaining relative links.

**Comment by Rick-Anderson** [comment]
> Yes, when I moved text to includes the build found all the remaining relative links.

But what about the current version that's not moved? I like to change them all. The new standard is absolute paths everywhere, no more relative. Then next version when we need to move current version to the include file, it's a copy/paste and no path fix ups.

**Comment by tdykstra** [comment]
I'll double-check to make sure I didn't miss any.

**Comment by Rick-Anderson** [comment]
I do a global search/replace for all open windows.

**Comment by Rick-Anderson** [comment]
`[](razor-pages-start/`
`[](~/somePath/razor-pages-start/`

**Pull request merged**
