### PR TITLE
Updated documentation on VS Publish to match the UX that shipped in the latest stable release (16.6)

### LINKED ISSUE #18366: Screenshots / steps out of date
The latest version of Visual Studio (16.6) looks and behaves differently than this article describes. That's because Publish in Visual Studio has been getting UX updates in the last few releases.

I own this feature in Visual Studio so if you need any help updating this content just let me know. I'm happy to submit PRs or whatever the right process is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.1&viewFallbackFrom=vs-2019)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by AngelosP**
Fixes #18366

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Looks great. Thanks @AngelosP

**Comment by Rick-Anderson** [comment]
@AngelosP  I did a merge to live so you changes will be visible in 10 minutes. Thanks again.

**Comment by AngelosP** [comment]
@Rick-Anderson thank you!

**Comment by AngelosP** [comment]
@Rick-Anderson I still see the old content [in the tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.1)

**Pull request merged**
