### PR TITLE
Cross-link Nginx subdirectory hosting post

### LINKED ISSUE #15464: Deploy to subdirectory
I need to host multiple apps in the same server under different subdirectories, for example http://myserver/myfirstapp and http://myserver/mysecondapp.
I tried to set up nginx with multiple locations, but request from browser can't seem to reach the app (404). It seems like the app works only if put on root (location /).
Need guidance on how to set up multiple apps in subdirectories with nginx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #15464

Sourabh, do you think we can cross-link @ndc's blog post for coverage on Nginx subdirectory hosting? I'm going to leave a comment in the topic here for a future rewrite to consider placing a section on this subject into the topic. I'm *very busy* 🏃😅 right now, so this is the best scenario for me at the moment.

btw - We've successfully used in-topic comments to message ourselves. It eliminates the need to keep an issue on the repo that might (*probably will be*) lost.

### CODE REVIEW

**Comment by guardrex** [comment]
Ping @shirhatti ... quick-ish look on this one.

**Comment by shirhatti** [comment]
I thought there was a policy against preventing us from linking to assets that we don't control from the docs.

@mairaw can probably confirm if there is a policy
 
Even if there isn't a rule, I'd be wary of linking to an external source that doesn't have HTTPS 😱

**Comment by guardrex** [comment]
@shirhatti Discussion goes back as far as DR's original remark on the subject at ...

https://github.com/dotnet/AspNetCore.Docs/issues/125#issuecomment-109008003

... but there isn't a formal policy that we're able to follow because the decision is subjective to a great degree. We **_generally don't link for important content_**. This ... this PR ... is one of those cases where I'd prefer to link to Nginx docs, but they won't contain the `UsePathBase` piece.

Alternatives:

1. Ask Endy for the content, edit and place into the topic, and provide authorship.
1. Delay until we can get free ... idk how long tho. We have issues sit for several months.

**Comment by mairaw** [comment]
Just FYI - we avoid linking to external assets but there's no rule preventing us from doing that.

**Comment by guardrex** [comment]
Thanks @mairaw ... I'll work this ... it shouldn't take too long. I've scheduled it for August. I'm still 🏃😅 to get caught up on Blazor issues right now.

**Pull request closed without merging**
