### PR TITLE
Merge to live

### PR DESCRIPTION
**Pull request by Rick-Anderson**
@guardrex  as soon as What's new in ASP.NET Core 5 #20140 merges, can you merge this?

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson 

**UPDATE** ... I'm still keeping an :eye: on the What's New PR. I'll merge this after that goes in unless you let me know otherwise.

**Comment by guardrex** [comment]
@Rick-Anderson There's a warning here for some API that won't be available until GA ...

>  Cross reference not found: 'Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions.RequestHeaderEncodingSelector'.

Do you want to go ahead, or should I code-fence that reference?

**Comment by Rick-Anderson** [comment]
Let's code fence for now. I can fix that.

**Comment by guardrex** [comment]
ok ... and ur here (awake-wise I mean :smile:), so I guess you'll merge this to live.

**Pull request merged**
