### PR TITLE
advise user to set Nullable property to disable

### PR DESCRIPTION
**Pull request by LayersOfAbstraction**
This fix disables the `<Nullable>` setting and will allow the user to create and update database records in SQL Server Local DB. This works in ASP.NET 6 and was originally report by @savionlee in #24541 

So to recap the nullable property in .csproj has been changed from:

```xml
<Nullable>enable</Nullable>
```

```xml
<Nullable>disable</Nullable>
```

This is the correct branch.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27259) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27259) before we can accept your contribution.<br/><br/>:x: LayersOfAbstraction [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27259)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=27259) it.</sub>

**Comment by Rick-Anderson** [comment]
I think the right way to fix this is to make `Enrollments `nullable.

**Comment by Rick-Anderson** [comment]
At most we would comment out 
`<Nullable>enable</Nullable>`

**Comment by Rick-Anderson** [comment]
moved to #27314

**Pull request closed without merging**
