### PR TITLE
Pivot the Blazor ToDo List tutorial

### LINKED ISSUE #22676: Pivot topic for WASM and Server
Make Blazor Server the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #22676

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.0&branch=pr-en-us-22675)

### CODE REVIEW

**Comment by danroth27** [comment]
This looks fine, but can we make Blazor Server the default pivot?

**Comment by guardrex** [comment]
It depends ... the whole doc set *remembers* what the user selects; so if they hit this from WASM on the last pivoted topic, then it's going to load as a WASM pivot.

The alternative is for us to have two of these ... standalone sister topics ... then we put them into the ToC in Blazor Server-Blazor WASM order.

**Comment by guardrex** [comment]
This would be the first pivoted topic in the Blazor doc set. We can reverse the order of the pivot sections so that (I think 🤔) the Server pivot should load first.

However, it's still going to default to what they selected for a prior topic as I said if they don't hit this topic first.

**Comment by danroth27** [comment]
> This would be the first pivoted topic in the Blazor doc set.

This one has the same pivots: https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration

> We can reverse the order of the pivot sections so that (I think 🤔) the Server pivot should load first.

Let's try that.

> However, it's still going to default to what they selected for a prior topic as I said if they don't hit this topic first.

I think that's ok, as long as Blazor Server is the default for new users that have never selected anything.

**Comment by guardrex** [comment]
Ok ... it's done.

I'm not sure *yet* what's going to happen in all of the spots that the WASM pivot is positioned above the Server pivot in docs. Docs very much favor WASM before Server in terms of the sequence of coverage. That goes all the way back to blazor.net 👴 lol.

I'll check the behaviors and shoot you a message later on how everything behaves ... but **_Yes!_** on a Blazor Server default now if they never made the pivot selection elsewhere.

**Pull request merged**
