### PR TITLE
Update to .NET Core 3.1 [Sample + Tutorial]

### PR DESCRIPTION
**Pull request by jamesmontemagno**
I updated the WebAPI project to ASP.NET Core 3.1 and updated the tutorial to reflect this with new images and source code pointing out how to do http clear traffic.

This is now a mirror of -> https://github.com/xamarin/xamarin-forms-samples/pull/694 however it would be nice to only have 1 backend sitting around instead of a duplicate. Any way to do this?

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> This is now a mirror of -> xamarin/xamarin-forms-samples#694 however it would be nice to only have 1 backend sitting around instead of a duplicate. Any way to do this?

I azure repo does this, that is reference snippets in another repo. 4 years ago I added some config to the repo to all this and got it working. My PR was rejected it was never checked in.

@scottaddie  @tdykstra do you have instructions on adding snippets from another repo?

**Comment by jamesmontemagno** [comment]
Linking to this PR -> https://github.com/xamarin/xamarin-forms-samples/pull/694

**Comment by tdykstra** [comment]
>do you have instructions on adding snippets from another repo?

https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master#out-of-repo-snippet-references

**Comment by Rick-Anderson** [comment]
Fixes #21443

@jamesmontemagno I'll create a new PR and pull in all your commits so you'll get credit. I should be able to take it from here sans a few questions I'll have.  Thanks again for this very valuable update.

**Comment by Rick-Anderson** [comment]
@jamesmontemagno I think https://github.com/xamarin/xamarin-forms-samples/pull/694 needs to merge for me to link to the samples.

**Comment by jamesmontemagno** [comment]
@Rick-Anderson awesome! it is in now :) I will try to update my PR with the new stuff and remove the sample here :) 1 less sample to maintain!

**Comment by Rick-Anderson** [comment]
@jamesmontemagno I'll take over and ping you when I'm stuck

**Comment by Rick-Anderson** [comment]
@jamesmontemagno  moved this to #21489 and brought your commits so when we merge, you'll get credit.

**Pull request closed without merging**
