### PR TITLE
Explain scoped DI in HttpClient handlers

### LINKED ISSUE #20401: Better documentation for scope DI usage with HttpClientFactory scenarios
> The IHttpClientFactory creates a separate DI scope for each handler. Handlers can depend upon services of any scope. Services that handlers depend upon are disposed when the handler is disposed.

This statement should be more visible (like a **NOTE** in yellow in bold). We should also show examples of how scoped services resolved. Show the same scoped service being resolve in an HttpMessageHandler and the request with difference lifetimes. That's bitten some people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#outgoing-request-middleware)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #20401.

I've put together an example and added a TODO into the topic for explanation. I'll do that in the next commit, but I'm offering this up here as a draft for some feedback on the approach.

@Rick-Anderson Does the approach I've gone with look OK here? It borrows heavily from the `Operation` concept used in the DI example, but just focuses on _Scoped_, because that's where it matters for the concept being explained.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1&branch=pr-en-us-20458)

**Comment by serpent5** [comment]
If you want to run it, just navigate to `/Operation`. You should see the request scope value change for each request, but the handler scope value will change every 2 minutes due to the default handler lifetime.

I know it's a huge week for .NET this week, so I understand that I might be waiting a while for feedback. 😎

**Comment by Rick-Anderson** [comment]
Looks great to me. @stevejgordon  can you take a quick look?

**Comment by serpent5** [comment]
@Rick-Anderson What should we do with this one? I've added all the sample code and linked it into the topic, but I haven't written up the explanation that brings it all together. Would you have some time to help with the write-up, assuming that what I've done makes sense?

I'm a bit pressed for time recently, with schools being closed here in the UK, but I'm aware that this PR has been sitting here for a while.

**Comment by Rick-Anderson** [comment]
> Would you have some time to help with the write-up,

Yes, I can help. No hurry either.

**Comment by Rick-Anderson** [comment]
@serpent5  I moved your commits to #21275 so you'll get the merge credit and I can work on it.

**Pull request closed without merging**
