### PR TITLE
Code-fence references to Program.cs

### PR DESCRIPTION
**Pull request by serpent5**
A global replace-all from `*Program.cs*` to `` `Program.cs` ``, excluding anything in `README.md` files.

cc @guardrex

### CODE REVIEW

**Comment by guardrex** [comment]
Are READMEs localized? ... I didn't think that they were part of the build.

**Comment by serpent5** [comment]
I don't think they're part of the build. That's why I didn't bother including them in the change here.

**Comment by guardrex** [comment]
Oh! Geez! 😆 ... I thought that said "including." DUH!

To cut down on caffeine, I started making my morning pot of ☕ with 1/2 caf and 1/2 decaf. **_I think I need to go back to 100% full caf!_** 😄

**Review by Rick-Anderson — APPROVED** [review]
Nice consistency change now that we don't have the `Startup` class.

**Pull request merged**
