### PR TITLE
Added endpoint for complete todos

### LINKED ISSUE #28303: Add app.MapGet("/todoitems/complete to DTO sample
See [code](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs#L12-L16)

[GetCompleteTodos](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs#L29-L31) was added in #28271, but no endpoint was added.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 62456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62456)

### PR DESCRIPTION
**Pull request by dersonmutemba**
Fixes #28303 

I have just realized that I coded the GetCompleteTodos method and haven't tested it, that explains the endpoint missing. But that will fix it. Thanks for your attention.

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
Thanks again @dersonmutemba

**Comment by dersonmutemba** [comment]
You're welcome @Rick-Anderson. Let me see if I can solve other issues. It has been a good experience so far.
Ahm, don't know if it was supposed to be that way, but in the article I saw that the code was updated but the contributers list wasn't

**Comment by Rick-Anderson** [comment]
> but in the article I saw that the code was updated but the contributers list wasn't

What article? By contributors list do you mean GitHub history?

Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Comment by dersonmutemba** [comment]
> > but in the article I saw that the code was updated but the contributers list wasn't
> 
> What article? By contributors list do you mean GitHub history?
> 
> Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

I was referring to this article: https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio
But maybe I misunderstood it. No problem

**Comment by Rick-Anderson** [comment]
It just uses GitHub history on the MD file, it doesn't look at the source files used.

image

**Comment by Rick-Anderson** [comment]
@dersonmutemba  can you take #28322 ? That will get you on the contributor list and you've done a good job reviewing the article. That date is when the article was last reviewed.

**Comment by Rick-Anderson** [comment]
@dersonmutemba can you send me an email? riande@microsoft.com

**Pull request merged**
