### PR TITLE
test versions life

### PR DESCRIPTION
**Pull request by Rick-Anderson**
---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/51f1186f881bb1bfe792b228fdb5c030e598e77e/aspnetcore/test/troubleshoot-azure-iis.md) | [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?branch=pr-en-us-32874) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  why isn't `version` displaying?

**Comment by Rick-Anderson** [comment]
@guardrex  @wadepickett @tdykstra  we should probably add this to all topics to be in conformance with archive mandates.

**Comment by guardrex** [comment]
All Blazor docs are using ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/not-latest-version.md

It can't be done in that file?

**Comment by Rick-Anderson** [comment]
> All Blazor docs are using ...
> 
> https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/not-latest-version.md
> 
> It can't be done in that file?

Yes, we should add it to that file.

**Comment by tdykstra** [comment]
> @tdykstra why isn't ~`version` displaying?~ I moved the image to GitHub and that works.

Try putting it somewhere not under an `includes` folder. docfx excludes resources from `includes` folders.

**Pull request closed without merging**
