### PR TITLE
Remove incorrect comments about kestrel limits

### LINKED ISSUE #31108: Kestrel limits are not loaded from appsettings.config
### Description

At the beginning of the article there is a statement that 

> By default, Kestrel configuration is loaded from the Kestrel section using a preconfigured set of configuration providers.

and a sample is given

``` json
{
  "Kestrel": {
    "Limits": {
      "MaxConcurrentConnections": 100,
      "MaxConcurrentUpgradedConnections": 100
    },
    "DisableStringReuse": true
  }
}
```
However, neither of these settings seems to be loaded from the config, from my observation.
I also peeked at the [KestrelConfigurationLoader](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs) and found no sign of these properties being loaded there.
I also found a [sample](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L154C24-L154C24) where Kestrel options for some reason are loaded manually from the config during startup:

>  options
>                .Configure(context.Configuration.GetSection("Kestrel"), reloadOnChange: true)

So either the documentation page contains wrong information, or this is a bug in the code. Or I'm missing something :)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/options.md

### Document ID

5a5a34c5-1c75-ff17-b3d6-762194391319

### Article author

tdykstra

---
[Associated WorkItem - 203246](https://dev.azure.com/msft-skilling/Content/_workitems/edit/203246)

### PR DESCRIPTION
**Pull request by amcasey**
Presently, they can't conveniently be configured from appsettings.json.  There are [workarounds](https://github.com/dotnet/aspnetcore/issues/4765), but none that seem worth recommending.

Fixes #31108

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/49d9d1fcbbe0b588305458266a8d46b32baea8a4/aspnetcore/fundamentals/servers/kestrel/options.md) | [Configure options for the ASP.NET Core Kestrel web server](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?branch=pr-en-us-31633) |

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
LGTM

**Review by Tratcher — APPROVED** [review]

**Comment by amcasey** [comment]
@tdykstra Is there way to backport this?  This functionality wasn't available in previous versions either.

**Comment by tdykstra** [comment]
Yes, I should have pointed that out when reviewing ... there's one earlier version and it's in the same file, following the line
`:::moniker range="< aspnetcore-6.0"`

**Comment by Rick-Anderson** [comment]
> @tdykstra Is there way to backport this? This functionality wasn't available in previous versions either.

We can take care of that.

**Pull request merged**
