### PR TITLE
Minimal API versioning /2

### LINKED ISSUE #26965: When WithName is removed, route name is not automatically inferred
According to the documentation as shown below,

minimal

route names will be inferred from the method name. 

Unfortunately the claim does not work.
If I remove `WithName(nameof(Hello))` then `Results.CreatedAtRoute(nameof(Hello), null, "Ok"))` throws an exception.

> System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Http.HttpResults.CreatedAtRoute`1.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

# Minimal Working Example

```csharp
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OpenApi;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();


if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

string Hello() => "Hello World";

// app.MapGet("/url", Hello); // Route name is not automatically inferred!
app.MapGet("/url", Hello).WithName(nameof(Hello));
app.MapGet("/", () => Results.CreatedAtRoute(nameof(Hello), null, "Ok"));


app.Run();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### LINKED ISSUE #27105: Minimal API  - Versioning support available.
The `Asp.Versioning.Http` package helps to implement versioning in Minimal API. Here is an example - [(MinimalApiExample)](https://github.com/dotnet/aspnet-api-versioning/tree/main/examples/AspNetCore/WebApi/MinimalApiExample)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #27105 Fixes #26965

review URLs
- [first](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-27115#minimal-api-versioning)
- [Second](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0&branch=pr-en-us-27115#api-versioning)
- [route name](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-27115#name-routes-and-link-generation-1)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@captainsafia  3 minute review please.

**Comment by captainsafia** [comment]
@Rick-Anderson The versioning section is pulled under the "Document your APIs" section in the new taxonomy (see https://github.com/dotnet/aspnetcore/issues/44257).

What are your thought on having the content there instead? I was planning on writing this up as part of the work I'm doing to revamp the docs for this.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson The versioning section is pulled under the "Document your APIs" section in the new taxonomy (see [dotnet/aspnetcore#44257](https://github.com/dotnet/aspnetcore/issues/44257)).
> 
> What are your thought on having the content there instead? I was planning on writing this up as part of the work I'm doing to revamp the docs for this.

I agree. Should I close this PR to avoid a merge conflict or should we merge this for now knowing you'll eventually move it?

**Comment by captainsafia** [comment]
@Rick-Anderson Feel free to close and I'll integrate into my upcoming updates to the OpenAPI page.

**Pull request closed without merging**
