### PR TITLE
Add Localization Samples for .NET 8

### LINKED ISSUE #34200: Add Localization Samples for .NET 8
### Description

Add Localization Samples for .NET 8

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?view=aspnetcore-9.0&branch=pr-en-us-34199

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization/make-content-localizable.md

### Document ID

72e0699e-f13a-8ca8-9106-59c301ee2de4

### Article author

@Rick-Anderson

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+72e0699e-f13a-8ca8-9106-59c301ee2de4)

---
[Associated WorkItem - 345578](https://dev.azure.com/msft-skilling/Content/_workitems/edit/345578)

### PR DESCRIPTION
**Pull request by hishamco**
@Rick-Anderson could you please check, coz the monikers made me crazy all the time :)

Fixes #34200

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/localization/make-content-localizable.md](https://github.com/dotnet/AspNetCore.Docs/blob/3bb2bc11a6c21dea91526bb46fcbb7218952f935/aspnetcore/fundamentals/localization/make-content-localizable.md) | [aspnetcore/fundamentals/localization/make-content-localizable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?branch=pr-en-us-34199) |
| [aspnetcore/fundamentals/localization/select-language-culture.md](https://github.com/dotnet/AspNetCore.Docs/blob/3bb2bc11a6c21dea91526bb46fcbb7218952f935/aspnetcore/fundamentals/localization/select-language-culture.md) | [aspnetcore/fundamentals/localization/select-language-culture](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?branch=pr-en-us-34199) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> I will follow up with a .NET 9.0 PR, I might wait until Orchard Core supports it which should done ASAP, or I will update the localization sample and then add the PO Localization sample later

Thanks so much. After Orchard Core is fine.

**Comment by Rick-Anderson** [comment]
@hishamco  how risky would it be to delete some of the CSS files and other files to get the file count down?

image

**Comment by hishamco** [comment]
Need to check if the styles & scripts can be restored before the build using Bower or Grunt

**Comment by hishamco** [comment]
Tweak the styles & scripts then tested .. everything works as expected

**Comment by hishamco** [comment]
Does anything block this?

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
