### PR TITLE
Improve custom validation classes section

### LINKED ISSUE #21626: Improve custom validation class attributes section
Improve the text and example to clarify the guidance.

> The code you're referring to should be placed in the component initializer. Also, you have to wire up the EditContext instance that you've created with the form by passing it as a parameter.

https://github.com/dotnet/aspnetcore/issues/30459#issuecomment-786064159

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#custom-validation-class-attributes)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #21626

Thanks @TanvirArjel! :rocket: ...

More work will be performed on the whole topic when I reach it on my [UE ("user experience," i.e., topic overhaul) tracking issue (dotnet/AspNetCore.Docs #19286)](https://github.com/dotnet/AspNetCore.Docs/issues/19286). I might provide a fully working example for this section at that time. Devs like to cut-'n-paste complete examples into test apps for their own experimentation and app development. This scenario is a good candidate for that type of experience.

I'll also continue to track on your engineering issue. You asked a follow-up question, and I'll keep an :eye: on it for additional updates to this section either on this PR or another PR later if we need to surface more content.

### CODE REVIEW

**Review by TanvirArjel — CHANGES_REQUESTED** [review]
Please add the following code before `@code` tag:

```C#
<EditForm EditContext="@editContext" OnSubmit="@HandleValidSubmit">
     .........
    <button type="submit">Submit</button>
</EditForm>
```

**Review by TanvirArjel — APPROVED** [review]
Now it looks good. Thank you.

**Comment by guardrex** [comment]
Still working on it.

The reason this was so badly documented is that the section was shot in here as a quick update directly from product unit notes. Now that I've had a chance to play with it, I can see what we'll need to call out.

... and I see what you mean about the way the current example will apply the style. However, you just need to qualify the field somehow. In the following example it only applies the style to the `Identifier` field of the Star Trek&trade; example.

```csharp
public class MyFieldClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext,
        in FieldIdentifier fieldIdentifier)
    {
        if (fieldIdentifier.FieldName == "Identifier")
        {
            var isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

            return isValid ? "validField" : "invalidField";
        }

        return string.Empty;
    }
}
```

**Review by TanvirArjel — CHANGES_REQUESTED** [review]
Please replace `background-color` with `border- color` as follows because developers don't use `background-color` to identify valid and invalid inputs. :)

```CSS
.validField {
    border-color: green;
}

.invalidField {
    background-color: red;
}
```

**Review by TanvirArjel — CHANGES_REQUESTED** [review]
The invalid field is still background-color :) make it `border-color` too.

**Comment by guardrex** [comment]
> replace background-color with border- color

Ok, but your color choices don't have enough **_panache_** for me. 😁 lol .... I'm a bit of a *nut case* around here.

I'll touch this section again with the full topic updates coming later to this article.

**Comment by guardrex** [comment]
I'm going to leave invalid as a background color. None of this bit really matters. The point is that the dev decides what the styles are. There could be several styles with complex logic that goes beyond just checking for the presence of a field validation error.

**Review by TanvirArjel — APPROVED** [review]
Looks good. 👍

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @guardrex !

**Pull request merged**
