### PR TITLE
Example EF6 project with .Net Core 3.1 for #15620

### LINKED ISSUE #15620: Update "ASP.NET Core and Entity Framework 6" for .NET Core 3.0
>To use Entity Framework 6, your project has to compile against .NET Framework, as Entity Framework 6 doesn't support .NET Core. If you need cross-platform features you will need to upgrade to Entity Framework Core.

This is no longer the case for ef6.3

Edit by @Rick-Anderson 
6K PV

See [Announcing Entity Framework 6.3 Preview with .NET Core Support](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/)

See also #15684 if it's relevant.

-----

`EDIT` : 6K PV
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [Get Started with ASP.NET Core and Entity Framework 6](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by attrib75**
[EDIT by guardrex]

Fixes #15620

Example EF6 project with .Net Core 3.1 for #15620

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19537) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19537) before we can accept your contribution.<br/><br/>:x: attrib75 [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19537)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=19537) it.</sub>

**Comment by guardrex** [comment]
@attrib75 Please sign the CLA if you agree with it's terms. :point_up:

File, language, and GH specs prefer files that have a newline on the last line. We don't go to the trouble of adding them on the 3rd party files (CSS, JS, for example), but we usually make sure that they're present on the other files of a sample. I recommend that you add them to the sample's non-3rd party files.

**Comment by guardrex** [comment]
Thanks @attrib75 ... Rick should be along in a bit to review this.

**Comment by attrib75** [comment]
Thanks @guardrex, I think I did the spacing right this time.  I will be happy to modify if you find anything incorrect.

**Comment by Rick-Anderson** [comment]
@attrib75 I brought your commits over to #19546, where I'll continue to work on it. Thanks for doing this, I should have something for you to review in a couple days.

**Pull request closed without merging**
