### PR TITLE
Fix instructions for setting up Nginx

### LINKED ISSUE #33159: Fix Nginx instructions
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&branch=pr-en-us-33132&tabs=linux-ubuntu

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md

### Document ID

815fe034-c9fc-aee3-a8b5-f2e860b30302

### Article author

@Rick-Anderson

### PR DESCRIPTION
**Pull request by kant2002**
Fixes #33159

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/e2d5250cfc293a356dfd498bab62ad2557829804/aspnetcore/host-and-deploy/linux-nginx.md) | [Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-33132) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@kant2002  I don't see any differences. What's changed?

**Comment by kant2002** [comment]
I remove http. Since that’s part inside nginx.conf where sites-available included

**Comment by Rick-Anderson** [comment]
@kant2002  got it thanks, just these two changes:
image

@javiercn please review

**Comment by kant2002** [comment]
@Rick-Anderson yes. it's correct.

**Pull request merged**
