### PR TITLE
Restructure OpenAPI content

### PR DESCRIPTION
**Pull request by mikekistler**
***EDIT by @Rick-Anderson to add preview link***

[Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-9.0&branch=pr-en-us-33656&tabs=visual-studio%2Cminimal-apis)

This PR just restructures the content in the OpenAPI section by adjusting head levels. The original structure looked like this:

```
# Generate OpenAPI documents
## Package installation
## Configure OpenAPI document generation
## Including OpenAPI metadata in an ASP.NET web app
### Summary and description
### tags
### operationId
### parameters
### requestBody
### Describe response types
#### Set responses for `ProblemDetails`
#### Multiple response types
### Excluding endpoints from the generated document
## Including OpenAPI metadata for data types
## type and format
## Using attributes to add metadata
## Other sources of metadata for generated schemas
### required
### enum
### nullable
### additionalProperties
### Metadata for polymorphic types
## Adding metadata with a schema transformer
## Options to Customize OpenAPI document generation
### Customize the OpenAPI document name
### Customize the OpenAPI version of a generated document
### Customize the OpenAPI endpoint route
### Customize the OpenAPI endpoint
#### Limit OpenAPI document access to authorized users
#### Cache generated OpenAPI document
## OpenAPI document transformers
### Customize OpenAPI documents with transformers
### Execution order for transformers
### Use document transformers
### Use operation transformers
### Use schema transformers
## Additional resources
```

and with these changes it looks like this:

```text
# Generate OpenAPI documents
## Package installation
## Configure OpenAPI document generation
## Including OpenAPI metadata in an ASP.NET web app
### Including OpenAPI metadata for endpoints
#### Summary and description
#### tags
#### operationId
#### parameters
#### requestBody
#### Describe response types
##### Set responses for `ProblemDetails`
##### Multiple response types
#### Excluding endpoints from the generated document
### Including OpenAPI metadata for data types
#### type and format
#### Using attributes to add metadata
#### Other sources of metadata for generated schemas
##### required
##### enum
##### nullable
##### additionalProperties
##### Metadata for polymorphic types
#### Adding metadata with a schema transformer
## Options to Customize OpenAPI document generation
### Customize the OpenAPI document name
### Customize the OpenAPI version of a generated document
### Customize the OpenAPI endpoint route
### Customize the OpenAPI endpoint
#### Limit OpenAPI document access to authorized users
#### Cache generated OpenAPI document
## OpenAPI document transformers
### Customize OpenAPI documents with transformers
### Execution order for transformers
### Use document transformers
### Use operation transformers
### Use schema transformers
## Additional resources
```

The key change was to group the metadata for endpoints and metadata for datatypes into their own sections.

I think the new structure is better but happy for feedback to make it even better.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/44663ab06adf4c8cfd6304583485c19e5e43ba61/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33656) |

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
Much better layout. Let's give them until EOD Friday to review, then I'll S&M. I'll fix anything they don't like.

**Comment by tdykstra** [comment]
[like]  Tom Dykstra reacted to your message:
________________________________

**Review by tdykstra — APPROVED** [review]
LGTM

**Review by captainsafia — COMMENTED** [review]
Retroactive approval!

**Pull request merged**
