### PR TITLE
from "dotnet aspnet-codegenerator" to "dotnet-aspnet-codegenerator"

### PR DESCRIPTION
**Pull request by slipperstree**
A simple fix from "dotnet aspnet-codegenerator" to "dotnet-aspnet-codegenerator".
#No Issue_Number.

### CODE REVIEW

**Comment by guardrex** [comment]
Hi @slipperstree ... IIRC, this isn't correct.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22367) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22367) before we can accept your contribution.<br/><br/>:x: slipperstree [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22367)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=22367) it.</sub>

**Comment by guardrex** [comment]
btw - It's best if you don't duplicate the alt text exactly for each image. The build system throws warnings for duplicate alt text even when versioned content is in use.

Before making any further updates, I recommend waiting on @Rick-Anderson to review: I don't think the original set of changes are correct WRT the command guidance. He'll let you know if/how to proceed.

**Comment by slipperstree** [comment]
> Hi @slipperstree ... IIRC, this isn't correct. It's only in that format for the install, not for use.
> 
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0

Hi @guardrex 
Thanks for your help. I'm sorry to push another merge before I noticed it.
I am a newer to .NetCore. I followed the doc until `dotnet aspnet-codegenerator` , that returns some error like this:

    Could not execute because the specified command or file was not found.
     Possible reasons for this include:
       * You misspelled a built-in dotnet command.
       * You intended to execute a .NET program, but dotnet-aspnet-codegenerator does not exist.
       * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I noticed that I have installed `dotnet-aspnet-codegenerator` before, so I try to use it, and when I succeeded, I thought there might be a small problem with the doc, so I tried to modified it. If my understanding is wrong, I'm sorry for that.
(But If it happens to me, it may happen to others as well...)
And Thank you for reminding me to sign CLA, I have just signed it.

**Comment by guardrex** [comment]
I think Rick has heard this feedback before on similar issues/PRs. I thought the problem had a simple explanation, such as failure to perform a system restart perhaps. He'll be along in a bit to look at this.

**Comment by Rick-Anderson** [comment]
Actually, `dotnet-aspnet-codegenerator` is slightly preferred on use now.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@slipperstree  thanks for fixing this and extra thanks for fixing the image descriptions.

**Comment by guardrex** [comment]
I see what you mean ... I found ur issue over there on that doc.

Sorry @slipperstree for my remarks. I wasn't aware of the churn in the command.

**Comment by Rick-Anderson** [comment]
NP @guardrex , me bad for not updating the docs. Thanks for pointing out the inconsistency so I could fix it.

**Pull request merged**
