### PR TITLE
Blazor - data-binding - event fix

### PR DESCRIPTION
**Pull request by hakenr**
"After each keystroke" is an `oninput` event
* fixed the text
* fixed the sampleˇ

cc @guardrex 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/0c07cd2179c502d2d37c093786764203bcd6fdc0/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-31957) |

### CODE REVIEW

**Comment by guardrex** [comment]
There was a different fix that would just have the text update to 'loss of focus' language, but now that I think about it the example might show both. I'll try a commit to see how that looks.

**Comment by guardrex** [comment]
After looking this over, I think the original intent was a loss of focus. Anyway, it's nice to show it both ways.

**Comment by guardrex** [comment]
I'll wait to merge until you have a chance to respond to my updates.

**Review by hakenr — COMMENTED** [review]
lgtm

**Pull request merged**
