### PR TITLE
Update "CLI" tab controls

### LINKED ISSUE #32536: Change tab control text
### Description

.NET Core CLI is now just called the .NET CLI. I'll check the whole Blazor node to see if there are any other instances of this.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md

### Document ID

85af7a99-672c-0438-dcc2-e8edfaf70c54

### Article author

@guardrex

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #32536

@Rick-Anderson @tdykstra @wadepickett ... I'm updating the Blazor tooling tab controls from ".NET Core CLI" to the correct (new) naming ".NET CLI" ... but I have a question on the tab code/markup for "netcore-cli" ...

```markdown
# [.NET CLI](#tab/netcore-cli/)
```

... IIRC 🤔, these are by convention. Did they change `netcore-cli` to `net-cli` on the backend? IIRC 🤔, there's an internal document somewhere that lists them. If they made that update, I'll perform another commit here to update that as well.

Note that there's a lot of ".NET Core CLI" lingo outside of the Blazor docs ... 133 instances across 56 files. I can place them on this PR if you want. It's just a find-'n-replace AFAICT to get them all on here. 👂 

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-32703) |
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/host-and-deploy/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-32703) |
| [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/progressive-web-app.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?branch=pr-en-us-32703) |
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/security/server/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-32703) |
| [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?branch=pr-en-us-32703) |
| [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md) | [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?branch=pr-en-us-32703) |
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/blazor/tutorials/signalr-blazor.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-32703) |
| [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/client-side/spa-services.md) | [aspnetcore/client-side/spa-services](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa-services?branch=pr-en-us-32703) |
| [aspnetcore/data/ef-mvc/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/data/ef-mvc/migrations.md) | [Tutorial: Part 5, apply migrations to the Contoso University sample](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?branch=pr-en-us-32703) |
| [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/data/ef-rp/intro.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?branch=pr-en-us-32703) |
| [aspnetcore/data/ef-rp/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/data/ef-rp/migrations.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?branch=pr-en-us-32703) |
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [[.NET Core CLI](#tab/netcore-cli) ](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-32703) |
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/fundamentals/host/hosted-services.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-32703) |
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32703) |
| [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/fundamentals/target-aspnetcore.md) | [Use ASP.NET Core APIs in a class library](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?branch=pr-en-us-32703) |
| [aspnetcore/getting-started/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/getting-started/index.md) | [Tutorial: Get started with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/getting-started/index?branch=pr-en-us-32703) |
| [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/host-and-deploy/azure-apps/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?branch=pr-en-us-32703) |
| [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md) | [aspnetcore/host-and-deploy/visual-studio-publish-profiles](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?branch=pr-en-us-32703) |
| [aspnetcore/migration/1x-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/migration/1x-to-2x/index.md) | [Migrate from ASP.NET Core 1.x to 2.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/index?branch=pr-en-us-32703) |
| [aspnetcore/migration/20_21.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/migration/20_21.md) | [Migrate from ASP.NET Core 2.0 to 2.1](https://review.learn.microsoft.com/en-us/aspnet/core/migration/20_21?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/accconfirm.md) | [Account confirmation and password recovery in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/add-user-data.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/customize-identity-model.md) | [aspnetcore/security/authentication/customize-identity-model](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/identity.md) | [Introduction to Identity on ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/individual.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/individual.md) | [Articles based on ASP.NET Core projects created with individual user accounts](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/individual?branch=pr-en-us-32703) |
| [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/authentication/windowsauth.md) | [Configure Windows Authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?branch=pr-en-us-32703) |
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/security/enforcing-ssl.md) | [[Visual Studio](#tab/visual-studio) ](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-32703) |
| [aspnetcore/tutorials/dotnet-watch.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/tutorials/dotnet-watch.md) | [aspnetcore/tutorials/dotnet-watch](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?branch=pr-en-us-32703) |
| [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/tutorials/getting-started-with-NSwag.md) | [Get started with NSwag and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-NSwag?branch=pr-en-us-32703) |
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf2b364c07836b002d672c6339096d8af62aa93b/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?branch=pr-en-us-32703) |

</details>

> [!NOTE]
> This table shows preview links for the 30 files with the most changes. For preview links for other files in this PR, select <strong>OpenPublishing.Build Details</strong> within [checks](https://github.com/dotnet/AspNetCore.Docs/pull/32703/checks).

### CODE REVIEW

**Comment by tdykstra** [comment]
> IIRC 🤔, there's an internal document somewhere that lists them. If they made that update, I'll perform another commit here to update that as well.

You're right, it's by convention and there's an approved values list. I just submitted a PR to change the approved list, so please do go ahead and make the change everywhere.

**Comment by guardrex** [comment]
Thx, @tdykstra ... I'll perform the update here for the full doc set, including the markdown to `tab/net-cli`, 🛑 ***and hold*** 🛑 this until you give the word on your PR going in.

I certainly can take care of all the ones ***here***. Aquent doesn't like it when I submit work to external repos. Can I open an issue over there for one of their doc authors to handle it on `dotnet/docs`?

**Comment by tdykstra** [comment]
> I certainly can take care of all the ones _**here**_. Aquent doesn't like it when I submit work to external repos. Can I open an issue over there for one of their doc authors to handle it on `dotnet/docs`?

Certainly, that would be great.

**Comment by guardrex** [comment]
Ok ... ***Everything seems alright!*** ......... put that on my *tombstone* PLZ! ⚰️😄 

Does anyone ... @tdykstra? ... want to review? ... or should we just roll the 🎲🎲 and take our chances on my scan 👀 of the diff?

Also, @tdykstra ... Does the fact that this built OK mean that we can merge now, or do we need to wait?

**Comment by tdykstra** [comment]
> Does anyone ... @tdykstra? ... want to review? ... or should we just roll the 🎲🎲 and take our chances on my scan 👀 of the diff?
> 
> Also, @tdykstra ... Does the fact that this built OK mean that we can merge now, or do we need to wait?

Merge now.  I'll take a quick look and approve the PR

**Comment by guardrex** [comment]
It's an EYE 👁️ popper. Break out the Visine&trade;! 😵

**Review by tdykstra — APPROVED** [review]

**Pull request merged**
