### PR TITLE
Update Blazor common sample example

### LINKED ISSUE #18865: TabSet.SetActivateTab should, maybe, be SetActiveTab
The `TabSet`'s `SetActivateTab` method doesn't read how I'd expect. Should it be `SetActiveTab`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7ba96d-bae0-96ee-e76a-71c6e5f4c23f
* Version Independent ID: 5fe884b8-51e1-1b91-57f8-522ff0b7890c
* Content: [ASP.NET Core Blazor cascading values and parameters](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/cascading-values-and-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #18865

The user triggers `ActivateTab`, and `SetActiveTab` is used to set the tab.

Thanks @serpent5! 🐢 ..... Do u want to 👀 this to make sure that I didn't create a PR :poop:? :smile:

### CODE REVIEW

**Comment by serpent5** [comment]
Sure, looks good.

_Purely_ just out of curiosity, I did also wonder whether the `SetActiveTab` functionality could be put into a setter for the `ActiveTab` property. Is that supported in Blazor WASM? I'm new to that side of things, and there's a whole 'nother argument whether it's appropriate, but yeah, I was curious.

**Comment by guardrex** [comment]
Possibly ... I didn't consider it. It doesn't seem like that change would have any bearing on what the example is here to show, namely *cascading parameters*. Actually, I kind'a feel that this whole example has too much going on to be a great introductory example for the concept. Anyway ... this example came from engineering this way, and I just dropped it into the docs. It was reviewed by Ryan on a big :eye: review before going to release, so I guess he felt it was right when he looked at it again.

**Comment by serpent5** [comment]
Yeah, I understand. It's totally irrelevant to the sample. I was just asking if it was supported; certainly _not_ challenging any decisions. I guess I should've just tried it myself, really. Thanks.

**Comment by guardrex** [comment]
Given my workload right now ... and for the *foreseeable future* ⛏️⛰️😅 ...  I don't have time to refactor/test that approach. If you come up with something that looks better, then put it up in an issue. We can certainly take a look at it and see what's what.

**Comment by serpent5** [comment]
It was never about suggesting something better. I was perhaps just thinking out loud, which was my mistake. I'm not trying to add to your workload and I'm not trying to cause issues for you. I understand that you're busy and I really am sorry for being a distraction.

**Comment by guardrex** [comment]
No distraction. I'm not *that busy* :smile:.

I must not be that busy ....... I'm working on Sunday again. Hold on while I :trollface: myself: _STOP working on Sunday you **GoObErReX!**_ lol

**Pull request merged**
