### PR TITLE
Prerender and Integrate work (Round 1)

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #30341
Addresses #28161

# ***Round 1*** 🥊😵💫

This will be at least a two-step process. I'm going to merge this one quickly to get out of the way on non-Blazor node updates (e.g., the ToC changes needed).

I'm just going to use the *old skool* Whole-topic Versioning approach without the INCLUDE because I'm not clear on naming/location for the extra content (in the INCLUDE) and slammed with work right now. I need to keep rolling with the Blazor updates 🏃😅.  I'll leave it to others to structure this article later for the new Whole-topic approach, if desired.

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-30455) |
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/integration.md) | [aspnetcore/blazor/components/integration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30455) |
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-30455) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-30455) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/prerendering-and-integration.md) | [Prerender and integrate ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?branch=pr-en-us-30455) |
| [aspnetcore/blazor/components/prerendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/components/prerendering.md) | [aspnetcore/blazor/components/prerendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering?branch=pr-en-us-30455) |
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/fundamentals/signalr.md) | [aspnetcore/blazor/fundamentals/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-30455) |
| [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md) | [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?branch=pr-en-us-30455) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-30455) |
| [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/blazor/security/webassembly/index.md) | [Secure ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?branch=pr-en-us-30455) |
| [aspnetcore/fundamentals/url-rewriting.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/fundamentals/url-rewriting.md) | [aspnetcore/fundamentals/url-rewriting](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?branch=pr-en-us-30455) |
| [aspnetcore/migration/30-to-31.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/migration/30-to-31.md) | [Migrate from ASP.NET Core 3.0 to 3.1](https://review.learn.microsoft.com/en-us/aspnet/core/migration/30-to-31?branch=pr-en-us-30455) |
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/migration/70-80.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30455) |
| [aspnetcore/mvc/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/mvc/overview.md) | [Overview of ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/overview?branch=pr-en-us-30455) |
| [aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md) | [Component Tag Helper in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?branch=pr-en-us-30455) |
| [aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md) | [Persist Component State Tag Helper in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?branch=pr-en-us-30455) |
| [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/mvc/views/view-components.md) | [aspnetcore/mvc/views/view-components](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?branch=pr-en-us-30455) |
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/razor-pages/index.md) | [Introduction to Razor Pages in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-30455) |
| [aspnetcore/release-notes/aspnetcore-3.1.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/release-notes/aspnetcore-3.1.md) | [What's new in ASP.NET Core 3.1](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.1?branch=pr-en-us-30455) |
| [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspnetcore/tutorials/choose-web-ui.md) | [Choose an ASP.NET Core web UI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?branch=pr-en-us-30455) |

</details>

### CODE REVIEW

**Comment by guardrex** [comment]
@wadepickett ... One of the articles that you manage ...

aspnetcore/tutorials/choose-web-ui.md

... requires a few updates here. Do you want to review that one?

**Comment by wadepickett** [comment]
Looking it over... thanks!

**Comment by wadepickett** [comment]
@guardrex, choose-web-ui.md changes look good!  I'm also taking note of the terminology changes you made so that I am using those. I didn't review/approve for the entire PR since there are some areas I'm not going to be the best reviewer for, although I didn't notice anything amiss.

**Comment by guardrex** [comment]
Thanks. I'll be merging this now to avoid blocking other work (e.g., ToC updates by others).

For ***Round 2*** 🥊.................

terminator2

&mdash; **_"I'll be back."_** - Cyberdyne Systems T-800 Series Model 101 ([Arnold Schwarzenegger](https://www.imdb.com/name/nm0000216/))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[*The Terminator*](https://www.imdb.com/title/tt0088247/) ©1984 [Skydance Media](https://skydance.com/)

**Comment by guardrex** [comment]
@Rick-Anderson ... The license check seems broken. I performed the old "turn of off and back on" (i.e., close/re-open) with no effect.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson ... The license check seems broken. I performed the old "turn of off and back on" (i.e., close/re-open) with no effect.

It's not the first time. Merge away.

**Comment by guardrex** [comment]
It will only allow me to set up auto-merge, and I don't think these necessarily clear without a close/re-open cycle, so I don't think auto-merge will be much help.

**Comment by guardrex** [comment]
# 🎉🍻 

Thanks, @Rick-Anderson!

**Pull request merged**
