### PR TITLE
First MVC: fix missing VSC code

### LINKED ISSUE #31367: First MVC Tutorial: VSC code not showing for DI example
### Description

For .NET version 7-8 of this topic:

Code snippet missing for VS code example for DI section.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio-code

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md

### Document ID

48e81b42-7c2b-afbf-71e6-d4f442a4bd1f

### Article author

@wadepickett

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #31367

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/5686c7d00a8afd1d89e688d3b5f782bda6d1250d/aspnetcore/tutorials/first-mvc-app/adding-model.md) | [Part 4, add a model to an ASP.NET Core MVC app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?branch=pr-en-us-31369) |

### CODE REVIEW

**Comment by wadepickett** [comment]
Sigh, turned out to just be a missing bracket at the end of the snippet that for some reason I just could not see.  Fixed.

**Comment by guardrex** [comment]
Sorry I led you astray on the mismatched tab groups. I thought it might be that selecting the 2nd tab of a 3-tab group wasn't loading the content of the 3rd tab of the 3-tab group, but I didn't look closely.

**Comment by wadepickett** [comment]
No worries, it was good to know it was a possibility to watch out for.  I was just being blind and not seeing the missing bracket right in front of me.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
