### PR TITLE
Versioning Test

### PR DESCRIPTION
**Pull request by guardrex**
[Internal Review:  Version 3.1](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-3.1&branch=pr-en-us-22776)
[Internal Review:  Version 5](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-5.0&branch=pr-en-us-22776)

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson ... I don't have high hopes here without guidance and with a PowerShell repo example that doesn't match our repo config, **_however_**, let's see how this turned out. :eyes:

Try these two links, and the Blazor *Environments* doc should load matching the pics with and without some links that are for >=5.0 ...

* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-5.0&branch=pr-en-us-22776 ... you should see two links here ...

  Capture

* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-3.1&branch=pr-en-us-22776 ... those links shouldn't be there ...

Capture1

Try the link without the `view` ... and then see if the doc loads and if the version selector works for 3.1 and 5.0 ...

* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-22776

Even if all of that works, does the Blazor > Fundamentals > Environments topic link in the sidebar ToC work and load the 5.0 version of the topic?

Capture2

**Comment by guardrex** [comment]
Oh! ... One more thing ... **_even if all of that is working_** ...

Does the `ms.technology` metadata come through in the `<head>` of the loaded page?

```html
<meta name="ms.technology" content="aspnetcore-blazor">
```

**Comment by Rick-Anderson** [comment]
Public review of doc build 
folders 5 and 3 for versions
- download https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0
- unzip
- view HTML file in FF (Fire Fox). It best to view the doc with the widest window that has no left or right TOC (Table  of contents)

**Comment by guardrex** [comment]
🤔 ... I don't think that's going to indicate if the single *Environments* file loads with correct versioning via the selector and with correct ToC behavior. I can see those built files locally with DocFX loaded from the `aspnetcore-3.1` and `aspnetcore-5.0` URL paths (see below). It doesn't tell us anything about the final docs render, but I think the internally built topics will indicate if all of that stuff is working :point_up: ... *maybe*.

Are you OOF today? If so, perhaps @wadepickett can look?

* http://localhost:8080/aspnetcore-5.0-dest/blazor/fundamentals/environments.html

  Capture1

* http://localhost:8080/aspnetcore-3.1-dest/blazor/fundamentals/environments.html

  Capture

**Comment by Rick-Anderson** [comment]
> Are you OOF today? If so, perhaps @wadepickett can look?

Yes, @wadepickett  can you help?

**Comment by wadepickett** [comment]
Downloading and taking a look...

**Comment by guardrex** [comment]
@wadepickett ... No ... not a download. Go up to my six questions :point_up: at https://github.com/dotnet/AspNetCore.Docs/pull/22776#issuecomment-883557180 and use the internally-built topics (if possible).

**Comment by wadepickett** [comment]
Sorry.  "take a look" was a git vague.  :)   Thanks.  looking at the internally built topics...

**Comment by Rick-Anderson** [comment]
> Try the link without the view ... and then see if the doc

which link?

**Comment by guardrex** [comment]
The link I put right there below that. It doesn't have a `view` segment. It's a test to see what version loads and if the sidebar navigation will work after it loads.

**Comment by Rick-Anderson** [comment]
Yes, those load 5.0

**Comment by wadepickett** [comment]
Tests 1-6 work as expected.    With item 6, checking the cross link it worked for 5.0.

**Comment by guardrex** [comment]
Ah! Very good. Thanks @wadepickett.

I can move to my next test now. The next test is a live repo test but NOT with an actual doc (e.g., *Environments*). I'll create a new dummy doc in those folders and have that in the ToC. We can do a live merge test on that. It won't affect the rest of the repo and doc set .......... **_probably_** 🤞😆.

I'll use this PR for it and then call for a review before merging. I'll ping u back in a bit.

**Comment by guardrex** [comment]
Cool :+1: ... the build looks clean.

The live test for this is to not only check the various cross-links and bookmarks but to also **edit** the doc ... our normal community process ... click the **Edit** button and submit a PR against it ... approve ... merge ... merge to live again ... check the update goes all the way through and on the right version of the topic.

I'm on a 🧠🥘 *brain fry* now ... I'll continue with this on Wednesday morning.

If successful without side-effects, I'll then back out these dummy topics and try this all again with a real Blazor topic. I won't use the *Environments* topic tho ... I need a topic that has a cross-link from a 3.1 topic so that I can check a 3.1-to-3.1 cross-link and a 5.0-to-5.0 cross-link for the same topic pair.

**OK** ... *drum roll plz* ... 🥁🥁🥁🥁🥁🥁 ... **_Shall I proceed here Wednesday morning with the live test?_**

**Comment by Rick-Anderson** [comment]
> OK ... drum roll plz ... 🥁🥁🥁🥁🥁🥁 ... Shall I proceed here Wednesday morning with the live test?

Yes, test live tomorrow morning. You can always revert if there's a major problem. I think it will work.

**Comment by guardrex** [comment]
I think so, too. This is consistent with what PowerShell docs do for their reference topics, and it's also consistent with the (tiny) bit of DocFX engineer remarks over on the DocFX repo. I'm cautiously optimistic ..... **_Hopefully, the 😈 will stay out of this!_** 😄

**Pull request merged**
