### PR TITLE
Updates note for emitting Razor generated files

### LINKED ISSUE #26804: "Inspect the Razor C# class generated for a view" obsolete for current versions
The section _"Inspect the Razor C# class generated for a view"_ is obsolete in current versions, since the generated views are not emitted by default anymore. There is no comment about manually enabling the output of the artifacts (e.g. described [in this blog post here](https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#inspect-the-razor-c-class-generated-for-a-view)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Ducki**
Updates the section 'Inspect the Razor C# class generated for a view' to reflect the behavior of recent versions that by default omit the generated source files. Adds information on how to re-enable it.

Since the directory structure that was shown in the previous version of the section has changed (in fact, all generated files now get dumped in one single directory instead of mirroring the original structure), I took the liberty of removing it.

(Fixes #26804)

### CODE REVIEW

**Comment by guardrex** [comment]
@Ducki ... This doc set versions content, so we can't just strike that section for all versions. Do you know what version of the framework these changes appeared for? If so, use markdown tags to isolate the content ...

```
::: moniker range=">= aspnetcore-6.0"

Content for 6.0 or later

::: moniker-end

::: moniker range="< aspnetcore-6.0"

Content for versions earlier than 6.0

::: moniker-end
```

That example is for 6.0 and later changes, but you see the pattern there for an earlier version.

**Comment by Ducki** [comment]
Whops, sorry about that.
I believe a relevant PR is [this one](https://github.com/dotnet/roslyn/pull/47047/commits/8030d8550de3c60da3f8b881275af976ead3c586#r479616801), where the behavior of the flag was discussed and the default changed to `false` (tbh, not sure if this is actually for the razor compilation).
The branch was `release/dev16.8`. If that means Visual Studio 16.8, then it launched with .NET 5.

I'll revert the previous text and add the monikered stuff accordingly.

**Review by guardrex — APPROVED** [review]
Thanks @Ducki! ... I'll ping Rick now to take a look at this. I can't speak to when the change occurred, but your coverage LGTM.

**Comment by guardrex** [comment]
... and check my updates to see if they're sane 😵😄. In the example cases, it's best to call out what the conditions are for the example result [i.e., specify that for 6.0 (`net6.0`) and `Debug` that the path is as shown with `net6.0` and `Debug` path segments].

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@Ducki  much appreciated. 
Check out [is:open is:pr label:"code help wanted"](https://github.com/dotnet/AspNetCore.Docs/pulls?q=is%3Aopen+is%3Apr+label%3A%22code+help+wanted%22) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Pull request merged**
