### PR TITLE
IdS with WebSockets and Server-Sent Events

### LINKED ISSUE #17751: SignalR Core Auth - Token in Query String section does not address AddIdentityServerJwt()
The Token in Query String section addresses the case where `AddJwtBearer()` is called directly:

```
 services.AddAuthentication()
        .AddJwtBearer(options =&gt;//options from documentation);
```

It does not cover the Identity Server case where `AddIdentityServerJwt()` is used instead, which is the default for Blazor WebAssembly apps scaffolded with authentication.

```
 services.AddAuthentication()
        .AddIdentityServerJwt();
```

In this case, calling `AddJwtBearer` after `AddIdentityServerJwt` does not work:

```
// this does not work
services.AddAuthentication()
                .AddIdentityServerJwt()
                .AddJwtBearer(options =&gt;//options from documentation);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes  #17751

[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&branch=pr-en-us-20269#websockets-and-server-sent-events)

Brennan ... I'm winging this one even more than usual from the context on the issue. I need help with it ...

* Is this the best spot?
* Are these remarks sufficient/correct?
* Is Caleb's code good to provide?

### CODE REVIEW

**Comment by BrennanConroy** [comment]
I don't think this belongs in Blazor docs as it's specific to using SignalR directly. I would probably put it in the signalr/authn-and-authz doc.

**Comment by guardrex** [comment]
I'll move it.

Does it warrant a cross-link from the Blazor IdS topic because Caleb said ...

> It does not cover the Identity Server case where `AddIdentityServerJwt()` is used instead, which is the default for Blazor WebAssembly apps scaffolded with authentication.

... implying that this was for a Blazor scenario in his case.

**Comment by BrennanConroy** [comment]
> implying that this was for a Blazor scenario in his case

Right, they were using SignalR in Blazor WASM, and you'll notice that they commented on the SignalR docs because it's a SignalR scenario. The only reason Blazor is mentioned is because the scaffolding for a Blazor app adds IdentityServerJwt by default. Anyone using IdentityServerJwt with SignalR outside of a Blazor app will have a similar issue.

I *could* see a possible cross-reference in the Blazor-Wasm with SignalR tutorial as a potential "next steps, adding auth" type of thing.

**Comment by guardrex** [comment]
Seems like it goes in the same section. I try to avoid unpaired child sections.

Does this compose well now?

**Comment by BrennanConroy** [comment]
Should we have subsections for this to make it more obvious that this section is for IdentityServer and the other one is for the built in Jwt auth? Otherwise, looks good

**Comment by guardrex** [comment]
See if the section naming on the last commit works.

Yes, I think *two* is good. I just didn't want to add one (unpaired) heading. I try to follow old skool outlining rules and pair sections (and bullets) when possible.

**Comment by BrennanConroy** [comment]
Another nit: the section about the clients should probably go above the first subsection now?
From "In the JavaScript client, the token can be provided..." to "To support this on the server, additional configuration is required:"

**Review by BrennanConroy — APPROVED** [review]

**Pull request merged**
