### PR TITLE
Updated error message on AddContact.razor

### PR DESCRIPTION
**Pull request by ItDidntCatchFire**
The previous error message was about updating the Contact however this page was only used for adding new ones so now the message reflects that.

Follow the guidelines [here](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) as this seems more like a documentation change than a code change.

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by guardrex** [comment]
Thanks for this @ItDidntCatchFire ... Do you want to add the same update on this PR for ...

* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/3.1/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/AddContact.razor
* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/6.0/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/AddContact.razor

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22916) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22916) before we can accept your contribution.<br/><br/>:x: ItDidntCatchFire [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22916)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=22916) it.</sub>

**Review by guardrex — APPROVED** [review]
Thanks @ItDidntCatchFire! :rocket::rocket:

**Comment by guardrex** [comment]
Oh ... the CLA ... please sign that if you agree with it's terms :point_up:.

**Pull request merged**
