### PR TITLE
Update model-binding.md

### PR DESCRIPTION
**Pull request by pranavkm**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1&branch=pr-en-us-20412)

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
See [my commit](https://github.com/dotnet/AspNetCore.Docs/pull/20412/commits/eda04f1b80fcaa59fadd69a01ec7316e57632d4f) for a couple changes.

**Comment by Rick-Anderson** [comment]
Does this fix an issue?

**Review by pranavkm — COMMENTED** [review]
Thanks, edits look good!

**Comment by pranavkm** [comment]
@Rick-Anderson I was looking to point to a doc article for https://github.com/dotnet/aspnetcore/issues/27489 but it does not specifically resolve that issue.

**Pull request merged**
