### PR TITLE
Fixed typo in code sample

### PR DESCRIPTION
**Pull request by merill**
It took me a while to figure out there was a typo in the case of the letter i instead of upper case I.

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Thanks @merill! 🚀 

Before merging, I'm going to add a commit to this to rotate the 7.0 content to the top of the doc. That's something that I do after each release, and it was performed ... this topic snuck by the effort 😈. I'll double-check the others separately to make sure that they're ok. Thanks again!

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=28358) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=28358) before we can accept your contribution.<br/><br/>:x: merill [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=28358)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=28358) it.</sub>

**Comment by guardrex** [comment]
@merill ... Please sign the CLA if you agree with its terms :point_up:.

**Comment by merill** [comment]
Done. Tx!

**Comment by guardrex** [comment]
It didn't trigger a new build, so I'll close and re-open it to fire that off.

**Pull request merged**
