### PR TITLE
Code style fixes cross-site-scripting

### PR DESCRIPTION
**Pull request by remcoeissing**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22762) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22762) before we can accept your contribution.<br/><br/>:x: remcoeissing [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22762)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=22762) it.</sub>

**Comment by guardrex** [comment]
Hello @remcoeissing ... Please sign the CLA if you agree with its terms. We can't accept a PR without it.

**Comment by Rick-Anderson** [comment]
@guardrex  I emailed @remcoeissing , he's not registered with MSFT-GitHub yet.

**Comment by guardrex** [comment]
@Rick-Anderson ... btw ... just curious ... what is a "Customer Engineer with @microsoft"? ... is that an official capacity?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson ... btw ... just curious ... what is a "Customer Engineer with @microsoft"? ... is that an official capacity?

ask @remcoeissing  - yes, it's official

He's correctly registered with MSFT - GitHub so I guess we'll ignore the CLA warning.

**Review by guardrex — APPROVED** [review]
LGTM

**Comment by Rick-Anderson** [comment]
Thanks the the PR @remcoeissing , keep them coming.

**Pull request merged**
