### PR TITLE
Add Include not-lastest-version: Part 1: client-side to grpc folders

### PR DESCRIPTION
**Pull request by wadepickett**
Contributes to fixing #32886 

1st of a few PR's.  This PR covers folders of content in alpha order from client-side to grpc.  148 files.

`[!INCLUDE[](~/includes/not-latest-version.md)]` was inserted with one blank line above and below it existing after the edit.

Only files that met all of the following conditions received the inserted text:
- Is a .md file.
- Has versioning, indicated by :::Moniker range inline or monikerRange in the metadata
- Does not already have `[!INCLUDE[](~/includes/not-latest-version.md)]` in it.
- Is not an include file.
- Does not start with an H2 "##" before instead of an H1.
- Is not a README.md file (A few of these are in sample folders but are not accessible from the TOC).

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-33124) |
| [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/client-side/spa-services.md) | [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa-services?branch=pr-en-us-33124) |
| [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/data/ef-rp/crud.md) | [Part 2, Razor Pages with EF Core in ASP.NET Core - CRUD ](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?branch=pr-en-us-33124) |
| [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/data/ef-rp/intro.md) | [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0000.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0000.md) | [aspnetcore/diagnostics/asp0000](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0000?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0001.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0001.md) | [ASP0001: Authorization middleware is incorrectly configured](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0001?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0003.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0003.md) | ["ASP0003: Do not use action results with route handlers"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0003?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0004.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0004.md) | [ASP0004: Do not use action results with route handlers](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0004?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0005.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0005.md) | [aspnetcore/diagnostics/asp0005](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0005?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0006.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0006.md) | [ASP0006: Do not use non-literal sequence numbers](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0006?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0007.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0007.md) | ["ASP0007: Route parameter and argument optionality is mismatched"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0007?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0008.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0008.md) | [ASP0008: Do not use ConfigureWebHost with WebApplicationBuilder.Host](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0008?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0009.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0009.md) | [aspnetcore/diagnostics/asp0009](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0009?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0010.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0010.md) | [ASP0010: Do not use UseStartup with WebApplicationBuilder.WebHost](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0010?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0011.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0011.md) | ["ASP0011: Suggest using builder.Logging over Host.ConfigureLogging or WebHost.ConfigureLogging"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0011?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0012.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0012.md) | [ASP0012: Suggest using builder.Services over Host.ConfigureServices or WebHost.ConfigureServices](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0012?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0013.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0013.md) | [aspnetcore/diagnostics/asp0013](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0013?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0014.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0014.md) | [ASP0014: Suggest using top level route registrations](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0015.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0015.md) | ["ASP0015: Suggest using IHeaderDictionary properties"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0015?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0016.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0016.md) | [ASP0016: Do not return a value from RequestDelegate](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0016?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0017.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0017.md) | [aspnetcore/diagnostics/asp0017](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0017?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0018.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0018.md) | [ASP0018: Unused route parameter](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0019.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0019.md) | [ASP0019: Suggest using IHeaderDictionary.Append or the indexer](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0019?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0020.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0020.md) | ["ASP0020: Complex types referenced by route parameters must be parsable"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0020?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0021.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0021.md) | [ASP0021: The return type of the BindAsync method must be `ValueTask<T>`.](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0021?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0022.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0022.md) | [aspnetcore/diagnostics/asp0022](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0022?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0023.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0023.md) | [ASP0023: Route conflict detected between route handlers](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0023?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0024.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0024.md) | ["ASP0024: A route handler has multiple parameters with the [FromBody] attribute"](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0024?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/asp0025.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/asp0025.md) | [ASP0025: Use AddAuthorizationBuilder to register authorization services and construct policies.](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0025?branch=pr-en-us-33124) |
| [aspnetcore/diagnostics/bl0001.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b8363ebe0040986edc9cf357cee455c9e7d54a/aspnetcore/diagnostics/bl0001.md) | [aspnetcore/diagnostics/bl0001](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/bl0001?branch=pr-en-us-33124) |

</details>

> [!NOTE]
> This table shows preview links for the 30 files with the most changes. For preview links for other files in this PR, select <strong>OpenPublishing.Build Details</strong> within [checks](https://github.com/dotnet/AspNetCore.Docs/pull/33124/checks).

### CODE REVIEW

**Comment by wadepickett** [comment]
Closing and reopening for a fresh build.

**Comment by wadepickett** [comment]
@Rick-Anderson or @tdykstra , I am getting blocking warnings on the [aspnetcore/includes/not-latest-version.md](https://github.com/dotnet/AspNetCore.Docs/blob/wadepickett/32886AddNotLatestVersion_part1/aspnetcore/includes/not-latest-version.md) itself.  Am I inserting or using it in a way that it was not intended possibly? Or perhaps we are just getting new build check warnings we did not get before?

**Comment by wadepickett** [comment]
@guardrex, you have been using this not-latest-version include for blazor content successfully.  I don't know the history on it.  Was it intended to included only for very for specific versions of doc with specific ranges?  See the build errors on this PR.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson or @tdykstra , I am getting blocking build warnings on the [aspnetcore/includes/not-latest-version.md](https://github.com/dotnet/AspNetCore.Docs/blob/wadepickett/32886AddNotLatestVersion_part1/aspnetcore/includes/not-latest-version.md) itself. Am I inserting or using it in a way that it was not intended possibly? Or perhaps we are just getting new build check warnings on that include we did not get before?

I had the same error and @tdykstra showed me how to fix it. I don't remember the fix.

**Comment by guardrex** [comment]
It can't be used in files that are versioned for the current release (or later). What I do is leave it in place commented out with a searchable comment for activation. For example ...

https://github.com/dotnet/AspNetCore.Docs/edit/main/aspnetcore/blazor/components/sections.md

When 9.0 comes out, and I search "UPDATE 9.0" in the Blazor node (which will return a bunch of little things that I need to do around the Blazor docs when I'm working 9.0 tasks), I activate them.

What you'll have to do is search out all files with either "`monikerRange: '>= aspnetcore-8.0'`" or "`monikerRange: '>= aspnetcore-9.0`" and either remove the INCLUDE links or comment them out as I have. Any that have it for docs versioned >=8.0 can be activated when 9.0 releases. Any that have it for docs versioned >=9.0, won't be able to activate it until 10.0 releases.

**Comment by wadepickett** [comment]
After discussing with TDykstra and including gaurdrex helpful info, it sounds like there are 3 conditions involved:

**If the doc meta data at the top of the page has a monikerRange of:**
monikerRange: '>= aspnetcore-8.0'

Then insert this just below the H1 (#):
```
<!-- UPDATE 9.0 Activate after release and INCLUDE is updated
[!INCLUDE[](~/includes/not-latest-version.md)]
-->
```

**If the doc meta data at the top of the page has a monikerRange of:**
:::moniker range=">= aspnetcore-9.0"

Then insert this just below the H1 (#)
```
[!INCLUDE[](~/includes/not-ga-yet.md)]

<!--
[!INCLUDE[](~/includes/not-latest-version.md)] 
Uncomment this when 9.0 is the default value in the version selector and delete not-ga-yet.md
-->
```
**If the doc meta data at the top of the page has a monikerRange that is anything <8.0:**
Then insert this just below the H1  (#):
```
[!INCLUDE[](~/includes/not-latest-version.md)]

```

**Comment by wadepickett** [comment]
I will close this and do a much smaller number of files at a time until I am confident it all seems to work.

**Comment by guardrex** [comment]
That all sounds right to me. The only piece that I'm not doing right now is the `[!INCLUDE[](~/includes/not-ga-yet.md)]` bit, but I don't have new 9.0+ Blazor docs coming in for this release. I'd use that in the future tho, but I'd always mark it in the comment with "UPDATE 9.0" so that I can search them out later to find them (as you showed in your first example). The "UPDATE {VERSION}" comments have been super helpful 🦸 in avoiding having to litter the repo with issues or keep a long list of things that I need to check and update later.

**Pull request closed without merging**
