### PR TITLE
Simplify OpenIddict's description

### PR DESCRIPTION
**Pull request by kevinchalet**
Keeping the ASP.NET Core versions list up-to-date in OpenIddict's description depends on community contributions and proved to be a painful process. Mentions of ASP.NET Core and Microsoft.Owin are also problematic as OpenIddict now includes a client stack that aims at being a universal .NET client (that can be used in ASP.NET Core and OWIN web apps and but also in console/WPF/WinUI/UWP and Linux desktop apps): listing all the supported environments would make the description messy, so `Flexible and versatile OAuth 2.0/OpenID Connect stack for .NET` seems to be a simpler option.

On a related note, it's not clear at all why non-.NET projects like Gluu Server (built on top of the Janssen Project, which is Java-based) and Authentik (Python-based, AFAICT) are included in this list. This `community.md` page was originally created to list exclusively the authentication projects designed and built for ASP.NET Core: has anything changed in this regard?

Note: I'm OpenIddict's developer.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/27f2b956254535c08203988fc114becd206d9eb9/aspnetcore/security/authentication/community.md) | [Community OSS authentication options for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/community?branch=pr-en-us-29116) |

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
Much better, thanks

**Comment by kevinchalet** [comment]
@Rick-Anderson thanks! 😃 

When you have a moment, that would be nice to clarify this part:

> On a related note, it's not clear at all why non-.NET projects like Gluu Server (built on top of the Janssen Project, which is Java-based) and Authentik (Python-based, AFAICT) are included in this list. This `community.md` page was originally created to list exclusively the authentication projects designed and built for ASP.NET Core: has anything changed in this regard?

**Comment by Rick-Anderson** [comment]
@Tratcher @blowdart  should we trim the list?

**Comment by blowdart** [comment]
I have no real opinion here, because the language here isn't that much of a concern unless you want integration with things like . Maybe separate them into .NET and Other Languages and Frameworks.

**Pull request merged**
