### PR TITLE
Updated custom-formatters doc to ASP.NET Core 3.1

### PR DESCRIPTION
**Pull request by KSchlobohm**
Fixes an issue with the custom-formatters doc. The sample used in the doc references code from ASP.NET Core 2.2 when ASP.NET Core 3.1 is selected.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=18905) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=18905) before we can accept your contribution.<br/><br/>:x: KSchlobohm [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=18905)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=18905) it.</sub>

**Comment by Rick-Anderson** [comment]
@KSchlobohm  it's best to check before a non-trivial PR.

See Update Custom Formmatter #18795

**Comment by KSchlobohm** [comment]
Thanks @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@KSchlobohm  thanks for the PR and effort. Hopefully we'll see you again .

**Pull request closed without merging**
