### PR TITLE
Add Blazor Hybrid to no-loc metadata

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #24956

We want to make sure that Blazor Hybrid isn't localized, just like Blazor WebAssembly and Blazor Server.

IIRC, we're adding the global changes (via find-'n-replace) **_to the front of the list_**, while we'd add individual terms/phrases for specific topics to the end.

### CODE REVIEW

**Comment by guardrex** [comment]
> I'd rather see "Blazor Hybrid" after "Blazor WebAssembly" in the global list

...... ah, **_BUT_** ... what you just said ...

> have a few no-locs that aren't consistent 

... is exactly why when there are hundreds ... like 600+ of these ... adding to the front the **_safest approach_**. It's sure-fire going to work every time. The inconsistencies were bound to show up over time, so we just said that we'd place new global ones on the front .and per-doc ones on the end. It should work if the 😈 stay out of our `no-loc` lists; specifically, duplicates could be a potential problem. True, the order isn't reasonable, but all of the global entries will go away one day, per the following ............

What we really need is a global list in the repo config, and I think that was something Jason said they were thinking about or planning. It's more of an internal docs thing, so I'll leave it to the team if someone wants to ping Khoi Pham and ask about that.

**Comment by guardrex** [comment]
I won't hold u to account for this one. I'll go ahead without review, and they can **_RETIRE ME_** if they want 🏖️🇧🇧🍹😄 if things go sideways.

**Comment by serpent5** [comment]
I think I can override them and do the merge. Shall I?

**Comment by guardrex** [comment]
> I think I can override them and do the merge. Shall I?

That's ok ... I'll fix them. We need them fixed anyway, so I may as well. I'm working on them right now.

> that aren't using the complete "global" list

That's up to the team to address. AFAIK, the Blazor ones are consistent.

**Comment by serpent5** [comment]
> AFAIK, the Blazor ones are consistent.

Yup, that's what I'm seeing too.

I'm more than happy to approve this PR. The comments I made were just higher-level. The approach you've got here makes sense to me. I did try and submit an approval, but it keeps hanging my browser. 🐌

**Comment by guardrex** [comment]
Ok ... that **_lick'd 'um!_** 🐮👅 

**_ONE more thing to do before the 3-day weekend!_** *Woot!*

**Pull request merged**
