### PR TITLE
Update code snippets to the correct API - loadbalancing.md

### PR DESCRIPTION
**Pull request by erni27**
Update code snippets to the correct API.

https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.Net.Client/GrpcChannelOptions.cs

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> Update code snippets to the current API.

If these are changes from .NET 5 to .NET 6, I need to make a .NET 6 version of this file for you. We need to preserve the .NET 5 version while it's supported.

**Comment by erni27** [comment]
Actually, that’s not an upgrade to .NET 6. At first, I thought it was because of an obselete API.
https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.Net.Client/GrpcChannelOptions.cs
But now everything points to a small omission by the author.

**Comment by guardrex** [comment]
That's right ... this needs the update. `GrpcChannelOptions` ...

>Credentials ... A ChannelCredentials instance.

https://docs.microsoft.com/aspnet/core/grpc/configuration#configure-client-options

**Review by guardrex — APPROVED** [review]
Thanks @erni27! :rocket:

**Pull request merged**
