### PR TITLE
Add simple way of using QR Codes on TOPT authenticator

### LINKED ISSUE #32749: Add www.qrplus.com.br QR code generation
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-8.0&branch=pr-en-us-32748

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-enable-qrcodes.md

### Document ID

270bedc7-a636-5bd0-9e2f-e42235deec8c

### Article author

@Rick-Anderson

---
[Associated WorkItem - 261690](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261690)

### PR DESCRIPTION
**Pull request by marcelo-qrplus**
- create qrcode without adding any new lib to yout project
- keep others recomendations

There are no issue about this, but everytime I create a new project using Identity I felt this, so decided to help.

***EDIT by @Rick-Anderson*** Fixes #32749

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/dotnet/AspNetCore.Docs/blob/f4090669b4113d123d647637c7f138b8416ee0c9/aspnetcore/security/authentication/identity-enable-qrcodes.md) | [Enable QR code generation for TOTP authenticator apps in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?branch=pr-en-us-32748) |

### CODE REVIEW

**Comment by marcelo-qrplus** [comment]
@dotnet-policy-service agree [company="qrplus-code"]

**Comment by Rick-Anderson** [comment]
@blowdart  @adityamandaleeka  can you recommend someone to review this customer submission? Anything that helps customers stop asking for SMS 2FA and do it right would be very beneficial.

**Comment by blowdart** [comment]
The problem here is using a service to generate a QR Code for TOTP by necessity must share the TOTP shared key, the site name and the username with a third party service, which in turn could log those and use them to generate a TOTP for a user at any time.

So I'm afraid this just isn't suitable.

**Comment by marcelo-qrplus** [comment]
@blowdart That's a fair concern. What can we do to make it safer and still proceed with the recommendation?

I understand the importance of protecting the TOTP shared key, site name, and username from potential exposure. What if [QR Plus](https://www.qrplus.com.br/) creates an Open Source API on GitHub for this process? This would allow for community inspection and auditing, ensuring that the data is not logged or misused.

**Comment by blowdart** [comment]
Even with an API you would need the shared secret and other information to generate a QR code, and sharing that is a huge security risk. It's not something I would ever sign off on I'm afraid.

**Pull request closed without merging**
