### PR TITLE
Enhance Blazor JS Interop coverage

### LINKED ISSUE #14879: Insufficient clarity about calling an instance from JS
This document is very confusing for me as a C# developer who left JavaScript behind 10 years ago.

Could use a section describing how DotNetObjectReference could be used to pass an instance of a Blazor component to JavaScript (and therefore make its methods available) - or pass an injected singleton, for example.

It was not obvious to me that .then is synonymous with .ContinueWith and .ContinueWith is not ideal in BlazorWASM. A more simple JavaScript example would be welcome, it looks like an attempt has been made to cram as many different use cases as possible into one example, and it reads like insanity - creating a whole class to be a DotNetObjectReference factory to then call JavaScript to call the object created in that factory, which is a separate class to any Blazor pages.

(In the real world, on Client-Side Blazor, I found it simplest to create a static method on the Blazor component and have that call a static Action which is set to the instance method I actually want to call by the component's OnInitialized method - which is great so long as I only have one instance of the Blazor component)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #14972: Instance method call section is overly complex.
It could at least have showed how to call methods from same component which doesn't take more than ten lines, which I consider is very common scenario. Calling a method from calling component after a promise is completed to show progress or maybe result. which are not possible by static methods.

But, It goes beyond that and shows how to call methods from different instances created later.

that section could've been simplified or at least be more elaborated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #16682: Avoid memory leaks when invoking .NET instance methods
From @partyelite (moved from https://github.com/aspnet/AspNetCore.Docs/issues/16680) ...

There is nothing in the docs about avoiding memory leaks. I dug through the MS docs and found this link

https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference-1?view=aspnetcore-3.1

It says here that in order to avoid leaking memory, the DotNetObjectReference (used for invoking .NET instance methods from JavaScript) must later be disposed by JS code or by .NET code.

What is the best practice for disposing DotNetObjectReferences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #16682
Fixes #14972
Fixes #14879

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1&branch=pr-en-us-17075)

@shashikantx ... I really like the direction this is taking. Your example was an excellent basis for the multi-component scenario. I put you on here as an author. What URL do you want for the link? I can put your company, blog, etc. URL, or you can leave it pointed at your GH profile. You should review this first, then I'll call for an engineering review.

### CODE REVIEW

**Comment by shashikantx** [comment]
@guardrex Glad to hear that I could bring something to the table. 

And thank you for adding me as author, could you please point it to my site http://wisne.co ? thank you again.

And about what should I review ? I am unable to access the link **Internal Review Topic** ? Maybe I don't have permission to do so?

**Comment by guardrex** [comment]
Access the content on the diff (the "Files changed" tab). It's often easier to read the content with the "rich diff" or use the gear icon to "split" the diff. Correct, the "Internal Review Topic" is only for Microsoft folks.

**Comment by shashikantx** [comment]
@guardrex everything looks good,

maybe you also might want to add dispose method to my example? or move dispose example to bottom and bring this example above. That way it looks everything is done per standards.

**Comment by guardrex** [comment]
I probably need to do a little more work on disposal in that earlier section, too. That section was improved recently, but I think I didn't go far enough. I probably need to explain that when the `DotNetObjectReference` is created and passed into `IJsRuntime.InvokeVoidAsync` that the framework won't dispose of the object by itself.

**Comment by shashikantx** [comment]
Okay, looking forward to see those improvements soon.

**Comment by guardrex** [comment]
That set of changes ...

* Uses the new **_disposing version_** of *ExampleJsInterop.cs* in the two common sample apps per the updates that were made earlier to that section of text.
* Calls `.dispose()` in the new "helper" section added here.
* Tells the dev that if they don't dispose in the class/component, that they should dispose on the client with `.dispose()`.

This guidance definitely needs our engineers :eyes: to confirm and help flesh it out a bit more or correct it.

**Comment by shashikantx** [comment]
Yes, I was also about to ask about disposing the `DotNetObjectReference` to instance class.

**Comment by guardrex** [comment]
@javiercn to make sure that I'm not **_making things up here!_** 🙈

It seems like the pattern for disposal is that if the class/component doesn't dispose of `DotNetObjectReference` that the JS **_should take care of it_**. In all cases except using `DotNet`, disposal should be happening **_somewhere_** in dev code. That's the direction that the prior PR and this one are going.

**Comment by shashikantx** [comment]
Okay, it will be better if everything about disposal in all cases be described in that section.

**Pull request merged**
