### PR TITLE
Update SameSite doc

### LINKED ISSUE #17001: Update SameSite
With https://github.com/blowdart/AspNetSameSiteSamples

9K PV

Also, update the following

- [ ] [Work with SameSite cookies in ASP.NET](https://docs.microsoft.com/en-us/aspnet/samesite/system-web-samesite)   11K PV
- [ ] [Work with SameSite cookies in OWIN](https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite) 2K PV

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1945dedd-e2b8-37c1-2676-e473498bcb30
* Version Independent ID: 631281cb-65db-3196-1a6a-da9b3f2e3fed
* Content: [Work with SameSite cookies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/samesite.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/samesite.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #17001

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1&branch=pr-en-us-17050)

### CODE REVIEW

**Comment by blowdart** [comment]
Just one thing, can we get the 2.2 samples under samples, so people can see it with MVC as well (I know it's the same, but it'll reassure folks). There doesn't seem a way to point to the runnable/downloaded samples/solution so that'd be good to have.

**Comment by Rick-Anderson** [comment]
@blowdart  I can move the sample download links later in the article if you like.

**Comment by blowdart** [comment]
Wow I missed them right at the top. Maybe duplicate that table under additional resources as well or give it a heading so it shows under In This Article?

**Comment by Rick-Anderson** [comment]
@blowdart  great idea. I added an H2 AND listed them at the bottom

**Pull request merged**
