### PR TITLE
Added Service Static Files from multiple paths

### PR DESCRIPTION
**Pull request by shawnwildermuth**
Adds a section to explain how to correctly handle multiple files for Static Files. It is referenced in the Issue (https://github.com/dotnet/aspnetcore/issues/41341). 

Without a good explanation, there are too many solutions that mention calling `UseStaticFiles` middleware more than once, but this causes other parts of the codebase that are relying on `WebRootFileProvider` to not find additional paths. 

Hopefully I did the xref's correctly. This is my first PR in this repo.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Tratcher  is this is bug in the Tag Helpers? I've verified what @shawnwildermuth  states. We have [Serve files from multiple locations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#serve-files-from-multiple-locations), but that code doesn't support the version tag helper attributes. The following code generates a versions number, where `"~/images/MyImage.jpg"` is under `wwwroot`

```
@page
@model PrivacyModel
@{
    ViewData["Title"] = "RP Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>RP: Use this page to detail your site's privacy policy.</p>

<img src="~/images/MyImage.jpg" class="img" alt="My image" asp-append-version="true" />
```

With the following code:

```
app.UseStaticFiles(); // Serve files from wwwroot
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(
        Path.Combine(builder.Environment.ContentRootPath, "MyStaticFiles"))
});
```

Access to `/MyStaticFiles/image3.png` finds the file, but doesn't generate a version number

```
@page
@model TestModel
@{
    ViewData["Title"] = "Test  MyStaticFIles";
}
<h1>@ViewData["Title"]</h1>

<p> Test of /MyStaticFiles/image3.png</p>
<img src="~/image3.png" class="img" asp-append-version="true" alt="Test">
```

If it's not a bug, I'll update the document to say [Serve files from multiple locations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#serve-files-from-multiple-locations) works for everything except tag helpers. To use Tag Helpers versions, use @shawnwildermuth  approach.

LMK if you want the simplest possible sample that reproduces the problem.

**Comment by shawnwildermuth** [comment]
@Rick-Anderson I just blogged about it (and this change includes new instructions on how it works). You only need the one StaticFiles but you need to change the WebRootFileProvider:

```csharp
// Build the different providers you need
var webRootProvider = new PhysicalFileProvider(builder.Environment.WebRootPath);
var newPathProvider = new PhysicalFileProvider(
  Path.Combine(builder.Environment.ContentRootPath, @"Other"));

// Create the Composite Provider
var compositeProvider = new CompositeFileProvider(webRootProvider,
                                                  newPathProvider);
```

See my blog post:

https://wildermuth.com/2022/04/25/multiple-directories-for-static-files-in-aspnetcore/

**Comment by serpent5** [comment]
Just FYI, I suggested a similar approach in #24559, but PU decided to stick with calling `UseStaticFiles` twice (https://github.com/dotnet/AspNetCore.Docs/issues/24559#issuecomment-1010311020).

**Comment by Rick-Anderson** [comment]
@shawnwildermuth  I  move your PR to #25743 
That way I can work on it and you'll get credit for the merge.

**Comment by shawnwildermuth** [comment]
@Rick-Anderson that's not talked to this

**Comment by Rick-Anderson** [comment]
@shawnwildermuth  oops, github changed the link and used the repo you first reported. It's https://github.com/dotnet/AspNetCore.Docs/pull/25743

**Pull request closed without merging**
