### PR TITLE
VS19 or VS2022 for prerequisites /7

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  I should probably drop this new file and just update `net-prereqs-vs-6.0.md` with these changes that add VS 2022. I can't think of any cases where VS 2022 wouldn't work.

**Comment by guardrex** [comment]
I'm a bit confused about the "16.10" part ... should it be 17.0 or later? ... I thought that was VS 2022's first version number.

**Comment by Rick-Anderson** [comment]
@guardrex I'll update the preview version weekly. Check my latest comit.

**Comment by guardrex** [comment]
It's best if you go ahead and merge without my understanding on this. I don't know what this doc (`net-prereqs-vs-6.0.md`) is supposed to cover. AFAIK, 16.10 can't work with ASP.NET Core 6.0, so I don't understand the updates here.

**Comment by Rick-Anderson** [comment]
@guardrex  Don't Read too much from the file name. It's the VS requirements. There are two VS version, 2019 and the latest released version of that is 16.11.1 - see https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes
I'm adding VS 2022 because both versions work with .NET 6

**Comment by Rick-Anderson** [comment]
> 16.10 can't work with ASP.NET Core 6.0, so I don't understand the updates here.

Is that published? I've been testing with both 16.11 and VS 2022

**Comment by guardrex** [comment]
I see ... I guess my confusion was that DR is pushing VS2022 preview for 6.0 in blog posts. Perhaps, he just meant *suggested* for users. I see in the VS posts that they talk about 6.0 features (e.g., Hot Reload, MAUI, etc.) working with 16.11.

**Review by guardrex — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
I better check with DR. In https://github.com/dotnet/AspNetCore.Docs/pull/22941#pullrequestreview-722340118 Fowler wrote
> We actually need VS 2022

That's true for minimal APIs. It might be true for Web apps too.

**Comment by Rick-Anderson** [comment]
@LadyNaggaga @glennc  is Visual Studio 2022 required for all ASP.NET Core 6.0 apps or just Minimal APIs?

**Review by guardrex — CHANGES_REQUESTED** [review]
Waiting on approval until after the feedback arrives.

**Review by guardrex — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@guardrex  you're right, only VS 2022 is supported. See https://dotnet.microsoft.com/download/dotnet/6.0

**Comment by guardrex** [comment]
Organon

### *Oh! My horoscope said I'd be useful to somebody today.*

&mdash; Organon ([Geoffrey Bayldon](https://www.imdb.com/name/nm0001933/)) Dr. Who: [The Creature from the Pit](https://www.bbc.co.uk/programmes/b00s63gx), &copy;1979 [BBC](https://www.bbc.com/)

**Review by guardrex — APPROVED** [review]

**Pull request merged**
