### PR TITLE
Update WebAPI intro to RTM from RC2

### LINKED ISSUE #19782: 5.0 RTM updates needed for Create a web API
* [add-nuget-packages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&branch=pr-en-us-19781&tabs=visual-studio#add-nuget-packages) image
* delete line Select the **Include prerelease** checkbox so the 5.0 RC version is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&branch=pr-en-us-19781&tabs=visual-studio#add-nuget-packages)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #19782
https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&branch=pr-en-us-20664&tabs=visual-studio#add-nuget-packages

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@wadepickett  please review this ASAP.

**Comment by wadepickett** [comment]
Do you still want it reviewed?  I just saw it now when you pinged me, sorry.  I gave a thumbs up to show I was starting but you merged.

**Comment by Rick-Anderson** [comment]
Yes, please review the changes.

**Review by wadepickett — COMMENTED** [review]
Looks good, approved.

**Comment by Rick-Anderson** [comment]
@wadepickett  next time you the approve radio please.

image

**Comment by wadepickett** [comment]
@Rick-Anderson, I had tried but  couldn't.   Once you merged I didn't have that option.

**Comment by Rick-Anderson** [comment]
OK, thanks, didn't realize that.

**Pull request merged**
