### PR TITLE
AD rename /4

### LINKED ISSUE #30186: Cloud authentication with Azure Active Directory B2C
rename Azure AD yo Microsoft Entra ID
See #30185

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

---
[Associated WorkItem - 153935](https://dev.azure.com/msft-skilling/Content/_workitems/edit/153935)

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #30186
See [New name for Azure Active Directory](https://learn.microsoft.com/azure/active-directory/fundamentals/new-name)

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/94529f2e7c9ccea63630fa88438fb3785178281a/aspnetcore/security/authentication/azure-ad-b2c.md) | [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?branch=pr-en-us-30188) |

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
If:

> "Microsoft Entra External ID for customers" is Microsoft’s new customer identity and access management (CIAM) solution" 

shouldn't instances of Azure AD B2C be changed to that name?

**Comment by Rick-Anderson** [comment]
@tdykstra  
> shouldn't instances of Azure AD B2C be changed to that name?

B2C  is on the exception list, right?

**Comment by Rick-Anderson** [comment]
@CamSoper  can you take a look?

**Review by CamSoper — APPROVED** [review]
lgtm

**Pull request merged**
