### PR TITLE
Blazor file versioning (toc.yml-per-group)

### PR DESCRIPTION
**Pull request by guardrex**
This might be one of the nastiest 🙈 **_RexHax_**&trade; 🙈 that I've ever put up around here. 😄 I'm guessing on how to compose the bits.

This builds locally without too many errors. I'll toss the 🎲🎲 here and see what happens. **_Papa needs a new pair of shoes!_** 😆

1. The local build liked it, but here it didn't care for `### YamlMime:XRefMap` on the YML files: `Unknown schema 'XRefMap'.`
1. Without a schema on the YML files: `Unknown schema ''.` 
1. With `ManagedReference` schema: Result: `Unknown schema 'ManagedReference'.`
1. With `items:` and no schema and indented: Result: `Unknown schema ''.`
1. With `TableOfContents` schema: Result: `Unknown schema 'TableOfContents'.`
1. `items` with left-justified entries per [this guidance](https://review.docs.microsoft.com/en-us/help/contribute/toc-management?branch=main#nested-tocs): Result: ` Unknown schema ''.`
1. `items`, left-justified, and use the exact filename `toc.yml` for each group (version): Result: **_Seems like it built OK!_**

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson @wadepickett ... A-ha ... 🦖 **_BRUTE FORCE REX!_**&trade; 🦖

Ok, so ... we have a successful build. Try these ...

Open the following links to the Blazor *Class libraries* topic ...

* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-3.1&tabs=visual-studio&branch=pr-en-us-22903
* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-5.0&tabs=visual-studio&branch=pr-en-us-22903
* https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio&branch=pr-en-us-22903

1. Does the whole Blazor ToC load into the sidebar ToC correctly in the right spot with the right links?
2. Does each of those links load the correct version of the *Class libraries* topic?
3. Does each of those ToC sidebar link text entries get the selected highlight cue after each topic loads?

**Comment by wadepickett** [comment]
Testing now...
for item 1 I see duplicate "Blazor"  toc's

image


The rest in a minute...

**Comment by wadepickett** [comment]
Correction, there are three Blazor toc's.    All three show under Web apps > MVC > Blazor.  The first one has what may be the complete Blazor TOC, but the next two copies at the same TOC level have only Blazor > Tutorials > Build your first Blazor app.

**Comment by guardrex** [comment]
Thanks @wadepickett ...

### Multiple ToCs

Ok ... that does make sense that those extra ToCs are showing up. Here's why ...

There's one link in the Blazor ToC that off-repo .. and it is **_that one_** ...

```
- name: Build your first Blazor app
  href: https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/intro
```

Because that ONE entry isn't falling into the versioning scheme of the groups here, the docs are rendering a 2nd and 3rd ToC **_just to show that one link_**. To kill 🔪 those extra ToCs, either the docs system needs to understand how to version that entry, or that entry **_has to go_** from the `toc.yml` file. The latter isn't necessarily a problem. If the tutorials for Blazor weren't in the ToC directly but cross-linked via **_a versioned topic_**, e.g., the **_ASP.NET Core Blazor tutorials_** article (`3.1/blazor/tutorials.md`, `5.0/blazor/tutorials.md`, `6.0/blazor/tutorials.md`), that would permit us to remove it from the `toc.yml` file ... and thus ... in theory 👨‍🏫 ... 😄 ... those extra ToCs would disappear. I'll research this further on Monday.

### Highlight cue

The bold/background is more severe here and still rather opaque to me outside of understanding that the `is-selected` CSS style is still not being applied correctly on load. I'll think about it a bit more on Monday morning, and I'll alert the DocFX engineers to these results.

Thanks again. I'll leave this open until Monday and re-mark it a draft.

**Comment by wadepickett** [comment]
Your assessment of what is going on sounds right to me.

**Comment by guardrex** [comment]
Closing this test now. I'm having some better luck with a different approach in live testing with test docs.

**Pull request closed without merging**
