### PR TITLE
Split localization samples per AspNetCore version

### LINKED ISSUE #18545: Update localization to 3.1
I have downloaded the example which is pointed out in the beginning of the article and it's outdated - version is 2.2 when the page is placed under version 3.1 and when I open up the page I get aggregated exceptions which is basically about NullReferenceException.
So please, either fix the existing example, so that it won't throw some strange un-debuggable (or at least hard-to-debug-for-newbie) exceptions, or upload the new version which will be applicable to version 3.1.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #18545

### CODE REVIEW

**Comment by hishamco** [comment]
@Rick-Anderson there's few things we need before merge:

1. Update the references in the docs, I may need your help here

2. Check the .csproj

3. Shall we add a `PoLocalization` sample?

**Comment by Rick-Anderson** [comment]
> Update the references in the docs, I may need your help here

I'll take care of that.

>Check the .csproj

OK

> Shall we add a PoLocalization sample?

Let's do that in another issue/PR when you have time.

**Comment by hishamco** [comment]
Regarding the docs it will detect the proper sample version based on the selected version or shall I add sort of monikers?

**Comment by hishamco** [comment]
> Let's do that in another issue/PR when you have time.

Ok

For me I think I done, but let me do a quick review before final approval

Thanks

**Comment by Rick-Anderson** [comment]
> Regarding the docs it will detect the proper sample version based on the selected version or shall I add sort of monikers?

I'll take care of monikers

**Pull request closed without merging**
