### PR TITLE
Update TOC to include new Choose ASP.NET Core UI topic

### PR DESCRIPTION
**Pull request by wadepickett**
[Internal Review of TOC](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-5.0&branch=pr-en-us-22956)

Related to new topic PR #22635

### CODE REVIEW

**Comment by wadepickett** [comment]
@Rick-Anderson, should put the Choose UI topic in the TOC at both of the following locations, or just the first? 
1. ASP.NET Core Documentation > Tutorials > Web Apps
2. ASP.NET Core Documentation > Web Apps 


image

**Comment by Rick-Anderson** [comment]
I'd put it in both places and in the MVC, RP, and Blazor tutorial I'd add a link in the first paragraph to it.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
we should merge this and merge to live so it's published.

**Comment by Rick-Anderson** [comment]
Actually, only one place but create a include with a link and put that in the other tutorials.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks, you usually do the weekly merge to live.  Do you want to do that or should I merge this to Live?

**Pull request merged**
