### PR TITLE
Update diagnostics.md

### PR DESCRIPTION
**Pull request by parid0kht**
change *Startup.cs* to *Program.cs*

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
That won't work for 5.0, the default version. We need to create a 6.0 version of this topic. I could prepare the document for you if you'd like to update it for 6.0

**Comment by parid0kht** [comment]
@Rick-Anderson  yes, please. that would be great. thank you.

**Comment by Rick-Anderson** [comment]
@wadepickett  can you make a V6 moniker section for this?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=23405) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=23405) before we can accept your contribution.<br/><br/>:x: parid0kht [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=23405)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=23405) it.</sub>

**Comment by wadepickett** [comment]
@ parid0kht,  I added a commit, moving the .NET 6.0 version of this topic in a 6.0 or above moniker section.  At the bottom is the old original, in a .NET 3.0 to 5 moniker section.

I think you need to address the "CLA not signed yet" alert that has popped up inline before a build of the doc can occur.

After that I will check the build to make sure the versions show up correctly.

**Comment by Rick-Anderson** [comment]
@wadepickett  closing now. Create a new PR with the moniker prep.

**Pull request closed without merging**
