### PR TITLE
Prevent Blazor from being localized

### PR DESCRIPTION
**Pull request by Youssef1313**
Contributes to https://github.com/dotnet/docs/issues/22731

### CODE REVIEW

**Comment by guardrex** [comment]
**_Confirmed_** ...

https://docs.microsoft.com/fr-fr/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=webassembly#in-memory-state-container-service-wasm

Thanks @Youssef1313 ... let me check one thing before we merge this because we may have a more general coverage problem that I'm not fully clear on. Actually, you may know and can respond .......

@JasonCard ... I was about to update the `no-loc` string here to match our normal one ...

```
no-loc: [appsettings.json, "ASP.NET Core Identity", cookie, Cookie, Blazor, "Blazor Server", "Blazor WebAssembly", "Identity", "Let's Encrypt", Razor, SignalR]
```

... but I have to ask the general question: Should we be doing this for **_all of our INCLUDES_** files? If so, I'll close this PR and open an issue to address it everywhere across the docs.

btw- @JasonCard ... Also, the rendered pivot box at the top isn't honoring the `no-loc` metadata.
"Choose a Blazor hosting model" --> "Choisir un modèle d’hébergement éblouissant" ... and the names in the buttons are incorrect.

**Comment by guardrex** [comment]
@Youssef1313 ... I don't think we'll be using the PR for the change. This is probably going to have to happen **_everywhere_** here. Let me get confirmation from @JasonCard and then I'll proceed from there.

**Comment by Youssef1313** [comment]
@guardrex Feel free to close and open an issue or PR to address this everywhere in the repository.

I'd personally like a feature that allows specifying "no-loc" once in [docfx.json](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/docfx.json). Just like any other metadata being defined globally. For example:

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/docfx.json#L69-L91

This is currently not supported for no-loc AFAIK. But it will make things much easier to manage.

**Comment by guardrex** [comment]
@Youssef1313 ... I think that they're working on it ...

https://github.com/dotnet/AspNetCore.Docs/issues/15627#issuecomment-590565860

**Comment by JasonCard** [comment]
@Youssef1313 @guardrex 

> ... but I have to ask the general question: Should we be doing this for all of our INCLUDES files? It seems that we should. If so, I'll close this PR and open an issue to address it everywhere across the docs.

Yes, this is currently needed for each file as we don't yet have a global solution to block terms from being localized in all files.

> btw- @JasonCard ... Also, the rendered pivot box at the top isn't honoring the no-loc metadata.
"Choose a Blazor hosting model" --> "Choisir un modèle d’hébergement éblouissant" ... and the names in the buttons are incorrect.

Thank you for pointing this out. I found that [zone-pivot-groups.yml](https://github.com/dotnet/AspNetCore.Docs/blob/live/aspnetcore/zone-pivot-groups.yml) file was being machine translated, but this file should not have been localized in the first place, so I've corrected this and it should be falling back to English shortly.

> I'd personally like a feature that allows specifying "no-loc" once in docfx.json. Just like any other metadata being defined globally.

This idea has been proposed, but was not a feasible solution. As docfx.json file is used for publishing, but not used to determine which text should be localized or not. The "no-loc" metadata is used by our loc platform when extracting localizable text from the source files and it's not feasible for it to reference docfx.json file. 
One pending global solution is a dynamic dictionary feature for our Machine Translation engine, but there is no ETA and it may take quite awhile.

**Comment by guardrex** [comment]
Thanks @JasonCard.

Thanks @Youssef1313 ... I'll open an issue and address this across the INCLUDES.

**Pull request closed without merging**
