### PR TITLE
Update key-storage-providers.md

### PR DESCRIPTION
**Pull request by RobinNorberg**
A small code syntax fix

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/708b3cc9bd006e28e8e6f6519c5c3bbf988cfa11/aspnetcore/security/data-protection/implementation/key-storage-providers.md) | [aspnetcore/security/data-protection/implementation/key-storage-providers](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?branch=pr-en-us-28768) |

### CODE REVIEW

**Comment by RobinNorberg** [comment]
@dotnet-policy-service agree

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@RobinNorberg  wow, it made you sign for a 1 character addition. Much appreciate the fix.
Fixes #28769

**Comment by Rick-Anderson** [comment]
@RobinNorberg  for more fun
Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Comment by Rick-Anderson** [comment]
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

**Pull request merged**
