### PR TITLE
[RC1] Doc Http/3 for Http.Sys

### PR DESCRIPTION
**Pull request by Tratcher**
Fixes https://github.com/dotnet/aspnetcore/issues/35204

Consider holding this update until RC1 releases.

### CODE REVIEW

**Comment by wtgodbe** [comment]
What about:

```
  <ItemGroup>
    <!-- Required for QUIC & HTTP/3 in .NET 6 - https://github.com/dotnet/runtime/pull/55332 -->
    <RuntimeHostConfigurationOption Include="System.Net.SocketsHttpHandler.Http3Support" Value="true" />
  </ItemGroup>
```

**Comment by Tratcher** [comment]
> What about:
> 
> ```
>   <ItemGroup>
>     
>     <RuntimeHostConfigurationOption Include="System.Net.SocketsHttpHandler.Http3Support" Value="true" />
>   </ItemGroup>
> ```

That's only required for HttpClient.

**Comment by Tratcher** [comment]
@Rick-Anderson the monikers need work. How should we handle them for 5.0 and 3.1?

**Review by Rick-Anderson — COMMENTED** [review]
> @Rick-Anderson the monikers need work. How should we handle them for 5.0 and 3.1?

I can fork this and fix them. You can review my PR and merge into this branch. OR, I could just create a new PR with them fixed and all the content you have here.  Your call.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson the monikers need work. How should we handle them for 5.0 and 3.1?

I should probably make a RC1 branch and when this is finished, merge to RC1. At RC1, we can merge the RC1 branch into main.

**Comment by Tratcher** [comment]
> > @Rick-Anderson the monikers need work. How should we handle them for 5.0 and 3.1?
> 
> I can fork this and fix them. You can review my PR and merge into this branch. OR, I could just create a new PR with them fixed and all the content you have here. Your call.

Whatever's easier for you.

**Comment by Rick-Anderson** [comment]
@Tratcher I can always prepare the `::: moniker range=">= aspnetcore-6.0"` section for you.

**Comment by Rick-Anderson** [comment]
moved  to  #23257

**Pull request closed without merging**
