### PR TITLE
Add docs on preventing rendering after event handling

### PR DESCRIPTION
**Pull request by captainsafia**
Addresses https://github.com/dotnet/aspnetcore/issues/18919.

### CODE REVIEW

**Comment by guardrex** [comment]
@captainsafia ... I understand why its here, but the subject matter groups well with the *Event Handling* topic. Is this one of those scenarios that really isn't being pushed out there in the open for the majority of use cases, thus it can hide a bit back here as a perf-only scenario for edge case folks dealing with perf trouble?

**Comment by captainsafia** [comment]
>  I understand why its here, but the subject matter groups well with the Event Handling topic. Is this one of those scenarios that really isn't being pushed out there in the open for the majority of use cases, thus it can hide a bit back here as a perf-only scenario for edge case folks dealing with perf trouble?

Yep -- we don't anticipate this is a common scenario and want to put it here for some select scenarios.

**Comment by guardrex** [comment]
@captainsafia ... See if I accidentally *GooberRexified*&trade; 🙈 your section. A few points ...

* I've been making most examples fully working cut-'n-paste examples.
* You had `onclick="@..."` syntax for the buttons' handlers. I changed them to the usual `@onclick="..."` syntax, and they seem to work that way. I'll revert if that's incorrect. :ear:

**Comment by captainsafia** [comment]
@guardrex Thanks for the edit! These changes look good.

> For ReceiverBase, the comment didn't seem complete ...

Actually, I like your approach better. No need to have comments on code users will be copying into their projects.

> You had onclick="@..." syntax for the buttons' handlers. I changed them to the usual @onclick="..." syntax, and they seem to work that way. I'll revert if that's incorrect. 👂

Should still work.

**Pull request merged**
