### PR TITLE
Host Linux Apache: Add distros Ubuntu & SLES & RHEL

### LINKED ISSUE #27205: ubuntu apache2 header rewrites note
in the deploying .net core apps with apache section it mentions setting up forwarded headers and configuring them in the example .conf file:
```
<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>
```

Using ubuntu - might be good to add a note in here that this might not necessarily work out of the box unless you enable the apache headers module with 
`sudo a2enmod headers`

Also, you may need to disable the default apache domain with `sudo a2dissite 000-default.conf ` and enable the example domain file with `sudo a2ensite helloapp.conf`

I couldn't use the existing document to get my example up and running without doing these two additional things on ubuntu and was a real head scratcher.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-6.0#https-configuration)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

---
[Associated WorkItem - 67368](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67368)

### LINKED ISSUE #27605: Host Linux Apache: Change for RHEL, Ubuntu & SLES and Apache2
Related to Linux content improvement project tracked internally here: [Azure DevOps 30648](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30648/)

Originally written/coded for CentOS and an early Apache2.  Add/update commands and config, mods etc. for RHEL, Ubuntu and SLES plus more recent Apache2 (changes in mods, config, etc. need to be reflected, and different per Linux distro.

This doc may require additional work be completed in a separate issue/pr.  The goal for this one is to get RHEL, Ubuntu and SLES represented quickly on what would be a reasonable Apache2 install stream.  

Also:
Investigate and fix for the following raised issues:
<html>
<body>

Area | Follows standard (yes/no) | Notes
-- | -- | --
Major Linux distributions | No | Prequisite requires CentOS- software is available for ALL major distros, new standard is tabs for all three distros (RHEL/SLES/Ubuntu) as seen in this doc example: see this example: :https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric
Linux distribution trees | No | Distribution level is EOLUpdate content to include most recent versions of RHEL and SLES and Ubuntu
Package management commands | No | several sections contain "yum" commands, will not work on SLES or Debian/Ubuntu servers New standard is tabs for all three distros (RHEL/SLES/Ubuntu) as seen in this doc example: see this example: :https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric
Linux tool/command preferences | No | several sections lists nano command. While Nano is considered commonly acceptable, it is not an industry standard like vi/vimConsider changing to vi/vim or make editor agnostic

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

---
[Associated WorkItem - 340923](https://dev.azure.com/msft-skilling/Content/_workitems/edit/340923)

### PR DESCRIPTION
**Pull request by wadepickett**
[Internal Review](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-8.0&branch=pr-en-us-28060&tabs=linux-ubuntu)

fixes #27605    Host Linux Apache: Change for RHEL, Ubuntu & SLES and Apache2
fixes #27205     ubuntu apache2 header rewrites note

Adding Ubuntu and SLES distros and command examples.

### CODE REVIEW

**Comment by wadepickett** [comment]
@leecow, I am in the middle of updating this ASP.NET served on Apache topic (Draft).  I am adding Ubuntu and SLES instruction as we did for the Nginx focused topic.   However, this original doc was centered on CentOS 7.  Should I change from CentOS to RHEL?  CentOS Stream will be changing often.  Going with RHEL 8 (or later) will keep this topic a bit more stable and folks can use it as a basis for whatever downstream distro of RHEL if they need to.  Thoughts?

**Comment by leecow** [comment]
I'd be surprised if CentOS Stream will be churny enough to disrupt an area like this but, who knows? That said, RHEL is a good choice as it will better represent the enterprise scenario

**Comment by wadepickett** [comment]
I will go with RHEL then, thanks @leecow.

**Comment by wadepickett** [comment]
@leecow & @Rick-Anderson,  I ran into a problem with this doc that is killing me here and hoping you might know what the issue is:   Changing this topic over to Ubuntu with required mods, I can get the virtual host config for the reverse proxy to work.  However, I can't with SLES and RHEL and I must be missing something basic.

Apache fails to run with the virtual host .config.  Checking error logs, apache status and running a `apachectl configtest` it is clear the ErrorLog and CustomLog settings in the .config is where it is being tripped up:
` [core:warn] [pid 30558] AH00111: Config variable ${APACHE_LOG_DIR} is not defined`

Here is the virtual host config:

<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/
    ServerName www.example.com
    ServerAlias *.example.com
    ErrorLog ${APACHE_LOG_DIR}helloapp-error.log
    CustomLog ${APACHE_LOG_DIR}helloapp-access.log common
</VirtualHost>


Sounds like I need to set something in the base default config or set a definition somewhere at a higher level specifically for Apache2 on RHEL and SLES but I honestly don't know what that is and I'm not finding the answer armed with just the error info.

Any ideas or helpful info would be greatly appreciated!

See [Internal Review - RHEL and SLES tabs for Install and Config](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-8.0&branch=pr-en-us-28060&tabs=linux-rhel#install-apache)

**Comment by wadepickett** [comment]
@adegeo, any ideas on the extra step missing here specifically for RHEL and SLES?

**Comment by wadepickett** [comment]
Issue solved:  Was simply that the original virtual host settings in this doc at some point had a typo and apparently its final version not tested.  A forward slash was missing. I didn't see it either.  (ugh).  Thanks for an awesome community member pointing this out on pr #28580.

ErrorLog ${APACHE_LOG_DIR}helloapp-error.log should be ErrorLog ${APACHE_LOG_DIR}/helloapp-error.log

**Comment by selvinfehric** [comment]
I would be glad to help with this if needed. I did a setup on Ubuntu 20.04 with Apache2 right now so I am fresh with it :) That is how I spotted #28580. I was also wondering why it is a CentOS-only doc... But now I see you are updating it.

**Comment by wadepickett** [comment]
@selvinfehric, cool thanks!  I will add you to the review list and keep you in the discussion.  Any suggestions always welcomed.

**Comment by Rick-Anderson** [comment]
@wadepickett  closing for now. You can open when you have time to work on this.

**Comment by wadepickett** [comment]
Thanks, yes best to close for now but will finish, sorry for leaving this open and unfinished so long.  We were only focusing on 8.0 last month and this month, so I had to put it on the back burner even though most of it was done and I finally figure out why one of the previous steps didn't work (and never did).

**Pull request closed without merging**
