### PR TITLE
Add HttpLogging docs

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/dotnet/aspnetcore/issues/31859

Still a WIP, but want to leverage CI for a few things I'm uncertain of.

***@Rick-Anderson  Edit MOVED TO #22103 - no commit here, do them in #22103***

### CODE REVIEW

**Comment by jkotalik** [comment]
@Rick-Anderson @guardrex most of the content is here now, can you help with polish?

**Comment by jkotalik** [comment]
This is brand new for preview4, I'm not sure when API docs will be available for it.

**Comment by guardrex** [comment]
@Rick-Anderson ... I'm neck-deep 😨 in Blazor forms and validation bits at the moment, but I should be free Friday if you want me to take this one.

@jkotalik ... If I end up assisting, I'll open a follow-up issue for post 6.0 GA to take care of the API doc cross-links.

WRT the *Cyberdine Systems Snippet Builder 5000* ... The build system isn't building with the preview SDK, so we'd end up merging without a passing build or alternatively upgrading to use the preview SDK.

**Comment by jkotalik** [comment]
It doesn't need to happen today, but ideally before mid may 😄

**Comment by Rick-Anderson** [comment]
I'll take care of it.

**Comment by Rick-Anderson** [comment]
@jkotalik  your writing is excellent. I'm pr'ing this PR in #22103, so you can see my changes. I can have it done by next week. I'm just getting started.

**Pull request merged**
