### PR TITLE
FF doesn't trust dev cert

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20349

### CODE REVIEW

**Comment by blowdart** [comment]
Seems odd, there should be an mechanism to import and trust in Firefox rather than ruling it out altogether.

**Comment by guardrex** [comment]
I use FF, and I'm not having the trust issue that @jaoord indicated. I recommend more analysis on what might be causing that.

**Comment by jaoord** [comment]
> 
> 
> I use FF, and I'm not having the trust issue that @jaoord indicated. I recommend more analysis on what might be causing that.

Interesting, because I also thought it used to work before. Are you on windows?

**Comment by jaoord** [comment]
> 
> 
> I use FF, and I'm not having the trust issue that @jaoord indicated. I recommend more analysis on what might be causing that.

Interesting, because I also thought it used to work before. Are you on windows?

**Comment by jaoord** [comment]
> I use FF, and I'm not having the trust issue that @jaoord indicated. I recommend more analysis on what might be causing that.

Thanks. I thought I was getting delusional because I thought it used to work before at my computer as well. I dug a little deeper and found this: [Firefox no longer trusts my internal certificate authority used for internal sites on our domain.](https://support.mozilla.org/en-US/questions/1175296#answer-1006092)

According to the accepted answer there you need to set **security.enterprise_roots.enabled** to **true** (in about:config).
Did that and verified that I can now visit my localhost dotnet core website over https.

**Pull request closed without merging**
