### PR TITLE
SignalR Hubs: Clarify hub essential part of client-to-client communication

### LINKED ISSUE #32066: SignalR Hubs: Clarify a hub is required
### Description

Customer feedback ported from the unified feedback tool:

Feedback Verbatim:
"I am not sure if a Hub is an essential part for each Blazor server app. E.g. do I need it if each client works isolated from any other."

[Internal tracking in DevOps Unified Feedback Item](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230046/)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md

### Document ID

fb016cdc-d281-6b5b-7466-2c718e7274b4

### Article author

@bradygaster

---
[Associated WorkItem - 251074](https://dev.azure.com/msft-skilling/Content/_workitems/edit/251074)

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #32066 

The intro to the hubs topic emphasizes that a SignalR Hub API enables communication between client and server and does not really give the impression that a hub is also essential to facilitate client-to-client communication. Making that role a little more explicit here in the intro since it was causing some confusion.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/336495fc1edd438519cee868fa79dc75d71b3e91/aspnetcore/signalr/hubs.md) | [Use hubs in SignalR for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/hubs?branch=pr-en-us-32516) |

### CODE REVIEW

**Comment by wadepickett** [comment]
@BrennanConroy, does this change in the intro to clarify the hub also has a role in client to client work OK?

**Comment by BrennanConroy** [comment]
"client to client" makes it sound like we're doing some kind of [STUN](https://en.wikipedia.org/wiki/STUN) server mechanism. But what we really mean is the server can send to clients, therefore you can indirectly send a message from one client to another through the server.

**Comment by wadepickett** [comment]
@BrennanConroy,  Thanks for the help.  Is this revised intro for the SignalR Hubs API better?

**Review by BrennanConroy — APPROVED** [review]
Thanks 😃

**Pull request merged**
