### PR TITLE
Fix Some Missing Accessible Names for Input Elements

### PR DESCRIPTION
**Pull request by Grunet**
These are just the ones I noticed from a quick search, I'm guessing there are others still around.

I picked the label wrapping approach for giving the inputs their accessible names because I saw other places in the code doing that.

Is there some kind of linter or unit test tool for `cshtml` files that could surface these more easily? (like axe linter) Just curious

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/08cd00d39a5db4ad62d68770fa76d9797e9c485c/aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md) | [ASP.NET Core Razor class libraries (RCLs) with static server-side rendering (static SSR)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries-and-static-server-side-rendering?branch=pr-en-us-33714) |
| [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/08cd00d39a5db4ad62d68770fa76d9797e9c485c/aspnetcore/mvc/models/model-binding.md) | [Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=pr-en-us-33714) |
| [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/08cd00d39a5db4ad62d68770fa76d9797e9c485c/aspnetcore/mvc/views/razor.md) | [Razor syntax reference for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?branch=pr-en-us-33714) |
| [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/08cd00d39a5db4ad62d68770fa76d9797e9c485c/aspnetcore/mvc/views/working-with-forms.md) | [aspnetcore/mvc/views/working-with-forms](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?branch=pr-en-us-33714) |
| [aspnetcore/release-notes/aspnetcore-5.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/08cd00d39a5db4ad62d68770fa76d9797e9c485c/aspnetcore/release-notes/aspnetcore-5.0.md) | [What's new in ASP.NET Core 5.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-5.0?branch=pr-en-us-33714) |

### CODE REVIEW

**Comment by Grunet** [comment]
@dotnet-policy-service agree

**Comment by guardrex** [comment]
Thanks @Grunet ... I'm ok with the Blazor update.

Note for future reference that we ask for an issue prior to submitting work for anything other than small patch changes.

**Review by guardrex — APPROVED** [review]

**Comment by Grunet** [comment]
> Thanks @Grunet ... I'm ok with the Blazor update.
> 
> Note for future reference that we ask for an issue prior to submitting work for anything other than small patch changes.
> 
> BTW ... Blazor forms work is tracked by an existing work item, and I'll be making this change and several others together. If you perform any further updates on the repo in this vein, filter out the Blazor articles (`blazor` folder) to avoid updates to them.

Ah got it sorry about that! I was initially planning on just addressing the 1 spot I originally noticed but then I noticed other spots had it too and got carried away...

**Review by wadepickett — APPROVED** [review]
I checked through the content to see if we happen to reference a line in a way that would need to change to sync with the addition of <label></label>.  I didn't find any.

Looks good. @Grunet, thanks very much for this contribution, greatly appreciated!

**Pull request merged**
