### PR TITLE
Add dotnet tools to PATH

### PR DESCRIPTION
**Pull request by themagiccog**

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @themagiccog ... This shouldn't be necessary. The SDK installer takes care of it. If you can repro it ***not*** behaving, please open an issue here with the steps so that they can investigate the problem with you ...

https://github.com/dotnet/sdk/issues

**Comment by themagiccog** [comment]
You can reproduce the issue by simply working thru the steps in the document.

**Comment by guardrex** [comment]
It has nothing to do with the document.

How did you install .NET on your system?

**Comment by themagiccog** [comment]
I followed this:
https://dotnet.microsoft.com/en-us/download

**Comment by guardrex** [comment]
Good, that's the correct approach if one isn't using VS to receive .NET.

You can try uninstalling .NET, confirming that the PATH entry is removed (or remove it manually), and re-installing from the SDK installer ***as an admin*** to see if that successfully updates the PATH. That's the only thing that leaps to mind. If it still doesn't make the PATH entry, then you'll need to open an issue for the team that works on the SDK at ...

https://github.com/dotnet/sdk/issues

... which is (for the most part) a different team than the ASP.NET Core product unit. They'll investigate with you why the PATH isn't being set properly.

**Pull request closed without merging**
