### PR TITLE
Minimal API windows service sample

### PR DESCRIPTION
**Pull request by tothalexlaszlo**
The sample shows how to host an ASP.NET Core app using Minimal API as a Windows Service .

### CODE REVIEW

**Comment by guardrex** [comment]
Is this for an issue, @tothalexlaszlo? If not, we usually require an issue for anything beyond a patch update.

**Comment by tothalexlaszlo** [comment]
> Is this for an issue, @tothalexlaszlo? If not, we usually require an issue for anything beyond a patch update.

Not for a posted issue. I run into this problem myself how to create a win service with Minimal API. I thought It would be help for others to find an example.

**Comment by guardrex** [comment]
We won't be able to take a PR on this without the associated topic changes.

The issue that goes with this is ...

**.NET 6: Host ASP.NET Core in a Windows Service**
https://github.com/dotnet/AspNetCore.Docs/issues/23847

Do you want to work with the topic, or should we close this and just mark your sample here on the issue for whichever doc author takes that issue on for work later?

**Comment by guardrex** [comment]
@tothalexlaszlo ... I think the best way to go is to go ahead and take this in ... and note in the issue that topic text work will need to be done to tie it in. Thanks for sending this.

**Review by guardrex — APPROVED** [review]

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25037) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25037) before we can accept your contribution.<br/><br/>:x: tothalexlaszlo [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25037)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=25037) it.</sub>

**Comment by guardrex** [comment]
@tothalexlaszlo ... Please sign the CLA if you agree with its terms. We can't accept the PR without it.

**Comment by tothalexlaszlo** [comment]
> @tothalexlaszlo ... Please sign the CLA if you agree with its terms. We can't accept the PR without it.

Signed

**Pull request merged**
