### PR TITLE
Add preview 2 features

### PR DESCRIPTION
**Pull request by tdykstra**
contributes to #31770 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/e853c018c2a062e1215dd9047e81b450f7ada3c9/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32034) |

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
NIT if you want to ... I'd recommend changing the broken sentence ("For example, the following code:" ... "Can now be simplified to the following code:") into two complete sentences. I suspect MT has a better shot if they're phrased as normal sentences.

**Comment by guardrex** [comment]
Side note for us all (@Rick-Anderson, @wadepickett) ... but u guys may already recall it ...

I was just reminded that under our new INCLUDE file scheme that updating an INCLUDE doesn't automatically update the *Migration* article. I'll probably flip the `ms.date` forward or backward or add/subtract a space at the end of a line to trigger the article to rebuild with an INCLUDE file change.

**Review by danroth27 — APPROVED** [review]
:shipit:

**Review by wadepickett — APPROVED** [review]
Looks great with the update.  Thanks Tom.

**Pull request merged**
