### PR TITLE
Broken links sweep

### PR DESCRIPTION
**Pull request by wadepickett**
Contributes to fixing #21751 

This PR fixes all 5.0 to 2.1 version broken links, except for a few where the link is still good but the issue was that the ssl cert expired.

### CODE REVIEW

**Comment by guardrex** [comment]
@wadepickett ... Looks like your remote wasn't up-to-date for this. Do you want me to take care of the Blazor node link updates and then you can just drop them from this? Your PR might ✨ **_Just Build_**&trade; ✨ when you drop those nonexistent Blazor links.

**Comment by guardrex** [comment]
I put the Blazor ones up at #23024. If you want, I can add the rest of them from this PR to that. Let me know. :ear:

**Comment by wadepickett** [comment]
@guardrex,  That sounds good, thanks for adding them to the PR.  It wasn't clear to me at first if the docs were deleted or moved at first after I had fixed the links.

**Comment by wadepickett** [comment]
Closing and opening a new PR that excludes the Blazor docs that moved, plus added some more.

**Pull request closed without merging**
