### PR TITLE
Blazor File Downloads Documentation

### PR DESCRIPTION
**Pull request by TanayParikh**
Fixes: https://github.com/dotnet/aspnetcore/issues/30736

### CODE REVIEW

**Comment by guardrex** [comment]
@TanayParikh ... I'll look closer in the morning, but is this meant to replace the existing coverage at ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-javascript-to-net
* https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript

**Comment by TanayParikh** [comment]
> but is this meant to replace the existing coverage at ...

No this is to provide a more in depth guide, specifically detailing how to download a file (and the associated nuances). The underlying mechanism of streaming from `.NET` to `JS` is covered by https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript, however this article expands on the functionality to facilitate downloads (including JS specific code to trigger a download).

**Comment by guardrex** [comment]
Ok, great ... then just a cross-link over in that section to this seems right.

Ok, cool. It's best if a make an edit pass on this as opposed to a lot of `suggestion` comments ... it'll be faster that way. I'll ping u back.

**Comment by guardrex** [comment]
Looks like the 😈 are having their way with you!! 😆 You don't have to sweat these build errors if you don't want to. I can fix them up on Monday.

**Comment by TanayParikh** [comment]
> Ok, great ... then just a cross-link over in that section to this seems right.

Updated 6ab1a9a55.

> Ok, cool. It's best if a make an edit pass on this as opposed to a lot of `suggestion` comments ... it'll be faster that way. I'll ping u back.
>
> I'll have to check my hours tho. I guess you don't mind if I do the update on Monday morning, right? I'm sure the **_rotten_** 🐱 will have me up at 4am again! 😡

Sounds great, feel free to edit / change as you see fit. And no rush at all. Have a great weekend! 😄

**Comment by TanayParikh** [comment]
> Looks like the 😈 are having their way with you!! 😆 You don't have to sweat these build errors if you don't want to. I can fix them up on Monday.

Fixed! 🥇

**Comment by guardrex** [comment]
Sorry for the delay ... got bogged down this morning in a couple of doc 🐛🐛.

I'll get on this right now and should have an update pass done within an hour 🤞.

**Comment by TanayParikh** [comment]
Thanks @guardrex, this looks great! I believe it should be ready to merge 😄

**Pull request merged**
