### PR TITLE
Update JS collocation guidance

### LINKED ISSUE #31321: There is a typo in one of the code examples
### Description

image

In the above code screenshot, it should read "var ..."

Without the "var" the code displays an error message (module is not defined)

image

I also want to note that the current Blazor 8 templates use "Home" instead of "Index".  The samples show the use of Index instead of Home.  Not a biggie, but I thought I would point it out.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#javascript-location

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/index.md

### Document ID

49fa31d8-72a6-01a1-027d-6edeac9e0fc4

### Article author

@guardrex

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #31321

Thanks @gregoryagu! 🎸 ... This should fix both problems ...

* I call out what `module` is as a private nullable JS object ref field, and I fix up our JS collocation guidance by using two INCLUDE files now, one for 7 or earlier with `Index` for Blazor and one for 8 or later with `Home` for Blazor, noting that MVC/RP have retained `Index` at 8.0.
* ~I also noticed that we had an error in our RP JS collocation coverage. That feature didn't come in until 6.0, but the RP doc didn't version the INCLUDE, so it was showing incorrectly for 3.1 and 5.0. I fixed that up.~ **CORRECTION**: No, there was a 6.0 moniker early in the article that I didn't see at first. It was good, but there's another problem with duplicate headings. I might need to back the changes out of the RP until Rick can take a look and adjust the article himself on a different PR later.

Thanks for the issue and Happy New Year! 🎉🍾💃🕺🥳 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/b58611d9fdece678e4264bb01852f9ce57e11b28/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-31322) |
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/b58611d9fdece678e4264bb01852f9ce57e11b28/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-31322) |
| [aspnetcore/blazor/hybrid/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/b58611d9fdece678e4264bb01852f9ce57e11b28/aspnetcore/blazor/hybrid/static-files.md) | [ASP.NET Core Blazor Hybrid static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/static-files?branch=pr-en-us-31322) |
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/b58611d9fdece678e4264bb01852f9ce57e11b28/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-31322) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b58611d9fdece678e4264bb01852f9ce57e11b28/aspnetcore/blazor/javascript-interoperability/index.md) | [aspnetcore/blazor/javascript-interoperability/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-31322) |

### CODE REVIEW

**Comment by gregoryagu** [comment]
Thanks Luke!  One more question:

My code doesn't actually work, but I am not sure why.  I followed the docs carefully, and this is what I come up with. But the code throws an error "Microsoft.JSInterop.JSException: 'Could not find 'showPrompt' ('showPrompt' was undefined)." 

But showPrompt is getting correctly downloaded to the browser:

image

So it is unclear to me why the call to showPrompt does not work.

```
<PageTitle>Home</PageTitle>


@inject IJSRuntime JS;

<button @onclick="ExecuteShowPrompt">showPrompt</button>


@code{

    public async void ExecuteShowPrompt()
    {
        await JS.InvokeVoidAsync("showPrompt", "Hello World");
    }

    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        var module = await JS.InvokeAsync<IJSObjectReference>("import", "./Components/Pages/Home.razor.js");
        await base.OnAfterRenderAsync(firstRender);
    }

}
```

**Comment by guardrex** [comment]
Call it from the module ... that's why `module` is set up as a field. Also, you'll dispose normally.

```razor
@page "/"
@rendermode InteractiveServer
@implements IAsyncDisposable
@inject IJSRuntime JS

<PageTitle>Home</PageTitle>

<h1>Home</h1>

<button @onclick="ExecuteShowPrompt">showPrompt</button>

@code {
    private IJSObjectReference? module;

    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        module = await JS.InvokeAsync<IJSObjectReference>("import", 
            "./Components/Pages/Home.razor.js");
    }

    public async void ExecuteShowPrompt()
    {
        if (module is not null)
        {
            await module.InvokeVoidAsync("showPrompt", "Hello World");
        }
    }

    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        if (module is not null)
        {
            await module.DisposeAsync();
        }
    }
}
```

I'm going to open a follow-up issue to improve the coverage on this. That way, I can get this PR in as more a 🪲 fix 😈, and then I'll have a little more time to flesh out the module use coverage.

**Comment by guardrex** [comment]
# 🤔

Hummmmm ... I wonder if I can just place that example right in here ***right now*** and avoid a follow-up issue. Let me see .........................

**Comment by guardrex** [comment]
Ok ... I think I found a much better way to manage all of this ...

* Make one INCLUDE for just RP/MVC. Take out the Blazor parts.
* Make a pair of INCLUDES for just Blazor, pre8 and 8 or later.
* Show the full `Home`/`Index` example as a complete cut-'n-paste, fully working example.

**Comment by guardrex** [comment]
BTW ... Check `firstRender` for module loading, which my first version of that example :point_up: didn't do. After it's loaded, you're good to go ... it's cached and doesn't need to be re-imported. I've updated that example :point_up:.

**Comment by gregoryagu** [comment]
Ok, now I am tracking, and the sample is working great.  Thank you so much, that was very helpful. I did not get the concept before that you call "module..." after it was imported but it makes total sense now.

**Comment by gregoryagu** [comment]
Ok, now I am tracking and the sample is working great.  Thank you so much, that was very helpful. I did not get the concept before that you call the "module..." after it was imported but it makes total sense now.

**Comment by guardrex** [comment]
***MUCH*** better ... glad I slept on it. The versioning can be dropped by moving off of `Home`/`Index` to just plain old user components. Also, I'd like to demo collocation with a standard JS FN/script and a JS module SxS with a pair of fully-working, cut-'n-paste examples. Later, both of these can go into the Blazor sample apps, so devs won't even need to cut-'n-paste them. I'm going to sleep on this for another night and make final changes tomorrow morning.

**Comment by guardrex** [comment]
Ok ... that looks good. The examples will be moved into the sample apps later this week.

Nice job ... *whoever did this.* Of course, it wasn't *ME* 🦖. As everyone knows, ***I'm on vacation!*** 🙈😆

**Pull request merged**
