### PR TITLE
Updated instructions and code snippets

### LINKED ISSUE #23953: Samples on page are not up-to-date
Most of the samples on this page are not up-to-date with .net 6 and VS2022.  Can I contribute with corrections?

/Johan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by johandanforth**
[Internal Review:  Microsoft Account external login](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-6.0&branch=pr-en-us-23989)

[Internal Review:  Google external login](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-6.0&branch=pr-en-us-23989)

[Internal Review:  Twitter external sign-in](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-6.0&branch=pr-en-us-23989)

[Internal Review:  Facebook external login](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-6.0&branch=pr-en-us-23989)

Updated instructions and code snippets for social authentication in .net 6 (ms, facebook, google and twitter)

Fixes #23953

### CODE REVIEW

**Comment by wadepickett** [comment]
@johandanforth, Sorry to just get to this now.  I was out on vacation for weeks and it was accidently assigned to me to review while I was out.  Testing through it today.  Thanks for taking this on.

**Comment by wadepickett** [comment]
@Rick-Anderson, this pr's build was originally giving a warning over this moniker, stating an end statement does not exist, but it does exist.  Is there any reason we can't use the following by chance?
 _**::: moniker range="< aspnetcore-6.0"**_

**Comment by wadepickett** [comment]
Refreshing build by closing and opening issue.

**Comment by Rick-Anderson** [comment]
It's probably a nested moniker, which is not supported.  You need to carry these commits over to a new branch and work from git bash.

**Comment by wadepickett** [comment]
@johandanforth , I am going to need to pull your changes here into a new branch and PR.  Please do not make any more changes to your pr here.  I will loop you in when I have the edit pass done.  Thanks again for your very helpful contributions.

**Comment by wadepickett** [comment]
Closed with a branch/PR based on this one for and edit pass.  Great work @johandanforth, thanks!

**Review by wadepickett — COMMENTED** [review]
Moved the review/edit pass to a new PR carrying over all commits by the contributor.  Review complete and commits merged there.

**Comment by johandanforth** [comment]
@wadepickett not important at all, but it would be cool if my name/user was listed in the contributors list for the pages I actually contributed to. It's fun to leave some trace of ones contributions 😊

**Pull request closed without merging**
