### PR TITLE
Update hubcontext.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes https://github.com/dotnet/AspNetCore.Docs.tr-tr/issues/19
cc @guardrex @scottaddie @wadepickett  @BrennanConroy

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@JasonCard  this is a surprising over-translation

The style guide prevents using styling types in headings, maybe that rule should be abandoned.

**Comment by guardrex** [comment]
Indeed ... Given our earlier convos with u, @JasonCard, I did style a few section headings that I knew would break if I didn't. 😈

**Comment by JasonCard** [comment]
The no-loc metadata should fix this over-localization issue without having the inline code style in headings, but I don't have any concerns with using the code style in headings. FYI, I found a new bug was introduced to the no-loc feature where the terms protected by no-loc metadata are displayed like ":::no-loc(SignalR):::". We're currently following up on this bug.

**Comment by guardrex** [comment]
> displayed like ":::no-loc(SignalR):::". We're currently following up on this bug.

There was a reader remark on that this morning. I'll let that reader know that it's being looked at when I get back from being OOF.

**Pull request merged**
