### PR TITLE
Added sample Code for an issue

### LINKED ISSUE #26346: .NET 7: Add sample for Minimal API Bind the request body as a Stream or PipeReader
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/

Sample goes in 
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/bindStreamPipeReader/7.0-samples

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.MapPost("/fileUp", async (IFormFile file) =>
{
    string tempfile = Path.GetTempFileName();
    using var stream = File.OpenWrite(tempfile);
    await file.CopyToAsync(stream);
});

app.MapPost("/FilesUp", async (IFormFileCollection myFiles) =>
{
    foreach (var file in myFiles)
    {
        string tempfile = Path.GetTempFileName();
        using var stream = File.OpenWrite(tempfile);
        await file.CopyToAsync(stream);
    }
});

app.Run();
```

### LINKED ISSUE #26370: .NET 7: Code sample for Microsoft.AspNetCore.Http.TypedResults
See [Typed results for minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#typed-results-for-minimal-apis)

Put the code in aspnetcore\fundamentals\minimal-apis\misc-samples\typedResults and remove the Readme.txt file.

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
Added Sample Code for https://github.com/dotnet/AspNetCore.Docs/issues/26346 and #26370

***@Rick-Anderson EDIT:***
Fixes #26346 Fixes #26370

### CODE REVIEW

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson @RickAndMSFT

**Comment by sammychinedu2ky** [comment]
Added sample code for this issue #26370
@Rick-Anderson and @wadepickett

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  testing the  sample, it's great. Works perfect from Postman but from curl I get the following error:
c:\>curl --request POST https://localhost:54535/register --header 'Content-Type: application/json' --data-raw '{ "Name":"Samson", "Age": 23, "Country":"Nigeria" }'
registeredcurl: (6) Could not resolve host: application
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: 23,
curl: (3) URL using bad/illegal format or missing URL
curl: (3) unmatched close brace/bracket in URL position 1:
}'
 ^

And the output window shows

info: PipeStreamToBackgroundQueue[0]
      Reading the stream from the request body.
fail: BackGroundQueueService.BackGroundQueue[0]
      ''' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

BTW, Reading the stream from the request body. comes from logging I put in program.cs.

**Comment by sammychinedu2ky** [comment]
ok, would try it out again. I'm making a new pull request soon on this

**Comment by sammychinedu2ky** [comment]
you'll also have to reset the position of the stream after reading from the body. Because it was designed to be read once.

**Comment by Rick-Anderson** [comment]
This fixes it
curl --request POST https://localhost:54535/register --header "Content-Type: application/json" --data-raw "{ \"Name\":\"Samson\", \"Age\": 23, \"Country\":\"Nigeria\" }"

Can't use single quotes, must be double quotes. You must be on a macboook

**Comment by sammychinedu2ky** [comment]
ooh, Thanks would use this in the pull request. I'm on windows 😅

**Comment by sammychinedu2ky** [comment]
I used GitBash to try out the curl. Your update also worked there as well. So I just stuck to the fix you made since it also worked there.

**Comment by sammychinedu2ky** [comment]
Made a new pull request here https://github.com/dotnet/AspNetCore.Docs/pull/26437

**Comment by Rick-Anderson** [comment]
image

**Comment by Rick-Anderson** [comment]
I just added them and it seems to be working. I'll look at the code now.

**Comment by sammychinedu2ky** [comment]
Opened a pull request for this last one here https://github.com/dotnet/AspNetCore.Docs/pull/26438

**Pull request closed without merging**
