### PR TITLE
Add a migration scenario for Blazor

### LINKED ISSUE #34007: Add Blazor content to the 9.0 Migration article
### Description

There's at least one item to call out, possibly more.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-8.0&tabs=visual-studio#blazor

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/80-90.md

### Document ID

ff7b9e49-f8a8-552a-e27e-c604c858b318

### Article author

&mdash;

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #34007

cc: @Rick-Anderson ... I'll get any remaining Blazor migration items on here as they come to light in my discussion with Mackinnon.

Mackinnon ... I think outside of the ASP.NET Core-wide changes (TFM, packages, Map Static Assets routing endpoint conventions) that simplified authentication state serialization is the only migration item ... an optional feature but probably a good idea for devs to adopt. Can you think of any others?

BTW ... Although the project templates and Blazor sample apps for 9.0 adopt the latest Bootstrap version, that's a dev task in their own apps that might require other Bootstrap-specific implementation changes, not a MS product, and not on the same release cadence as .NET. Therefore, I'm not placing guidance on updating for latest Bootstrap.

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]
LGTM

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@guardrex  can we merge this and ask others to open an issue of they find a problem? Can you hook this up to WN9?

**Comment by guardrex** [comment]
Give me a little more time to get back online. My ISP said that they've sent a second tech out. I hope to be back online in a couple of hours.

**Comment by guardrex** [comment]
Sorry @Rick-Anderson ... I did just add the WN link that u requested to this PR. Both PRs had one added. We're good, and I'll double-check things after my ISP gets me back online.

Per Rick's suggestion, I'll merge this now. Other reviewers can leave addl feedback here for a separate patch PR.

**Pull request merged**
