### PR TITLE
refactor: remove always true condition

### PR DESCRIPTION
**Pull request by FrediKats**
image

Result of .ToArray() is always not null.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @FrediKats ... but let's go the **_Javier Way!&trade;_**, which I believe is more efficient. I can't explain why the `ToArray` is there really ........ **_WAIT!_** *Yes! Indeed, I do know how that got there!* ........

# 👽 

*They are among us!* :smile:

Cross-reference: https://github.com/javiercn/BlazorAuthRoles/blob/master/Client/RolesClaimsPrincipalFactory.cs#L24-L25

**Comment by Bibletoon** [comment]
Can you please explain what does Javier Way!™ mean. I really can't understand it.

**Comment by guardrex** [comment]
I was just joking that we should adopt Javer's approach to solve this problem with the example. He's one of Microsoft's top engineers, and I try to get his suggestions into the docs when he has an example for a scenario like this. 

I think to `ToArray` is slow and unnecessary. If you disagree with the update that I made,vi can ping Javier to look at this :eyes:.

**Comment by Bibletoon** [comment]
Ok, thanks for the explanation.

**Pull request merged**
