### PR TITLE
Update httpapi sample with gRPC JSON transcoding

### PR DESCRIPTION
**Pull request by ArminShoeibi**
Hello there folks.
According to this PR https://github.com/dotnet/AspNetCore.Docs/pull/25825
I updated the sample with a newer code.

### CODE REVIEW

**Comment by ArminShoeibi** [comment]
I have a question, Do we need to change the folder name to something else?
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/grpc/httpapi

**Comment by JamesNK** [comment]
Thanks. Where is this file used from?

**Comment by ArminShoeibi** [comment]
> Thanks. Where is this file used from?

Thank you for second commit.
I think we can't change the folder name because it has some references in other issues and pull requests

**Comment by Rick-Anderson** [comment]
@ArminShoeibi  I can't see where this file is used in the documents so I'm inclined to close the PR.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi I can't see where this file is used in the documents so I'm inclined to close the PR.

Okay thank you

**Pull request closed without merging**
