### PR TITLE
Add links to port tunneling in VS

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Internal review URLs, link is under the following doc's. See the TOC

* [Handle errors in ASP.NET Core web APIs](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0&branch=pr-en-us-27193)
* [OpenAPI support in minimal APIs - ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0&branch=pr-en-us-27193)
* [test node](https://review.learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-7.0&branch=pr-en-us-27193)

image

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sayedihashimi  this is already documented. Should I open an issue on the doc to update the next release?
I've linked to the doc here.

**Review by wadepickett — APPROVED** [review]
I checked the TOC and followed the links.  Looks good.

**Comment by sayedihashimi** [comment]
> @sayedihashimi this is already documented. Should I open an issue on the doc to update the next release? I've linked to the doc here.

The linked docs do cover tunneling but it also contains some Power Platform specific content. I was hoping we could have a dedicated page(s) to cover tunneling in VS outside of that. We can link to that doc for now and later create a new doc?

**Comment by Rick-Anderson** [comment]
@sayedihashimi 
> The linked docs do cover tunneling but it also contains some Power Platform specific content. I was hoping we could have a dedicated page(s) to cover tunneling in VS outside of that. We can link to that doc for now and later create a new doc?

Sure. Doesn't that belong in https://learn.microsoft.com/en-us/visualstudio/get-started/visual-studio-ide?view=vs-2022 ?
I could help write it. Or do you think it should be in this repo?

cc @ghogen

**Comment by sayedihashimi** [comment]
@Rick-Anderson yes you are correct it should be in the VS docs repo. Sorry about that.

**Pull request merged**
