### PR TITLE
Update model-binding.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Restores #26581

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ladeak did I miss any changes?

**Comment by ladeak** [comment]
Those were the lines I did not find yes.

**Review by ladeak — APPROVED** [review]

**Comment by brunolins16** [comment]
@Rick-Anderson it is showing as:

image

But should be:

image

**Comment by brunolins16** [comment]
I think you need to add a whitespace in the lines `1033` and `402`.

**Comment by Rick-Anderson** [comment]
See https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0&branch=pr-en-us-27423#collections

**Review by brunolins16 — APPROVED** [review]

**Comment by ladeak** [comment]
Thank you for the quick response.

**Comment by Rick-Anderson** [comment]
@ladeak thanks for catching this.

**Pull request merged**
