### PR TITLE
Add WebApplication under "Host" in TOC

### PR DESCRIPTION
**Pull request by halter73**
Given we document 3 hosts in the overview, I think there should be three listed in the TOC as well.

[Internal Review Link](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-7.0&branch=halter73%2Fwebapplication-host-toc&tabs=macos#host).

### CODE REVIEW

**Comment by halter73** [comment]
The internal review link isn't showing the TOC changes. Is this just an issue with the internal review, or did I do something wrong?

**Comment by guardrex** [comment]
It's another error in a different file ... `aspnetcore/fundamentals/index.md` ... bad XREF to `migration/49-to-60`.

**Comment by guardrex** [comment]
... which is bonkers because I don't see that XREF in the file.

**Comment by halter73** [comment]
Thanks. I must have accidentally hit [ctrl-x](https://vim.fandom.com/wiki/Increasing_or_decreasing_numbers) in VIM's normal mode 😆

**Review by Rick-Anderson — APPROVED** [review]
HUGE IMPROVEMENT

**Pull request merged**
