### PR TITLE
Fix variable name typo

### PR DESCRIPTION
**Pull request by mattferderer**
It appears the wrong variable was used here. `tdparam` is declared elsewhere in the code. I believe IsValid should be using `todoParam` that is mentioned in the line above it.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@mattferderer There are compile errors in that endpoint definition that need to be fixed and this isn't one of them. Do you want to fix the code or should I close this?

**Comment by Rick-Anderson** [comment]
@mattferderer  see #27396

**Comment by mattferderer** [comment]
@Rick-Anderson Cloned it, added a fix, ran & tested locally.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
Fixes #27396

@mattferderer  great work, much appreciated. cc @captainsafia

**Comment by Rick-Anderson** [comment]
@mattferderer  take a look at [`is:open is:issue label:"code help wanted"`](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22code+help+wanted%22)

**Pull request merged**
