### PR TITLE
Update working-with-forms.md

### PR DESCRIPTION
**Pull request by TanayParikh**
Fixes: https://github.com/dotnet/aspnetcore/issues/43808

image

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@TanayParikh see #27314
In many cases, the scaffolder generates this code.

**Comment by TanayParikh** [comment]
Thanks for the context @Rick-Anderson. Closing out this PR in favor of https://github.com/dotnet/AspNetCore.Docs/pull/27314.

**Comment by TanayParikh** [comment]
Hmm, actually that PR doesn't address this specific snippet. What would your suggestion be here in that case?

**Comment by Rick-Anderson** [comment]
@TanayParikh  I just mentioned that because I thought it was related. Sorry for the confusion.

**Comment by guardrex** [comment]
Looks like this will be added to the cross-linked PR for add-on work there. I'll leave it to you 🐈🐈🐈 to note to Jordon what's needed for this ... if that's what you plan to do.

**Comment by TanayParikh** [comment]
Looks like https://github.com/dotnet/AspNetCore.Docs/pull/27399 is blocked (and covers a much broader range of documentation). @guardrex can we please re-open this PR? (I don't have permissions).

**Comment by guardrex** [comment]
It won't permit me to reopen it ***from your branch*** (`TanayParikh-patch-1`) ... but it looks like it's gone now ...

https://github.com/dotnet/AspNetCore.Docs/tree/TanayParikh-patch-1

**Comment by TanayParikh** [comment]
I have brought this upon myself 😄

**Comment by TanayParikh** [comment]
https://github.com/dotnet/AspNetCore.Docs/pull/27425

**Pull request closed without merging**
