### PR TITLE
Add reference for ApiAuthorization nuget package

### LINKED ISSUE #18757: Include mention of Microsoft.AspNetCore.ApiAuthorization.IdentityServer nuget package.
Despite being titled "Authentication and authorization for SPAs" the information seems generally relevant to API authorization whether using an SPA or not. In either case, a reference to the templates' reliance on `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` for the important extension methods (`AddApiAuthorization`, `AddIdentityServerJwt`) outlined in the `Startup` class would be useful knowledge for someone not relying on templates, or attempting to integrate simple api authorization into an existing application. 

I'd propose something similar to pr #18685 for issue #18538, or something similar to the wording [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#package) for the nuget reference used in the Worker service template.  If you'd accept a pr on this, I'd be happy to contribute it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by stevebelskie**
Fixes #18757

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @stevebelskie! :rocket:

Scott, for that second one, I'm not sure which one ... I'll give u both so that you can make the right call .....

```
<xref:Microsoft.AspNetCore.Authentication.AuthenticationBuilderExtensions.AddIdentityServerJwt%2A>
```

```
<xref:Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiResourceCollection.AddIdentityServerJwt%2A>
```

**Comment by guardrex** [comment]
Oh ... rubber 🦆 says, "Look at the **_package name_** you *GooberRex!* I got it. Stand-by for the commit.

**Comment by scottaddie** [comment]
@guardrex The only thing I'd change in this PR is to remove the trailing slash in the NuGet package URL.

**Comment by guardrex** [comment]
ok ... standby ... I'll do that.

**Comment by scottaddie** [comment]
Also, fix the misspelling of "package"

**Comment by guardrex** [comment]
kk ... that got it.

Thanks again @stevebelskie!

**Pull request merged**
