### PR TITLE
Fix link to sample on GitHub

### LINKED ISSUE #17918: Wrong url
This section has wrong url:

"View or download sample code from the AspNetCore GitHub repository. Download the dotnet/AspNetCore repository ZIP file. Unzip the file. Navigate to the src/Security/samples/CustomPolicyProvider project folder."

View or download sample code is wrong.
The good one is this one:
https://github.com/dotnet/aspnetcore/tree/master/src/Security/samples/CustomPolicyProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by mjrousos**
Fixes #17918

### CODE REVIEW

**Comment by guardrex** [comment]
btw - We've had trouble in the past linking to `master`, as it isn't the current release and sometimes engineering churn leads to a dev :boom::cry:. However, there's also been trouble linking to a specific release branch, as it's difficult to get all of the links updated every release and the linked code becomes stale.

**Comment by Rick-Anderson** [comment]
master changes. Can you use https://github.com/dotnet/aspnetcore/tree/v3.1.3/src/Security/samples/CustomPolicyProvider

**Comment by mjrousos** [comment]
As long as that branch hangs around, that would work. This issue started, though, because we were linking to 2.2 and it looks like that branch must have gone away when it went out of support.

Maybe linking to a particular commit would be better since those should never change or go away ([for example](https://github.com/dotnet/aspnetcore/tree/8b7f6621695d93b2a55fb8a5b1be99c4af867ae4/src/Security/samples/CustomPolicyProvider))? Though then we won't see any updates. It's a bit of a balancing act where we trade off an up-to-date sample for a possibly missing or broken sample.

**Comment by mjrousos** [comment]
Actually, it looks like tags stick around. I'll use /tree/3.1.3

**Comment by guardrex** [comment]
I've had some luck in in some cases with a link that has a `{RELEASE BRANCH}` segment. However, I do have to tell the reader to go the engineering repo and find the release in the branch selector that they want. The idea is that if the rest of the link doesn't change, it will be stable for a long time.

*Welcome to your Koyabahi Maru training!* :smile:

**Comment by Rick-Anderson** [comment]
I've had good luck with tags

**Pull request merged**
