### PR TITLE
remove ref, not needed

### LINKED ISSUE #20153: misuse of ref keyword in sample code
In section "Pipelines", the sample code 
`private static void AddStringToList(ref List<string> results, in ReadOnlySequence<byte> readOnlySequence)`
where the keyword `ref` for method parameter `List<string> results` is not needed, and misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b15fd3-39b5-3ad9-8c4e-b8160360dee9
* Version Independent ID: c33981af-93ce-d4be-a265-5d4696666c7a
* Content: [Request and Response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/request-response.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/request-response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #20153

Tested and it works.
@pinkli please review

### CODE REVIEW

**Comment by pinkli** [comment]
Nice work!

**Review by scottaddie — COMMENTED** [review]
The code changes look good. The TestPipes.JPG image appears to be unused. I recommend deleting that before merging.

**Comment by Rick-Anderson** [comment]
@scottaddie  the image is helpful for testing the app. I'll add a comment to doc saying that.

**Comment by scottaddie** [comment]
@Rick-Anderson The image should also be relocated to the *static* directory.

**Review by scottaddie — APPROVED** [review]

**Pull request merged**
