### PR TITLE
Update min-api-filters.md

### PR DESCRIPTION
**Pull request by WeihanLi**
Update the name

### CODE REVIEW

**Comment by wadepickett** [comment]
Just a note on this to add. 
History on this name change:
Issue: https://github.com/dotnet/aspnetcore/issues/42589

**Comment by Rick-Anderson** [comment]
@WeihanLi see
## Public review  of the doc build:
- download the [HTML files](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
- unzip
- view HTML file in a browser.
- For links outside the doc, remove the `review.` from URL.
' Still one `RouteHandlerInvocationContext` in the .MD file and all the code is using the same names. For example, https://github.com/WeihanLi/AspNetCore.Docs/blob/patch-1/aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/Filters/Program.cs#L47

Can you update the code too?

**Comment by Rick-Anderson** [comment]
@WeihanLi  it looks like you created the PR from the browser. I can take over this PR if you like, you'll still get credit once it merges.

**Comment by Rick-Anderson** [comment]
@WeihanLi  thanks for the start. I moved your commits to #26698

**Comment by WeihanLi** [comment]
Thanks @Rick-Anderson

**Pull request closed without merging**
