### PR TITLE
HttpContext in Razor Page View instead of Context

### LINKED ISSUE #22805: Context does not work, use HttpContext in RazorView
`Context` does not work in my case (Razor Page .Net 6 preview 6).
Rather, I need to use `HttpContext` in the View, just like in the code behind.

**Got Error "Context does not exist"**
```
@{
    var username = Context.User.Identity.Name;
}
```
**Works**
```
@{
    var host = HttpContext.Request.Host;
}
```
```
 <p>@HttpContext.Request.Headers["Host"]</p>
 <p>@host</p>
```
I did not check on lower versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Ponant**
Fixes #22805

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Ponant but the section is [Use HttpContext from a Razor view](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#use-httpcontext-from-a-razor-view)

Razor views expose the `HttpContext` directly via a [RazorPage.Context](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorpage.context#Microsoft_AspNetCore_Mvc_Razor_RazorPage_Context) property on the view. The following example retrieves the current username in an intranet app using Windows Authentication:

@serpent5  what's going on here?

**Comment by serpent5** [comment]
@Rick-Anderson I think the issue here is because of some confusion between the [`RazorPage`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorpage?) class, which _represents properties and methods that are needed in order to render **a view that uses Razor syntax**_, and a Razor Pages Page, which is really a [`PageModel`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razorpages.pagemodel).

In the docs, it's the "Use HttpContext from Razor Pages" section that applies, because @Ponant is working with a Razor Pages Page. The "Use HttpContext from a Razor view" section applies to Razor Views that are backed by controllers, in the traditional MVC approach. It's unfortunate that the class used for MVC Views is named `RazorPage`, I think.

**Comment by Ponant** [comment]
"Use HttpContext from Razor Pages" shows only what to do on the code behind. Perhaps an additional block for the corresponding view would fix this confusion. @Rick-Anderson , indeed my apologies I forgot MVC! I mean in RP view it really is HttpContext, just like in the code behind. @serpent5 is right. I can fix this tomorrow if you wish as it is late here, except that I do not know how to properly call such kind of RP views??

**Comment by Rick-Anderson** [comment]
@Ponant  thanks for bringing this to our attention. No hurry, it's been this way for years.

@serpent5  and I can clean up any wording.

**Comment by Rick-Anderson** [comment]
@Ponant  let me know if you have time to fix this.

**Comment by Ponant** [comment]
@Rick-Anderson , I made it a few days ago. It was waiting for you to review.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson , I made it a few days ago. It was waiting for you to review.

Sorry, I missed that. @serpent5 please review

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
