### PR TITLE
Add a note about output formatter buffering

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by zvolkov** [comment]
This is nice, but does not mention change of behavior as far as response completion. If this were me, I would add a paragraph saying "When buffering is enabled, Content-Length header is set by the output formatter even if it wasn't set by your code. When this happens, the client will consider the request completed as soon as all bytes are received and before your middleware finishes e.g. saving the session state. For more details see the following GitHub issue:"

**Comment by pranavkm** [comment]
> saving the session state, because the client may now send the next request before the previous request is done updating the state.

This seems problematic and we wouldn't recommend doing this to our users. I'm happy to document the Content-Length since it's something users have asked for.

**Comment by zvolkov** [comment]
That piece was just an example of the problem, not a recommendation.

**Comment by Rick-Anderson** [comment]
Branched to #18853, work on that until it merges into this branch.

**Comment by Rick-Anderson** [comment]
@pranavkm  can I S&M (squash and merge)?

**Comment by pranavkm** [comment]
:shipit:

**Pull request merged**
