### PR TITLE
Update OIDC lib remark to MSAL

### LINKED ISSUE #30418: Update for MSAL
Some passages escaped updates for MSAL/PKCE.

**UPDATE**: Looks like there's just one offensive line here, which refers to the OIDC Client Library. I'll fix that now, and we can take a look at the whole topic after RC2 releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c572618c-8b98-95af-6a75-1f8e413071db
* Version Independent ID: 8670b314-460d-3194-c53b-9a44f39c6b2a
* Content: [Secure ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #30418

It looks like there's one offensive line 😈 that slipped by the MSAL updates. That will be fixed on this PR.

I'm not aware of any problems with the OIDC process remarks further down the article.

This article ... all of them, actually ... will be updated and reviewed in the RC2 period sometime around the end of October/start of November. We'll be adding the BWA guidance in that period and adjusting for any framework changes made for WASM apps (and WASM components of BWA apps).

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce8f71d73ddc5cd24d63f4a97065b06bc9eb613b/aspnetcore/blazor/security/webassembly/index.md) | [Secure ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?branch=pr-en-us-30421) |
| [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce8f71d73ddc5cd24d63f4a97065b06bc9eb613b/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md) | [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?branch=pr-en-us-30421) |

### CODE REVIEW

**Comment by guardrex** [comment]
Be more specific ...

> Auth provider specific page

AFAICT, all of the content after this PR goes in say that only PKCE auth code is supported. ***BUT***, that's what I'm asking ... ***exactly*** what article/section/paragraph/sentence are you saying is a problem? ... keeping in mind that I'm referring to the Blazor docs. We don't control docs outside of the Blazor docs.

> you don't need msal to make code flow work and that it works with the Auth provider standalone too.

Well, you do tho if you're using the MSAL NuGet package maintained by the ASP.NET Core team (and thus MSAL script) OOB. That's all that we support. That's all that Javier wants to tell devs. I think this subject came up years ago, and he said something like we shouldn't be mentioning to devs how to do anything different than what we describe/show because it isn't safe (in the product unit's opinion) and isn't supported by management ***here*** ... our direct management.

MSAL does support such things, they don't want to even mention it. You can go to the Identity Platform/MSAL docs and read all about all of the flows and how to implement them.

**Comment by JohnGalt1717** [comment]
This is the problem: Devs don't want to be using MSAL. It's lock in.

They want to be using what's listed under the standalone Authentication page using Authentication Provider.  That page needs to state explicitly that this is using OpenIdConnect Authorization Code Flow and does not support implicit code flow.

And then the introduction page should make it clear that MSAL is an alternative approach and not required to get OpenIdConnect Authorization Code Flow.

**Comment by guardrex** [comment]
> standalone Authentication page using Authentication Provider. That page needs to state explicitly that this is using OpenIdConnect Authorization Code Flow and does not support implicit code flow.

Ok, I see what you mean now. Yes, I'll work on that for the next commit.

> MSAL is an alternative approach and not required to get OpenIdConnect Authorization Code Flow.

That's true in the general sense. The article's remarks are focused on our package that uses MSAL, so it isn't an alternative in that sense. Let me see if I can add a carefully-worded remark about *not using the package*.

**Comment by damienbod** [comment]
@guardrex tokens in the browser is no longer recommended, maybe this should be updated as well.

Greetings Damien

**Comment by guardrex** [comment]
Sure ... let me hear from Javier on that, too.

... and I wasn't focused on token-related remarks this morning. I'll need to take another look on Thursday morning. I'm OOF for most of the rest of the day.

**Comment by guardrex** [comment]
I'm not going to hold up fixing the bug for mere review of the other line updates. Given that it's Friday, this won't be seen today. I'll make a note to ping the product unit on Monday morning to take a look. For now, we'll go with this.

@damienbod ... I'll ask about the token language, too, and we'll work on that after I hear back.

**Pull request merged**
