### PR TITLE
Update Blazor WASM integrity PS script

### LINKED ISSUE #24260: Update Blazor WASM integrity PS script
https://github.com/dotnet/aspnetcore/issues/38668

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #24260 

Tanay and Javier, the engineering issue is at https://github.com/dotnet/aspnetcore/issues/38668.

Nevermind on my earlier bug report ... I inadvertently tried the script with a running Blazor Server app.

> No error founds. Application is consistent.

I fix the sentence "No error founds." on the next update.

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]
Thanks @guardrex. Looks good to me. 

@javiercn could you please review the `ps1` change when you return?

**Comment by TanayParikh** [comment]
@guardrex can we actually hold off on merging.

**Comment by guardrex** [comment]
Yes.

btw - I'm testing now with a WASM app. I'll report back.

**Comment by guardrex** [comment]
I've updated the PR with the sentence changed to: "No errors found." I've updated the hashes for the script.

I ran a test with a WASM app hosted by IIS locally. I received the following, but that might be correct regarding the cert being expired ...

```
Invoke-WebRequest: C:\Users\XXXXX\Desktop\integrity.ps1:126
Line |
 126 |    Invoke-WebRequest $url -Headers @{'Accept-Encoding' = 'identity' }  …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The remote certificate is invalid because of errors in the certificate chain: NotTimeValid,
     | UntrustedRoot

No error founds. Application is consistent.
```

**Comment by TanayParikh** [comment]
> No error founds. Application is consistent.

What happens if you edit one of the server dlls? Does it report an error?

**Comment by guardrex** [comment]
I'm not sure which one tho ... don't I need to corrupt one that doesn't break the app and stop it from running? Which one should I break?

**Comment by TanayParikh** [comment]
Thanks for checking, LGTM, :shipit: !

**Review by TanayParikh — APPROVED** [review]

**Pull request merged**
