### PR TITLE
Update .repoman.yml

### PR DESCRIPTION
**Pull request by adegeo**
Fixed the metadata field name. Feel free to squash-merge

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  @adegeo  should we try reverting this and see if merge to live works?

**Comment by Rick-Anderson** [comment]
That was it
image

**Comment by adegeo** [comment]
@Rick-Anderson why would that break it? How do we update the repoman config?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson why would that break it? How do we update the repoman config?

I have no idea, but it did. Reverting fixed the build. You're welcome to try again:

1. Merge to live.
2. PR this, merge,
3. Merge to live again. If it breaks, revert.

**Pull request merged**
