### PR TITLE
First MVC Series: Versioning

### LINKED ISSUE #28234: Move MVC Getting Started Series to New Versioning Architecture
Move this 10-tutorial series to new versioning architecture.

Background: When updating this for the MacOS/.NET 7 version for #27383 I decided it would be best to take this on as a separate task for the whole series rather than trying to tackle that at the same time since it is my first time doing so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 61250](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61250)

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #28234 

No other work here, just moving this series to the cool new versioning by file system.

[Internal Review - Getting started - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Adding controller - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Adding View - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Adding Model- Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Working with SQL- Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Controller methods views - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-7.0&branch=pr-en-us-28504)
[Internal Review - Search- Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-7.0&branch=pr-en-us-28504)
[Internal Review - New field- Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Validation 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-7.0&branch=pr-en-us-28504)

Moving 10 tutorial First MVC series to new versioning architecture.

- 7.0 tutorial had previous versions removed.
- Each tutorial has an includes folder containing versions previous to 7.0. 
- .png paths changed to absolute paths.
- Step-by-step links changed to absolute paths.

### CODE REVIEW

**Comment by wadepickett** [comment]
Checks complete, build not running.  Close and reopen to restart build

**Comment by wadepickett** [comment]
closing and reopening to force new build.

**Comment by wadepickett** [comment]
@tdykstra, I moved this series to the new include file versioning system we have.  It all shows up fine, but there is one problem.
The primary topic for each has the metadata set for monikerRange: '>= aspnetcore-3.1'
But only these two tutorials redirect to the latest version if you select to view a version  below 3.1
[Internal Review - Adding controller - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)
[Internal Review - Adding View - Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)

The rest ignore that moniker range restriction for some reason in the metadata. such as this one:
[Internal Review - Working with SQL- Vers 3.1 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-7.0&branch=pr-en-us-28504&tabs=visual-studio)

Comparing them all, I don't see what making the others ignore monikerRange: '>= aspnetcore-3.1'.   Any ideas?

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
