### PR TITLE
[BULK] - DocuTune - Remove expired ms.custom values

### PR DESCRIPTION
**Pull request by alexbuckgit**
Remove expired ms.custom values

CorrelationId: be4e6f69-4173-4365-a9c5-e7e7557a20cb
PointOfContact: @kcpitt

#docutune

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/data/ef-mvc/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/data/ef-mvc/migrations.md) | [Tutorial: Part 5, apply migrations to the Contoso University sample](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?branch=pr-en-us-31656) |
| [aspnetcore/fundamentals/choose-aspnet-framework.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/fundamentals/choose-aspnet-framework.md) | [Choose between ASP.NET 4.x and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?branch=pr-en-us-31656) |
| [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/fundamentals/host/platform-specific-configuration.md) | [Use hosting startup assemblies in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?branch=pr-en-us-31656) |
| [aspnetcore/razor-pages/sdk.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/razor-pages/sdk.md) | [aspnetcore/razor-pages/sdk](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?branch=pr-en-us-31656) |
| [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/razor-pages/ui-class.md) | [Create reusable UI using the Razor class library project in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/2fa.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/2fa.md) | [Two-factor authentication with SMS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/add-user-data.md) | [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/azure-active-directory/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/azure-active-directory/index.md) | [aspnetcore/security/authentication/azure-active-directory/index](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/index?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/jwt-authn.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/jwt-authn.md) | [Manage JSON Web Tokens in development with dotnet user-jwts](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/social/facebook-logins.md) | [Facebook external login setup in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/social/google-logins.md) | [Google external login setup in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?branch=pr-en-us-31656) |
| [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authentication/windowsauth.md) | [Configure Windows Authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?branch=pr-en-us-31656) |
| [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/authorization/secure-data.md) | [Create an ASP.NET Core web app with user data protected by authorization](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?branch=pr-en-us-31656) |
| [aspnetcore/security/data-protection/extensibility/key-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/data-protection/extensibility/key-management.md) | [aspnetcore/security/data-protection/extensibility/key-management](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/extensibility/key-management?branch=pr-en-us-31656) |
| [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/security/key-vault-configuration.md) | [Azure Key Vault configuration provider in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mongo-app.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mvc-app/adding-controller.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mvc-app/adding-model.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mvc-app/adding-view.md) | [Part 3, add a view to an ASP.NET Core MVC app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mvc-app/start-mvc.md) | [Get started with ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?branch=pr-en-us-31656) |
| [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/tutorials/first-mvc-app/working-with-sql.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?branch=pr-en-us-31656) |

</details>

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@alexbuckgit  let me know when I can merge.

**Comment by Rick-Anderson** [comment]
@alexbuckgit  hopefully we don't have too many custom meta-data that needs to be updated. I hate polluting the history.

**Comment by Rick-Anderson** [comment]
@alexbuckgit  @kcpitt let me know when this can be publishd.  @alexbuckgit  marked it draft.

**Pull request merged**
