### PR TITLE
Apply 'no-loc' entries across the doc set

### LINKED ISSUE #18076: Terms that should not be localized
This article contains product name "Razor" that should not be localized and some of those are being over-localized by Machine Translation. It would be great if those terms can be blocked from localization by using [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #18076

* I was able to get away with a simple RegEx-based find-'n-replace.
* There were existing entries for "Identity" and "Let's Encrypt," so I preserved those in the new list.
* I hope 🙏 that "Identity" in quotes will only address the capitalized word.
* From this point forward, a plain old find-'n-replace will be a snap to maintain the list.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Really nice work!

**Comment by guardrex** [comment]
Luckily, it only took a couple of minutes. The RegEx find-'n-replace is powerful ... *if one can figure out the crazy RegEx syntax!* 😵😄

**Comment by wadepickett** [comment]
@guardrex , great you even caught oddities like the UID reference.  Well done.

**Comment by guardrex** [comment]
blood

@scottaddie I'm going to go ahead and get this in ... It's creating 💥 *merge conflicts* 💥 all over the place! :smile: Message me if I need to make changes.

**Comment by wadepickett** [comment]
@JasonCard, this larger fix across the en-us doc set was originally triggered by this specific request for a correction tot he Polish version:  [Loc Issue: 18076](https://github.com/dotnet/AspNetCore.Docs/issues/18076#event-3300818190).   We have some product unit PM's and customers that would like to be notified when that Polish version is updated.  What would be the timeline for this fix to appear in the localized version of the docs, specifically for that document in Polish?   Thanks again for your guidance.

**Comment by JasonCard** [comment]
@wadepickett Once the changes are merged to the live branch, our automation platform should detect the changes and machine translated content should be updated and published within 1-2 days.

**Comment by wadepickett** [comment]
Cool!  Thanks Jason!

**Pull request merged**
