### PR TITLE
Add roles/groups coverage to the BWA+OIDC article

### LINKED ISSUE #32512: [Suggestion] Add some instructions for getting role claims.
### Description

I ran into a use case where I wanted to not only validate that a user can sign in, but that they are in a particular role before viewing a page/component.

I had made a ticket here https://github.com/dotnet/aspnetcore/issues/55314 and I thought it might be useful for others to have this documented. It could be helpful for other providers as well if they have something like multiple policies you'd like to map or another claim type with multiple values. 

I am using Entra as my oidc provider, so the prerequisites for this are having an entra app and app registration in order to assign users/groups/apps to role(s).

A user can be assigned to multiple roles so I needed to adjust the UserInfo Class at https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/UserInfo.cs to the following 

```cs
using System.Security.Claims;

namespace BlazorWebAppOidc.Client;

// Add properties to this class and update the server and client AuthenticationStateProviders
// to expose more information about the authenticated user to the client.
public sealed class UserInfo
{
    public required string UserId { get; init; }
    public required string Name { get; init; }
    public required string[] Roles { get; init; }

    public const string UserIdClaimType = "sub";
    public const string NameClaimType = "name";
    private const string RoleClaimType = "roles";

    public static UserInfo FromClaimsPrincipal(ClaimsPrincipal principal) =>
        new()
        {
            UserId = GetRequiredClaim(principal, UserIdClaimType),
            Name = GetRequiredClaim(principal, NameClaimType),
            Roles = principal.FindAll(RoleClaimType).Select(c => c.Value).ToArray(),
        };

    public ClaimsPrincipal ToClaimsPrincipal() =>
        new(new ClaimsIdentity(
            Roles.Select(role => new Claim(RoleClaimType, role))
                .Concat(new[]
                {
                    new Claim(CustomClaimType, UserId),
                    new Claim(NameClaimType, Name)
                }),
            authenticationType: nameof(UserInfo),
            nameType: NameClaimType,
            roleType: RoleClaimType));

    private static string GetRequiredClaim(ClaimsPrincipal principal, string claimType) =>
        principal.FindFirst(claimType)?.Value ?? throw new InvalidOperationException($"Could not find required '{claimType}' claim.");
}
```

Also the Entra string claim for the role claim is actually "roles" so you need to change the string value in https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
This portion was elusive for me and seems silly now, but I imagine different providers can have different naming. When I was using just microsoft identity nuget packages the roles actually came through as `appRole` 🤷‍♀️

```cs
oidcOptions.TokenValidationParameters.RoleClaimType = "roles";
```

Finally, in your UserClaims page component you can add the following in order to test out your roles

```cs
@attribute [Authorize(Roles = "Role1")]

<PageTitle>User Claims</PageTitle>
<AuthorizeView Roles="Role2">
    <Authorized>
        You have Role2
    </Authorized>
    <NotAuthorized>
        You do not have Role2
    </NotAuthorized>
</AuthorizeView>
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=with-bff-pattern#configuration-1

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #32512

Thanks @travaille-dev! 🎸 ...

* I'm going with two sections for this, one focused on roles for general OIDC providers and one for ME-ID.
* The ME-ID section includes guidance for Azure security/distribution groups (`groups` claims) and ME-ID built-in administrator roles (`wids` claims), which devs can then base authz policies on. A lot of devs want to know how to use these Azure/ME-ID features, but it can be difficult to track down the guidance in the Azure/ME-ID docs. *This should make it a snap!* ✨
* I also made an update to the sample apps to assign `roles` instead of `role` to the role claim type. I call out in the article that it's done for ME-ID and to consult their IdP docs on it.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/7dfe325a696379a84575241d2c0f217627791ebd/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-33201) |
| [aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/7dfe325a696379a84575241d2c0f217627791ebd/aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md) | [ASP.NET Core Blazor WebAssembly with Microsoft Entra ID groups and roles](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/microsoft-entra-id-groups-and-roles?branch=pr-en-us-33201) |

### CODE REVIEW

**Comment by travaille-dev** [comment]
👩‍🍳 👌  I really appreciate the care you put into entra groups and roles doc.

**Comment by guardrex** [comment]
Sure thing, @travaille-dev.

I'm a bit thrown off by one aspect of this tho: It doesn't seem to matter what the role claim type is set to in options ...

```csharp
oidcOptions.TokenValidationParameters.RoleClaimType = "...";
```

For ME-ID/OIDC, it doesn't have to be "`roles`" here. It can be set to anything AFAICT. Same deal with the name claim type. They seem to be ignored, and `IsInRole` checks seem to work, too, regardless of the config. I'm debating if I should try to contact Halter about it.

**Comment by travaille-dev** [comment]
in my base project
```cs
builder.Services.AddAuthentication(MS_OIDC_SCHEME)
    .AddOpenIdConnect(MS_OIDC_SCHEME, oidcOptions =>
    {
        oidcOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        oidcOptions.Authority = builder.Configuration.GetValue<string>("Authority");
        oidcOptions.ClientId = builder.Configuration.GetValue<string>("ClientId");
        oidcOptions.ClientSecret = builder.Configuration.GetValue<string>("ClientSecret");
        oidcOptions.Scope.Add(builder.Configuration.GetValue<string>("ApiScope") 
                              ?? throw new InvalidOperationException("You need to configure ApiScope in secrets"));
        oidcOptions.ResponseType = OpenIdConnectResponseType.Code;
        oidcOptions.MapInboundClaims = false;
        oidcOptions.TokenValidationParameters.NameClaimType = JwtRegisteredClaimNames.Name;
        oidcOptions.TokenValidationParameters.RoleClaimType = "roles";
    })
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme);
```

in my client project
```cs
using System.Security.Claims;

namespace blahblah.Client;

// Add properties to this class and update the server and client AuthenticationStateProviders
// to expose more information about the authenticated user to the client.
public sealed class UserInfo
{
    public required string Email { get; init; }
    public required string Name { get; init; }

    public required string[] Roles { get; init; }
    
    public required string UserId { get; init; }

    private const string UserIdClaimType = "preferred_username";
    public const string NameClaimType = "name";
    private const string RoleClaimType = "roles";
    private const string CustomClaimType = "userid";

    public static UserInfo FromClaimsPrincipal(ClaimsPrincipal principal) =>
        new()
        {
            Email = GetRequiredClaim(principal, UserIdClaimType),
            Name = GetRequiredClaim(principal, NameClaimType),
            Roles = principal.FindAll(RoleClaimType).Select(c => c.Value).ToArray(),
            UserId = (GetRequiredClaim(principal, UserIdClaimType).Split("@")[0])
        };

    public ClaimsPrincipal ToClaimsPrincipal() =>
        new(new ClaimsIdentity(
            Roles.Select(role => new Claim(RoleClaimType, role))
                .Concat(new[]
                {
                    new Claim(UserIdClaimType, Email),
                    new Claim(NameClaimType, Name),
                    new Claim(CustomClaimType, UserId)
                }),
            authenticationType: nameof(UserInfo),
            nameType: NameClaimType,
            roleType: RoleClaimType));

    private static string GetRequiredClaim(ClaimsPrincipal principal, string claimType) =>
        principal.FindFirst(claimType)?.Value ??
        throw new InvalidOperationException($"Could not find required '{claimType}' claim.");
}
```

If I change both to "role" ideally it wouldn't make a difference what I name the role claim (to your point)

It could just be local development blues, but I've tried it in incognito, clearing cookies/cache, and trying different browsers, but alas this is what my user-claims page shows from ssr,

Screenshot 2024-08-01 at 1 23 21 PM

and this is after the userinfo process gets done and loads the client version

Screenshot 2024-08-01 at 1 30 16 PM

And here's my user-claims page for good measure
```cs
@page "/user-claims"
@using System.Security.Claims
@using Microsoft.AspNetCore.Authorization

<PageTitle>User Claims</PageTitle>
<AuthorizeView Roles="Test">
    <Authorized>
        Neat
    </Authorized>
    <NotAuthorized>
        Not Neat
    </NotAuthorized>
</AuthorizeView>

<h1>User Claims</h1>

@if (_claims.Any())
{
    <ul>
        @foreach (var claim in _claims)
        {
            <li><b>@claim.Type:</b> @claim.Value</li>
        }
    </ul>
}

@code {
    private IEnumerable<Claim> _claims = Enumerable.Empty<Claim>();

    [CascadingParameter]
    private Task<AuthenticationState>? AuthState { get; set; }

    protected override async Task OnInitializedAsync()
    {
        if (AuthState == null)
        {
            return;
        }

        var authState = await AuthState;
        _claims = authState.User.Claims;
    }
}
```

**Comment by guardrex** [comment]
@travaille-dev ... 

> If I change both to "role" ideally it wouldn't make a difference what I name the role claim (to your point)

It doesn't matter what I set `oidcOptions.TokenValidationParameters.RoleClaimType` to. Here, only `RoleClaimType` in `UserInfo` has to be `roles`, which makes sense because that's what's working with the claims after authentication. I'm just saying that `RoleClaimType` doesn't seem to affect anything on the OIDC side (with Entra ID anyway). It looks like the claim comes down `roles` and stays `roles` regardless of what that role claim type is set to, but IDK if it affects something else.

> what my user-claims page shows from ssr

I think you're referring to the "not neat" part of that, but I can't repro that behavior here. Using your exact `UserInfo` class and the following `UserClaims` component, I get functional `IsInRole` and `AuthorizeView` behaviors for both interactive SSR (before switchover to the client) and CSR after the switchover. I'll show everything in a moment.

I ask Halter to review this PR before I merge it and ask a few questions that might lead to additional remarks.

Here's what I used along with your `UserInfo` class. I set up two `appRoles` in the app's manifest, `Admin` and `Developer` and assigned them both to my test user, Chris Green. He also has a security group (a `groups` claim) and is a Billing Administrator in Azure (a `wids` claim). Entra ID always sends down an extra `groups` (I don't know yet what it means) and an extra `wids` claim (that's [explained here](https://learn.microsoft.com/en-us/answers/questions/678108/what-b79fbf4d-3ef9-4689-8143-76b194e85509-in-wids)).

`UserClaims.razor` ...

```razor
@page "/user-claims"
@using System.Security.Claims
@using Microsoft.AspNetCore.Authorization
@attribute [Authorize]

<PageTitle>User Claims</PageTitle>

<h1>User Claims</h1>

@if (claims is not null && claims.Any())
{
    <ul>
        @foreach (var claim in claims)
        {
            <li><b>@claim.Type:</b> @claim.Value</li>
        }
    </ul>
}

<p>
    User is in role 'Admin': @isAdmin
</p>

<p>
    User is in role 'Developer': @isDev
</p>

<AuthorizeView Roles="Admin">
    <Authorized>
        <p>User is an Admin in AuthorizeView</p>
    </Authorized>
    <NotAuthorized>
        <p>User is NOT an Admin in AuthorizeView</p>
    </NotAuthorized>
</AuthorizeView>

<AuthorizeView Roles="Developer">
    <Authorized>
        <p>User is an Developer in AuthorizeView</p>
    </Authorized>
    <NotAuthorized>
        <p>User is NOT an Developer in AuthorizeView</p>
    </NotAuthorized>
</AuthorizeView>

@code {
    private IEnumerable<Claim>? claims;
    private bool isAdmin;
    private bool isDev;

    [CascadingParameter]
    private Task<AuthenticationState>? AuthState { get; set; }

    protected override async Task OnInitializedAsync()
    {
        if (AuthState == null)
        {
            return;
        }

        var authState = await AuthState;
        claims = authState.User.Claims;

        var user = authState?.User;

        isAdmin = user?.IsInRole("Admin") ?? false;
        isDev = user?.IsInRole("Developer") ?? false;
    }
}
```

SSR ...

Screenshot 2024-08-02 073908

CSR ...

image

**Comment by travaille-dev** [comment]
> @travaille-dev ...
> 
> > If I change both to "role" ideally it wouldn't make a difference what I name the role claim (to your point)
> 
> It doesn't matter what I set `oidcOptions.TokenValidationParameters.RoleClaimType` to. Here, only `RoleClaimType` in `UserInfo` has to be `roles`, which makes sense because that's what's working with the claims after authentication. I'm just saying that `RoleClaimType` doesn't seem to affect anything on the OIDC side (with Entra ID anyway). It looks like the claim comes down `roles` and stays `roles` regardless of what that role claim type is set to, but IDK if it affects something else.
> 
I seem to have found my failure. I figured that `oidcOptions.TokenValidationParameters.RoleClaimType` and `RoleClaimType` in `UserInfo` both needed to be the same. 

For me, if I update `oidcOptions.TokenValidationParameters.RoleClaimType` to `role` and keep `RoleClaimType` in `UserInfo` as `roles` then SSR will evaluate `user?.IsInRole("Test") ?? false;` to false, but CSR evaluates it to true.

so if I change the `[Authorize]` in UserClaims to `@attribute [Authorize(Roles = "Test")]` I get redirected to the access denied page.

**Comment by guardrex** [comment]
I see. I can't explain the difference. What I'll probably do is publish this in its present form, which doesn't remark on having `RoleClaimType` set any particular way, allowing developers to assume that they should be the same value. I'll make a note to myself to discuss this with Halter later this year, when he'll probably have more time in his schedule.

I think I will wait until Monday to wrap this up. I want to look it over one more time before publishing it.

**Pull request merged**
