### PR TITLE
Update Blazor WASM auth nav guidance

### LINKED ISSUE #27567: Update Blazor WASM auth nav breaking change content update
* https://github.com/dotnet/aspnetcore/issues/44973
* https://github.com/aspnet/Announcements/issues/497
* https://github.com/dotnet/AspNetCore.Docs/pull/27562

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #27567

### CODE REVIEW

**Comment by guardrex** [comment]
@javiercn ... The docs were updated for using `history.state` over ?`returnUrl=` and obsoleting `SignOutSessionStateManager`, ***BUT*** I didn't get the *Migration* topic updated. I didn't see your announcement until after it posted.

If you need to cross-link to the new migration guidance, it will appear at ...

```
https://learn.microsoft.com/aspnet/core/migration/60-70#blazor-webassembly-authentication-uses-history-state-for-redirects
```

It will be live ⚡ in a few minutes.

**Comment by javiercn** [comment]
@guardrex how can I best review the changes?

Can you point me to the exact doc pages? (doing so inside the PR is a bit hard).

**Comment by guardrex** [comment]
Yeah ... stand-by for the live update. I got pulled off on something else for a sec 😈.

I'll ping back here when it goes live.

**Comment by guardrex** [comment]
@javiercn ... It's up now ...

https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio#blazor-webassembly-authentication-uses-history-state-for-redirects

I'll patch based on any feedback.

If it looks like I'm going awfully 🏃😨 ... ***I AM!*** 😆 I still have quite a bit of work to do to get everything done post release.

**Pull request merged**
