### PR TITLE
Merge to live - 6/18

### PR DESCRIPTION
**Pull request by guardrex**

### CODE REVIEW

**Comment by guardrex** [comment]
@adegeo ... Is this a problem, or should I just go ahead and merge this to live?

https://github.com/dotnet/AspNetCore.Docs/pull/22568/checks?check_run_id=2862295358

**Comment by guardrex** [comment]
I'll close and re-open just to make sure it's a stable failure.

**Comment by guardrex** [comment]
Yeah ... ooops ... @adegeo ... looks like your PR broke **_the Internet!_** :smile:

**Comment by Rick-Anderson** [comment]
In #22567 right?

**Comment by Rick-Anderson** [comment]
That was it
image

**Comment by Rick-Anderson** [comment]
> @adegeo ... Is this a problem, or should I just go ahead and merge this to live?
> 
> https://github.com/dotnet/AspNetCore.Docs/pull/22568/checks?check_run_id=2862295358
> 
> > Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/dotnet/samples/main/.github/actions/status-checker'. Did you forget to run actions/checkout before running your local action?

That seemed to be the problem. Maybe because I just backed off on actions and now only allow local actions.

**Pull request merged**
