### PR TITLE
Add 'How to open an issue' to the README

### LINKED ISSUE #33946: Add 'How to open an issue' to the README
Add a section to the README per https://github.com/dotnet/AspNetCore.Docs/issues/33940#issuecomment-2441573203.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #33946

Thanks @bukowa! 🚀 

### ❓ 

Rick, Tom, Wade ... It might also help to add a section to the *Fundamenals* > *Overview*. I've been running for many years with one for Blazor that might be helping me a little bit ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-8.0#support-requests

If you'd like me to add a similar section tailored generally for the whole repo, let me know. 👂 I can add it to this PR.

### ~❓~ ***Resolved*** 

~Also... ***Rick*** ... this SO link is lacking your "area" of SO tag thing that you place on your SO links that you give to folks. I couldn't find a quick example of that tag ... what tag/link do you give them ... is it this one ...~

```
https://stackoverflow.com/questions/tagged/asp.net-core
```

~Whatever it is, I'll update the SO link on this PR.~

### ❓ 

I'm seeking to add a `blank-issue.md` template. Is that the right naming? I'm not sure if it's going to load into a blank issue ... it's a guess for sure based on the names of the other templates.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [.github/ISSUE_TEMPLATE/blank-issue.md](https://github.com/dotnet/AspNetCore.Docs/blob/b5a975f9d83c3b5adc822dde562e1b4b80ef27b4/.github/ISSUE_TEMPLATE/blank-issue.md) | [.github/ISSUE_TEMPLATE/blank-issue](https://review.learn.microsoft.com/en-us/aspnet/core/.github/ISSUE_TEMPLATE/blank-issue?branch=pr-en-us-33947) |

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
LGTM

**Review by wadepickett — APPROVED** [review]
Looks great.  Thanks!

**Comment by guardrex** [comment]
Idk if Rick looked. He can modify it if needed.

The only open question is if the `blank-issue.md` is the by-convention correct naming to load that into a completely blank issue, which I'll check on and report back after I merge this.

Let's go ahead  :shipit:.

**Comment by guardrex** [comment]
# 🐀🍔 ***Roasted Rat Burgers!*** 🐀🍔 

It didn't work .......

image

I'll just delete that file. I don't know how to name it to get it to load properly.

**Pull request merged**
