### PR TITLE
Adjust the syntax for Update package references

### PR DESCRIPTION
**Pull request by ichan-akira**
Fixing typo in code sample for Update package references.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24446) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24446) before we can accept your contribution.<br/><br/>:x: ichan-akira [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24446)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=24446) it.</sub>

**Review by guardrex — APPROVED** [review]
Thanks @ichan-akira! :rocket: ... I added a few nit updates.

**Comment by guardrex** [comment]
@ichan-akira ... Can you sign the CLA if you agree with its terms :point_up:? We can't accept the PR without it.

**Comment by ichan-akira** [comment]
@guardrex done

**Comment by guardrex** [comment]
@ichan-akira ... It's not indicating that you clicked the "sign now" link. Could you try again?

**Comment by ichan-akira** [comment]
oops sorry I have tried it again @guardrex hope this time it works

**Pull request merged**
