### PR TITLE
Add "Unit Testing" page to .NET Core Incremental Migration

### PR DESCRIPTION
**Pull request by afshinm**
As discussed in this issue https://github.com/dotnet/systemweb-adapters/issues/401, there are some additional steps that must be followed if the subject under test make use of `HttpRuntime`. 

This PR adds a new subpage **Unit Testing** to [ASP.NET to ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-7.0) and explains how that particular issue can be resolved.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/migration/inc/unit-testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/15be33f0cf3e51aa66fd68df5b20f33205a568b9/aspnetcore/migration/inc/unit-testing.md) | [aspnetcore/migration/inc/unit-testing](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/unit-testing?branch=pr-en-us-30537) |

### CODE REVIEW

**Comment by afshinm** [comment]
The build is failing with `Can't find branch, tag, or commit 'main' for repo https://github.com/Microsoft/templates.docs.msft`, which makes sense but I'm not sure how to fix it. cc @Rick-Anderson if you know how to fix this error.

**Comment by Rick-Anderson** [comment]
@afshinm  fixed by closing and reopening, yes, I'm a wizard 🥇 

Should I put this under **Incremental Migration** and add it to a few of the 
## Additional Resources sections?

image

cc @tdykstra

**Comment by afshinm** [comment]
> @afshinm  fixed by closing and reopening, yes, I'm a wizard 🥇 
> 
> 
> 
> Should I put this under **Incremental Migration** and add it to a few of the 
> 
> ## Additional Resources sections?
> 
> 
> 
> image
> 
> 
> 
> cc @tdykstra 

Yes please, that would be great.

**Comment by twsouthwick** [comment]
LGTM!

**Pull request merged**
