### PR TITLE
Move identity social providers into Identity

### PR DESCRIPTION
**Pull request by damienbod**
improve security authentication menus

### CODE REVIEW

**Comment by guardrex** [comment]
Can the ellipsis (and favoritism) in the "Google, Facebook ..." heading be dropped in favor of a general heading, such as "External authentication providers"?

**Comment by damienbod** [comment]
I have no problem with this, I did not want to change this and leave it as was :)

**Comment by damienbod** [comment]
Renamed to **External authentication providers**, I can revert if further feedback advises against this

**Comment by guardrex** [comment]
Thanks ... I think that's better.

Rick, Tom, and Wade will be here soon to review/merge.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
