### PR TITLE
Update docs for debugging in VS Code

### PR DESCRIPTION
**Pull request by captainsafia**
Updates the instructions for debugging in VS Code now that the new version of Omnisharp is out.

Steps for debugging standalone and hosted apps, an explanation of our config options, and some sample `launch.json` files for different scenarios.

### CODE REVIEW

**Comment by guardrex** [comment]
Cool ... I'll edit direct for the grammar+style pass. It's faster that way than providing suggestions. You can re-edit my edits after the commit. I'll do it now.

**Comment by guardrex** [comment]
It needs image links for the following? ...

* index/_static/blazor-vscode-debugtypes.png
* /Users/captainsafia/Desktop/Screen Shot 2020-05-27 at 11.40.52 AM.png

**Comment by captainsafia** [comment]
> It needs image links for the following? ...

> index/_static/blazor-vscode-debugtypes.png
> /Users/captainsafia/Desktop/Screen Shot 2020-05-27 at 11.40.52 AM.png

Woops! That second screenshot should be removed. And I uploaded the first one to the static folder.

I'll have to rebase since I forgot to save another set of changes.

**Comment by guardrex** [comment]
> I uploaded the first one to the static folder.

Oh, yes, I see.

It should be in a folder that matches the name of the topic file (*debug.md*). For this topic, the path would be *debug/_static*.

**Comment by guardrex** [comment]
There's already a *debug* folder. There's a static file there without a *_static* folder. That's ok. I can clean this up later. Usually, we go with ...

* *_static* for images.
* *samples* for samples (e.g., *samples/3.x/CoolSample*)
* *samples_snapshot* for snapshot files of code (this is where that *launchSettings.json* file should be)

I'll fix it up later. This topic, like the rest, is due for a UE pass.

**Comment by captainsafia** [comment]
Got it! I took the guidance in the CONTRIBUTING.md but assumed that there were probably different ways since I noticed different image references in the file.

Your changes look good.

**Comment by captainsafia** [comment]
Got it. Let's go ahead with merging so we can get user feedback on this.

**Comment by guardrex** [comment]
I'll take it live now.

**Comment by guardrex** [comment]
@captainsafia btw - I tried the steps for VSC, and I received ...

Capture

I don't have Chrome on here at the moment. I do have Edge tho (v 44.18362.449.0).

I haven't tried the suggestion from that dialog yet.

**Comment by captainsafia** [comment]
@guardrex What are the contents of your `launch.json`? The debugger uses Chrome by default but you can configure it by setting `"browser": "edge"`.

**Comment by guardrex** [comment]
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "edge"
        }
    ]
}
```

btw --- That dialog suggests setting the runtime executable for Edge (`runtimeExecutable`) ... that doesn't seem like good advice. The Edge folks don't seem keen on letting anyone know much about how Edge is launched, certainly they don't speak to an executable that does it.

I tried to to provide troubleshooting guidance for WASM security topics whereby the dev sets up a VS **Browse With** browser profile for in-private browsing in Edge ... you know ... a clean environment to run tests with tokens on every debug launch, but I hit a brick wall with Edge ... never did find out what to give it to launch the browser vis-a-vis an executable.

Anyway ..... I'm concerned about the advice for that dialog in this context. I couldn't find out that info, and I doubt anyone else will find it easy to determine. I don't really think such a thing exists for Edge. I think they use some other launch mechanism, but please correct me if I'm wrong. I'd love to go in and add Edge to my FF and Chrome troubleshooting content in those WASM security topics.

**Comment by captainsafia** [comment]
@guardrex Can you option an issue for this so I can dig into this a little bit more?

**Pull request merged**
