### PR TITLE
v6 Update ASP.Net Hub

### LINKED ISSUE #22599: Hub page updates for ASP.NET Core: new Hub design and reflect .NET 6 related changes
Updates for [ASP.NET Docs Hub](https://docs.microsoft.com/en-us/aspnet/core/)

Reviewed details with Bill Wagner.   This update request is aligned with the .NET 6 timeline and there are new HUB designs we will be using that are not ready at the moment. (So I will work on this yet.)

I will be handling both the .NET and ASP.NET Hub pages for .NET 6 changes and Hub design changes.
Related to .NET Hub page update dotnet/docs#21005 on dotnet/docs

For now I reviewed all links, verified the Hub page is working as is.  Seems to be good for now.  6/23/21

### PR DESCRIPTION
**Pull request by wadepickett**
[Internal Review: ASP.NET hub page](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-6.0&branch=pr-en-us-23804)

Fixes #22599 

- Reviewed hub topic data to see if any highlighted links need to move. (Data made available on Teams)
- Updated to .NET 6 / VS 2022
- Verified Hub uses latest required template.

### CODE REVIEW

**Comment by wadepickett** [comment]
@Rick-Anderson, are there any new topics you know of that you think should be listed prominently here on the hub page that are missing?  I put data for clickthroughs for the ASP.NET hub page on teams, if you want to look it over.

**Comment by Rick-Anderson** [comment]
@rafikiassumani-msft @davidfowl @LadyNaggaga @captainsafia should we change first WebAPI from the controller version to the minimal API version?

image

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson  Is the second link under Restful APIs supposed to be `Create a Minimal Web API with ASPNET Core` ?  Can we promote that instead of the controller base example?

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson  Is the second link under Restful APIs supposed to be `Create a Minimal Web API with ASPNET Core` ?  Can we promote that instead of the controller base example?

**Comment by Rick-Anderson** [comment]
@rafikiassumani-msft  see [Internal Review: ASP.NET hub page](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-6.0&branch=pr-en-us-23804)

**Comment by Rick-Anderson** [comment]
And we're not supposed to use Resful APIs, they're HTTP APIs :)

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson can we get `Create Your First Web API` in the top titles to land on Minimal rather than the controller base examples ?

**Comment by Rick-Anderson** [comment]
@wadepickett  yes, make that change.

**Comment by wadepickett** [comment]
@Rick-Anderson and @rafikiassumani-msft,  Highlighted section's First Web API pointing to minimal version. Thanks.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson one more thing.  Can we also get the first link with a checkbox to land on Minimal rather than the controller example?  Also, the second link is broken.  If the intent for the two links is to represent the two patterns (Controllers vs minimal), should we be more specific? 

1. Create a Minimal Web API with ASPNET Core -> Lands on Minimal
2. Create Controller based Web API with ASPNET Core -> Lands on controller based example ?

 @davidfowl @DamianEdwards, @LadyNaggaga   any thoughts ?

image

**Comment by wadepickett** [comment]
@rafikiassumani-msft, thanks for the great feedback.   To answer your question on the broken link: The link you pointed out that was broken, will resolve in production, but it can't jump repos for the review build.  I have verified it resolves correctly to the topic.  (Good to point out anyway just in case.)

**Comment by wadepickett** [comment]
@rafikiassumani-msft & @Rick-Anderson,  I updated the links in the RESTful web API apps section. Thanks @rafikiassumani-msft.  It was goofy they way those two were listed with the same title to begin with.  One was for a Learn series.

**Comment by Rick-Anderson** [comment]
@rafikiassumani-msft @LadyNaggaga  we shouldn't be using **RESTful** APIs, should we change that to **HTTP** APIs?

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson  I think the change makes sense given the fact that `REST` is pattern. HTTP is more inclusive (Both rest and any other type of http endpoint/pattern).

**Comment by Rick-Anderson** [comment]
@wadepickett  can you change RESTful to HTTP?

**Comment by wadepickett** [comment]
@Rick-Anderson, would one of these examples work?
1. "HTTP web API apps"
2. "HTTP web API services"
3. "RESTful HTTP web API apps"
4. "RESTful HTTP web API services"

**Comment by Rick-Anderson** [comment]
We need to remove RESTful.

How about **HTTP API apps**?
@rafikiassumani-msft do you have a preference. cc @serpent5

**Comment by wadepickett** [comment]
@Rick-Anderson, updated section title to "HTTP API apps" and changed the summary to "Develop HTTP services with ASP.NET Core web API".

**Comment by wadepickett** [comment]
@rafikiassumani-msft, does that work?   Updated section title to "HTTP API apps" and changed the summary to "Develop HTTP services with ASP.NET Core web API".   I should get this published soon so we are pointing to .NET 6 content for this, API, migration content, etc.

**Comment by rafikiassumani-msft** [comment]
@wadepickett can we change this ` Develop HTTP services with ASP.NET Core web API` to `Develop HTTP services with ASP.NET Core`

**Comment by wadepickett** [comment]
Thanks to you both for the great feedback.  I updated and will squash and merge.

Here is what it looks like now for that last bit:
image

**Pull request merged**
