### PR TITLE
Draft-WIP: ModelState.AddModelError /2

### LINKED ISSUE #27861: Model Validation should mention `ModelState.AddModelError`
`aspnetcore/mvc/models/validation.md` may be the first page someone reads about validation. Yet it seems to miss the simplest method to return a validation error to the user (where built-in attributes fall short): [ModelState.AddModelError](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.addmodelerror).

This method makes it particularly easy, for example, if the validation needs to check a database

```
if (dbContext.Records.Any(record => record.Name == model.Name))
{
    ModelState.AddModelError("Name", "The Name is already in use.");
    return View(model);
}
```

The existing documentation leads the reader to believe that creating a custom `ValidationAttribute` or implementing `IValidatableObject` are the only alternatives to built-in attributes.

Thanks for your consideration!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 64069](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64069)

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #27861

code from https://github.com/dotnet/AspNetCore.Docs.Samples/pull/115
https://github.com/dotnet/AspNetCore.Docs.Samples/issues/92
https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/RazorPages/models/ModelStateError/Pages/Contacts/Create.cshtml.cs#L26

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  you got [credit for the merge](https://github.com/dotnet/AspNetCore.Docs/graphs/contributors). Can you review my changes here and open an issue if you see any problems.

**Comment by Rick-Anderson** [comment]
Arg, it doesn't look like you got credit, even though you were the first commit. I'll have to [watch author](https://github.blog/changelog/2022-09-15-git-commit-author-shown-when-squash-merging-a-pull-request/) when I do this again, but it doesn't look like there's any way to select the author.

**Comment by sammychinedu2ky** [comment]
Sure that's fine . But where do you check if I got credit or not cause I can see my commit in the commit tab. Is there somewhere else that you check? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
image

Looks like they changed how they determine who gets credit. I'll find something else for you to get that credit back.

**Comment by sammychinedu2ky** [comment]
Sure no worries. 😅

**Pull request merged**
