### PR TITLE
Blazor state container example fix

### LINKED ISSUE #21948: ASP.NET Core Blazor state management code smell
Hi,
The "In-memory state container service" demo code contains a major code-smell --

```cs
    public string Property { get; set; } = "Initial value from StateContainer";

    public event Action OnChange;

    public void SetProperty(string value)
    {
        Property = value;
        NotifyStateChanged();
    }
```

The property `Property` has a public setter but the demo code shows that the property should be set through the `SetProperty` method. It's bad practice to have both a SetPropertyName method, and public property setter which would only set the autoproperty without doing the other bits (like the notifying of the UI which defeats the point!)

A sub-optimal fix would be to make the set private on the property so SetProperty must be called.
Better, the fix would be to scrap the SetProperty, move its implementation into the setter, and have a backstore for the property.

```cs
        private string savedStringValue;

        public string SavedStringValue
        {
            get => savedStringValue;
            set 
            {
                savedStringValue = value;
                NotifyStateChanged();
            }
        }
 ```

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&pivots=server#in-memory-state-container-service-server)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #21948

Thanks @kjhf! :rocket: ... Would u like to review this?

### CODE REVIEW

**Comment by guardrex** [comment]
I'm going to go ahead and get this in as soon as the build is clear. I had the J&J vaccine 💉 yesterday ... mild soreness everywhere kept me up last night. I need to go lie down 🛏️ for a little while. Ping me for a patch if it needs it.

**Comment by guardrex** [comment]
Arrrr ... looks like the build system melted down. :boom:

**Comment by Rick-Anderson** [comment]
That's the fix the internal folks recommended close/reopen

**Comment by kjhf** [comment]
Looks great thank you for your work on this @guardrex :)

**Comment by guardrex** [comment]
Sure thing. Thanks again for pointing me in the right direction.

**Pull request merged**
