### PR TITLE
Fix aspnetcore\tutorials\min-web-api\samples\7.x\todo\ build

### PR DESCRIPTION
**Pull request by Elanis**
Hello,

When building the current version of [this example for .NET 7](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/min-web-api/samples/7.x/todo) there is an error:
```log
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Message.cs(6,12): warning CS8618: Non-nullable pro
perty 'Text' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [G:\A
spNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\TodoApi.csproj]
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Program.cs(120,43): error CS0246: The type or name
space name 'Message' could not be found (are you missing a using directive or an assembly reference?) [G:\AspNetCore.Do
cs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\TodoApi.csproj]
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Program.cs(121,15): error CS0246: The type or name
space name 'Message' could not be found (are you missing a using directive or an assembly reference?) [G:\AspNetCore.Do
cs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\TodoApi.csproj]
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Program.cs(125,49): error CS0246: The type or name
space name 'Message' could not be found (are you missing a using directive or an assembly reference?) [G:\AspNetCore.Do
cs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\TodoApi.csproj]
    1 Warning(s)
    3 Error(s)

Time Elapsed 00:00:02.66
```

This PR fixes the issue.

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @Elanis ... The better fix for this is to remove the namespace given to the `Message` class in `Message.cs` because the `Todo` class doesn't set a namespace. Do you want to make that change, or would you like me to open a new PR to make the update?

**Review by guardrex — CHANGES_REQUESTED** [review]
Remove line 83 from `Program.cs` added by the PR and drop the namespace at the top of `Message.cs`.

**Comment by Elanis** [comment]
Hi @guardrex

Indeed, could be a solution as well.
I pushed the changes :)

**Comment by guardrex** [comment]
Yeah ... compiler static analysis isn't going to agree, but this is more consistent with what's here.

cc: @wadepickett ... I think you're managing the tutorial. The OLD code 👴 wasn't really adopting general .NET conventions, but it was making it simpler in the old days for devs to consume code from examples without having to update namespaces. Nowdays, we probably all favor adding them everywhere to make the compiler happy; and if the dev needs to match them to their app, then that's just what they'll need to do. Anyway ... @Elanis's PR here will fix up the bug.

@Elanis ... Would you also kill 🔪 this one, too ............

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/8.x/todo/Message.cs#L1

**Review by guardrex — APPROVED** [review]
Nevermind on that last one ... I'll zap it in a sec on a new PR.

**Comment by guardrex** [comment]
Thanks for this, @Elanis!

**Comment by Elanis** [comment]
No problem, thank you for the review and fast replies 😄

**Pull request merged**
