### PR TITLE
v6 update: gRPC Intro: Moniker added only

### PR DESCRIPTION
**Pull request by wadepickett**
[Internal Review for added moniker](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0&branch=pr-en-us-23395)

Added 6.0 version moniker which will be merged before content is updated so it is easy to diff.

Contributes to #23085

### CODE REVIEW

**Comment by wadepickett** [comment]
Closing and opening in attempt to get the build to occur.  Same issue across two different PR's last night, looks like build was having some issues.

**Comment by wadepickett** [comment]
Tested and merging a moniker only update to v6.0 per Rick's request so the following v6 update is much easier to diff.

**Comment by wadepickett** [comment]
@Rick-Anderson, have no merge option available I guess until it is reviewed.  It sounded like for these quick moniker updates before the actual update begins that I would just merge myself after testing and keep going, but it does not look like that is possible.  Maybe I misunderstood.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, have no merge option available I guess until it is reviewed.

You have to remove draft

**Pull request merged**
