### PR TITLE
Update sample readme for Create gRPC client & server

### PR DESCRIPTION
**Pull request by wadepickett**
For Internal Review: I am not sure how to get a review build for sample readme.md files which lacks structure used by the review build process.

Partially addresses issue #16467

Updated the readme.md to point to the sample tutorial rather than duplicate the tutorial in the readme itself which became quickly out of date.

### CODE REVIEW

**Comment by wadepickett** [comment]
@Rick-Anderson, I'm not sure how to get a review build and URI for this sample readme.md.
I would think it would generate something like: https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/readme?view=aspnetcore-3.1&branch=pr-en-us-18169&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
You can add the readme content to one of your repos like I did [here](https://github.com/Rick-Anderson/Stop-Watch/blob/master/README.md)

I don't see any value to the readme, I think you can delete it. All the info is in a tutorial, right?

**Comment by wadepickett** [comment]
The only value the readme provides, is a way for the sample to be discoverable through the sample browser system.  The readme is required by  the sample system for that to happen.

**Comment by wadepickett** [comment]
For now, I will update the readme so it at least points to the right tutorial until I can get it removed from the samples system.

**Comment by wadepickett** [comment]
@Rick-Anderson, sorry, I forgot I didn't have patches to squash and squashed when merging.  I will try to remember not to do that.

**Comment by wadepickett** [comment]
Fixes #16467

**Pull request merged**
