### PR TITLE
Update new-field.md

### PR DESCRIPTION
**Pull request by tamilselvan719**
Added the missing DB migration command (Visual Code SQL lite section) to make it easy for anyone new

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> dotnet ef migrations add InitialCreate

You can't do that unless you deleted the migration. update looks at the DB state and runs all the migrations needed.

**Comment by Rick-Anderson** [comment]
@tamilselvan719 check my suggested change. cc @tdykstra

**Comment by tdykstra** [comment]
>  check my suggested change. 

Works if there's only been one migration, alternative that works regardless of number of migrations is to delete the Migrations folder.

**Comment by Rick-Anderson** [comment]
@tamilselvan719  thanks for the PR, much appreciated. Keep them coming.

**Pull request merged**
