### PR TITLE
Update sdk.md

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by guardrex** [comment]
@pranavkm ❓ ... If this is the recommended alternative and since this content is versioned, would it better to **_replace_** the current entry with the new property completely.

btw - either way - we can remove the version bit from that line, since this content is versioned >=3.0.

**Comment by pranavkm** [comment]
It's a bit weird, because the property if a feature of the .NET Sdk (which does not have any documentation). `CopyRefAssembliesToPublishDirectory` is the property RazorSDK defines and understands, and it aliases it to `PreserveCompilationReferences` when present.

**Comment by guardrex** [comment]
Perhaps the best way to go for a while is to have **_two entries_** in the table, where `CopyRefAssembliesToPublishDirectory` recommends to use `PreserveCompilationReferences` for >=3.0.

**Comment by pranavkm** [comment]
Better?

**Comment by guardrex** [comment]
**_Yikes!!!!_** 😨 ... that will :boom: *badly break* :boom: the table. :smile: lol

I'll fix it up.

**Comment by guardrex** [comment]
Ok 😅 ..... it's happy now.

**Comment by pranavkm** [comment]
🚢 🇮🇹

**Comment by guardrex** [comment]
:smile: ..... it's a bit fragile .... a table like that could bring the docs build system to its knees. lol

**Pull request merged**
