### PR TITLE
Corrected a typo at StartupMap.cs

### PR DESCRIPTION
**Pull request by NLipatov**
I noticed a typo in an article on learn.microsoft.com. The tag was open, but not closed. I think it was supposed to use "Hello from non-Map delegate." inside the p tag.

If so, I suggest using this quick fix. Thanks!

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @NLipatov ... I think the `<p>` and leading space should be removed, and this isn't the only spot where this occurs. There are several files within ...

https://github.com/NLipatov/AspNetCore.Docs/tree/feature/corrected-a-typo-at-StartupMap/aspnetcore/fundamentals/middleware/index/snapshot

... that need the update.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27512) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27512) before we can accept your contribution.<br/><br/>:x: NLipatov [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=27512)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=27512) it.</sub>

**Comment by NLipatov** [comment]
> Thanks @NLipatov ... I think the `<p>` and leading space should be removed, and this isn't the only spot where this occurs. There are several files within ...
> 
> https://github.com/NLipatov/AspNetCore.Docs/tree/feature/corrected-a-typo-at-StartupMap/aspnetcore/fundamentals/middleware/index/snapshot
> 
> ... that need the update.

@guardrex, Oh, indeed, there were several other files with the same problem. Removed the leading space and a p tag in all the files where it was needed. Please take a look.

**Review by guardrex — APPROVED** [review]
Thanks @NLipatov ... LGTM.

I'll ping Rick for a final 👁️ and ✔️ just to make sure.

**Pull request merged**
