### PR TITLE
Update BooksController.cs

### PR DESCRIPTION
**Pull request by the-wazz**
Existing code caused a warning. I didn't test the Delete method 'as is' but I think this is the fix. (The Remove-arg was not passed-in properly).

[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&branch=pr-en-us-24983&tabs=visual-studio).

### CODE REVIEW

**Comment by serpent5** [comment]
Hi @the-wazz. Thanks for taking the time to open a PR.

Can you share the warning that this code fixes? I just tried building the project and I only see one error that 3.0 is no longer supported.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24983) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24983) before we can accept your contribution.<br/><br/>:x: the-wazz [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24983)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=24983) it.</sub>

**Review by serpent5 — APPROVED** [review]
The change looks good. I applied the same fix to the 6.x version.

**Comment by Rick-Anderson** [comment]
@the-wazz  can you sign the CLA agreement? @serpent5  commit pushed it over the limit.

**Comment by Rick-Anderson** [comment]
Thanks for the fix. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

**Pull request merged**
