### PR TITLE
Refactor WASM security package text

### PR DESCRIPTION
**Pull request by damienbod**
Microsoft.Identity.Web.UI is not required for Web APIs in doc hosted-with-azure-active-directory.md

PR removes this from the doc.

Fixes #Issue_Number

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory

### CODE REVIEW

**Comment by damienbod** [comment]
@scottaddie @Rick-Anderson Should I create an issue for this?

Greetings Damien

**Comment by guardrex** [comment]
Thanks @damienbod ... No, you don't need an issue for this. Let me check something first tho. I thought Javier placed these on purpose. Stand-by.

**Comment by guardrex** [comment]
The deal on this one is that the project template provides is automatically.

Let's try a wording change to call out the details.

@javiercn ... Can you confirm that the update here is sane?

If so, @damienbod or I can update the other doc to match.

**Comment by guardrex** [comment]
@damienbod ... Do you want to update the other topic with this, too? It's easier if you do it over my having to commit to your fork. Alternatively, I can open a follow-up PR and take care of it separately. :ear:

I think it starts in `blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md` at Line 157.

**Comment by damienbod** [comment]
I'll do it, thanks @guardrex

**Comment by damienbod** [comment]
@guardrex Should be good now, thanks

**Review by guardrex — APPROVED** [review]
Thanks. We'll go ahead and merge this after it builds. Javier will get me 😨😄 if I've missed something here.

**Pull request merged**
