### PR TITLE
SignalR with Blazor Server samples+pivot

### LINKED ISSUE #19264: SignalR with Blazor Server
Can this be updated or forked to include how it would be done in Blazor Server as well?

I don't see anything official using or mentioning using SignalR with Blazor Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #19264

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-3.1&branch=pr-en-us-21271)

Notes:

* Pivots for WASM and Server. Preserves all 3.x vs. 5.x coverage. Adds 3.x and 5.x Blazor Server sample apps, which are confirmed running here per the new guidance.
* Updates title, metadata, and ToC with a redirect file entry. Cross-links updated, and I don't see any broken cross-links on the build report.
* I flesh out and fix up nits and bits here and there along the way, but I'll take another look at this on the UE pass later for this topic on https://github.com/dotnet/AspNetCore.Docs/issues/19286. Of course, let's fix/improve anything that you want here and now.
* Probably best to take a special look at the **_Add the System.Text.Encodings.Web package_** section in both pivots. I'm mostly concerned about **_version advice_** for the `System.Text.Encodings.Web` package, which is currently ...

  > Select the version of the package that matches the shared framework in use.

  Is that correct?

* ... and the **_gotchas_** 😈 to call out for Blazor Server ... what are they? I'll place them in the text.

### CODE REVIEW

**Comment by guardrex** [comment]
@BrennanConroy ... You were going to look at this one later? No rush ... I just want to confirm that it didn't fall off of your radar. It's not blocking anything that I'm working on.

**Comment by guardrex** [comment]
@BrennanConroy ... Should I go ahead and roll the 🎲🎲 on this one and merge it? We've been using a one week rule for when product unit engineers are just too busy to look 👀. DR says that he won't call for my head 🔪😨 if we must do so and nits are present. My guidance is just to get the nits out asap as discovered. We can go ahead here if you're 🏃😅.

**Comment by BrennanConroy** [comment]
Sorry, I did take a quick look at this and it looks good. As far as gotchas, it looks like there are some mentioned in the threat mitigations doc https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-5.0, wonder if that can be linked to?

**Comment by guardrex** [comment]
Sure thing. I'll take care of that and then give it one more look-see 👀 before merging.

**Pull request merged**
