### PR TITLE
signalr javascript snippet reverted

### PR DESCRIPTION
**Pull request by fiyazbinhasan**
***@Rick-Anderson  edit:*** [Internal review url](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0&branch=pr-en-us-22861#connect-to-a-hub)

@Rick-Anderson @BrennanConroy snippet reverted. But the information in this [section](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#manually-reconnect) is wrong. Please apply a fix for it. Thanks 🙌 
image

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
I thought the aspnetcore/signalr/javascript-client.md was fixed. The problem with the last PR was you had a stale branch to work with.

**Comment by fiyazbinhasan** [comment]
Actually, the problem was that the snippet in the sample was updated to,

```
connection.onclose(function (error) {
        if (error) {
            console.log(`Connection closed with error: ${error}`);
        } else {
            console.log("Connection closed.");
        }
    });
```

But the doc was not updated for some reason. This section needs to be changed as the information doesn't match with the snippet,

> The following code demonstrates a typical manual reconnection approach:
> 1. A function (in this case, the start function) is created to start the connection.
> 2. Call the start function in the connection's onclose event handler.
```
async function start() {
    try {
        await connection.start();
        console.log("SignalR Connected.");
    } catch (err) {
        console.log(err);
        setTimeout(start, 5000);
    }
};

connection.onclose(function (error) {
        if (error) {
            console.log(`Connection closed with error: ${error}`);
        } else {
            console.log("Connection closed.");
        }
    });
```

**Comment by BrennanConroy** [comment]
> But the information in this [section](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#manually-reconnect) is wrong.

Oh I think I see what happened. The PR that changed the sample, just changed the sample code without regard for the doc page that was using it for the manual reconnect section.

So I think you fixed it in https://github.com/dotnet/AspNetCore.Docs/pull/22826. We should probably keep it as is in main currently. Sorry for the extra work 😄

**Comment by fiyazbinhasan** [comment]
No problem. The doc has a mixture of hard-coded snippets and reference snippets from the sample, hence the confusion. 😸

**Pull request closed without merging**
