### PR TITLE
add RDG012 example

### LINKED ISSUE #30484: Move embedded snippets to project file 12
Create Rdg12 folder to contain sample [here](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/aot/diagonstics) and follow [Rdg1](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/aot/diagonstics/Rdg1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98b9d6b6-fdd2-4600-2392-eb2c2cdd61f5
* Version Independent ID: 98b9d6b6-fdd2-4600-2392-eb2c2cdd61f5
* Content: [RDG012: Unable to resolve inaccessible type](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg012?view=aspnetcore-8.0)
* Content Source: [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @captainsafia
* Microsoft Alias: **safia**

### PR DESCRIPTION
**Pull request by timdeschryver**
Fixes #30484
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/207 needs to be merged first

image

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md](https://github.com/dotnet/AspNetCore.Docs/blob/3caa5d1ec80e0cc9ade3d1af2d44fe605cf8f924/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md) | [RDG012: Unable to resolve inaccessible type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg012?branch=pr-en-us-30579) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@timdeschryver  when I run the sample, I get

```
 System.InvalidOperationException
  HResult=0x80131509
  Message=Call UseKestrelHttpsConfiguration() on IWebHostBuilder to automatically enable HTTPS when an https:// address is used.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  ```

**Comment by timdeschryver** [comment]
@Rick-Anderson I'll take a look at it later today

**Comment by timdeschryver** [comment]
@Rick-Anderson if I'm not mistaken this is because the snippets use `WebApplication.CreateSlimBuilder()` . With the slim builder you need to enable/configure https support. Using `WebApplication.CreateBuilder()` fixes this problem.

If you agree we can update all the examples to use  `WebApplication.CreateBuilder()` (I think this is also the most used)
 in https://github.com/dotnet/AspNetCore.Docs.Samples/issues/201.

**Comment by Rick-Anderson** [comment]
> If you agree we can update all the examples to use WebApplication.CreateBuilder() (I think this is also the most used)
in https://github.com/dotnet/AspNetCore.Docs.Samples/issues/201.

Let's do one PR and have the PU (product unit) review it. Anything we can do to simplify the code is beneficial.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson if I'm not mistaken this is because the snippets use `WebApplication.CreateSlimBuilder()` . With the slim builder you need to enable/configure https support. Using `WebApplication.CreateBuilder()` fixes this problem.
> 

That fixes it. The `Properties\launchSettings.json` I added didn't, so I'll remove that file. But I'm not getting a warning.

**Pull request merged**
