### PR TITLE
Add doc for new ASP.NET Core JSON extension methods

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/26250

Preview: https://review.docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-5.0&branch=pr-en-us-20259

***EDIT*** by @Rick-Anderson ~work moved to #20276~

### CODE REVIEW

**Comment by JamesNK** [comment]
@davidfowl @glennc Are you happy with the TOC location, title and content?

**Comment by Rick-Anderson** [comment]
@JamesNK  any chance we could use
route to code (RTC) or even R2C
I'm a little worried how `route to code` will MT (machine translate).

**Comment by Rick-Anderson** [comment]
@JamesNK  I could add "route to code" to the no-loc list.

**Comment by JamesNK** [comment]
Sure, go ahead.

**Review by scottaddie — APPROVED** [review]

**Comment by scottaddie** [comment]
Thank you for the PR, @JamesNK!

**Pull request merged**
