### PR TITLE
Improvements to Blazor auth coverage

### LINKED ISSUE #14304: Need to get claims when logging in to Azure B2C
Hi, I am building a Blazor Server app (preview9) and need to use Azure Active Directory B2C for authentication. I have started with your template project, and have made sure that the token returned from B2C includes First Name, Given Name and a couple of other properties (viewed from https://jwt.ms). I cannot however work out how to access these properties from the code in the LoginDisplay.razor file. Do you know how to get that information?

Thanks,    Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #16932: Output AuthenticationStateProvider to screen, not Console
Perform following changes
&lt;p&gt;@message&lt;/p&gt;
private string message {get; set; } = "None";
            message = $"{user.Identity.Name} is authenticated.";
            message = "The user is NOT authenticated.";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authenticationstateprovider-service)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #16996: Surface tooling guidance for VS4Mac and CLI
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #17221: Passing tokens to a server-side Blazor app
Opening a new issue for this as per @danroth27 request.

This is how you pass and use access tokens and refresh tokens to a server-side Blazor API
https://github.com/javiercn/blazor-server-aad-sample

There's several people asking for this on a regular basis, (AAD or any other provider) so this sample and associated redme covers it.

I'll leave it up to @danroth27 and the docs team from here.

### LINKED ISSUE #17401: SignInManager incompatible with Blazor?
At the top of this documentation it implies that "using ASP.NET Core's Identity system" is a viable option.  The Identity scaffold generates Razor pages (.cshtml & .cs) but not Blazor pages (.razor, which is damn confusing, but a different topic).  However, in my testing, SignInManager will always throw an exception: "The response headers cannot be modified because the response has already started."  SignInManager is incompatible with Blazor's underlying SignalR technology.  The work-arounds are either API  call to the Server, or implementing JWT Identity Server.  
Is SignInManager incompatible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authentication)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #17402: Examples on how to recover user name and ID
It would be helpful to add examples on how to recover user ID and name from within the server/controller code, since, with the proposed configuration, the traditional UserManager methods fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #17415: Request additional access tokens - standalone
Hi,

I need 'Request additional access tokens' scenario but for wasm - standalone, I suppose this is already possible but probably the documentation about it is missing.
Then, what's also missing is how to use those tokens further in httpClient calls. I assume that we don't have to inject those tokens manually.
I'd appreciate if you could add this.

I described what I need to achieve in detail: https://stackoverflow.com/questions/60754751/blazor-webassembly-standalone-access-multiple-aad-protected-apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #17470: Prerendering with Authentication
Content is here https://github.com/dotnet/aspnetcore/issues/15253#issuecomment-604581439

### LINKED ISSUE #17517: UserManager.GetUserAsync returns null when using the default Blazor WebAssembly template.
I'm using Blazor WebAssembly with Authentication (Indivual User Accounts, Store users accounts in-app, ASP.NET Core hosted), I'm able to run the app, register and login, but when I try to retrieve the logged-in ApplicationUser on the Server through the UserManager I'm always getting null.
My Startup ConfigureServices() looks like this:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));

    services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
        .AddEntityFrameworkStores<ApplicationDbContext>();

    services.AddIdentityServer()
        .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

    services.AddAuthentication()
        .AddIdentityServerJwt();

    services.AddControllersWithViews();
    services.AddRazorPages();
}
```

I'm trying to retrieve the ApplicationUser in a Controller like this:
```csharp
var currentApplicationUser = await userManager.GetUserAsync(User).ConfigureAwait(false);
```

What resolved the issue for me was adding:

```csharp
services.Configure<IdentityOptions>(options => options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);
```

Not sure if this behavior is expected or not, but might be needed to add this line of code as part of the template or fix the issue causing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #17401
Fixes #17517
Fixes #17402
Fixes #17415
Fixes #16996
Fixes #14304
Fixes #16932
Fixes #17470
Fixes #17221

On-going improvements to Blazor auth topics ...

* Move the Blazor Server template content from the *Overview* topic to the *Blazor Server* security auth topic.
* Add a NOTE to highlight that Blazor WebAssembly remarks apply to Preview 2 or later with the template version guidance. We can't use one of the existing INCLUDES here because the content of the NOTE has to be a little different in this context.
* Update/enhance the package and namespace requirements for Blazor WebAssembly apps.
* Call out explicitly that `SignInManager` and `UserManager` aren't Razor component concepts.
* Improve a couple of the code examples.
  * Write the result to the rendered component output, not to the console.
  * Add in displaying the user's claims, too.
* It wasn't clear that a custom auth state provider will work in Blazor Server. I expand that section to cover Blazor Server; but in spite of it working (I tested it here), I may have created some kind of an anti-pattern :boy::gun:, so let me know if I need to revert the changes. :ear:
* Added info for `UserManger` and `SignInManager` ... and `IdentityUser` ... for Server projects of Hosted apps ... the user identifier claim type has to be established with a line that isn't part of the template. Javier was pinged :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17517#issuecomment-605993247
* Enhance the example in *Request additional access tokens*, and move that section to the top of that doc.
* Enhance auth example to show getting a specific claim.
* Cover prerendering with auth.
* Cover passing tokens to a Blazor Server app.

### CODE REVIEW

**Comment by guardrex** [comment]
Note to self: Get the VS4Mac instructions into the Blazor Server security topic.

**Comment by guardrex** [comment]
@mkArtakMSFT FYI ... I'm adding updates to this right now to cover some additional issues. I should be done in a bit and will ping u back.

**Comment by danroth27** [comment]
@guardrex Ideally @javiercn would have a look at these changes. If he's fine, then I'm fine.

**Comment by mkArtakMSFT** [comment]
@javiercn, I need your input for these two things (from @guardrex 's comments):
- It wasn't clear that a custom auth state provider will work in Blazor Server. I expand that section to cover Blazor Server; but in spite of it working (I tested it here), I may have created some kind of an anti-pattern 👦🔫, so let me know if I need to revert the changes. 👂

- If I understand this correctly, we've said that prerendering with Auth is not supported. @javiercn can you confirm this? If this is the case, then the `prerendering with auth` piece is also good.

**Comment by mkArtakMSFT** [comment]
The rest looks good to me.

**Comment by guardrex** [comment]
**On the first point ...**

If you go to the live topic at :point_right: https://docs.microsoft.com/aspnet/core/security/blazor/#implement-a-custom-authenticationstateprovider ... you'll see that it *sounds* a bit too focused on WASM. E.g., ...

> If you're building a Blazor WebAssembly app ...

> In a Blazor WebAssembly app ...

... but it works just fine in a Blazor Server app, so the updates on this PR take care of that.

**On the 2nd point ...**

It comes from :point_right: https://github.com/dotnet/aspnetcore/issues/15253#issuecomment-604581439, so it's probably good. 🤞

**Pull request merged**
