### PR TITLE
Add a note about model binding record types

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
Slight edit. Thanks for doing this.

**Comment by Rick-Anderson** [comment]
@pranavkm  what about Razor Pages?

**Comment by pranavkm** [comment]
It should be identical, no changes there.

**Comment by Rick-Anderson** [comment]
@pranavkm  see my last [commit](https://github.com/dotnet/AspNetCore.Docs/pull/19968/commits/20a08170db3325f57df1270cda8598233b50efc7)

**Comment by pranavkm** [comment]
Looks great. I have some additional write up about what works and does not that was created as part of the PR: https://github.com/dotnet/aspnetcore/pull/23976. Pasting it here because that PR takes forever to load. In case you think there's anything useful for you to add to the docs:

-------------------------------

A summary of what works and what does not:

## We allow binding to and validating record types.
```
public record Person([Required] string Name, [Range(0, 100)] int Age);
```
For this to work, we require that the type

* Is a record type,
* has exactly one public constructor
* every parameter has a property with the same name (no difference in casing) and type


### We do not bind to regular POCOs that do not have parameterless constructors.
e.g., this will result in an exception saying that the type must have a parameterless constructor.

```
public class Person(string Name)
When a record type has more than one constructor, binding will fail stating this is unsupported:
public record Person([Required] string Name, [Range(0, 100)] int Age)
{
   public Person(string Name) : this (Name, 0);
}
```

### Record types with manually authored constructors that look like primary constructors will work:

```
public record Person
{
   public Person([Required] string Name, [Range(0, 100)] int Age) => (this.Name, this.Age) = (Name, Age);

   public string Name { get; set; }
   public int Age { get; set; }
}
```

### For record types, validation and binding metadata on parameters is used. Any metadata on properties is ignored.

```
public record Person (string Name, int Age)
{
   [BindProperty(Name = "SomeName")] // This does not get used
   [Required] // This does not get used
   public string Name { get; init; }
}
```

### Validation uses metadata on the parameter but uses the property to read the value. In the ordinary case with primary constructors, the two would be identical. However, there are ways to defeat it:
```
public record Person([Required] string Name)
{
   private readonly string _name;
   public Name { get; init => _name = value ?? string.Empty; } // Now this property is never null. However this object could have been constructed as `new Person(null);`
}
```

### TryUpdateModel does not update parameters on a record type
```
public record Person(string Name)
{
   public int Age { get; set; }
}

var person = new Person("initial-name");
TryUpdateModel(person, ...);
```

In this case, MVC will not attempt to bind Name again. However, Age is allowed to be updated

**Comment by Rick-Anderson** [comment]
@pranavkm  fantastic. I'll take care of it. I created #19969 for tracking.

**Pull request merged**
