### PR TITLE
Schedule automatic runs of merge-live

### PR DESCRIPTION
**Pull request by serpent5**
Adds a scheduled trigger to open a merge-live PR [At 08:00 on every day-of-week from Monday through Friday](https://crontab.guru/#0_8_*_*_1-5). The time is UTC, so I think 8AM is a good starter, and I don't think it needs to run at weekends. We can still do it manually [here](https://github.com/dotnet/AspNetCore.Docs/actions/workflows/merge-live.yml):

image

Very much open to feedback on all of this. The next step is automated merge of the PR, but I have some investigation around status checks to do first.

### CODE REVIEW

**Comment by guardrex** [comment]
I yield to Rick.

**Comment by serpent5** [comment]
> I yield to Rick.

Ok, fair enough. In future, would you like me to at least cc you on changes in this area?

**Comment by guardrex** [comment]
Yes. These types of changes often affect how we work.

**Review by Rick-Anderson — APPROVED** [review]

**Review by Rick-Anderson — APPROVED** [review]
Why not run it everyday? If there's a merge to live, it won't create a new one.

**Comment by serpent5** [comment]
Going All In

**Comment by Rick-Anderson** [comment]
@serpent5  what's that all in clip from?

**Comment by serpent5** [comment]
[Angie Tribeca](https://m.imdb.com/title/tt3597790)

**Pull request merged**
