### PR TITLE
Demonstrate GET, POST, PUT, and DELETE with HttpClient

### LINKED ISSUE #12580: HTTP POST example?
This page is ranking # 2 on google for "send http post request in .net core" and yet it does not contain a single example on how to send a POST request.

I understand this might not be the place to put such documentation, but I haven't been able to find a single post request example in the .net core official docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#outgoing-request-middleware)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #12580.

Creating as a draft for visiblity. Things still left to do:

- [x] <strike>Complete the sample, which is mostly just cleaning up some of the copy/paste.</strike>
- [ ] <strike>Demonstrate `System.Net.Http.Json` as a more streamlined approach to sending/receiving JSON.</strike> See #18716.
- [ ] Add a section or two to the topic to discuss the code demonstrated in the sample.

### CODE REVIEW

**Comment by serpent5** [comment]
@Rick-Anderson Are you happy with this approach? I think I'll skip the `System.Net.Http.Json` stuff in this PR but cover it later in another change. If you have time, and you're interested, you should be able to run the sample app as is.

**Comment by Rick-Anderson** [comment]
Wow, this is fantastic. We just need to document it must be run from `https://localhost:5001` (or you must change the port). I tried to catch the socket exception and return a warning but was unable to. The would probably pollute the  clean code anyway.
Good plan. Let me know how I can help.

**Comment by serpent5** [comment]
@Rick-Anderson Thanks for taking a look. I added a commit that uses the incoming request to determine the correct address to use, so it should work whatever the host/port is.

I'm going to work on getting some content into the topic next. What kind of detail do you think should go into the topic?

**Comment by Rick-Anderson** [comment]
@serpent5  we don't want a cook-book step by step instructions how you made the code - like what MSDN used to do. Let the code do the talking. Refer to the code and explain how it work. 

Does that help?

**Comment by serpent5** [comment]
Yeah, sure, that makes sense.

I'll work on adding a new section that focuses on the POST example but also refers the to the PUT and DELETE examples, for completeness. I'm hoping the reader can just spin up the sample and see it all in action, without being cook-booked through it, like you said. I should have it ready by the end of the week, if not a bit earlier.

**Comment by serpent5** [comment]
@Rick-Anderson I'm getting a 404 on the Dropbox link. If you're happy with how this renders, don't worry about providing a new link.

**Comment by Rick-Anderson** [comment]
Have a look at the published doc when you have time.

**Pull request merged**
