### PR TITLE
Dataedo

### PR DESCRIPTION
**Pull request by Piotr-Dataedo**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21922) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21922) before we can accept your contribution.<br/><br/>:x: Piotr-Dataedo [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21922)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=21922) it.</sub>

**Comment by guardrex** [comment]
Thanks for submitting the image for consideration. @Rick-Anderson will let you know if this is ok. Personally, I'm not too keen on MS picking 'winners' because it can stifle innovation and give the community a false sense of MS support and approval of 3rd party products and services for which no survey and review of available solutions has been conducted.

Anyway, I recommend as I always do that if the attribution appears in the doc with the image that the usual warning goes with it to cover MS ...

> Dataedo isn't maintained or supported by Microsoft.

**Comment by Piotr-Dataedo** [comment]
Hey Luke,

Thanks for the message. We were talking with Rick, and he suggested the approach.

Best regards,
[Tom's photo]
Tom Wasiewicz
Customer Success Manager
+48 58 500 49 32<tel:+48%2058%20500%2049%2032>
Chat with me<https://dataedo.com/chat?&utm_source=footer&utm_medium=email> | Book a ***@***.***/meet?utm_source=footer&utm_medium=email>
[Dataedo logo]<https://dataedo.com/?&utm_source=footer&utm_medium=email>

**Comment by guardrex** [comment]
Oh ... very well, @Piotr-Dataedo. I withdraw my comment.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@Piotr-Dataedo  thanks for the PR. 
@guardrex It's the only tool I could find to make a ERD. It was really easy to deploy the app to Azure and make the diagram. I wasn't able to find any other tools to do that.

**Comment by Rick-Anderson** [comment]
@guardrex  NP, you had the right response. This is the best way to make sure we have permission for the image.

**Pull request merged**
