### PR TITLE
Blazor lifecycle diagram and text updates

### LINKED ISSUE #20403: Blazor lifecycle diagram and text updates
From @mrpmorris ...

> have the path that leads from await=>render always on the right. At the moment the first example has a default flow downwards and the additional flow of the await flows to the right. The two following ones have the default flow path to the right and the additional task path flows downwards (the opposite). I'd have the default flow downwards, and the alternative (additional task) to the right.
>
> Call `OnInitialized{Async}`, then render immediately. If a `Task` is returned then await the completion of the `Task` and render again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #20403

Thanks @mrpmorris! :rocket:

Given the fix on the description of processing for `OnInitialized{Async}`, I suspect that there's a better way to represent the flow in the diagram. We *might* want to take another hand at drawing that bit of processing behavior ('render immediately/rerender after `Task` returns') when I circle back around for a UE pass on this topic later (@mrpmorris, I'll ping u when I get back to this topic). Hopefully, that will happen in the 🎁 *holidays period* ⛄ post 5.0 GA. For now tho, let's see if this is generally accurate.

### CODE REVIEW

**Comment by guardrex** [comment]
Given that the images aren't immediately evident the diff, I'll shoot them into a comment here :point_down:.

I'm also making a nit change: I'm going with 96 ppi at the same physical dimension (width). We shrunk these a bit so that they would look better on a webpage. On a mobile device with the current site styles, it's not really the best approach. If the build system gave me direct control (i.e., ``), I could fix this problem, but it doesn't, so we'll go with the best compromise that we can. Anywho ... Printing might still be *rough* at this resolution, and that's something that I'll try to remember to check later. I'll improve the resolution for printing if these are really nasty looking 🙈😄. 

lifecycle1

lifecycle2

lifecycle3

**Comment by mrpmorris** [comment]
Feel free to use either or both of these. Personally I prefer "big picture" diagrams rather than small pieces of the story.

https://blazor-university.com/wp-content/uploads/2020/07/component-lifecycle-1.jpg
https://blazor-university.com/wp-content/uploads/2020/07/component-lifecycle-await-v2.jpg

Credit not necessary, but appreciated :)

**Comment by guardrex** [comment]
Those are very nice, but I've been 💂 *ordered* 💂 to use Steve's diagrams for this. I'll keep an :ear: open if they change their mind.

**Comment by mrpmorris** [comment]
There's no accounting for taste ;)

**Comment by guardrex** [comment]
> There's no accounting for taste ;)

*That sort of thing is well above my pay grade!* :smile: lol

cordo

*"Praise the company!"* - Cordo ([Roy Macready](https://www.imdb.com/name/nm0534321/)), [Doctor Who](https://www.bbc.co.uk/programmes/b006q2x0): [The Sun Makers](https://www.bbc.co.uk/programmes/p00q05st), ©1977 [BBC](https://www.bbc.com/)

**Comment by guardrex** [comment]
Ping @SteveSandersonMS for review.

**Comment by SteveSandersonMS** [comment]
@guardrex Your diagrams (https://github.com/dotnet/AspNetCore.Docs/pull/20430#issuecomment-723104905) look great to me!

**Review by SteveSandersonMS — APPROVED** [review]

**Pull request merged**
