### PR TITLE
ROPC for Blazor

### LINKED ISSUE #33523: ROPC Blazor
### Description

See #33504

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/movie-database-app/index.md

### Document ID

2eb6b551-01af-4d8b-4c2c-55297295c7b7

### Article author

@guardrex

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #33523
Addresses #33504

Notes ...

* There are two Blazor articles that pertain to use of a local dB, the new BWA tutorial and the old Blazor+EF Core article+sample.
* I couldn't make good use of an INCLUDE because I use different language between the tutorial and article.
* Sections made more sense than a NOTE in these cases.
* I definitely can't cross-link to what you guys are cross-linking ... implicit flow for SPAs 🤮😄. We'd need a PKCE cross-link for our Blazor scenarios. Since things are covered in the Blazor security node, that's where I cross-link.
* No period used after the word "node" in the lists or after article title text of the cross-links. These aren't complete sentences, and it's funky to period titles and phrases in pure lists IMO.
* I like the bit you placed, Rick, for managed identities. I include that with its cross-links here.

BTW WRT images, I'm not sure if any action is required. I don't think orphaned images are here, but I'm not 100% sure about it. WRT image content, I'm not sure what to look for that should change. 👂 Same thing on the GUID aspect ... I can't tell from the issue what's changing, and I don't have access to the internal guidance.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/3c4fff749faadb5bed3c26b6522129e219f115e9/aspnetcore/blazor/blazor-ef-core.md) | [ASP.NET Core Blazor with Entity Framework Core (EF Core)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-33524) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3c4fff749faadb5bed3c26b6522129e219f115e9/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-33524) |
| [aspnetcore/blazor/tutorials/movie-database-app/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3c4fff749faadb5bed3c26b6522129e219f115e9/aspnetcore/blazor/tutorials/movie-database-app/index.md) | [Build a Blazor movie database app (Overview)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/index?branch=pr-en-us-33524) |
| [aspnetcore/blazor/tutorials/movie-database-app/part-4.md](https://github.com/dotnet/AspNetCore.Docs/blob/3c4fff749faadb5bed3c26b6522129e219f115e9/aspnetcore/blazor/tutorials/movie-database-app/part-4.md) | [Build a Blazor movie database app (Part 4 - Work with a database)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-4?branch=pr-en-us-33524) |

### CODE REVIEW

**Review by wadepickett — APPROVED** [review]
Looks great to me as far as info.  It seems like we would use an include here for the common text.  I don't like to overuse includes, but this seems like it might be a great candidate for one.

**Comment by guardrex** [comment]
The text is different between the two articles, so an INCLUDE won't work in this case. It's OK tho, as I know where my two instances of this are located.

**Comment by guardrex** [comment]
Well ... this part tho ......

> For Microsoft Azure services, we recommend using \*managed identities\*. Managed identities are a secure way to authenticate to services without storing credentials in app code. For more information, see the following resources:
>
> \* \[What are managed identities for Azure resources? (Microsoft Entra documentation)](/entra/identity/managed-identities-azure-resources/overview)
> \* Azure services documentation:
>   \* \[Managed identities in Microsoft Entra for Azure SQL](/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity)
>   \* \[How to use managed identities for App Service and Azure Functions](/azure/app-service/overview-managed-identity)

If Rick is agreeable on that bit for his added piece at ...

https://github.com/dotnet/AspNetCore.Docs/pull/33521

... that could be an INCLUDE.

However, my sections would still be hacked a bit given that I'm using different language outside of that.

**Comment by guardrex** [comment]
NIT phrasing change on the last commit ...

```diff
- Managed identities are a secure way to authenticate to services
+ Managed identities securely authenticate to Azure services ...
```

**Comment by Rick-Anderson** [comment]
>   * [How to use managed identities for App Service and Azure Functions](/azure/app-service/overview-managed-identity)
> 
> If Rick is agreeable on that bit for his added piece at ...
> 
> #33521
> 
> ... that could be an INCLUDE.
> 
> However, my sections would still be hacked a bit given that I'm using different language outside of that.

Sure

**Comment by guardrex** [comment]
I'll rework this after you place the INCLUDE on your PR.

**Comment by guardrex** [comment]
Actually, I'll modify the content after the INCLUDE appears. I want to clear this issue at the moment.

**Pull request merged**
