### PR TITLE
C177636 : removing extra hyphen to avoid broken display of table

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Extra hyphen is broken display on table for this page https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-2.2

### CODE REVIEW

**Comment by v-maudel** [comment]
Hi @Rick-Anderson , It seems our previous [fix](https://github.com/dotnet/AspNetCore.Docs/pull/17384) didn't work. Could you please help us with this one? For aspnetcore > 2.2 the hyphen I removed is not present. 
Regards

**Comment by guardrex** [comment]
The "fix" ...

> ... .EXTENSION} \*.exe* extension on ...

... seems like it would break the rendering because escaping the first asterisk isn't going to result in emphasis. Perhaps since this one topic (the table perhaps) is causing so much trouble, the asterisks here should be removed in favor of just text extensions ...


> ... .EXTENSION} .exe extension on ...

... or code ...

> ... .EXTENSION} \`.exe\` extension on ...

cc: @scottaddie

**Comment by Rick-Anderson** [comment]
@guardrex @scottaddie  this is rendering correctly. I'm going to S&M and push to live unless I hear an objection.

**Comment by guardrex** [comment]
The asterisks aren't right ... a quick edit could just make the extensions plain text to resolve it.

**Comment by guardrex** [comment]
Interesting how they are rendered correctly. Seems strange tho that it works that way.

**Comment by Rick-Anderson** [comment]
@guardrex can you edit/fix it. I'd go with 

`... .EXTENSION} .exe extension on ...`

The simplest approach.

**Comment by guardrex** [comment]
Ok ... I think that licked it.

**Comment by Rick-Anderson** [comment]
@guardrex  nice work

**Comment by v-maudel** [comment]
Thanks @Rick-Anderson, @guardrex

**Pull request merged**
