### PR TITLE
file-uploads.md grammar corrected

### PR DESCRIPTION
**Pull request by unethicalwhitehat**
---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/d8162ba77a59e6fc8a76cb13aa478af5e09062ec/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-29750) |

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @unethicalwhitehat ... "HTML" is stated verbally by letters, and "H" is pronounced "/eɪtʃ/" ... starting with a vowel. Therefore, the text is correct.

**Comment by unethicalwhitehat** [comment]
Ah, I'm British so that explains it. Fair enough considering Microsoft is an American company.

**Comment by guardrex** [comment]
Yes ... I was just thinking that it's a good idea to ping @khoiph1 on the localization team for this. The loc team can program their MT (machine translation) system to localize the docs for "a HTML" in GB-English if they agree it's the right thing to do. I'll send him (Khoi Pham) an offline email, too, as I don't think he sees GH pings.

**Comment by unethicalwhitehat** [comment]
Damn, I was happy to accept that it's simply a localisation thing, especially considering that practically every language I work with uses US English for keywords, but that would be a pretty cool thing to implement

**Comment by guardrex** [comment]
I emailed him. He should see this.

**Pull request closed without merging**
