### PR TITLE
Rebrand Office 365 to Microsoft 365: User Story 1737442, Part 10

### PR DESCRIPTION
**Pull request by damabe**
Fixes #1737442

Addresses rebranding "Office 365" to "Microsoft 365".

I'll add a comment when the PR is ready for review. I'll leave the PR open for 48 hours and address any feedback. After that, I'll sign off for merge.

Thanks -

### CODE REVIEW

**Comment by damabe** [comment]
This PR is ready for review.

You're welcome, but not required, to review these proposed rebranding changes. I'll leave the PR open for 48 hours and address any feedback. After that, I'll sign off for merge.

**Comment by guardrex** [comment]
@Rick-Anderson ... FYI ... In the repo, I see some links that have "office365" segments.

I see one more change in this vein for the naming of a AAD security role (`Office apps administrator`). I'll verify that they changed it in the Azure portal and then change the doc. I'll ping u on that @damabe or report back here either way. I'll look at that now.

**Comment by guardrex** [comment]
No 🎲🎲 @damabe ... They didn't change the role name. I've opened a new issue to address it when they do.

https://github.com/dotnet/AspNetCore.Docs/issues/19694

**Comment by damabe** [comment]
@guardrex Please do report that to them. I don't have any real interaction with the team.

**Comment by guardrex** [comment]
@Rick-Anderson ... I have an AAD engineering contact. Should I reach out to him, or would you take it from here?

**Comment by Rick-Anderson** [comment]
Try your contact and let me know if you need help.

**Comment by guardrex** [comment]
I sent him a message offline.

btw - I also inquired in the message on the AAD built-in Administrator Roles table of Object Ids. I plan to open an issue next week on the Azure docs repo to see if we can get this table ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1#aad-adminstrative-role-group-ids

... moved over there. Then, I can link to it. We really shouldn't have to maintain that ... it's not an ASP.NET Core concept.

**Pull request merged**
