### PR TITLE
Fixes #8567 How to configure CRA to point to dev ASP.NET Core server for API calls

### LINKED ISSUE #8567: How to configure CRA to point to dev ASP.NET Core server for API calls?
I realize this is a React/JavaScript question more than an ASP.NET Core question, but it would be nice if in the "Run the CRA server independently" section there was a note about how to point your API calls to the appropriate localhost/port for development. Else, the weather forecast page will attempt to fetch from localhost:3000/... and fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by VirtuaBoza**
Fixes #8567

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for contributing this, @VirtuaBoza.

However, I don't know why this would be needed. As long as your browser is pointing to your ASP.NET Core application (and *not* to the underlying CRA server), then it should already be using the correct URLs.

Is the issue that you're trying to browse directly to the CRA server instead of using the site served by `UseProxyToSpaDevelopmentServer`?

**Comment by VirtuaBoza** [comment]
Thanks for the look, Steve. It appears that the issue (which I wrote) I’m trying to fix is the result of a misunderstanding of the documentation. Following step 1 (npm start) would launch a browser pointed to :3000. If you use this without my change, fetches will fail.  I think you’re saying is that developers are not meant to use that browser tab, but instead they’re meant to close it, start the asp.net application and VS launch a browser session which will proxy requests to the :3000 server. 

Do I understand this correctly? 

Do you think that many other developers might have the same misunderstanding and start trying to use the browser session launched by npm start? If so, I could try to change this branch to make those instructions more clear.

**Comment by VirtuaBoza** [comment]
@SteveSandersonMS I was just playing around with this to figure out just that. Adding an .env file with BROWSER=none will prevent CRA from launching a browser window on start. I'd like to scratch the changes I made about the CRA proxy and add this suggestion to step 1. I'll update this branch when I get a chance today.

**Comment by VirtuaBoza** [comment]
@SteveSandersonMS Previous change removed and instruction to prevent CRA from launching the broswer added with e6fd4c7.

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS 	looks like this is ready for a quick review. @VirtuaBoza 	added the short `Add a *.env* file to the *ClientApp* subdirectory with the following setting:` instruction.

**Comment by SteveSandersonMS** [comment]
Wouldn't you say that *everyone* should have that `.env` file there? And if so, perhaps this should be baked into the project template, rather than being something we document for people to do themselves.

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/templating/issues/1752

**Pull request merged**
