### PR TITLE
5.0 refactoring

### PR DESCRIPTION
**Pull request by JeremyLikness**
This is the suggested refactoring for #20763 ... put some other changes in too.

This won't merge clean because I didn't rebuild all of the separate migrations steps. It has the completed project and a single migration. A few notes:

TL;DR;

- New many-to-many without a join table
- TPT configured for Student and Instructor

Longer:

- The original project looked like it was trying to support both SQL Server and SQLite. I just focused on SQLite because I don't have my SQL Server configured and the SQLite solution is cross-platform anyway. Obviously if the tutorial needs to work for SQL Server we can look at that too.
- SQLite doesn't have RowVersion support so that version was breaking. I added a guid as the concurrency token on `Department` which is programmatic but works across providers and in my opinion is cleaner than marking  all of the fields as concurrency.
- I created a base class `Person` that `Student` and `Instructor` inherit from
- `CourseAssignment` was a join table that doesn't have payload so I removed it, refactored `Instructor` to have a list of `Course` and `Course` to have a list of `Instructor`
- Configured the M2M relationship in the model builder
- The seed code was saving, then querying individual records to get ids, then saving again, etc. Now there is just one save and it just uses class references to build up relationships
- Instead of doing the specific `DbContext.Entity.AddRange` I simplified the code to use `DbContext.AddRange`
- Finally, I wanted to show how smart EF is and don't add instructors or students directly. They are indirectly added from the course, etc. references
- Simplified the model configuration and removed the redundant `ToTable` calls except where needed for TPT
- Moved from magic strings to `nameof` where practical to make refactoring easier

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Internal review URLs:
* [Part 1](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&branch=pr-en-us-21023&tabs=visual-studio)
* [ Part 2](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-5.0&branch=pr-en-us-21023)

See the build errors:

File | Status | Preview URL | ms.author | Details
-- | -- | -- | -- | --
aspnetcore/data/ef-rp/intro.md | Warning | View | riande | Line 303: [Warning] Invalid code snippet link: 'intro/samples/cu50/appsettingsSQLite.json'.Line 378: [Warning] Invalid code snippet link: 'intro/samples/cu50/StartupSQLite.cs'.Line 504: [Warning] Invalid code snippet link: 'intro/samples/cu50/StartupMaxMBsize.cs'.
aspnetcore/data/ef-rp/crud.md | Warning | View | riande | Line 106: [Warning] Invalid code snippet link: 'intro/samples/cu50/ViewModels/StudentVM.cs'.Line 110: [Warning] Invalid code snippet link: 'intro/samples/cu50/Pages/Students/CreateVM.cshtml.cs'.Line 119: [Warning] Invalid code snippet link: 'intro/samples/cu50/Pages/Students/CreateVM.cshtml'.

> original project looked like it was trying to support both SQL Server and SQLite. I just focused on SQLite because I don't have my SQL Server configured and the SQLite solution is cross-platform anyway.

75% of our customers use VS and SQL Server.  Very few production apps on Azure use SQLite.  cc @tdykstra 

It looks like Part 1 and Part 2 have been updated. Won't that break Parts 3-8?

**Comment by JeremyLikness** [comment]
I was only focused on a draft PR to validate the project direction. If we support SQL Server that's fine but we should remove the broken SQLite code and point the 25% to something else, or have two different projects that handle concurrency differently. I just tried to update what I though was the final code as a proof-of-direction for the changes. I have not yet attempted to look at what the step-by-step snapshots and migrations are to build from scratch, that will take a lot longer but didn't make sense to tackle until we agree on the final project. Again, this is a throw-away draft to review project direction and not suitable for merging.

**Comment by ajcvickers** [comment]
@JeremyLikness @Rick-Anderson I think we need to keep the SQLite version, or come up with something else for those people using Mac or Linux where SQL Server LocalDb is not available.

**Comment by ajcvickers** [comment]
I haven't read through the code in detail, but the changes make sense to me. You could consider using the optimistic concurrency solution for SQLite that @bricelam mentioned. This would leave the SQL Server code idiomatic for how people do concurrency on SQL Server.

**Comment by Rick-Anderson** [comment]
@JeremyLikness  all you need to do is finish the code. I'll push commits to update the article and supply the SQL Server version.

**Comment by Rick-Anderson** [comment]
@JeremyLikness  pulled your commits to #21576 so you'll get credit for the merge. I'll ping you when I get stuck.

I'll test with both Sqlite and SQL Server. To use Sqlite:

* In *Program.cs* , uncomment `// #define SQLite`
* Copy contents of *appsettingsSQLite.json* to *appsettings.Development.json*  (Dev settings override *appsettings.json* in dev  mode).

**Pull request closed without merging**
