### PR TITLE
CSS isolation inheritance, minor cleanup

### LINKED ISSUE #21269: Blazor CSS isolation scopes
https://github.com/dotnet/aspnetcore/issues/29493

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

### LINKED ISSUE #21289: Scoped CSS file and associated .razor component must be in the same directory - but this is not mentioned anywhere
It would seem that for CSS isolation to work the CSS file has to be placed in the same directory as the associated razor component. It took me a little while to figure out as it's not written in the documentation.

Ideally I'd prefer to be able to keep these files in separate directories, but if it can at least be added to the docs that they need to be in the same directory that'd probably save the next guy some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by daveabrock**
[EDIT by guardrex to add the internal review topic link]

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0&branch=pr-en-us-21378)

This pull request addresses #21269, which answers the question: how do I achieve inheritance with Blazor CSS isolation? I added to the custom scopes section to address how to do this.

While in the file, I also did some cleanup:
- Addressed #21289, where it wasn't abundantly clear the `razor.css` files need to be in the same directory as the component it is associated with
- Noticed that, for the `razor.css` references in the project file, I didn't include the `Pages\` path before it. Oops! It's fixed now.

Fixes #21269
Fixes #21289
Fixes #29780

### CODE REVIEW

**Comment by guardrex** [comment]
Awesome @daveabrock ... thanks for this ⭐. I'm 🏃😅, and this is a big help given my desire to push forward with all of the UE passes that I need to perform on the whole doc set.

I'll review and get back to you Monday. If there are only grammar bits to touch, I'll submit a commit directly for those and ask Safia to look things over before merging.

**Comment by guardrex** [comment]
Let's do one of the following to have a single lead-in example:

* Remove the `Counter` example in favor of the generic component example and flesh that out further. I did it on the commit, but we can easily revert back to using `Counter` if you think that's best. :ear:
* Remove the generic example and focus the example on the `Counter` component scenario.

UE updates are supposed to be worked in association with my UE pass issue, but I've slipped into working some UE items here, too. You'll see that I'm ...

* Dropping "My"-named things everywhere. Although we don't localize most text that names things with a "My" prefix, "My" is meaningless in most localized contexts and rather meaningless generally. I use "Example" here, but something else could be used. Whatever the name, let's avoid "My"-something things.
* Devs ❤️ to copy-'n-paste the code into their own test apps, so most code examples now get explicit file name and location (folder) guidance. In the process, any colons at the ends of existing lines go with a period. The file name/location lines have the colons now.

For Line 44 ...

> In order to guarantee style isolation when bundling occurs, `@import` Razor blocks aren't supported with scoped CSS files.

"Razor blocks"? ... Should this say, "`@import` CSS rules", and be cross-linked to MDN's page?

**Comment by daveabrock** [comment]
No worries, @guardrex - thanks for clarifying. Any outstanding work for me here, or can I proceed with putting #29780 changes in here?

**Comment by daveabrock** [comment]
> For Line 44 ...
> 
> > In order to guarantee style isolation when bundling occurs, `@import` Razor blocks aren't supported with scoped CSS files.
> 
> "Razor blocks"? ... Should this say, "`@import` CSS rules"? If so, we can cross-link to MDN's page ...
> 
> > ... [`@import`](https://developer.mozilla.org/docs/Web/CSS/@import) CSS rules ...
> 
> ... and we might want to say "in" rather than "with" ... "files." 🤔

Nope, this is in response to people wanting "@css" sections at the bottom of the Razor files (like there is for "@code" today). I can clean that up, too.

**Comment by guardrex** [comment]
Yes ... I'm done (hopefully not messing it up! 🙈).

Everything I do is subject to reversion, so if I break something or lean something the wrong way, let's definitely revert or try something else. Most of the UE changes work out (I hope 🤞), but there are cases where a change is a regression in quality or fails to realize an even better third approach.

> Nope, this is in response to people wanting "@css" sections at the bottom of the Razor files (like there is for "@code" today). I can clean that up, too.

Ok ... I was confused ... obviously. :smile: lol

**Comment by guardrex** [comment]
btw --- What prompted me to ask is that we don't document (because it doesn't exist) a Razor directive named `@import`, so I didn't want to have confusion on that. I figured if `@import` is the CSS at-rule, then it could say that and link to the MDN doc on it. That's the only reason I brought it up.

**Comment by daveabrock** [comment]
Sounds good - I'll clean up at `@import` line when I make the changes for the other issue.

**Comment by daveabrock** [comment]
OK, I pushed my changes and should be ready for your review again, @guardrex.

**Review by guardrex — APPROVED** [review]
Nice @daveabrock ... There was only a *Tiny Baby*&trade; nit on Line 44 ... "is not" :point_right: "isn't". I'll ask Safia to see if she can run an :eye: over it.

**Review by captainsafia — APPROVED** [review]

**Comment by guardrex** [comment]
Thanks @captainsafia 🙏🙇. 

Ready to merge @daveabrock?

**Comment by daveabrock** [comment]
@guardrex - YOU KNOW IT!

**Comment by guardrex** [comment]
# 🍻 **_Booyeah!_**

Thanks again!

**Pull request merged**
