### PR TITLE
Metadata updates

### LINKED ISSUE #31410: Update repo metadata
Updates ...

* `ms.prod: aspnet-core` to `ms.service: aspnet-core`.
* `ms.technology: aspnetcore-{AREA}` to `ms.subservice: {AREA}`.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #31410

Best guess on it from the build report is ...

* `ms.prod: aspnet-core` to `ms.service: aspnet-core`.
* `ms.technology: aspnetcore-{AREA}` to `ms.subservice: {AREA}`.

`introduction-to-aspnet-core.md` had an `ms.technology` of merely `aspnetcore`, so I dropped that and didn't apply a `ms.subservice` to it, given that it doesn't have an area.

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md) | [ASP.NET Core Request Delegate Generator (RDG) diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg-ids?branch=pr-en-us-31411) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md) | [ASP.NET Core Request Delegate Generator (RDG) for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg?branch=pr-en-us-31411) |
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/abtesting.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/abtesting.md) | [aspnetcore/migration/inc/abtesting](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/abtesting?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/adapters.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/adapters.md) | [System.Web adapters](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/adapters?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/overview.md) | [Incremental ASP.NET to ASP.NET Core update](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/remote-app-setup.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/remote-app-setup.md) | [Remote app setup](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-app-setup?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/remote-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/remote-authentication.md) | [Remote Authentication](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/remote-session.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/remote-session.md) | [aspnetcore/migration/inc/remote-session](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-session?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/session.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/session.md) | [ASP.NET to ASP.NET Core incremental session state migration](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/session?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/start.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/start.md) | [Get started with incremental ASP.NET to ASP.NET Core migration](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/start?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/unit-testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/unit-testing.md) | [Unit Testing](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/unit-testing?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/usage_guidance.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/usage_guidance.md) | [Usage Guidance](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/usage_guidance?branch=pr-en-us-31411) |
| [aspnetcore/migration/inc/wrapped.md](https://github.com/dotnet/AspNetCore.Docs/blob/80825e796989abcc43950b33e38856ed091298e7/aspnetcore/migration/inc/wrapped.md) | [aspnetcore/migration/inc/wrapped](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/wrapped?branch=pr-en-us-31411) |

</details>

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
Thanks for doing this.

**Comment by guardrex** [comment]
Well ... I have a few more updates to make to get additional `ms.prod` entries out.

I'll shoot another commit for the obvious changes, then we can see about the acceptable values for the `subservice` entries.

**Comment by guardrex** [comment]
Ok ... getting closer ...... it doesn't like these `ms.subservice` values ...

> Line 50: [Warning] Invalid value for 'ms.subservice': 'clientside' is not valid with 'ms.service' value 'aspnet-core'.
> Line 51: [Warning] Invalid value for 'ms.subservice': 'data' is not valid with 'ms.service' value 'aspnet-core'.
> Line 53: [Warning] Invalid value for 'ms.subservice': 'getstarted' is not valid with 'ms.service' value 'aspnet-core'.
> Line 55: [Warning] Invalid value for 'ms.subservice': 'hostdeploy' is not valid with 'ms.service' value 'aspnet-core'.
> Line 60: [Warning] Invalid value for 'ms.subservice': 'razorpages' is not valid with 'ms.service' value 'aspnet-core'.
> Line 61: [Warning] Invalid value for 'ms.subservice': 'releasenotes' is not valid with 'ms.service' value 'aspnet-core'.
> Line 63: [Warning] Invalid value for 'ms.subservice': 'signalr' is not valid with 'ms.service' value 'aspnet-core'.
> Line 64: [Warning] Invalid value for 'ms.subservice': 'test' is not valid with 'ms.service' value 'aspnet-core'.
> Line 66: [Warning] Invalid value for 'ms.subservice': 'webapi' is not valid with 'ms.service' value 'aspnet-core'.
> Line 67: [Warning] Invalid value for 'ms.subservice': 'whatsnew' is not valid with 'ms.service' value 'aspnet-core'.
> Line 69: [Warning] Invalid value for 'ms.subservice': 'blazorhybrid' is not valid with 'ms.service' value 'aspnet-core'.

Is anything known about what they should be?

**Comment by guardrex** [comment]
Ah ... I see they have some docs ...

https://review.learn.microsoft.com/en-us/help/platform/validation-ref/ms-service-subservice-invalid?branch=main

... but I can't access the link in that doc to the `[ms.service allowlist](https://taxonomy.docs.microsoft.com/TaxonomyServiceAdminPage/#/taxonomy/detail/2022-03-21T23:12:29.5228914Z!4509d9e0-94dc-4f2f-a88e-1b344de4723f/ms.service).

**Comment by guardrex** [comment]
Something went very sideways here in terms of process. Until this gets fixed, PRs can't merge, so the repo is broken. It doesn't look like it can be truly fixed until they approve the correct `ms.subservice` values ... the ones we use. We'll need a workaround ... perhaps eliminate these broken subservice values until the pairs can be approved. Shall I cut them out and open a follow-up issue?

**Comment by guardrex** [comment]
I'm giving that plan a shot now just to unblock us.

If this builds, then I'll open a follow-up issue for one of the docs 🐱 to put in the subservice requests. I'll place a cut-'n-paste into the issue for the full section to make it easy to wire things back up later after they approve the request.

**Comment by guardrex** [comment]
Ok ... that seems to be a reasonable workaround.

I opened https://github.com/dotnet/AspNetCore.Docs/issues/31413 to follow-up here. That lists the ones we need, and it has a cut-'n-paste of the original config for `docfx.json`.

**Comment by guardrex** [comment]
I'll wait until I hear back on the workaround. This workaround isn't what they intended for us to do, but they kind'a left us no choice in order to be able to keep working without forced merges.

**Comment by Rick-Anderson** [comment]
> Ah ... I see they have some docs ...
> 
> https://review.learn.microsoft.com/en-us/help/platform/validation-ref/ms-service-subservice-invalid?branch=main
> 
> ... but I can't access the link in that doc to the [ms.service allowlist](https://taxonomy.docs.microsoft.com/TaxonomyServiceAdminPage/#/taxonomy/detail/2022-03-21T23:12:29.5228914Z!4509d9e0-94dc-4f2f-a88e-1b344de4723f/ms.service).

image

**Comment by Rick-Anderson** [comment]
@guardrex  why don't we merge it? We can always revert.

**Comment by guardrex** [comment]
Ok ... the issue will need one of the docs cats to work given that I can't make the request.

**Pull request merged**
