### PR TITLE
Update model.md

### LINKED ISSUE #21887: 'Server' keyword exception
VSCode - Window tutorial

The problem only occurs when open https://localhost:5001/Movies. I guess in the scaffolding step miss '-sqlite' for generating the correct connection string.

Without -sqlite
`"ConnectionStrings": {
    "RazorPagesMovieContext": "Server=(localdb)\\mssqllocaldb;Database=RazorPagesMovieContext-6d928de8-07d6-40a3-aac5-0282c61ff5a2;Trusted_Connection=True;MultipleActiveResultSets=true"`

After add -sqlite
`"ConnectionStrings": {
    "RazorPagesMovieContext": "Data Source=RazorPagesMovieContext-7736068c-1c78-4f01-943c-6ab74a71edfc.db"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&branch=pr-en-us-22029&tabs=visual-studio-code)

Fixes #21887

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@wadepickett  @topweeradet please test

**Comment by wadepickett** [comment]
@Rick-Anderson, sure, I'll test.  Sorry to ask, but are you testing your changes here?  If not please test first, then ask for a review.  If you are testing your work and just want to make sure we all are too, that's cool.

**Comment by Rick-Anderson** [comment]
The previous version manually created the db context and connection string. When I had you remove those and let the scaffolder do all that work, this bug was introduced.  I wasn't notified the other bug was fixed (windows vs non-windows). Shouldn't take more than 5 minutes to test. Might need to retain the `-dc RazorPagesMovieContext` for multiple reasons (wrong default name, etc).

**Comment by wadepickett** [comment]
@Rick-Anderson: Test results: 
Scaffolding ran.  However, on the "Create the initial database schema.. " step when running dotnet ef database update I get the following exception where it is not finding the DbContext:
"No DbContext was found in assembly 'RazorPagesMovie'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic."

Also, just a heads up that there are build warnings indicated above for the PR, checks were not successful.

**Comment by Rick-Anderson** [comment]
Here's the output for `dotnet aspnet-codegenerator razorpage --help`

Was a `DbContext ` generated? If so, post it here.

Generator Arguments:
  razorPageName : Name of the Razor Page
  templateName  : The template to use, supported view templates: 'Empty|Create|Edit|Delete|Details|List'

Generator Options:
  --model|-m                          : Model class to use
  --dataContext|-dc                   : DbContext class to use
  --referenceScriptLibraries|-scripts : Switch to specify whether to reference script libraries in the generated views
  --layout|-l                         : Custom Layout page to use
  --useDefaultLayout|-udl             : Switch to specify that default layout should be used for the views
  --force|-f                          : Use this option to overwrite existing files
  --relativeFolderPath|-outDir        : Specify the relative output folder path from project where the file needs to be generated, if not specified, file will be generated in the project folder
  --namespaceName|-namespace          : Specify the name of the namespace to use for the generated PageModel
  --partialView|-partial              : Generate a partial view, other layout options (-l and -udl) are ignored if this is specified
  --noPageModel|-npm                  : Switch to not generate a PageModel class for Empty template
  --useSqlite|-sqlite                 : Flag to specify if DbContext should use SQLite instead of SQL Server.

**Comment by Rick-Anderson** [comment]
@deepchoudhery ,  the output for `dotnet aspnet-codegenerator razorpage --help` has

`  --dataContext|-dc                   : DbContext class to use`

We're not supplying the DbContext class. Should the help be changed to 

`  --dataContext|-dc                   : DbContext class to use, if one exists, otherwise the name of the DbContext class to generate`

**Comment by wadepickett** [comment]
@Rick-Anderson, your last update tests out fine for the instructions, so you found the solution.   Note the build check above failed.

**Comment by Rick-Anderson** [comment]
> Note the sample build check failed.
@wadepickett  did you look at the warnings? It's the moniker bug.

**Review by wadepickett — APPROVED** [review]

**Comment by wadepickett** [comment]
@Rick-Anderson, I was referring to the sample build check, not the doc build check, if that is what you are referring to.  What bug is "The moniker bug"?

**Comment by deepchoudhery** [comment]
@Rick-Anderson hey, second option LGTM. 
Thanks

**Pull request merged**
