### PR TITLE
Fix hightlight selection in PO localization docs

### LINKED ISSUE #28409: Fix fr.po and a few more typos
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1098b7-dbe7-a8d8-f57f-017b1c94e960
* Version Independent ID: 96179de2-df1c-ff1d-5a2e-89b0949e0620
* Content: [Configure portable object localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/portable-object-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/portable-object-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @sebastienros
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 64210](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64210)

### PR DESCRIPTION
**Pull request by hishamco**
Fix tiny issues in #28376

/cc @Rick-Anderson

Fixes #28409

### CODE REVIEW

**Comment by hishamco** [comment]
BTW Rick is there a way to access the review URL with hotmail email? It's very useful indeed

**Comment by hishamco** [comment]
BTW Rick is there a way to access the review URL with hotmail email? It's very useful indeed

**Comment by Rick-Anderson** [comment]
## Public review  of the doc build:
- download the [HTML files](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
- unzip
- view HTML file in a browser.
- For links outside the doc, remove the `review.` from URL.

You don't need any account, just follow the instructions.

**Comment by sebastienros** [comment]
This looks more French than Czech.

**Comment by hishamco** [comment]
It was a typo, because I didn't find pluralization in the French file, anyhow got fixed

**Comment by Rick-Anderson** [comment]
@hishamco  looks good to me. Can I S&M?

**Pull request merged**
