### PR TITLE
Fixed typos in the table assignment

### LINKED ISSUE #25167: SqlException: Invalid object name 'Instructor'
Run Results: SqlException: Invalid object name 'Instructor'.

You need to change the table assignment for "Student" and "Instructor":
 ...
            modelBuilder.Entity<Course>().ToTable("Course");
            modelBuilder.Entity<Enrollment>().ToTable("Enrollment");
            modelBuilder.Entity<Student>().ToTable("Person");    // <--- HERE
            modelBuilder.Entity<Department>().ToTable("Department");
            modelBuilder.Entity<Instructor>().ToTable("Person");   // <--- HERE
            modelBuilder.Entity<OfficeAssignment>().ToTable("OfficeAssignment");
            modelBuilder.Entity<CourseAssignment>().ToTable("CourseAssignment");
            modelBuilder.Entity<Person>().ToTable("Person");
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by ankitwww**
Fixes #25167 - Typos in the table assignment

### CODE REVIEW

**Review by wadepickett — APPROVED** [review]

**Comment by wadepickett** [comment]
@ankitwww, thanks very much for the fix!

**Comment by wadepickett** [comment]
I looked through the topics to verify where this is used.  It is not referred to in the topics, but rather is the final example provided after the tutorial is complete and the change is correct.

**Comment by wadepickett** [comment]
@ankitwww, the original was correct for an inheritance example used in one of the tutorials.  So it has been reverted.

**Comment by ankitwww** [comment]
Thanks @wadepickett .

**Pull request merged**
