### PR TITLE
RDG001 warning /5

### LINKED ISSUE #30423: DiagnosticDescriptor UnableToResolveRoutePattern RDG001
See [source](https://source.dot.net/#Microsoft.AspNetCore.Http.RequestDelegateGenerator/DiagnosticDescriptors.cs,514e3f675c3339e5,references)

```
[GetHelpLinkUrl]
$"https://learn.microsoft.com/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/{id}";

helpLinkUri: GetHelpLinkUrl("RDG001"));

```

Are each of these manually created from the [source](https://source.dot.net/#Microsoft.AspNetCore.Http.RequestDelegateGenerator/DiagnosticDescriptors.cs,514e3f675c3339e5,references)  similar to [ASP0000: Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0000?view=aspnetcore-7.0)

---
[Associated WorkItem - 161716](https://dev.azure.com/msft-skilling/Content/_workitems/edit/161716)

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #30423

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/RDG001.md](https://github.com/dotnet/AspNetCore.Docs/blob/d170b7e205ff19581226222ed8141156a902a545/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/RDG001.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/RDG001](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/RDG001?branch=pr-en-us-30426) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md](https://github.com/dotnet/AspNetCore.Docs/blob/d170b7e205ff19581226222ed8141156a902a545/aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md) | [aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rgd_ids?branch=pr-en-us-30426) |

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  check the build, all blazor errors.

**Comment by Rick-Anderson** [comment]
@captainsafia do you want something like this?

**Comment by guardrex** [comment]
@Rick-Anderson ... It looks like the 🧀 moved on the API for the RC1 release because these didn't throw when I placed them. They have different namespaces now. I'll create a new PR now to fix them up.

**Comment by Rick-Anderson** [comment]
>  It looks like the 🧀 moved on the API for the RC1 

Common for early APIs, I'm guessing no more   🧀 moving
Thanks for the fix

**Comment by Rick-Anderson** [comment]
Replaced by #30446

**Pull request closed without merging**
