### PR TITLE
Add sample code in docs to handle URL-encoded client certs, eg. on NGINX / Kubernetes NGINX Ingress

### PR DESCRIPTION
**Pull request by rctay**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22484) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22484) before we can accept your contribution.<br/><br/>:x: rctay [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=22484)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=22484) it.</sub>

**Comment by guardrex** [comment]
@rctay ... Thanks for sending this in. In the future tho, please open an issue first to discuss significant changes.

**Comment by guardrex** [comment]
Stand-by a bit @rctay ... we haven't forgotten about this.

+Brennan per Artak.

Note that this looked a bit 😨 *scary* 😨 to me, so it's best to get PU :eyes: on it.

**Comment by guardrex** [comment]
@BrennanConroy ... What's your take on this one/this approach? IIRC, Artak mentioned offline that you might be able to advise/approve/decline.

**Comment by guardrex** [comment]
cc: @blowdart ... I'm not getting any ❤️ on this one. :smile: Is this the safe/correct approach, and do you want to show this in the docs?

bueller

**_Bueller? ... Bueller? .............. Bueller?_** - Economics Teacher ([Ben Stein](https://www.mrbenstein.com/))
[Ferris Bueller's Day Off](https://www.paramountmovies.com/#/product/ferrisbuller) ©1986 [Paramount Pictures](http://www.paramount.com/)

**Comment by guardrex** [comment]
Thanks ... no ... I meant no ❤️ from asking others earlier. I only just pinged you the first time. But ... *Yes! The rotten family 😼 here wakes me up daily at 4am CST!* 😡 *Arrrrrrgh! CAT!*

**Comment by blowdart** [comment]
@bartonjs Didn't we add pem support so the string replace here isn't strictly necessary?

**Comment by bartonjs** [comment]
Yeah, the code could be

```C#
string certPem = WebUtility.UrlDecode(headerValue);
clientCertificate = X509Certificate2.CreateFromPem(certPem);
```

Removing the header and footer and then doing base64decode are all redundant with that new (as of .NET 5) method.

**Comment by guardrex** [comment]
Thx @blowdart and @bartonjs.

@rctay ... Can you check the updates and see if I broke anything? In particular, are we all good on `var certPem = ...` over `string certPem = ...` and `var bytes = ...` over `byte[] bytes = ...`?

**Comment by guardrex** [comment]
Thanks @rctay ..... Would you believe that I always disliked the word "passed" and just wanted to see if we could compose this without it??!!!!

*No??!!* ...... ok. :smile: ... Yeah, idk what happened there. Need *MORE* ☕ I guess. 😆

**Comment by guardrex** [comment]
I'll hold for a sec here to see if @blowdart and/or @bartonjs sign-off on the latest updates. If I don't hear back within a few days, I'll go ahead and merge.

**Comment by rctay** [comment]
@guardrex I pushed a commit to add a missing word, "passed", I think it got lost in the midst of the replacement `s/your application/the app/`. Apart from that it looks good, thank you for the changes.  

Before: "...the client certificate is to the app in URL-encoded form..."

Now: "... the client certificate is **_passed_** to the app in URL-encoded form..."

**Comment by blowdart** [comment]
As it's not obvious what the type would be, and you may prefer clarity for docs. string for pem would be better.

Once  UrlEncodedPemToByteArray is deleted in any _v5_ docs (should be kept for v3) and switched to X509Certificate2.CreateFromPem looks fine to me.

**Comment by guardrex** [comment]
> Once UrlEncodedPemToByteArray is deleted in any v5 docs

Yes, versioned now for <5.0 via the latest commits here.

**Pull request merged**
