### PR TITLE
Updates to use the dotnet/blazor-samples repo

### PR DESCRIPTION
**Pull request by guardrex**

### CODE REVIEW

**Comment by serpent5** [comment]
I _think_ you might the equivalent of the following for a new repo:

https://github.com/dotnet/AspNetCore.Docs/blob/e4f1a20574e12fd8e5afec2fe76dcccda03ef69d/.openpublishing.publish.config.json#L46-L51

**Comment by guardrex** [comment]
I'm assembling the commit for that now.

**Comment by serpent5** [comment]
Ha, ok, sorry. I jumped the gun there. Should've know you had it covered.

**Comment by guardrex** [comment]
*I'm hacking it as a go!* 😆 I have their doc in front of me, but I didn't catch that link initially.

**Comment by guardrex** [comment]
Well .... 

```
:::code language="csharp" source="~/../blazor-samples/6.0/BlazorSample_Server/ExampleModel.cs" highlight="6":::
```

... is fine here, but that's throwing just like Xamarin repo cross-links locally ...

> [22-02-04 04:16:06.743]Warning:\[BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.BuildConceptualDocument](blazor/fundamentals/static-files.md)The code snippet "~/../blazor-samples/6.0/BlazorSample_Server/ExampleModel.cs" could not be found.

Capture1

I'll hack on it a bit more. The goal is to get it showing locally **_AND_** get it passing here.

What did work locally resulting in ...

Capture

... was ...

```
:::code language="csharp" source="~/../../blazor-samples/6.0/BlazorSample_Server/ExampleModel.cs" highlight="6":::
```

... soooooooo ... if I place the `dotnet/blazor-server` repo GH folder locally where it prefers them here (and make sure it's ignored with a local `.gitignore`, then that might do the trick. I'll try that next.

**Comment by guardrex** [comment]
@serpent5 @Rick-Anderson @wadepickett @terrajobst @danroth27 @mkArtakMSFT 

### *That seems to have licked it!* :+1:

The only **_RexHack!_**&trade; is to keep the local GH folder for the `dotnet/blazor-samples` repo **_inside the local `dotnet/AspNetCore.Docs` GH folder_** and ignore it there in `.gitignore` so that it only lives on my local machine.

This way, my local DocFX finds the files, and the docs build system finds the files.

Unless anyone has an alternate suggestion for my hack, I'll work this way.

Otherwise, I'll be picking back up with this effort next week ...

* Place remaining samples into the new repo.
* Set up the README for `dotnet/blazor-samples`.
* Update markdown links, possibly using a script that does it automatically.
* In the end, get the sample repo listed at https://docs.microsoft.com/en-us/samples/browse/ and drop the existing 6.0 samples from the `dotnet/AspNetCore.Docs` repo. We won't be moving 5.0 and 3.1. We're just going to let those drop off as support drops and those doc sets sunset. Upcoming 7.0 and later releases will use the repo.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
