### PR TITLE
Update dotnet-client.md

### PR DESCRIPTION
**Pull request by Yawnder**
Added a clarification on the impact (or lack there of) on how using strong-typed hubs affects the client side.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
I don't think this comment having it's own section is particularly useful, if you really want this just add a note in [Call client methods from hub](https://docs.microsoft.com/aspnet/core/signalr/dotnet-client?view=aspnetcore-5.0&tabs=visual-studio#call-client-methods-from-hub)

**Comment by Yawnder** [comment]
Indeed, it maybe doesn't need it's own section. The reason why I added one rather than a note is that in Server Concept/Hubs, there is a section for it, and there was no note anywhere regarding the client side of the same concept.

Feel free to close the PR if it's not helpful.

**Comment by guardrex** [comment]
I already made it a note. @BrennanConroy will provide final signoff (or updates) before we merge this.

**Comment by Yawnder** [comment]
Excellent. Thanks!

**Pull request merged**
