### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by henry-js**
Previously referenced .md file is no longer in this repository

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @henry-js ... Thanks for pointing this out, but this won't be the right fix. We don't point to markdown files. Let me research it out and see what we can do here. I'll edit the PR with whatever I come up with.

**Comment by serpent5** [comment]
@guardrex I _just_ made an update to fix this, then saw your comment and assignment.

**Comment by guardrex** [comment]
I don't see why you're calling this one out, @henry-js. It's live at ...

https://docs.microsoft.com/dotnet/core/testing/unit-testing-code-coverage

**Comment by guardrex** [comment]
HA ... nevermind ... I see we're in a markdown file. 😄 ..... **_MORE_** ☕ **_PLZ!_** ... I'm not fully awake yet.

**Comment by guardrex** [comment]
@serpent5 ... Is it ok now? I just saw that we'll need the full URL to that topic.

**Comment by serpent5** [comment]
@guardrex I'll sort it.

**Comment by guardrex** [comment]
Yeah ... it depends if the contributing page shows up at the site. We have markdown files that don't ... that aren't reachable at docs.microsoft.com ... then we need the full URL. If they are reachable at docs.microsoft.com, then the relative URL is cool.

**Comment by serpent5** [comment]
Yeah, it caught me out too. I fixed it by completely undoing the change... 🤦... Should be OK now.

**Review by guardrex — APPROVED** [review]

**Comment by serpent5** [comment]
Thanks @henry-js.

**Comment by guardrex** [comment]
Yeah ... thanks again, @henry-js! 🚀 We don't normally "FIX" a **_"FIX"_** for a **_community-contributed "FIX"_** ... but it does happen from time-to-time. 😄 The whole docs system is rather complex. There are at least *HUNDREDS* ... several hundred, probably ... little rules and *NITs* and 😈 **_gotchas_** 😈 around here. The links are one of them because it depends on where they show up and where they're going.

... add on to that a less-than-ideal amount of ☕☕☕☕ for things to get a little sketchy in the morning! 😆

**Pull request merged**
