### PR TITLE
Remark on DP protection of persisted component state

### LINKED ISSUE #33767: Mention that DP is used to secure PCS data sent to the client
### Description

https://github.com/dotnet/aspnetcore/issues/47669

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0#persist-prerendered-state

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/prerendering-and-integration.md

### Document ID

3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2)

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #33767

Still guessing a little on the exact phrasing.

cc: @hakenr 

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/96e569edfad6ae93bd01cf8aaa8a5d251f3af6e2/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-33819) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/96e569edfad6ae93bd01cf8aaa8a5d251f3af6e2/aspnetcore/blazor/components/prerendering-and-integration.md) | [aspnetcore/blazor/components/prerendering-and-integration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?branch=pr-en-us-33819) |

### CODE REVIEW

**Comment by guardrex** [comment]
> prerendered data sent to a client ... in-transit

I might need to reword these remarks to make this say it's data sent *round-trip for server payloads*. Currently, it sounds like it's one-way server to client.

**Comment by hakenr** [comment]
My proposal:

_The persisted prerendered state is transferred to the interactive client, where it's used to restore the component state. In `InteractiveWebAssembly` render mode, this data is exposed to the browser and must not contain any sensitive information that needs to remain secure. For `InteractiveServer` render mode, ASP.NET Core Data Protection ensures that data is transferred securely. `InteractiveAuto` render mode combines WebAssembly and Server interactivity, so it's also necessary to consider data exposure to the browser, as in the `InteractiveWebAssembly` case._

This is intended as a suggested level of simplification, not exact wording. I’d avoid going into details about in-transit or similar concepts.

**Comment by guardrex** [comment]
Yes, that's nice. I'll put it in place with a few NIT updates.

**Comment by guardrex** [comment]
Ok ... try it now 👀.

**Comment by guardrex** [comment]
Since we're coming to agreement, I'll drop the Javier review request.

**Review by hakenr — APPROVED** [review]
lgtm

**Pull request merged**
