### PR TITLE
Update HTTP Requests to 6.0

### LINKED ISSUE #23174: 6.0 : HTTP requests using IHttpClientFactory
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #23174.

[Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0&branch=pr-en-us-23787).

### CODE REVIEW

**Comment by serpent5** [comment]
I'll push another commit with an updated `ms.date` once this gets approval. Should I change anything else in the metadata? e.g. author?

**Review by Rick-Anderson — APPROVED** [review]
Great work.

**Review by wadepickett — APPROVED** [review]
I don't have anything to add beyond the helpful suggestions Rick already made.   To answer your question about ms.author, I am fine with changing that to you if you like.   Well done on this update.

**Comment by serpent5** [comment]
Thanks @Rick-Anderson and @wadepickett for the feedback.

**Pull request merged**
