### PR TITLE
Copy .NET 6 code to .NET 9 folder

### LINKED ISSUE #33961: Prep code/folders for .NET 9
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md

### Document ID

fa488196-1f98-08ea-adcc-17d9dac86727

### Article author

@tdykstra

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #33961
Preps #4633

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/data/ef-rp/intro/samples/cu90/wwwroot/lib/jquery-validation/LICENSE.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a76b1eac0998e41d50d3b15728db6269e74e7ee/aspnetcore/data/ef-rp/intro/samples/cu90/wwwroot/lib/jquery-validation/LICENSE.md) | [aspnetcore/data/ef-rp/intro/samples/cu90/wwwroot/lib/jquery-validation/LICENSE](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro/samples/cu90/wwwroot/lib/jquery-validation/LICENSE?branch=pr-en-us-33960) |

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
Or do we want to start from scratch in a folder appropriately located for a Blazor Web App version of the tutorial series?

**Comment by Rick-Anderson** [comment]
> Or do we want to start from scratch in a folder appropriately located for a Blazor Web App version of the tutorial series?

I'll let them decide but I think RP is more complete than https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core

**Comment by guardrex** [comment]
Is this about jQuery validation? ... If so, it isn't supported for Blazor.

**Comment by Rick-Anderson** [comment]
> Is this about jQuery validation? ... If so, it isn't supported for Blazor.

Nope, it's like your EF/Movies/Blazor tutorial only more advanced. It uses no jQuery.

**Comment by guardrex** [comment]
Gotcha ... but I think if you're refering to the Blazor movie dB tutorial, it isn't ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core

It's this one ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/?view=aspnetcore-8.0

**Pull request merged**
