### PR TITLE
Add Rebus to Third-party SignalR backplane providers

### PR DESCRIPTION
**Pull request by ryanbuening**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
My main concern is that the library is versioned 0.0.5 and hasn't been updated in 11 months. @bradygaster

**Comment by bradygaster** [comment]
I share your concern as well. @ryanbuening do you feel this is an ongoing project that will continue to be maintained and supported? Customers are sure to ask questions once there's a doc on it.

**Comment by ryanbuening** [comment]
@mookid8000 has been responsive to Rebus issues in the past. [Rebus](https://github.com/rebus-org/Rebus) itself is actively maintained and supported.

**Comment by bradygaster** [comment]
Then I'm okay with it - as long as support exists and the project isn't waning or being abandoned, I'm okay with the doc change.

**Pull request merged**
