### PR TITLE
Changed ASP.NET Core version "2.1" to "3.1"

### PR DESCRIPTION
**Pull request by alavifazel**
Changed a mistakenly written ASP.NET Core version "2.1" to "3.1" inside a paragraph.

### CODE REVIEW

**Comment by alavifazel** [comment]
Or it should be changed to something like "2.1 or above".

**Comment by alavifazel** [comment]
Its corresponding code snippet (CompatibilityVersion.Version_2_1) should also be changed.

**Comment by guardrex** [comment]
@alavifazel ... Check your document version selector in the upper left-hand corner of your screen. This PR is changing the version in the <3.0 version of the topic (see Line 264). I think you're just looking at the wrong version of the topic in your browser.

**Comment by guardrex** [comment]
Oh ... I better let @Rick-Anderson look at this ... I see a 2.1 reference on Line 162. There might be something for that line instead. Stand-by @alavifazel ... he'll be on in a bit to look at this.

**Pull request closed without merging**
