### PR TITLE
Manage table 1st column width in gRPC topic

### LINKED ISSUE #17124: Style change has made table column too small
The "Option" column in the tables on this page is small and the option name is being wrapped. It is hard to understand what it is suppose to say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc8dc9f-9cc8-bda7-2cda-e9461f7c3a5d
* Version Independent ID: 85b23cfb-29a8-37f4-16f7-fdf6b0dde773
* Content: [gRPC for .NET configuration](https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/grpc/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #17124

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.0&branch=pr-en-us-17133#configure-services-options)

Is everyone cool with our HTML hack approach on this one? It 🤞 *should* 🍀 work. Applying this to the longest entry should set the column width to accommodate all entries in that column of the table. Can someone check the internal build topic to confirm?

... also wondering in passing if they chose the best style in this case. Perhaps, `<code>` in a table cell should have this style set everywhere. 🤔

### CODE REVIEW

**Comment by JamesNK** [comment]
I don't think it worked. Looks the same on my PC

image

**Comment by guardrex** [comment]
Did you open the internal review topic? I don't see the style applied there. Try hitting refresh, too.

**Comment by guardrex** [comment]
It should work because the build system doesn't touch our tags (manually entered into docs).

**Comment by JamesNK** [comment]
That is the internal link, and I did a hard refresh to make sure.

**Comment by guardrex** [comment]
Hum ..... that's strange. Let's wait for @scottaddie to take a look. We put tags into tables from time-to-time, and the build system leaves them alone (e.g., bare returns, lists `<ul>`). Perhaps, Scott knows why this approach is failing this time around (at least in the internal build). Perhaps if we go live with it, it will work.

**Comment by Rick-Anderson** [comment]
```

The following table describes options for configuring gRPC services:</p>
--
   <table>
   <thead>
   <tr>
   <th>Option</th>
   <th>Default Value</th>
   <th>Description</th>
   </tr>
   </thead>
   <tbody>
   <tr>
   <td><code>MaxSendMessageSize</code></td>
   <td><code>null</code></td>
   <td>The maximum message size in bytes that can be sent from the server. Attempting to send a message that exceeds the configured maximum message size results in an exception.</td>
   </tr>
   <tr>
   <td><code>MaxReceiveMessageSize</code></td>
   <td>4 MB</td>
   <td>The maximum message size in bytes that can be received by the server. If the server receives a message that exceeds this limit, it throws an exception. Increasing this value allows the server to receive larger messages, but can negatively impact memory consumption.</td>
   </tr>
   <tr>
   <td><code>EnableDetailedErrors</code></td>
   <td><code>false</code></td>
   <td>If <code>true</code>, detailed exception messages are returned to clients when an exception is thrown in a service method. The default is <code>false</code>. Setting <code>EnableDetailedErrors</code> to <code>true</code> can leak sensitive information.</td>
   </tr>
   <tr>
   <td><code>CompressionProviders</code></td>
   <td>gzip</td>
   <td>A collection of compression providers used to compress and decompress messages. Custom compression providers can be created and added to the collection. The default configured providers support <strong>gzip</strong> compression.</td>
   </tr>
   <tr>
   <td><code>ResponseCompressionAlgorithm</code></td>
   <td><code>null</code></td>
   <td>The compression algorithm used to compress messages sent from the server. The algorithm must match a compression provider in <code>CompressionProviders</code>. For the algorithm to compress a response, the client must indicate it supports the algorithm by sending it in the <strong>grpc-accept-encoding</strong> header.</td>
   </tr>
   <tr>


```

**Comment by guardrex** [comment]
*Yuck!* :smile: ... besides ... it might just break in code with spaces like that.

Really tho, the build system shouldn't be touching a **_tag_** that we drop in. I think this is likely an internal build-only problem. The way to check is to merge the PR the way that I did it and see what happens on the live site.

**Comment by guardrex** [comment]
Maybe they strip styles from `<code>` elements. They really shouldn't do that tho imo.

**Comment by Rick-Anderson** [comment]
My 89bc5d0a3ff09c57790b030f29a33637d26bb789 commit actually made it worse, so I removed it. I don't mind merging to live to see if it solves the problem, but I'm skeptical it will work on live. They're supposed to use the same build system on review and live.

@guardrex  if you'd like me to merge this to live let me know. If anyone objects speak now.

**Comment by guardrex** [comment]
I'm curious to know *why* they're changing a tag if that's what they're doing.

I'll do the merge. I have a few minutes here to see. I'll ping back with the outcome.

**Comment by Paul-Dempsey** [comment]
As you have surmised, the docs build system sanitizes tags and styles (for many good reason :-).

**Pull request merged**
