### PR TITLE
Fixed links to wrong methods

### PR DESCRIPTION
**Pull request by alex-jitbit**
The article links to controller (!) methods, but it is actually talking about ActionFilter (!) methods!!!

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Thanks @alex-jitbit! :rocket: ... I added a few API cross-link updates to this.

@serpent5, do you want to :eyes: the updates?

**Comment by serpent5** [comment]
This all looks sensible to me, but I think it'd be slightly better to link to the interface methods. This would be more consistent with some of the other links and it would match the code samples that follow, which implement the interfaces directly.

@guardrex I'll leave it for you to decide if that's actionable. This is definitely a good improvement as it is.

**Comment by guardrex** [comment]
Thanks @serpent5, are you recommending? ...

```
<xref:Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecuting%2A>
```

... to ... 

```
<xref:Microsoft.AspNetCore.Mvc.Filters.IActionFilter.OnActionExecuting%2A>
```

... and ...

```
<xref:Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecuted%2A>
```

... to ... 

```
<xref:Microsoft.AspNetCore.Mvc.Filters.IActionFilter.OnActionExecuted%2A>
```

**Comment by serpent5** [comment]
Yes, that looks right. There's also this one, I think:

```
<xref:Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync%2A>
```

... to ...

```
<xref:Microsoft.AspNetCore.Mvc.Filters.IAsyncActionfilter.OnActionExecutionAsync%2A>
```

**Comment by guardrex** [comment]
Thanks ... I'll make the updates @alex-jitbit.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
