### PR TITLE
Repair bad root component param guidance

### LINKED ISSUE #29009: Add additional step required for parameters to cascade from Main component
[EDIT by guardrex to fix the code blocks]

The documentation is lacking one crucial step (and another is incorrect). The steps related to editing the Main.razor file should include the following:

```razor
<Found Context="routeData">
  <CascadingValue Value="@KeypadViewModel">
    <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
  </CascadingValue>
</Found>
```

The next steps that state you need to add a private field to MainLayout.razor should be updated to:

```csharp
[CascadingParameter]
public string? KeypadViewModel { get; set; }
```

Based on my testing, this is the only way to get the value passed using the RootComponent.Parameters property to actually cascade from root. After making these changes, the parameters work as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e560e9f-cf5e-d6ab-6ba3-3bf7a45986a5
* Version Independent ID: 5e560e9f-cf5e-d6ab-6ba3-3bf7a45986a5
* Content: [Pass root component parameters in ASP.NET Core Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/root-component-parameters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/root-component-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/root-component-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #29009

Thanks @UnusualJustin! 🚀 

Let's look at this carefully because it's (obviously) a bit tricky. I think my app turned out a bit different than your suggestion, @UnusualJustin, in that you suggested a change in `MainLayout.razor` that I don't need to cascade this param. In a nutshell on the PR, the new guidance is ***only to*** ...

In the `Main` component (`Main.razor`):

* Add a parameter matching the type of the object passed to the root component:

  ```razor
  @code {
      [Parameter]
      public KeypadViewModel KeypadViewModel { get; set; }
  }
  ```

* Cascade the `KeypadViewModel` with the [`CascadingValue` component](xref:blazor/components/cascading-values-and-parameters#cascadingvalue-component). Update the `<Found>` XAML content to the following markup:

  ```xaml
  <Found Context="routeData">
      <CascadingValue Value="@KeypadViewModel">
          <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
          <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
      </CascadingValue>
  </Found>
  ```

... and ***that's it.*** There's no need to do anything with the `MainLayout` component (unless one wanted to use the cascaded value there, which we don't in this example).

*Yes! Indeed!* Please check the updated guidance on the PR carefully. I do find this a bit tricky, partially because I'm just not used to Hybrid apps yet ... *being a silly web dev!* 🤣 I'm learning tho! 👍 

***OH!*** ... and there will be another commit here in a sec. I think I want to update the sample link at the top of the article to make sure that devs find the model.

**UPDATE**: I changed my mind about cross-linking. The MAUI sample app doesn't have the file (or example) in the 7.0 version. I've placed the view model into this topic. It will be safe and stable to go this way with it.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/hybrid/root-component-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/b20f34f659434075134b2ff8cf18daf06d57e0db/aspnetcore/blazor/hybrid/root-component-parameters.md) | [Pass root component parameters in ASP.NET Core Blazor Hybrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/root-component-parameters?branch=pr-en-us-29041) |

### CODE REVIEW

**Comment by UnusualJustin** [comment]
I took a look and I agree with your approach. I had mistakenly Cascaded the value again in MainLayout, but that appears to be unnecessary. I've updated (and simplified) my project.

This is all pretty new to me as well (WPF developer here). 

Thank you for your help.

**Comment by guardrex** [comment]
Very well ... if @davidbritch is cool with the updates, I'll get this merged and live immediately.

Thanks again for the issue! In spite of all my efforts, some rotten 😈 get into the docs. I'm glad that we have devs like you around to catch and report them for immediate ***squashing*** 💀.

**Comment by davidbritch** [comment]
I was initially surprised at the no modifications to MainLayout.razor required, but now I've read the doc I understand and it all looks good to me.

**Review by davidbritch — APPROVED** [review]
LGTM!

**Pull request merged**
