### PR TITLE
Add Blazor keyboard composition events to what's new

### PR DESCRIPTION
**Pull request by tdykstra**
See https://github.com/dotnet/AspNetCore.Docs/issues/32042#issuecomment-2040200923

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/488d0f96c020c8b969e45b47c0160f8d2565efe2/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32349) |

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Thanks @tdykstra! 🎷

**Comment by guardrex** [comment]
BTW @tdykstra ... Dan would sort of like these to go live around the time of the release. Was this for Pre3? ... and sorry if I missed it ... my head has been down blasting through non-.NET 8 backlogged issues lately. I do need to catch up with the PU on anything missed for Pre3 (not much I think) and for Pre4 upcoming.

**Comment by guardrex** [comment]
Nevermind!!! Yes, Pre3 ... I see it. OK ... all good. Thanks again!

**Review by danroth27 — COMMENTED** [review]
Thanks @tdykstra!

**Pull request merged**
