### PR TITLE
Updated  the program.cs and removed the startupjavascript.cs and updated the document

### PR DESCRIPTION
**Pull request by smandia**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/Program.cs can't be changed as it's used for https://docs.microsoft.com/aspnet/core/tutorials/first-web-api
That's why I temporarily left the file name``StartupJavaScript.cs`
The project needs to compile and work.

Rename the `StartupJavaScript.cs` `ProgramJavaScript.cs` and surround it with
```
#if NEVER
#region snippet

// Code here
#endregion
#endif
```

Comment out the `Program.cs` file and `// #if NEVER` for testing. When you're done testing restore `Program.cs` file and `#if NEVER` 

This is an unusual sample that borrows the same code from another tutorial.

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
Revert Program.cs changes and follow my other changes.

**Comment by smandia** [comment]
@Rick-Anderson  I have done changes . I hope this time all is good.

**Comment by Rick-Anderson** [comment]
@smandia  OK and you tested everything and it works?

**Comment by smandia** [comment]
@Rick-Anderson I tested the sample by copying it else where and it worked .Not sure I need to test something else also.

**Comment by Rick-Anderson** [comment]
Perfect. Thanks for you good work.

**Pull request merged**
