### PR TITLE
Blazor-SignalR configuration updates

### LINKED ISSUE #26465: Add additional SignalR configuration
A couple of items to address:

* Timed-out connections: See https://github.com/dotnet/aspnetcore/issues/42778#issuecomment-1188852129 for content to add. The `serverTimeout`/`serverTimeoutInMilliseconds` settings are in the SignalR config doc, which is cross-linked, but we don't mention a `Blazor.start` config specifically outside of `configureLogging` for `configureSignalR`. Add a section on this subject, possibly via an INCLUDE file so that I can be posted to the *Host and Deploy* SignalR content and to the Blazor SignalR config article. Also, the `configureSignalR` with `Blazor.start` aspect should be mentioned *very* early, right at the top of the doc where the cross-link to SignalR config doc is provided.
* While here, we need better cross-linking for *Host and Deploy* SignalR content to the Blazor SignalR config content, possibly also doubling the sticky sessions config coverage with an INCLUDE.

Cross-ref: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-6.0#signalr-configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #26465

Brennan, this is a bit *drafty* at the moment, but it's probably worth sorting out the SignalR settings for this before I copy content for multiple versions of the content ... and even across docs, since we probably need these updates for the hosted WASM case, too.

This PR is mostly about addressing Javier's ask at ...

**Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.**
https://github.com/dotnet/aspnetcore/issues/42778#issuecomment-1188852129

There are several **permutations** of the configuration. Ultimately, I'm trying to cover both hosting models, WebSockets (primary) and Long Polling (fallback), and server/client config for when latency is spawning the reconnection UI.

The critical piece is Lines 754-828 in the *Host and Deploy* > *Server* article where the settings to avoid timeouts are covered. After that content is corrected, I'll flesh out a version of it for the WASM article (as a hosted WASM scenario).

I couldn't quite tell from the issue and API exactly which settings are required where. I probably need to **prune** one or more of them.

Since it might be easier to just look at that bit right here in a comment instead of sorting through all of the doc churn, here it is. If you let me know for this bit what's right, what's wrong, and **_what's iNsAnE_** 😵😄 ... I'll update from there and then ping you back later for a full review of the PR.

> Recommendations for global deployments to geographical data centers:
>
> \* Deploy the app to the regions where most of the users reside.
> \* Take into consideration the increased latency for traffic across continents.
> \* For Azure hosting, use the \[Azure SignalR Service](#azure-signalr-service).
>
> If a deployed app frequently displays the reconnection UI due to ping timeouts caused by Internet latency, lengthen the server and client timeouts:
> 
> \* \*\*Server\*\*
> 
>   At least double the maximum roundtrip time expected between the client and the server. Test, monitor, and revise the timeouts as needed. For the SignalR hub, set the \<xref:Microsoft.AspNetCore.SignalR.HubOptions.ClientTimeoutInterval> (default: 30 seconds), \<xref:Microsoft.AspNetCore.SignalR.HubOptions.HandshakeTimeout> (default: 15 seconds), and \<xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> (default: 15 seconds).
> 
>   For a Blazor Server app in \`Program.cs\`:
> 
>   \`\`\`csharp
>   builder.Services.AddServerSideBlazor()
>   &nbsp;&nbsp;&nbsp;&nbsp;.AddHubOptions(options =>
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;options.ClientTimeoutInterval = TimeSpan.FromSeconds(60);
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;options.HandshakeTimeout = TimeSpan.FromSeconds(30);
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;options.KeepAliveInterval = TimeSpan.FromSeconds(30);
>   &nbsp;&nbsp;&nbsp;&nbsp;});
>   \`\`\`
> 
>   For more information, see \<xref:blazor/fundamentals/signalr#circuit-handler-options-for-blazor-server-apps>.
> 
> 
> \* \*\*Client\*\*
> 
>   Typically, double the value used for the server's \<xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> to set the timeout for the client server timeout (\`serverTimeoutInMilliseconds\`, default: 30,000 milliseconds). Match the keep alive interval (\`keepAliveIntervalInMilliseconds\`, default: 15,000 milliseconds) to the server's \<xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval>. To configure the client, set the \`autostart\` attribute to \`false\` and configure the SignalR options in \[\`Blazor.start\`](xref:blazor/fundamentals/startup):
> 
>   \`\`\`html
>   \<script src="_framework/blazor.server.js" autostart="false">\</script>
>   \<script>
>   &nbsp;&nbsp;Blazor.start({
>   &nbsp;&nbsp;&nbsp;&nbsp;configureSignalR: function (builder) {
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;builder.serverTimeoutInMilliseconds = 60000;
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;builder.keepAliveIntervalInMilliseconds = 30000;
>   &nbsp;&nbsp;&nbsp;&nbsp;}
>   &nbsp;&nbsp;});
>   \</script>
>   \`\`\`
> 
>   For more information, see \<xref:blazor/fundamentals/signalr#configure-signalr-server-timeout-and-keep-alive-on-the-client>.

Those two "For more info ..." cross-links will go back to the *Fundamentals* > *SignalR* topic, where the settings are covered in a more general way, not specifically for ping timeout/latency problems. The fundamentals topic will also have cross-links to this *Host and deploy* coverage.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
My only _minor_ complaint is that the keep alive interval isn't directly related to the problem and doesn't necessarily need to be changed. If your issue is due to timeouts, then the timeouts can be increased and the keep alive intervals can stay the same. If you do change them then they should be 50% or less of the timeout values, and maybe you do want to change them at the same time as you increase the timeouts in order to reduce bandwidth.

**Comment by guardrex** [comment]
Thanks @BrennanConroy ... I'll complete the work on this within the next few days ... probably early next week, including updates to address your feedback using your language. I'll ping u back.

**Comment by guardrex** [comment]
**NOTE**: **_NO rush on this. Let's take it up next week if you like, @BrennanConroy._** I needed to wait on further JS interop (new API) just a bit longer for another PR that I was going to work this morning. Since I'm pushing that off to Monday, I was able to set it all up this morning.

To avoid serious 👁️ strain, here are the two sections now (one for Blazor Server *Host and Deploy*, one for hosted Blazor WebAssembly *Host and Deploy*). Note that the base coverage in the Blazor > *Fundamentals* > *SignalR* topic didn't change because that's just basic coverage on how to change the properties, no specific guidance is present there.

**NOTE**: I'm not going to *beautify* 🌷 the following content paste-ins. I'm rapidly running out of time this week and a bit *exhausted* and in need of a weekend break 😩. I'm just going to paste the content directly from the diff.

If the following is right ... or can be fixed up with a little more feedback ... I won't need further review of this PR. What's below is the **meat** 🍖 for the whole PR. The rest is just nits, bits, cross-links, and fluff.

## For Blazor Server ...

## SignalR configuration

Blazor Server apps use [ASP.NET Core SignalR](xref:signalr/introduction) to communicate with the browser. [SignalR's hosting and scaling conditions](xref:signalr/publish-to-azure-web-app) apply to Blazor Server apps.

Blazor works best when using [WebSockets](xref:fundamentals/websockets) as the SignalR transport due to lower latency, better reliability, and improved [security](xref:signalr/security). [Long Polling](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md#long-polling-server-to-client-only) is used by SignalR when WebSockets isn't available or when the app is explicitly configured to use Long Polling. When deploying to Azure App Service, configure the app to use WebSockets in the Azure portal settings for the service. For details on configuring the app for Azure App Service, see the [SignalR publishing guidelines](xref:signalr/publish-to-azure-web-app).

A console warning appears if Long Polling is utilized:

> :::no-loc text="Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection.":::

Recommendations for global deployments to geographical data centers:

* Deploy the app to the regions where most of the users reside.
* Take into consideration the increased latency for traffic across continents.
* For Azure hosting, use the [Azure SignalR Service](#azure-signalr-service).

If a deployed app frequently displays the reconnection UI due to ping timeouts caused by Internet latency, lengthen the server and client timeouts:

* **Server**

  At least double the maximum roundtrip time expected between the client and the server. Test, monitor, and revise the timeouts as needed. For the SignalR hub, set the <xref:Microsoft.AspNetCore.SignalR.HubOptions.ClientTimeoutInterval> (default: 30 seconds) and <xref:Microsoft.AspNetCore.SignalR.HubOptions.HandshakeTimeout> (default: 15 seconds). The following example assumes that <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> uses the default value of 15 seconds.

  > [!IMPORTANT]
  > The <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> isn't directly related to the reconnection UI appearing. The <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> doesn't necessarily need to be changed. If the reconnection UI appearance issue is due to timeouts, the <xref:Microsoft.AspNetCore.SignalR.HubOptions.ClientTimeoutInterval> and <xref:Microsoft.AspNetCore.SignalR.HubOptions.HandshakeTimeout> can be increased and the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> can remain the same. The important consideration is that if you change the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval>, make sure that the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> value is 50% or less of the timeout values and that the `keepAliveIntervalInMilliseconds` on the client matches the server setting.
  >
  > In the following example, <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> is set to the default value of 15 seconds and shown for demonstration purposes in case you need to change the value.

  For a Blazor Server app in `Program.cs`:

  ```csharp
  builder.Services.AddServerSideBlazor()
      .AddHubOptions(options =>
      {
          options.ClientTimeoutInterval = TimeSpan.FromSeconds(60);
          options.HandshakeTimeout = TimeSpan.FromSeconds(30);
          options.KeepAliveInterval = TimeSpan.FromSeconds(15);
      });
  ```

  For more information, see <xref:blazor/fundamentals/signalr#circuit-handler-options-for-blazor-server-apps>.

* **Client**

  Typically, double the value used for the server's <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> to set the timeout for the client's server timeout (`serverTimeoutInMilliseconds`, default: 30,000 milliseconds). To configure the client, set the `autostart` attribute to `false` and configure the SignalR options in [`Blazor.start`](xref:blazor/fundamentals/startup).

  > [!IMPORTANT]
  > The `keepAliveIntervalInMilliseconds` isn't directly related to the reconnection UI appearing. The `keepAliveIntervalInMilliseconds` doesn't necessarily need to be changed. If the reconnection UI appearance issue is due to timeouts, the `serverTimeoutInMilliseconds` can be increased and the `keepAliveIntervalInMilliseconds` can remain the same. The important consideration is that if you change the `keepAliveIntervalInMilliseconds`, make sure that the `keepAliveIntervalInMilliseconds` value is 50% or less of the timeout value and that the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> on the server matches the client setting.
  >
  > In the following example, `keepAliveIntervalInMilliseconds` is set to the default value of 15 seconds and shown for demonstration purposes in case you need to change the value.

  For a Blazor Server app in `Pages/_Host.cshtml`:

  ```html
  <script src="_framework/blazor.server.js" autostart="false"></script>
  <script>
    Blazor.start({
      configureSignalR: function (builder) {
        builder.serverTimeoutInMilliseconds = 60000;
        builder.keepAliveIntervalInMilliseconds = 15000;
      }
    });
  </script>
  ```

  For more information, see <xref:blazor/fundamentals/signalr#configure-signalr-server-timeout-and-keep-alive-on-the-client>.

For more information on SignalR configuration, see <xref:blazor/fundamentals/signalr>.

## For Blazor WebAssembly ...

## SignalR configuration

When a developer has implemented [ASP.NET Core SignalR](xref:signalr/introduction) in a hosted Blazor WebAssembly app, [SignalR's hosting and scaling conditions](xref:signalr/publish-to-azure-web-app) apply.

Blazor works best when using [WebSockets](xref:fundamentals/websockets) as the SignalR transport due to lower latency, better reliability, and improved [security](xref:signalr/security). [Long Polling](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md#long-polling-server-to-client-only) is used by SignalR when WebSockets isn't available or when the app is explicitly configured to use Long Polling. When deploying to Azure App Service, configure the app to use WebSockets in the Azure portal settings for the service. For details on configuring the app for Azure App Service, see the [SignalR publishing guidelines](xref:signalr/publish-to-azure-web-app).

A console warning appears if Long Polling is utilized:

> :::no-loc text="Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection.":::

Recommendations for global deployments to geographical data centers:

* Deploy the app to the regions where most of the users reside.
* Take into consideration the increased latency for traffic across continents.
* For Azure hosting, use the [Azure SignalR Service](#azure-signalr-service).

If a deployed app frequently displays the reconnection UI due to ping timeouts caused by Internet latency, lengthen the server and client timeouts:

* **Server**

  At least double the maximum roundtrip time expected between the client and the server. Test, monitor, and revise the timeouts as needed. For the SignalR hub, set the <xref:Microsoft.AspNetCore.SignalR.HubOptions.ClientTimeoutInterval> (default: 30 seconds) and <xref:Microsoft.AspNetCore.SignalR.HubOptions.HandshakeTimeout> (default: 15 seconds). The following example assumes that <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> uses the default value of 15 seconds.

  > [!IMPORTANT]
  > The <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> isn't directly related to the reconnection UI appearing. The <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> doesn't necessarily need to be changed. If the reconnection UI appearance issue is due to timeouts, the <xref:Microsoft.AspNetCore.SignalR.HubOptions.ClientTimeoutInterval> and <xref:Microsoft.AspNetCore.SignalR.HubOptions.HandshakeTimeout> can be increased and the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> can remain the same. The important consideration is that if you change the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval>, make sure that the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> value is 50% or less of the timeout values and that the `keepAliveIntervalInMilliseconds` on the client matches the server setting.
  >
  > In the following example, <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> is set to the default value of 15 seconds and shown for demonstration purposes in case you need to change the value.

  For a hosted Blazor WebAssembly app in `Program.cs` of the **:::no-loc text="Server":::** project:

   ```csharp
   builder.Services.AddSignalR(options =>
   {
       options.ClientTimeoutInterval = TimeSpan.FromSeconds(60);
       options.HandshakeTimeout = TimeSpan.FromSeconds(30);
       options.KeepAliveInterval = TimeSpan.FromSeconds(15);
   });
   ```

  For more information, see <xref:blazor/fundamentals/signalr#circuit-handler-options-for-blazor-server-apps>.

* **Client**

  Typically, double the value used for the server's <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> to set the timeout for the client's server timeout (`serverTimeoutInMilliseconds`, default: 30,000 milliseconds). To configure the client, set the `autostart` attribute to `false` and configure the SignalR options in [`Blazor.start`](xref:blazor/fundamentals/startup).

  > [!IMPORTANT]
  > The `keepAliveIntervalInMilliseconds` isn't directly related to the reconnection UI appearing. The `keepAliveIntervalInMilliseconds` doesn't necessarily need to be changed. If the reconnection UI appearance issue is due to timeouts, the `serverTimeoutInMilliseconds` can be increased and the `keepAliveIntervalInMilliseconds` can remain the same. The important consideration is that if you change the `keepAliveIntervalInMilliseconds`, make sure that the `keepAliveIntervalInMilliseconds` value is 50% or less of the timeout value and that the <xref:Microsoft.AspNetCore.SignalR.HubOptions.KeepAliveInterval> on the server matches the client setting.
  >
  > In the following example, `keepAliveIntervalInMilliseconds` is set to the default value of 15 seconds and shown for demonstration purposes in case you need to change the value.

  For a hosted Blazor WebAssembly app in `wwwroot/index.html` of the **:::no-loc text="Client":::** project:

  ```html
  <script src="_framework/blazor.webassembly.js" autostart="false"></script>
  <script>
    Blazor.start({
      configureSignalR: function (builder) {
        builder.serverTimeoutInMilliseconds = 60000;
        builder.keepAliveIntervalInMilliseconds = 15000;
      }
    });
  </script>
  ```

  For more information, see <xref:blazor/fundamentals/signalr#configure-signalr-server-timeout-and-keep-alive-on-the-client>.

For more information on SignalR configuration, see <xref:blazor/fundamentals/signalr>.

**Comment by guardrex** [comment]
@BrennanConroy ... This looks good. I used your language. I don't think it requires further review. I'll take community feedback on it going forward.

**Pull request merged**
