### PR TITLE
Blazor - Update component ref text and examples ctnd

### PR DESCRIPTION
**Pull request by hakenr**
continuation of #31866

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/25c22a55010b7979f479467cee3b4348a62db33a/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-31868) |

### CODE REVIEW

**Comment by hakenr** [comment]
@guardrex Sorry, the tooling didn't allow me to make code suggestions (?) to #31866, so I created a continuation PR. 😇

**Comment by hakenr** [comment]
You will probably have to polish the English language, but I hope you get my intention.
* remove the `!' (this is just for nullable references here?) as it does not bring any runtime value here
* express what to avoid
* give examples how to use the captured component reference correctly

**Comment by guardrex** [comment]
Let's take this up on the original PR. If you can't file a GH suggestion for a line, then use quote markdown ...

> My lingo

... to ...

> Your lingo

**Comment by hakenr** [comment]
OK

**Pull request closed without merging**
