### PR TITLE
Linkfix: ASP.NET (2021-06)

### PR DESCRIPTION
**Pull request by v-kents**
This PR is the result of running a Link Repair script on the included content. This script is primarily being run to cleanup links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes:

- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
  - This also includes cleanup of the appended query string for MSDN (redirectedfrom=MSDN).
- Fixes articles that are redirected in `.openpublishing.redirection.json` and updates the link to the current final location (this has a lot of customer usability fixes).

Please note the [Contributor Guide: Links](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master) has been updated with the following link-type preference order:

```
By order of preference, links hosted on Docs should be Relative if they are in the same repository and docset. If they are in a different docset, even if in the same repository, they should be Site Relative. Links to content hosted on Docs shouldn't use a complete URL, otherwise known as Fully Qualified Domain Names (FQDN). Using a complete URL from Docs to other content on Docs will cause that link to be non-functional in air-gap environments.
```

### CODE REVIEW

**Comment by guardrex** [comment]
@v-kents ... We can't merge this. Most (all?) of these are in `readme.md` files that load on the GH domain. Relative links will break from there. I recommend that you provide an exception for `readme.md` files.

**Review by guardrex — CHANGES_REQUESTED** [review]
See comment. ☝️

**Review by Rick-Anderson — APPROVED** [review]

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
Fix items mentioned by @guardrex

**Comment by guardrex** [comment]
I think all of the files here are `readme.md` files; therefore, there's nothing to fix. This is a **_won't-fix_** scenario.

WRT the link tooling in use tho: I recommend filtering out `readme.md` files and writing it to replace with XREF-UIDs. Anyway, that's not germane to the PR. It's just a side suggestion.

**Comment by v-kents** [comment]
closing per @guardex's comments. I'll see about getting the tool to ignore readme files in the future (at the very least for this repo)

**Pull request closed without merging**
