### PR TITLE
.NET 9 Update: RP Tutorials Series

### LINKED ISSUE #32693: "Code First" language ... Is it still a thing?
### Description

Wade, I noticed something else that's worth a mention ...

I went into the EF Core docs while working on the upcoming Blazor tutorial to look at a few things, and it looks like the EF folks (and doc cats) dropped "Code First"/"code-first" language when they moved from EF6 to EF Core. It's also possible that they used that language with EF Core in the past and dropped it at some point. Anyway, I don't see them using that language in EF Core docs today. However, the tutorials here contain quite a bit of "code first" language.

I'm going to avoid it for the Blazor tutorial. If you plan to keep it, please close this, as it's just a passing notion for consideration.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/new-field.md

### Document ID

24699fe5-9744-1796-0798-f7b211ec0f2f

### Article author

@wadepickett

---
[Associated WorkItem - 270946](https://dev.azure.com/msft-skilling/Content/_workitems/edit/270946)

### LINKED ISSUE #32694: The `Movie` model class changes between tutorial parts
### Description

The `Movie` model in this part of the tutorial is different than the one shown earlier in the series at ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio#add-a-data-model

... here's the delta section ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio#adding-a-rating-property-to-the-movie-model

NRTs before, no NRTs here.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/new-field.md

### Document ID

24699fe5-9744-1796-0798-f7b211ec0f2f

### Article author

@wadepickett

---
[Associated WorkItem - 261112](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261112)

### LINKED ISSUE #32707: .NET 9:Razor Pages Tutorial Series and improvements
### Description

- [ ] Update the entire series, instruction screenshots and code samples for .NET 9.
- [ ] Consider how we might address the problem of having two commands in a row to copy/paste, but the 2nd only runs if you notice to hit the return key again such as for `Add-Migration` and `Update-Database`.  

Rick suggested considering an innocuous command at the end such as:
`Echo Update complete`.
`Get-Date`
`$null = $null`
`Write-Host "commands complete"`

Luke considered splitting the command instruction and instead of grouping the information on what the commands do, separating them between the two commands for each. 

There is also the possibility of joining commands with && so an additional return is not required but that might cause some confusion. See 5-23-24 9:02 thread discussion. 

Check in with what Luke decided to do for the same issue for Blazor. The same problem exists for the Razor Pages tutorial series as well.

- [ ] Minor item but don't forget: The overview page needs an updated version of the example app artwork copyright shows 2022.  

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md

### Document ID

5492c641-af15-64b8-beaa-ddf511be73e6

### Article author

@wadepickett

---
[Associated WorkItem - 261117](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261117)

### LINKED ISSUE #32932: Include/add-EF-NuGet-SQLite-CLI-7.md: Create new version for 9 with prerelease
For:
aspnetcore/includes/add-EF-NuGet-SQLite-CLI-7.md

Create new ones for version 8 and 9.

For v9 include --prerelease for the packages.  (Not for the global tools).

---
[Associated WorkItem - 270942](https://dev.azure.com/msft-skilling/Content/_workitems/edit/270942)

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #32707
Fixes #32693
Fixes #32694
Fixes #32850
Fixes #32932

- Update all 9 Tutorials for Razor Pages Getting Started Series.  Instructions, code app samples and screenshots.
- Used the latest .net project template and updated the samples accordingly. Verified with dev team the template is not likely to change again before GA.
- Updated Include/add-EF-NuGet-SQLite-CLI-7.md nuget commands for v8 and then v9 for --prerelease.
- Remove VS for Mac tab instructions.
- Re-test series for VS Code on macOS and Linux with Preview NuGet packages for .NET 9.
- Re-test series for VS on Windows with Preview NuGet packages for .NET 9.
- Improvements based on customer feedback.
- Code samples snippets and their links in the tutorials were a bit randomly in both the SnapshotSample and the final sample over the years.  I cleaned this up and moved all snapshot snippets to the SnapshotSample for version 9  going forward.  The final sample includes just the final code, although Program.cs has two different #define groups you can run.  One for SQL Server or one for SQLite.
- Did side by side comparison for all tutorials and both VS and VS Code tabs to verify code highlights, ranges and images were displaying the same where intended vs updated where they needed to change.

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/da1.md) | [Part 5, update the generated pages in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/index.md) | [Tutorial: Create a Razor Pages web app with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/index?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/model.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/new-field.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/page.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/razor-pages-start.md) | ["Tutorial: Get started with Razor Pages in ASP.NET Core"](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/wwwroot/lib/jquery-validation/LICENSE.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/wwwroot/lib/jquery-validation/LICENSE.md) | [aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/wwwroot/lib/jquery-validation/LICENSE](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/wwwroot/lib/jquery-validation/LICENSE?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample9/wwwroot/lib/jquery-validation/LICENSE.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample9/wwwroot/lib/jquery-validation/LICENSE.md) | [aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample9/wwwroot/lib/jquery-validation/LICENSE](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/snapshot_sample9/wwwroot/lib/jquery-validation/LICENSE?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/search.md) | [Part 6, add search to ASP.NET Core Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/sql.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?branch=pr-en-us-32850) |
| [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/2be3591411a3526a53737cba18664d0b13776878/aspnetcore/tutorials/razor-pages/validation.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?branch=pr-en-us-32850) |

</details>

### CODE REVIEW

**Comment by wadepickett** [comment]
WIP:  Initial commit:  First 3 of the tutorial series in so far.  Sample Apps will still change extensively as I get through the rest.

**Comment by Rick-Anderson** [comment]
@wadepickett  you should check with the PU and verify their won't be any template changes for RP and MVC.

**Comment by wadepickett** [comment]
@Rick-Anderson, yes thanks.  I verified with Dan.  I am already using the latest and there are no additional significant changes in the plan.  Although I will keep watching the repo and the [feature-templates](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Faspnetcore%2Fissues%3Fq%3Dis%253Aopen%2Bis%253Aissue%2Blabel%253Afeature-templates&data=05%7C02%7Cwpickett%40microsoft.com%7C42c22c2c2f6945bd43fb08dc9138c967%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638544920291406385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=27RNqiAu6EBQhpd99n3A35d%2B0T7%2FpPz55A6O2NzWXfw%3D&reserved=0) label.

**Review by tdykstra — APPROVED** [review]
This is great work! I just noted a couple of nits.

**Pull request merged**
