### PR TITLE
https://github.com/dotnet/AspNetCore.Docs/issues/11801

### LINKED ISSUE #11801: Guidance on how to log to a message queue for slow data stores
Can you give me more precision regarding this sentence : "If your logging data store is slow, don't write to it directly. Consider writing the log messages to a fast store initially, then move them to the slow store later. For example, log to a message queue that's read and persisted to slow storage by another process."

I want to store log in SQL server, so I suppose it's a slow data store. So I would like what you mean by "log to a message queue".  Do you reffer to RabbitMQ for example ?

Yours sincerely,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#built-in-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by sguitardude**
Fixes #11801

I've tried to create a sample that synchronously adds log messages to an in-memory queue and has a background worker pull the messages out of the queue to do the asynchronous work of pushing data to SQL Server.

If the team agrees, then we can go back and update this article
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#aspnet-core-and-ef-core-categories

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19497) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19497) before we can accept your contribution.<br/><br/>:x: sguitardude [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=19497)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=19497) it.</sub>

**Comment by guardrex** [comment]
Hello @sguitardude ... It's been challenging for the small team to keep samples up-to-date ... see https://github.com/dotnet/AspNetCore.Docs/issues/5495. In this case, third party providers are heavily recommended, and they use this (or similar) approaches for SQL Server. For example, I know Serilog accumulates and batch-writes to SQL Server. They'll let you know, but don't take it the wrong way if they have to decline. If they can't accept, it's probably just going to be for staffing/maintenance reasons in light of the popularity of third-party providers.

**Comment by sguitardude** [comment]
No worries.  I'll check out Serilog and other ways to contribute.

**Comment by Rick-Anderson** [comment]
@sguitardude  can you put this on your GitHub? If so, I can tweet it.

**Pull request closed without merging**
