### PR TITLE
Blazor DynamicComponent coverage

### LINKED ISSUE #22005: Blazor DynamicComponent
Good morning,

I'm not sure your timeline in documenting the `DynamicComponent` released with .NET 6 Preview 1, but I can lend a hand if you'd like (I [wrote about it](https://daveabrock.com/2021/04/08/blazor-dynamic-component) just now and it seems to be straightforward).

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #22045 
Fixes #22005 

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-6.0&branch=pr-en-us-22984)

@daveabrock ... See how this is shaping up thus far.

* Follows your general blog post layout.
* Loosely follows your examples. However, I wasn't clear on why you had the types in the metadata for the passing parameters piece. You don't have the full implementation shown in your post, so I'm not sure how you use your metadata dictionary. I just keep the parameters and the name (for display) in the metadata and generate the options from it. Also, the naming might still be a bit dodgy ... I'm still working on that a bit.
* I'm not on the new bits yet. I tend to adopt preview releases starting with RC1 (for stability in what I'm documenting). This merely *looks like* 👀 it will work ... *maybe* 😆 ... or not 💥😆.

### CODE REVIEW

**Comment by daveabrock** [comment]
Hey Rex, sorry for the delay but this looks great! Yeah, a lot of it was early days when I wrote it so I didn't expand on a lot of topics. As such, if this deviates from the post (which is no big deal!) no worries about taking my name off the byline. 😀

**Comment by guardrex** [comment]
It can stay as long as you like. This is based on your post. If you reach a point that you want off of this (and the CSS isolation topic), let me know. I think the MVP folks like to see this sort of thing, so I recommend leaving it at least until you confirm keeping that status.

**Comment by daveabrock** [comment]
Thanks so much - you're too good to me. I appreciate that.

**Comment by guardrex** [comment]
I'll merge this shortly after making one more edit pass. I'll ask the PU to look later during RC1. They're all 🏃🏃🏃😅 right now working on 6.0 things.

**Comment by guardrex** [comment]
@daveabrock ... Ok ... I think looks fine for a *draft-ish* preview doc. I'll come back to this at RC1 to make sure that it **_actually works_** 😄 (I hate when I put up docs that *don't work.* 🤦‍♂️) I'll also review+edit the whole thing at that time. I'll leave this here for a few hours to give you a chance to run a final 👁️ over it this morning and then merge it.

**Comment by daveabrock** [comment]
Looks good to me, @guardrex!

**Comment by guardrex** [comment]
Thanks @daveabrock! 🎷

**Pull request merged**
