### PR TITLE
Add NBomber to list of load-testing tools

### PR DESCRIPTION
**Pull request by inech**
Hi,

Please add NBomber to the list of load-testing tools

> Very simple load testing framework for Pull and Push scenarios. It's 100% written in F# and targeting .NET Core and full .NET Framework.

Github: https://github.com/PragmaticFlow/NBomber
Docs: https://nbomber.com/docs/index.html

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]
@guardrex  you OK with these?

**Comment by guardrex** [comment]
I'm not familiar with them, and I'm not sure what the editorial policy is for linking to external frameworks. For Blazor, we're sending most devs to *Awesome Blazor*, and we cross-link to that. That's all I know. DR didn't address third-party for non-Blazor scenarios.

**Comment by Rick-Anderson** [comment]
@guardrex  see https://docs.microsoft.com/en-us/aspnet/core/test/load-tests?view=aspnetcore-5.0#third-party-tools

Is a list of 3rd party tools.

**Comment by guardrex** [comment]
Yes, I know. I'm just saying that DR didn't want these types of links or link lists generally in Blazor docs but didn't offer any advice on what to do elsewhere.

**Comment by Rick-Anderson** [comment]
@javiercn can we add NBomber to list of load-testing tools?

**Pull request merged**
