### PR TITLE
Fix Powershell script in /fundamentals/host/platform-specific-configuration sample

### PR DESCRIPTION
**Pull request by abeven**
The `AppendToEnvironmentVariable` function in `Deploy.ps1` is incorrectly setting environment variables to `StartupDiagnostics` instead of the supplied value when setting instead of appending.

### CODE REVIEW

**Review by Rick-Anderson — COMMENTED** [review]
@guardrex  this looks correct to me.

**Review by guardrex — CHANGES_REQUESTED** [review]
Yes, it came from Pavel that way at ...

https://github.com/dotnet/AspNetCore.Docs/pull/9478/files#diff-db568676869a7e0472c7fd73bc66bb926f38d57a32d9f973db1c3812b7bf03c9R5

... but I agree with the update. This code breaks for `DOTNET_ADDITIONAL_DEPS` and `DOTNET_SHARED_STORE` if the vars don't exist ... it gives them the wrong value.

@abeven ... Could you add one more update to this PR? Fix it here, too, back in the 2.x sample ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/platform-specific-configuration/samples/2.x/RuntimeStore/deploy.ps1#L5

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25803) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25803) before we can accept your contribution.<br/><br/>:x: abeven [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=25803)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=25803) it.</sub>

**Review by abeven — COMMENTED** [review]
All set!

**Review by guardrex — APPROVED** [review]
Thanks @abeven! :rocket:

**Pull request merged**
