### PR TITLE
Add breaking changes for claims mapping in .NET 8

### PR DESCRIPTION
**Pull request by damienbod**
fixes https://github.com/dotnet/AspNetCore.Docs/issues/30935

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/security/authentication/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/255de2fe54ba855fecc481afa75ca65e324994e8/aspnetcore/security/authentication/claims.md) | [Mapping, customizing, and transforming claims in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?branch=pr-en-us-30939) |
| [aspnetcore/security/authentication/claims/sample8/WebRPmapClaims/wwwroot/lib/jquery-validation/LICENSE.md](https://github.com/dotnet/AspNetCore.Docs/blob/255de2fe54ba855fecc481afa75ca65e324994e8/aspnetcore/security/authentication/claims/sample8/WebRPmapClaims/wwwroot/lib/jquery-validation/LICENSE.md) | [aspnetcore/security/authentication/claims/sample8/WebRPmapClaims/wwwroot/lib/jquery-validation/LICENSE](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/claims/sample8/WebRPmapClaims/wwwroot/lib/jquery-validation/LICENSE?branch=pr-en-us-30939) |

### CODE REVIEW

**Review by guardrex — APPROVED** [review]
Thanks @damienbod! 🎸 ... I just touched a little spacing and added some returns on some of the files to make GH happy (although there are probably a few more that I didn't fix in the hidden files on the diff).

The article doesn't describe any actual breaking changes. I suppose this is just an update for the line ...

```csharp
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
```

... to ...

```csharp
JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear();
```

If you want to roll in a versioned remark on just the API name, here are the cross-links for those ...

* \<xref:System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.DefaultInboundClaimTypeMap?displayProperty=nameWithType>
* \<xref:Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.DefaultInboundClaimTypeMap%2A?displayProperty=nameWithType>

**Review by Rick-Anderson — APPROVED** [review]

**Comment by damienbod** [comment]
@Rick-Anderson @guardrex 

When viewing the preview 8 version, I see both code snippets. Only 1 should be displayed but the monikers look correct to me.

Do you see a problem here?

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0#claims-namespaces-default-namespaces

Greetings Damien

**Comment by damienbod** [comment]
@guardrex 

https://github.com/dotnet/AspNetCore.Docs/pull/30956

found it...

**Comment by luccawilli** [comment]
Is it possible to add the breaking changes notice also to the Main-"Breaking changes in .NET8" Page?
https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0

**Comment by guardrex** [comment]
@luccawilli ... Open an issue for the request from the bottom of that article using the **Open a documentation issue** link..

**Pull request merged**
