### PR TITLE
Modify nginx proxy_pass address

### LINKED ISSUE #21944: Modify nginx proxy_pass address
[EDIT by guardrex to add the metadata. @FatTigerWang, please use the **This Page** feedback button and form at the bottom of the English-US topic to open issues on the docs repo, which attaches the metadata and pings the topic author automatically.]

# Issue description

In [Configure Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx) Part，It is recommended to modify `proxy_pass http://localhost:5000` to `proxy_pass http://127.0.0.1:5000`, because proxy `localhost` will cause `nginx` to proxy `IPv6` at the same time, and many applications (especially Local applications that require proxy) will only listen on the `IPv4` address, so you will see this error in the error log of `nginx`：
```txt
 [error] 2195#0: *2645 connect() failed (111: Connection refused) while connecting to upstream, client: ipaddress, server: domain, request: "GET /path HTTP/1.1", upstream: "http://[::1]:5000/path", host: "domain", referrer: "domain"
```
You can see `Nginx` proxyed the local `IPv6` port and displayed an error: `upstream: "http://[::1]:5000/path"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by FatTigerWang**
Modify nginx proxy_pass address Fixes #21944

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21945) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21945) before we can accept your contribution.<br/><br/>:x: FatTigerWang [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21945)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=21945) it.</sub>

**Comment by guardrex** [comment]
Thanks @FatTigerWang ... I've pinged the PU to take a look.

**Comment by shirhatti** [comment]
> It is recommended to modify proxy_pass http://localhost:5000 to proxy_pass http://127.0.0.1:5000, because proxy localhost will cause nginx to proxy IPv6 at the same time, and many applications (especially Local applications that require proxy) will only listen on the IPv4 address, so you will see this error in the error log of nginx：

I'm unconvinced we need to make this change. ASP.NET Core by default binds to both IPv4 and IPv6 on loopback. If you've gone out of your way to change what you're binding to, then by all means change your proxy configuration as well. I don't think this warrants changing the default recommendation.

@halter73 in case he disagrees with my assessment

**Comment by halter73** [comment]
Is there any harm in using `127.0.0.1` instead of `localhost` in the docs? 

While I agree this only matters is Kestrel was explicitly told to bind to `127.0.0.1` and not `localhost`, I don't see the downside of this change. If it helps one developer who might not be aware of the distinction between the two, maybe it's worth it.

**Comment by shirhatti** [comment]
Fair enough. (Though I'll be chuffed if we see another issue a few years from now where someone only has IPv6 enabled 😛)

**Review by shirhatti — APPROVED** [review]

**Comment by FatTigerWang** [comment]
The problem is that if I am a novice, I will configure according to the official nginx configuration, but I will see an error in the nginx error log later, which makes me at a loss

**Pull request merged**
