### PR TITLE
Update virtualization.md to include RefreshDataAsync

### PR DESCRIPTION
**Pull request by qin-guan**
I added documentation for the use of `RefreshDataAsync` on `Virtualize`, the related PR and issue from the dotnet repository is:

[PR](https://github.com/dotnet/aspnetcore/pull/26177/files#diff-18b60327e5f9093f24b96ed344268589R101-R107)
[Issue](https://github.com/dotnet/aspnetcore/issues/26110)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21146) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21146) before we can accept your contribution.<br/><br/>:x: qin-guan [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=21146)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=21146) it.</sub>

**Comment by guardrex** [comment]
Hello @qin-guan ... It's best to open an issue to discuss potential changes to the docs for anything outside of a patch update. 

Covering `RefreshDataAsync` has already been merged on https://github.com/dotnet/AspNetCore.Docs/pull/21136 and should go live shortly.

An example isn't required because this is a simple scenario ... one just calls it to refresh data from the `ItemsProvider`. I don't think we want to lengthen the document this much for such a simple scenario.

**Comment by qin-guan** [comment]
Ah, sorry. I did not notice the PR. Thanks for taking the time :)

**Comment by guardrex** [comment]
If doc issues come in on it where devs don't see it or run into trouble with it, then *yes* ... I'd feel like we need a full section. Let's take feedback for a while and see if devs open issues on it. I'll cross-link this PR to my tracking issue so that I don't lose track of this in the event that we need something like this in the future.

**Pull request closed without merging**
