### PR TITLE
WIP - Update Web API tutorial for VS 2022 for Mac

### PR DESCRIPTION
**Pull request by jongalloway**

### CODE REVIEW

**Comment by jongalloway** [comment]
@Rick-Anderson FYI - Starting a PR to add VSM 2022 / .NET 6 to this tutorial.

**Comment by wadepickett** [comment]
@jongalloway , OK if I jump in to help on this draft?  Thanks for getting all the new screenshots and includes in!

**Comment by wadepickett** [comment]
Very helpful!  Thanks for getting it going John!

**Comment by wadepickett** [comment]
Getting the doc build to kick in again by closing and re-opening...

**Pull request closed without merging**
