### PR TITLE
v9 Update: Min Web API Tutorial

### LINKED ISSUE #32706: .NET 9 Update: Min Api Tutorial and improvements
### Description

While updating and testing for .NET 9:

- [ ] Update the instruction, screenshots and code samples for .NET 9

- [ ] Add a note about the `difference between using the `web` template vs the `webapi` template (and the VS template name counterparts)

- [ ] Remove VS for mac tabbed content.

This tutorial purposely uses an empty project without any example code or control structure.

For .NET 7 the webapi template included controllers and example code by default. At the same time the .Net 7 the web template was simplified in its project structure to only include minimal necessary components, did not include sample code and was used for creating minimal API's going forward and this topic was updated accordingly.

Then for .Net 8 the webapi template created a minimal API by default without controllers, but it included example code, and this tutorial starts from scratch to show what is really needed beyond an empty web project.

Based on community feedback using the `web` template instead of `webapi` without an explanation is confusing.
For a more recent example see PR discussion #32700,

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Document ID

ab408035-6313-a183-9940-32de00e0e977

### Article author

@wadepickett

---
[Associated WorkItem - 261118](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261118)

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #32706

.NET 9 update for Min Web API Tutorial.
Update instructions, screenshots and its 8 app samples for both VS and VS Code.
Remove VS for Mac tabs/instruction.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/69f11ea06e5577fe8b9b776146601529f3021dfe/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-32943) |

### CODE REVIEW

**Comment by wadepickett** [comment]
Build has not updated with the new content, still showing Mac tabs which are gone for example. 
Closing and reopening to force new build.

**Comment by wadepickett** [comment]
@tdykstra, can you spot the problem with tabs on this PR?  I can't see what I am doing wrong.  Verson 9 that was reduced to 2 tabs is fine.   Setting the version selector to 3.1 to 8 for any of those versions, the 3 tab combinations are not working, it drops more than one tab in the URL and as a result, both tabs show as highlighted.

I checked the prework PR I did for this and all three tabs work, so it is something I introduced here.  But I have not touched versions 3.1 through 8.

**Comment by wadepickett** [comment]
@tdykstra, there is something fundamental about how tabs work for our architecture of file versioning by include that I must not be aware of.

By reducing to two tabs instead of 3 and excluding VS for Mac I have created a problem:
the tabs work for this version 9 topic fine, but then the earlier versions 3.1-8 (which I didn't touch) no longer have tabs working, one of them stays highlighted as you select a different one.

Do you know of a way to work around this problem?

**Comment by wadepickett** [comment]
@tdykstra, removed VS for Mac specific tabs for all versions as discussed.  All works great now, ready for review.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
