### PR TITLE
Return DTO with an identifier generated by EF

### PR DESCRIPTION
**Pull request by ganesanarun**
In the DTO approach, right now the response from create API does not return the id, this change would fix it.

### CODE REVIEW

**Comment by ganesanarun** [comment]
I understand that this tutorial is about asp.net core minimal API, I can't resist ask, should we introduce the Deconstruct method in Todo class?

**Comment by Rick-Anderson** [comment]
@wadepickett  be sure to test original code and this change.

**Review by wadepickett — CHANGES_REQUESTED** [review]
The suggested change would not compile as is.

**Comment by wadepickett** [comment]
@Rick-Anderson and @ganesanarun,  I may not be catching on to what needs to be done here.  id does return with the code as it already was. 

{
    "id": 1,
    "name": null,
    "isComplete": false
}

The changed line suggested in this PR at this moment however will not compile, nor would I expect it to.  todo is not defined.

**Comment by ganesanarun** [comment]
I agree that 

return TypedResults.Created($"/todoitems/{todoItem.Id}", new TodoItemDTO(todo)); should be 
TypedResults.Created($"/todoitems/{todoItem.Id}", new TodoItemDTO(todoItem)); 

but I don't think the current create API returns id at all.

anyway it's up to you folks. @Rick-Anderson @wadepickett

**Pull request closed without merging**
