### PR TITLE
Improve Nuget package cross-links

### LINKED ISSUE #33688: Improve NuGet package link text
Improve links to include "NuGet package" in the link text to distinguish the links for NuGet.org over API docs.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #33688 

@Rick-Anderson @tdykstra @wadepickett ... Seems better to have "NuGet package" in the link text for Nuget.org cross-links, which makes it clearer that the link isn't to an API (namespace) article.

There weren't too many to update in Blazor docs (14 instances), but I see 103 spots across 59 files in the main doc set. Would you like me to add them to this PR?

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-33689) |
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-33689) |
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/fundamentals/configuration.md) | [ASP.NET Core Blazor configuration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?branch=pr-en-us-33689) |
| [aspnetcore/blazor/hybrid/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/hybrid/troubleshoot.md) | [Troubleshoot ASP.NET Core Blazor Hybrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/troubleshoot?branch=pr-en-us-33689) |
| [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/hybrid/tutorials/windows-forms.md) | [aspnetcore/blazor/hybrid/tutorials/windows-forms](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?branch=pr-en-us-33689) |
| [aspnetcore/blazor/hybrid/tutorials/wpf.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/hybrid/tutorials/wpf.md) | [Build a Windows Presentation Foundation (WPF) Blazor app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?branch=pr-en-us-33689) |
| [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/javascript-interoperability/import-export-interop.md) | [JavaScript `[JSImport]`/`[JSExport]` interop with ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?branch=pr-en-us-33689) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-33689) |
| [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/security/server/additional-scenarios.md) | [Server-side ASP.NET Core Blazor additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?branch=pr-en-us-33689) |
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/6709e7475878e008fb53ec9a9479297578b5cf8f/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [aspnetcore/blazor/security/webassembly/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-33689) |

### CODE REVIEW

**Comment by wadepickett** [comment]
@guardrex, you are right, that is very helpful to add.  Sure, if you would like to add the rest, that would be awesome!

**Comment by guardrex** [comment]
Great ... I'll take care of it Tuesday morning.

**Comment by guardrex** [comment]
I just took a further look. Unfortunately, this isn't going to work out in a reasonable amount of time. There are another 100 updates to make just for Blazor where the link format is ...

> blah blah blah ... \[\`The.Package.Name\`](...) package ... blah blah blah

... and then the whole doc set there are hundreds of the "NuGet package" and "package" links. Find and replace won't work. This type of change has to be performed manually. This change isn't worth the effort. Closing as a `won't fix` scenario. 😢

**Comment by Rick-Anderson** [comment]
@guardrex  I agree. AFAIK, we've never had a complaint on NuGet pkg vs API.

**Comment by guardrex** [comment]
It wasn't so much about a complaint ... just an observation that our NuGet package links look a lot like API doc links. No worries ... this ship has already sailed and it is a very minor thing to consider.

**Pull request closed without merging**
