### PR TITLE
Fixed capitalization of Program.cs on line 18

### PR DESCRIPTION
**Pull request by stacklysm**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24196) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24196) before we can accept your contribution.<br/><br/>:x: stacklysm [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=24196)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=24196) it.</sub>

**Review by guardrex — APPROVED** [review]
Thanks @stacklysm! :rocket:

**Comment by guardrex** [comment]
Oh, @stacklysm ... Could you please sign the CLA :point_up:. We can't accept this without it.

**Comment by stacklysm** [comment]
Done, signed up the CLA. Glad to help!

**Pull request merged**
