### PR TITLE
redis cache

### LINKED ISSUE #19542: Distributed caching points to a deprecated Chocolatey package
[This section](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache) points to a [deprecated package](https://chocolatey.org/packages/redis-64).
Is there a replacement package?

To install Redis on your local machine:

1. Install the [Chocolatey Redis package](https://chocolatey.org/packages/redis-64/).
1. Run `redis-server` from a command prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #19542

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@mohsinnasir  using an Azure Redis cache for dev is probably pretty expensive. You don't want to use the same instance as the production cache.

**Comment by mohsinnasir** [comment]
@Rick-Anderson I totally agree that using azure cache for redis for development is pretty expensive plus its response time would also be slow as it ill be over wan while doing development on local machine. However, there should be an emulator for azure cache for redis like CosmosDb or MongoDB

**Comment by mohsinnasir** [comment]
@Rick-Anderson Changes looks fine to me

**Review by mohsinnasir — APPROVED** [review]
looks good

**Pull request merged**
