### PR TITLE
Update index.md

### LINKED ISSUE #21847: Book link gives 404 - not found
The link to the .pdf file for the mentioned book, as well as the link behind the cover photo, lead to the GitHub 404 - not found page.

I managed to find the book eventually, but this should be fixed so that other people do not have to search too long ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0d56c8f-85da-6c32-ce99-1df8d1a71edd
* Version Independent ID: 388cf375-58cc-1035-4de0-6ed3f6ae6b9c
* Content: [DevOps with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/aspnet/core/azure/devops/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/azure/devops/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/azure/devops/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #21847

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@hugh-maaskant please review

**Comment by hugh-maaskant** [comment]
Hi Rick,

I'm sorry, but I still get the 404 :-(

This is the link on the page:
https://aka.ms/devopsbook

And this is what it expands to: 
https://github.com/dotnet/AspNetCore.Docs/raw/master/aspnetcore/azure/pdf/DevOps-with-ASP.NET-Core-and-Azure.pdf

Could it have something to do with the fact that I am located in Europe and therefore get a different DNS resolve ??? This is what I resolve:

% ping github.com 
PING github.com (140.82.121.3): 56 data bytes
64 bytes from 140.82.121.3: icmp_seq=0 ttl=51 time=23.995 ms

I also tried to walk the URL path, it goes wrong (404 returned) at:
https://github.com/dotnet/AspNetCore.Docs/raw/

So to clarify
https://github.com/dotnet/AspNetCore.Docs/
is till OK, I land on the  "dotnet / AspNetCore.Docs" repository page with you as most recent committer ;-)

Rick-Anderson Update memory.md (#21814) 70cf7a6 14 hours ago 11,779 commits 

Please let me know if I can be of further assistance!

best regards, Hugh

**Comment by Rick-Anderson** [comment]
@hugh-maaskant  that's the wrong link in the PR. Try
https://github.com/dotnet-architecture/eBooks/blob/master/current/devops-aspnet-core/DevOps-with-ASP.NET-Core-and-Azure.pdf

That's updated link

old/new side by side
https://github.com/dotnet/AspNetCore.Docs/raw/master/aspnetcore/azure/pdf/DevOps-with-ASP.NET-Core-and-Azure.pdf
https://github.com/dotnet-architecture/eBooks/blob/master/current/devops-aspnet-core/DevOps-with-ASP.NET-Core-and-Azure.pdf

**Comment by hugh-maaskant** [comment]
Hi Rick,

I do not fully understand what you are trying to say. Indeed the link you gave me leads to the book. But my PR was on this page:

https://docs.microsoft.com/en-us/aspnet/core/azure/devops/?view=aspnetcore-5.0

If I go there, and click on either the image of th book cover opr the link in this text:

"This guide is available as a downloadable PDF e-book."

I still get a 404 not found ...

Best regards, Hugh

**Comment by Rick-Anderson** [comment]
The PR will fix the page. That's how PR's work.

**Pull request merged**
