### PR TITLE
docs(min-web-api): Use Postman collection for testing

### PR DESCRIPTION
**Pull request by anishkny**
It would be nice to add a [Postman collection](https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-and-exporting-overview/) which can be imported for testing.

[Internal review URL: ***Install Postman to test the app***](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&branch=pr-en-us-30135&tabs=visual-studio-code#install-postman-to-test-the-app)  ***<-- Use this link to see changes***

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/8fba74f02a4d81397024e32f7ff0b4974b259e8b/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-30135) |

### CODE REVIEW

**Comment by anishkny** [comment]
@dotnet-policy-service agree

**Comment by guardrex** [comment]
@anishkny ... Thanks for sending this in.

As a general practice, it seems a hair scary to directly consume a web resource without inspection. I'm probably overly paranoid 😨, but alternatives are to either show the file and require the dev to copy-paste it into a local file for use or link to it so that it opens in a new browser window for consumption. The dev will know what they're using, as opposed to blindly grabbing the file in Postman from a web resource via a link. @anishkny, Wade will be along in a bit to review and decide what's best. I'm just mentioning my concern in passing.

**Comment by anishkny** [comment]
@guardrex Good point. But in general I hope getting a Postman collection into the docs is a good idea. I defer to the team's judgement on specifics.

**Comment by guardrex** [comment]
It's up to Wade ... he'll be along in a bit to take a look. I think he'll like this. It looks 😎👍 to me anyway.

**Comment by wadepickett** [comment]
Working through the tutorial with this addition, I feel like it expands the scope of this starter tutorial too much.  I also took a look again at the getting started tutorials at the Postman site: https://learning.postman.com/docs/getting-started/first-steps/sending-the-first-request/.   They do the same there, bringing in the feature/concept for working with collections later.  Sorry @anishkny, I hate to turn down the PR and your great work.  If you have you own blog you want to add this too as a tutorial on testing with Postman, I'm happy to consider personally pointing to it from my X (twitter) account, although, I don't have following, so I realize that is not offering much!  We always appreciate awesome community effort like this.  Best to create an issue first suggesting what you want to add before doing the work.

**Review by wadepickett — CHANGES_REQUESTED** [review]
See notes already added just above this.  It takes this starter tutorial too far out of its intended scope.

**Comment by Rick-Anderson** [comment]
> See notes already added just above this. It takes this starter tutorial too far out of its intended scope.

So PR the PR and create part 2 just like  [the controller based Web API tutorial](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio#call-the-web-api-with-javascript)

**Comment by anishkny** [comment]
@guardrex Yes my bad on not discussing this on as issue first - got too excited 😄 and I agree this addition might make the tutorial too heavy with stuff.

Although I do like @Rick-Anderson 's idea of spinning out a follow up tutorial like [Tutorial: Call an ASP.NET Core web API with JavaScript](https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-7.0).

Ultimately I leave it up to you folks - no hard feelings either ways! 🙏

**Comment by wadepickett** [comment]
Rick will take it from here.

**Comment by Rick-Anderson** [comment]
> I also share the concern raised by @guardrex above.

What's your concern @wadepickett ? This is for testing.

**Comment by Rick-Anderson** [comment]
## Public review  of the doc build:
- download the [HTML files](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
- unzip
- view HTML file in a browser.
- For links outside the doc, remove the `review.` from URL.

@anishkny  can you look at the public review and make sure your changes work as expected? The link to `aspnetcore/tutorials/min-web-api/_static/minimal-api-tests.postman_collection.json` obviously won't work at this point.

**Comment by anishkny** [comment]
@Rick-Anderson LGTM

**Comment by guardrex** [comment]
@Rick-Anderson ... My concern is that even in a testing environment, I wouldn't personally type a link for some content that I haven't inspected directly into any tooling that takes some action with that content ...

> * Start Postman.
> * Select **File** > **Import**.
> * Select **Link** and enter `https://learn.microsoft.com/aspnet/core/tutorials/min-web-api/_static/minimal-api-tests.postman_collection.json`. Select **Continue**.

I'm somewhat paranoid ... that's a 🎃 ***scary practice*** 👻 to me for any scenario and notwithstanding that the file is hosted by MS ... like MS has never been hacked before. I'd want to inspect the file first. I suggest either ...

* Place a GH link that opens the file in a new browser window. The dev copies/downloads the content from there (or they can use the direct link after that, but I wouldn't tell them to just use the link without looking).
* Inline the file into the doc and force the dev to use the doc copy button to obtain it for the file that they'd create on their system.

**Comment by wadepickett** [comment]
Sounds reasonable, thanks @guardrex.

**Pull request closed without merging**
