### PR TITLE
Dropping 8.0 Blazor tracking

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #28161

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6b103fa63c840ac26c5ea3464105a61784c2/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-33256) |
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6b103fa63c840ac26c5ea3464105a61784c2/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-33256) |
| [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6b103fa63c840ac26c5ea3464105a61784c2/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md) | [ASP.NET Core code generator tool (`aspnet-codegenerator`)](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?branch=pr-en-us-33256) |

### CODE REVIEW

**Comment by wadepickett** [comment]
Review requests seem a little wacky now.  Or maybe I just don't understand the intent of how it is to work.  I was requested and received a notice, but I don't show up under requested reviewers' pane on the page.  Looks like switching from draft to review requests three of us. But then it does not show show us as requested reviewers in the reviewer's pane?  I liked the previous system when it was intentional and manual.

**Comment by guardrex** [comment]
We're you guys ordered on pain of death 💀😆 to review every PR, no matter how trivial?

**Comment by wadepickett** [comment]
For all three of us at once for everything no matter what even if we have a specific reviewer that would be best for that topic?  Not that I know of, but maybe I missed the thread.

**Comment by wadepickett** [comment]
It auto might be good in my opinion for when no reviewer has been selected at all, or a community member has submitted a PR.

**Comment by wadepickett** [comment]
...waiting for build to complete successfully to review this one...

**Comment by wadepickett** [comment]
@Rick-Anderson & @tdykstra just to loop in the short conversation above about auto review when switching from draft.

**Comment by guardrex** [comment]
I think this is resolved ***for Blazor PRs*** per Tom's updates on https://github.com/dotnet/AspNetCore.Docs/pull/33253.

I think that's best. I recommend just letting me crank away and call for reviews as needed manually.

**Comment by guardrex** [comment]
The build system is buggy 🪲 today.

**Review by wadepickett — APPROVED** [review]
The three small changes look good of course.  So I will go ahead and approve.  Watching anyway for the build, but I also don't want to hold you up just in case build issues go on all day and I miss the window.

**Comment by tdykstra** [comment]
I'll change the CODEOWNERS file to list only the actual owners of folders where that is known, and I'll omit naming a code owner where it isn't known or there's a mix.

**Pull request merged**
