### PR TITLE
highlighting index fix

### PR DESCRIPTION
**Pull request by fiyazbinhasan**
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22297

### CODE REVIEW

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson please reiew

**Comment by Rick-Anderson** [comment]
Top one is fixed but not the last
image

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
fix last

**Comment by Rick-Anderson** [comment]
Thanks for fixing this.

**Pull request merged**
