### PR TITLE
fix snippet /2

### LINKED ISSUE #23827: Missing code for IAsyncDisposable section
In the [IAsyncDisposable supported](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#iasyncdisposable-supported) section, towards the end and below the words **"Awaits DisposeAsyncCore, shown in the following code"**...there doesn't seem to be any code in the box:

image

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #23827

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
See fix at https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0

**Comment by JuergenGutsch** [comment]
@Rick-Anderson I'm sorry, I wasn't that fast to check the sample, because of a different time-zone (CET)

**Comment by Rick-Anderson** [comment]
@JuergenGutsch I should have been more clear. It's easier for you to check after I merge and merge to live, that way you can check the public/live topic. That's what I meant. Otherwise, I have to build you a private preview build. Can you take a look at your updated sample [here](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#iasyncdisposable-supported)

**Comment by JuergenGutsch** [comment]
@Rick-Anderson Got it. thanks for the clarification. 
I had a look. It looks good

**Pull request merged**
