### PR TITLE
Blazor snippet and EFCore-Server sample updates

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #22045

Jeremy, I don't have much confidence that the NRT updates that I made are sane ...

link

### *It's gotta be the ugliest hack I have ever done.*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&mdash; Link ([Harold Perrineau](https://www.imdb.com/name/nm0674782/?ref_=ttfc_fc_cl_t53)), [The Matrix Reloaded](https://www.warnerbros.com/movies/matrix-reloaded), &copy;2003 [Warner Brothers Entertainment, Inc.](https://www.warnerbros.com/)

* I took the compiler's advice on making objects nullable.
* I mostly dealt with possible null reference returns by checking with the operator or testing the object.

The app runs. There's one lingering warning that I can't grok ...

> c:\Users\XXX\Documents\GitHub\AspNetCore.Docs\aspnetcore\blazor\samples\6.0\BlazorServerEFCoreSample\BlazorServerDbContextExample\Pages\Index.razor(207,33): warning CS8602: Dereference of a possibly null reference. [C:\Users\XXX\Documents\GitHub\AspNetCore.Docs\aspnetcore\blazor\samples\6.0\BlazorServerEFCoreSample\BlazorServerDbContextExample\BlazorServerDbContextExample.csproj]

... referring to `var contact = await context.Contacts?` of ...

```csharp
private async Task DeleteContactAsync()
{
    using var context = DbFactory.CreateDbContext();
    Filters.Loading = true;

    if (Wrapper is not null)
    {
        var contact = await context.Contacts?
            .FirstAsync(c => c.Id == Wrapper.DeleteRequestId);

        if (contact != null)
        {
            context.Contacts?.Remove(contact);
            await context.SaveChangesAsync();
        }
    }

    Filters.Loading = false;

    await ReloadAsync();
}
```

... but that warning doesn't seem to stop the app. Checking `context` for null doesn't seem to help.

You'll have to let me know how you would like to proceed with the whole sample app and all of the updates ...

* You could review this (now or later).
* We could merge this temporarily until you (or some other PU engineer) creates a good EF Core-Blazor Server conversion, then I'll dump their/your whole app into the 6.0 folder for this sample.

In a broader context for scenarios like making component parameters nullable or assigning a default value to all of them, I'll check with DR/Artak, possibly Pranav/Javier/Steve. I might have gotten suckered into making a bunch of incorrect changes due to poor compiler advice 😈. I'll chat with them about some of these errors in the post-RC2 release period ...

* warning CS8618: Non-nullable property 'XXX' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
* warning CS8602: Dereference of a possibly null reference.
* warning CS8622: Nullability of reference types in type of parameter 'XXX' of 'YYY' doesn't match the target delegate 'ZZZ' (possibly because of nullability attributes).

### CODE REVIEW

**Comment by JeremyLikness** [comment]
@guardrex I will review sometime this week if that works for you.

Jeremy

**Comment by guardrex** [comment]
@JeremyLikness ... I'll need to get this merged by EOD to continue working on the NRTs in the snippet samples. You could come back to the sample app later if you don't have time to look at it today. As long as everything is wrapped up by GA, we're all good.

**Review by JeremyLikness — APPROVED** [review]
@guardrex I skimmed this and looks good. Obviously there are caveats as you mentioned but I don't see major issues with the other changes you've made. This of course wasn't a deep dive but wanted to keep the ball rolling so I looked at what I can.

**Comment by guardrex** [comment]
Ok ... thanks. I'll take a look at that one scenario :point_up: again soon when I work on the snippet sample apps to fix up their NRTs. If I can't figure it out, I'll ask Steve and/or Javier to look later.

**Pull request merged**
