### PR TITLE
Non-Development static files for Blazor Server

### LINKED ISSUE #26751: Note requirement to include UseStaticWebAssets in Staging environment
[EDIT by guardrex to change the metadata]

I bumped into a nasty error when switching from Devlopment so Staging environment: In Staging, static web assests (e.g. site.css and other java scripts) are not served automatically. You can try this by making a new Blazor Server Side App, switch to Staging and you will see, that site.css is not loaded.

The [fix](https://forum.radzen.com/t/radzen-blazor-components-dont-respect-custom-environments/2690/2) seems to be to include `UseStaticWebAssets`. Unfortunately, it took me quite a while to figure out where to include this, so a code example would be useful. I work off the .net 5 template, so in `Program.cs` I added
`Host.ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStaticWebAssets();   
                    webBuilder.UseStartup<Startup>();
                })`

I also did not find a description of the side effects when including `UseStaticWebAssets` in all environments and I don't know how to access the Environment in `ConfigureWebHostDefaults`.

- [ ] I think it would be good to mention/highlight the need to include `UseStaticWebAssets` on this page in the documentation and also in the xml documentation of `ConfigureWebHostDefaults`, as it mentions that static assets are included, but does not mention that this is only in development environment.

- [ ] Please also elaborate on the side effect of using `UseStaticWebAssets` in all environments in the api documentation [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilderextensions.usestaticwebassets?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStaticWebAssets)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=aspnetcore-6.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0af7f84-f8dd-92d9-dacd-2aab76d3a039
* Version Independent ID: 25458428-030f-6acb-457e-1b4dfa722043
* Content: [ASP.NET Core Blazor static files](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #26751

[Internal Review Topic (links to 7.0 section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-7.0&branch=pr-en-us-26759#static-files-in-non-development-environments-for-blazor-server-apps)

cc: @captainsafia ... Idk if you want to look 👀 at this given your participation in the PU discussion. I'll ping Halter for review; but of course, you're very welcome to help me with this. I didn't see a final summary set of suggestions for *all versions*, including 3.1 (which I think is the same as 5.0), at the end of the PU discussions **_from the PU engineers_**.

Thanks @KurtP20! 🚀 

cc: @voroninp ... I see that you asked about documenting this on [another PU issue](https://github.com/dotnet/aspnetcore/issues/43110). It's being worked on here for the docs.

I'm using a modified version of your, @KurtP20, approach for 5.0 ...

```csharp
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        if (webBuilder.GetSetting(WebHostDefaults.EnvironmentKey) == Environments.Staging)
        {
            webBuilder.UseStaticWebAssets();
        }

        webBuilder.UseStartup<Startup>();
    });
```

**❓for the PU: _Can I copy that approach back for 3.1 coverage on this, or should I just go with 5.0 and later coverage?_**

For 6.0 or later, the new guidance goes with ...

```csharp
if (builder.Environment.IsStaging())
{
    builder.WebHost.UseStaticWebAssets();
}
```

The PU discussions and the PR related to this docs PR ...

* https://github.com/dotnet/aspnetcore/issues/39596#issuecomment-1015279408
* https://github.com/dotnet/aspnetcore/issues/38212
* https://github.com/dotnet/aspnetcore/pull/41182
* https://github.com/dotnet/aspnetcore/issues/43110

### CODE REVIEW

**Comment by guardrex** [comment]
btw ... Just learned that we should probably scope the calls to the exact non-production environment in use per ...

https://github.com/dotnet/aspnetcore/issues/43110#issuecomment-1206573745

I'll update this PR very soon to cover it.

**Comment by guardrex** [comment]
Ok ... let's see how that looks, @KurtP20. It has a check now for the environment to cover Javier's warning about targeting the call.

We'll see what our PU friends think ... is this 👍 **_OK!_** 👍 ... or is it another 💩 **_RexStinker!_**&trade; 💩🤣?

**Comment by KurtP20** [comment]
Okay, so there is a side effect of calling `UseStaticWebAssets` and one should not call it in Production environment. Thanks for the example code for .net 5, I would have never come up with this, but it seems to work for me.

I lost track if the example is included in the documentation, but I think it would be really helpful.

Thanks for fixing this issue, it feels cool to have contributed, even though only by making you more work 😄 👍

**Comment by guardrex** [comment]
Yes, it's included on the PR. 

The only thing not here is placing the content for 3.1, and we'll see on PU review if I can copy back the 5.0 content for 3.1. If they're too busy to look at this, then I'll merge in a week without that and take feedback to see if any devs on 3.1 run into trouble. 

> making you more work

**_No worries!_** This is a great addition for a common use case (if the product unit approves, noting that they never asked for coverage on it AFAIK).

**Comment by guardrex** [comment]
I think this is going to work out fine based on the PU issue remarks and covering their bases for scoping the call in the examples and with the WARNING note that I placed in the coverage. I think the PU is too busy 🗻⛏️😅 to look right now. The .NET 7 work is the top priority. I'll go ahead with this for now and take further feedback. This PR will also be mentioned to management in my weekly communication with them; so if they have any concerns, they can let me know to make a tracking note to myself somewhere to get up with engineering later on it.

**Pull request merged**
