### PR TITLE
sample snapshot fort the new app.Use overload

### PR DESCRIPTION
**Pull request by fiyazbinhasan**
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/23688

### CODE REVIEW

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson I've added a snapshot file showing the usage of the `Use` overloads and also added some comments which I think could be mentioned in the documentation. Please check 😺

**Review by serpent5 — CHANGES_REQUESTED** [review]
Thanks for this work, @fiyazbinhasan. I can see you've been a huge help here with many great contributions to the docs. ⭐ 

I have a couple of change requests for this one:

- Can we reduce this to just the second snippet, `snippet2`? I don't think we'll link to the first and third snippets in the article, so they're not needed here.
- Can we remove the `CultureInfo` context here, to simplify the example? In keeping with the sample code we have for some of the other examples, could we have something like this?:

    ```csharp
    app.Use(async (context, next) =>
    {
        // Do work that doesn't write to the Response.
        await next.Invoke(context);
        // Do logging or other work that doesn't write to the Response.
    });
    ```

---

Apologies for the triple-post. It looks like I heard a network issue and the retry-logic was quite excited to take over. 😄

**Review by serpent5 — CHANGES_REQUESTED** [review]
[removed duplicate post]

**Review by serpent5 — CHANGES_REQUESTED** [review]
[removed duplicate post]

**Comment by fiyazbinhasan** [comment]
Hi @serpent5. thanks for the review 😸! I've reduced the code snippets to just show the usage of `next(context)`.

Although I do think that this [section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#prefer-appuse-overload-that-requires-passing-the-context-to-next) in the doc need some information like this, (when not using `next` at all)

```
/*
    1. next is not used i.e. it is a terminal middleware
    2. Every other middleware after a terminal middleware is skipped
    1. Use should be replaced with Run or it will throw a compile time error (CS0121: ambiguous)

    app.Use(async (context, next) => {
        await context.Response.WriteAsync(
            $"Hello {CultureInfo.CurrentCulture.DisplayName}");
    });
*/

app.Run(async (context) =>
{
    await context.Response.WriteAsync(
        $"Hello {CultureInfo.CurrentCulture.DisplayName}");
});
```

What do you think?

**Comment by serpent5** [comment]
Thanks @fiyazbinhasan. That was a very quick turnaround. 🏃

I think we should just start by documenting this in the context of `next` being invoked, as the code snippet you've provided shows. If we receive customer reports around *not* calling `next`, that would be the time to add the extra information around using `Run`, etc. We can leave your helpful comments in the snippet, so we can surface it later if we need to.

@Rick-Anderson Let me know if you disagree with the above. We still need to display this sample in the article. Would you like to add anything else in light of this comment from the article?:

> TODO, a minimum, provide a sample usage. Better, use this overload in the 6.0 version

**Review by serpent5 — APPROVED** [review]
Ok, let's get this merged and then follow up with another PR, as @Rick-Anderson suggests.

Thanks again @fiyazbinhasan. I'll pick up your other PR tomorrow.

**Pull request merged**
