### PR TITLE
[HOLD, Pre6] Blazor static asset delivery and fingerprinting

### LINKED ISSUE #33005: Static asset delivery and fingerprinting
### Description

* https://github.com/dotnet/aspnetcore/issues/52824
* https://github.com/dotnet/aspnetcore/pull/56045
* https://github.com/dotnet/aspnetcore/issues/56076
* API implementation issues
  * https://github.com/dotnet/aspnetcore/issues/54873
  * https://github.com/dotnet/aspnetcore/issues/54874
  * https://github.com/dotnet/aspnetcore/issues/54875

Additional design remarks: https://github.com/dotnet/aspnetcore/issues/52824#issuecomment-1977047241

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md

### Document ID

25458428-030f-6acb-457e-1b4dfa722043

### Article author

@guardrex

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #33005
Addresses #32960
Addresses #31909

~I still need to go through the full doc set and add/version the `href`s for static assets. However, should I just wait until the tilde-slash (`~/`) feature is implemented for the compiler before doing that? I think there might be like ... mmmmm 🤔 ... 50 or so spots to update. I'd like to wait and hit them on one pass if the `~/` feature will be implemented soon.~

The compiler feature won't make .NET 9. I'm versioning `href`s on this PR.

---

#### Internal previews

<details><summary><strong>Toggle expand/collapse</strong></summary><br/>

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-33010) |
| [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/components/css-isolation.md) | [ASP.NET Core Blazor CSS isolation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?branch=pr-en-us-33010) |
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-33010) |
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/fundamentals/environments.md) | [aspnetcore/blazor/fundamentals/environments](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-33010) |
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33010) |
| [aspnetcore/blazor/host-and-deploy/webassembly-caching/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/host-and-deploy/webassembly-caching/index.md) | [ASP.NET Core Blazor WebAssembly .NET runtime and app bundle caching](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-caching/index?branch=pr-en-us-33010) |
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/server/additional-scenarios.md) | [Server-side ASP.NET Core Blazor additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [aspnetcore/blazor/security/webassembly/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Microsoft Entra ID](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-microsoft-entra-id?branch=pr-en-us-33010) |
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-33010) |

</details>

### CODE REVIEW

**Comment by danroth27** [comment]
> However, should I just wait until the tilde-slash (~/) feature is implemented for the compiler before doing that?

We don't expect the compiler feature to get implemented for .NET 9.

**Comment by guardrex** [comment]
In that case, I'll add the updates tomorrow morning well before release.

**Comment by guardrex** [comment]
@javiercn @danroth27 @mkArtakMSFT  ... I'm not sure if HREFs are changing for RCLs with the new static file delivery optimizations ... e.g. ...

```html
<link href="_content/ComponentLibrary/additionalStyles.css" rel="stylesheet" />
```

 ... to ...

```html
<link href="@Asset["_content/ComponentLibrary/additionalStyles.css"]" rel="stylesheet" />
```

If I don't hear back, I'll just check on this in a few hours with Pre6 release bits and make a quick set of separate updates.

**Comment by guardrex** [comment]
I'm attempting a Blazor doc-wide approach for versioning HREF link examples on the last commit:

* Place a section entitled *Summary of static file `<link>` `href` formats* into the *Static Files* article. The section presents tables by release version and app type with examples.
* For our doc examples of static file `<link>`s ...
  * Give them the static file location (path).
  * Cross-link to the new section.

If that works, we won't end up in 😈 ***VERSIONING HELL*** 😈 because there are a lot of permutations now of app type and `href` format.

**Comment by javiercn** [comment]
> @javiercn @danroth27 @mkArtakMSFT ... I'm not 100% sure if HREFs are changing for RCLs with the new static file delivery optimizations ... e.g. ...
> 
> ```
> <link href="_content/ComponentLibrary/additionalStyles.css" rel="stylesheet" />
> ```
> 
> ... to ...
> 
> ```
> <link href="@Assets["_content/ComponentLibrary/additionalStyles.css"]" rel="stylesheet" />
> ```
> 
> I assume that's correct. If I don't hear back, I'll just check on this in a few hours with Pre6 release bits and make a quick set of separate updates if needed to revert this set of updates.
> 
> ... and noting in passing that since the file optimizations only apply to server-side Blazor apps that things might get tricky in spots where a passing reference is made to a static file link. Not only am I versioning 9.0+ for `@Assets[]`, I also need to leave the original non-`@Assets[]` HREF for standalone WASM apps ....... _somehow_ 🤔. I'll work on it.

About the last paragraph. This works for Server and Webassembly, the main difference is hosted vs standalone applications.

**Comment by guardrex** [comment]
> the main difference is hosted vs standalone applications

Covering this with so many permutations will create versioning hell in individual articles because the articles are usually already versioning content that would have to be further versioned to support this (without ***Version-by-File***, which isn't available) and because we're now also throwing in app type differences. I think my centralized approach will work. See if the new section entitled *Summary of static file `<link>` `href` formats* in the *Static Files* article covers it correctly.

**Pull request merged**
